import { createClient } from 'jsr:@supabase/supabase-js@2';
const H={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, content-type','Content-Type':'application/json','Cache-Control':'no-store'};
const clean=(s:string)=>String(s||'').toLowerCase().replace(/&/g,'and').replace(/[^a-z0-9]+/g,' ').trim().replace(/\b(fc|afc)\b/g,'').replace(/\s+/g,' ').trim();
const aliases:Record<string,string>={'man utd':'manchester united','man united':'manchester united','man city':'manchester city','nott m forest':'nottingham forest','nottingham':'nottingham forest','spurs':'tottenham hotspur','tottenham':'tottenham hotspur','wolves':'wolverhampton wanderers','wolverhampton':'wolverhampton wanderers','brighton':'brighton and hove albion','newcastle':'newcastle united','west ham':'west ham united'};
const canon=(s:string)=>aliases[clean(s)]||clean(s);
const num=(v:any)=>v==null||v===''?null:Number.isFinite(Number(v))?Number(v):null;
const csv=(text:string)=>{const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean),head=lines[0].split(',').map(x=>x.trim());return lines.slice(1).map(line=>{const vals:string[]=[];let q=false,b='';for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){b+='"';i++}else q=!q}else if(c===','&&!q){vals.push(b);b=''}else b+=c}vals.push(b);return Object.fromEntries(head.map((h,i)=>[h,vals[i]??'']))})};
const dateOf=(r:any)=>{const raw=r.Date||r.date;if(!raw)return null;const m=String(raw).match(/^(\d{1,2})\/(\d{1,2})\/(\d{2,4})$/);if(m){let y=Number(m[3]);if(y<100)y+=2000;return new Date(Date.UTC(y,Number(m[2])-1,Number(m[1]),12)).toISOString()}const d=new Date(raw);return Number.isNaN(+d)?null:d.toISOString()};
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:H});try{const body=await req.json().catch(()=>({}));const urls:string[]=body.urls||['https://www.football-data.co.uk/mmz4281/2526/E0.csv'];const gw=body.gameweek==null?null:Number(body.gameweek);const sb=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false}});const {data:teams,error:te}=await sb.from('teams').select('id,name,short_name');if(te)throw te;const tm=new Map<string,any>();for(const t of teams||[]){tm.set(canon(t.name),t);if(t.short_name)tm.set(canon(t.short_name),t)}let parsed=0,inserted=0,unmatched:any[]=[],sourceErrors:any[]=[];for(const url of urls){const res=await fetch(url,{headers:{'user-agent':'football-intelligence-engine/0.1'}});if(!res.ok){sourceErrors.push({url,status:res.status});continue}for(const r of csv(await res.text())){if(!r.HomeTeam||!r.AwayTeam)continue;parsed++;const home=tm.get(canon(r.HomeTeam)),away=tm.get(canon(r.AwayTeam)),kickoff=dateOf(r);if(!home||!away||!kickoff){unmatched.push({home:r.HomeTeam,away:r.AwayTeam,date:r.Date,home_canon:canon(r.HomeTeam),away_canon:canon(r.AwayTeam)});continue}const base={fixture_kickoff:kickoff,captured_at:new Date().toISOString(),source:'football-data.co.uk',source_match_id:`${r.Date}|${r.HomeTeam}|${r.AwayTeam}`,competition:r.Div||'E0'};const rows=[{...base,team_id:home.id,venue:'home',goals_for:num(r.FTHG),goals_against:num(r.FTAG),shots_for:num(r.HS),shots_against:num(r.AS),raw:r},{...base,team_id:away.id,venue:'away',goals_for:num(r.FTAG),goals_against:num(r.FTHG),shots_for:num(r.AS),shots_against:num(r.HS),raw:r}];const {data,error}=await sb.from('team_match_intelligence').upsert(rows,{onConflict:'source,source_match_id,team_id',ignoreDuplicates:true}).select('id');if(error)throw error;inserted+=(data||[]).length}}
let signals=null;if(gw!=null){const {data,error}=await sb.rpc('generate_observational_intelligence',{p_gameweek:gw});signals=error?{error:error.message}:{inserted:data}}
return new Response(JSON.stringify({ok:true,parsed_matches:parsed,new_team_rows:inserted,unmatched_count:unmatched.length,unmatched:unmatched.slice(0,50),source_errors:sourceErrors,signals,model_effect_enabled:false,note:'Football-Data supplies results/shots but not xG; xG remains null until an xG source enriches the canonical match.'}),{headers:H})}catch(e){return new Response(JSON.stringify({ok:false,error:e instanceof Error?e.message:String(e)}),{status:500,headers:H})}});