import { createClient } from 'npm:@supabase/supabase-js@2.112.3';
const H={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, content-type, x-engine-token','Content-Type':'application/json','Cache-Control':'no-store'};
const clean=(s:string)=>String(s||'').toLowerCase().replace(/&/g,'and').replace(/[^a-z0-9]+/g,' ').trim().replace(/\b(fc|afc)\b/g,'').replace(/\s+/g,' ').trim();
const aliases:Record<string,string>={'man utd':'manchester united','man united':'manchester united','man city':'manchester city','nott m forest':'nottingham forest','nottingham':'nottingham forest','spurs':'tottenham hotspur','tottenham':'tottenham hotspur','wolves':'wolverhampton wanderers','wolverhampton':'wolverhampton wanderers','brighton':'brighton and hove albion','newcastle':'newcastle united','west ham':'west ham united','coventry':'coventry city','hull':'hull city','ipswich':'ipswich town'};
const canon=(s:string)=>aliases[clean(s)]||clean(s);
const num=(v:any)=>v==null||v===''?null:Number.isFinite(Number(v))?Number(v):null;
const csv=(text:string)=>{const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean),head=lines[0].split(',').map(x=>x.trim());return lines.slice(1).map(line=>{const vals:string[]=[];let q=false,b='';for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){b+='"';i++}else q=!q}else if(c===','&&!q){vals.push(b);b=''}else b+=c}vals.push(b);return Object.fromEntries(head.map((h,i)=>[h,vals[i]??'']))})};
const dateOf=(r:any)=>{const raw=r.Date||r.date;if(!raw)return null;const m=String(raw).match(/^(\d{1,2})\/(\d{1,2})\/(\d{2,4})$/);if(m){let y=Number(m[3]);if(y<100)y+=2000;return new Date(Date.UTC(y,Number(m[2])-1,Number(m[1]),12)).toISOString()}const d=new Date(raw);return Number.isNaN(+d)?null:d.toISOString()};
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:H});try{const ks=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')||'{}');const sb=createClient(Deno.env.get('SUPABASE_URL')!,ks.default||Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false}});const {data:adminToken,error:authError}=await sb.rpc('get_backend_secret',{secret_name:'FOOTBALL_ENGINE_ADMIN_TOKEN'});if(authError||!adminToken||req.headers.get('x-engine-token')!==adminToken)return new Response(JSON.stringify({ok:false,error:'Unauthorized'}),{status:401,headers:H});const body=await req.json().catch(()=>({}));const urls:string[]=body.urls||['https://www.football-data.co.uk/mmz4281/2526/E0.csv','https://www.football-data.co.uk/mmz4281/2526/E1.csv'];const gw=body.gameweek==null?null:Number(body.gameweek);const {data:teams,error:te}=await sb.from('teams').select('id,name,short_name');if(te)throw te;const tm=new Map<string,any>();for(const t of teams||[]){tm.set(canon(t.name),t);if(t.short_name)tm.set(canon(t.short_name),t)}let parsed=0,inserted=0,matchedTeamRows=0,skippedNoncurrentTeamRows=0,invalidRows=0,sourceErrors:any[]=[];const sourceStats:any[]=[];for(const url of urls){const res=await fetch(url,{headers:{'user-agent':'football-intelligence-engine/0.1'}});if(!res.ok){sourceErrors.push({url,status:res.status});continue}let sourceMatches=0,sourceMatched=0;for(const r of csv(await res.text())){if(!r.HomeTeam||!r.AwayTeam)continue;parsed++;sourceMatches++;const home=tm.get(canon(r.HomeTeam)),away=tm.get(canon(r.AwayTeam)),kickoff=dateOf(r);if(!kickoff){invalidRows+=2;continue}const base={fixture_kickoff:kickoff,captured_at:new Date().toISOString(),source:'football-data.co.uk',source_match_id:`${r.Date}|${r.HomeTeam}|${r.AwayTeam}`,competition:r.Div||'unknown'};const recs:any[]=[];if(home)recs.push({...base,team_id:home.id,venue:'home',goals_for:num(r.FTHG),goals_against:num(r.FTAG),shots_for:num(r.HS),shots_against:num(r.AS),raw:r});else skippedNoncurrentTeamRows++;if(away)recs.push({...base,team_id:away.id,venue:'away',goals_for:num(r.FTAG),goals_against:num(r.FTHG),shots_for:num(r.AS),shots_against:num(r.HS),raw:r});else skippedNoncurrentTeamRows++;if(!recs.length)continue;matchedTeamRows+=recs.length;sourceMatched+=recs.length;const {data,error}=await sb.from('team_match_intelligence').upsert(recs,{onConflict:'source,source_match_id,team_id',ignoreDuplicates:true}).select('id');if(error)throw Error(`history upsert: ${error.message}`);inserted+=(data||[]).length}sourceStats.push({url,competition:url.includes('/E1.csv')?'E1':'E0',source_matches:sourceMatches,matched_current_team_rows:sourceMatched})}
let signals=null;if(gw!=null){const {data,error}=await sb.rpc('generate_observational_intelligence',{p_gameweek:gw});signals=error?{error:error.message}:{inserted:data}}
return new Response(JSON.stringify({ok:true,parsed_matches:parsed,new_team_rows:inserted,matched_current_team_rows:matchedTeamRows,skipped_noncurrent_team_rows:skippedNoncurrentTeamRows,invalid_rows:invalidRows,source_stats:sourceStats,source_errors:sourceErrors,signals,model_effect_enabled:false,note:'Rows are ingested independently for current 2026/27 teams. E0 covers retained EPL teams; E1 supplies prior-season Championship history for promoted current teams. Missing xG remains null.'}),{headers:H})}catch(e){return new Response(JSON.stringify({ok:false,error:e instanceof Error?e.message:String(e)}),{status:500,headers:H})}});