import { createClient } from 'jsr:@supabase/supabase-js@2';
const VERSION='C0233_ADVERSARIAL_RED_TEAM_V01';const N=(x:any,d=0)=>Number.isFinite(Number(x))?Number(x):d;
async function sha(x:any){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(x)));return[...new Uint8Array(b)].map(v=>v.toString(16).padStart(2,'0')).join('')}
Deno.serve(async(req:Request)=>{try{
 const keys=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')||'{}'),key=keys.default||Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!key)return Response.json({ok:false,error:'service credential missing'},{status:500});const sb=createClient(Deno.env.get('SUPABASE_URL')!,key,{auth:{persistSession:false}});const{data:tok,error:ae}=await sb.rpc('get_backend_secret',{secret_name:'FOOTBALL_ENGINE_ADMIN_TOKEN'});if(ae||!tok||req.headers.get('x-engine-token')!==tok)return Response.json({ok:false,error:'unauthorized'},{status:401});
 const b=await req.json().catch(()=>({})),gw=N(b.gameweek),h=Math.max(1,Math.min(5,N(b.horizon,5)));if(!gw)return Response.json({ok:false,error:'gameweek invalid'},{status:400});
 const [er,sr,fr,orr,rr]=await Promise.all([
  sb.from('fpl_squad_ensemble_runs').select('id,result,input_signature,model_error_margin_points').eq('gameweek',gw).eq('horizon',h).order('captured_at',{ascending:false}).limit(1).single(),
  sb.from('fpl_structural_control_runs').select('id,result,input_signature').eq('gameweek',gw).eq('horizon',h).order('captured_at',{ascending:false}).limit(1).single(),
  sb.from('fpl_forward_management_runs').select('id,result,input_signature').eq('gameweek',gw).eq('horizon',h).order('captured_at',{ascending:false}).limit(1).single(),
  sb.from('fpl_or_utility_runs').select('id,result,input_signature').eq('gameweek',gw).eq('horizon',h).order('captured_at',{ascending:false}).limit(1).single(),
  sb.from('fpl_team_regime_diagnostic_runs').select('id,result,input_signature').eq('gameweek',gw).order('captured_at',{ascending:false}).limit(1).single()
 ]);for(const x of [er,sr,fr,orr,rr])if(x.error||!x.data?.result?.ok)throw x.error||new Error('required autonomy layer missing');
 const e:any=er.data.result,s:any=sr.data.result,f:any=fr.data.result,o:any=orr.data.result,r:any=rr.data.result,err=N(er.data.model_error_margin_points,1),cands=e.candidates||[];const raw=[...cands].sort((a:any,b:any)=>N(b.objective)-N(a.objective))[0],challenger=cands.find((x:any)=>x.profile===s.structural_preferred?.profile)||null;if(!raw||!challenger)return Response.json({ok:false,status:'RED_TEAM_CANDIDATE_MISSING',decisioning:false},{status:409});
 const rawIds=new Set((raw.squad||[]).map((p:any)=>N(p.player_id))),chIds=new Set((challenger.squad||[]).map((p:any)=>N(p.player_id))),rawOnly=(raw.squad||[]).filter((p:any)=>!chIds.has(N(p.player_id))),chOnly=(challenger.squad||[]).filter((p:any)=>!rawIds.has(N(p.player_id)));
 const signalMap=new Map<string,any[]>();for(const z of r.signals||[])signalMap.set(String(z.team),z.signals||[]);const support=(ps:any[])=>{let positive=0,negative=0,details:any[]=[];for(const p of ps){const sig=signalMap.get(String(p.team))||[],side=['MID','FWD'].includes(p.position)?'ATTACK':'DEFENCE';const rel=sig.filter((x:any)=>x.side===side);const pos=rel.filter((x:any)=>String(x.type).includes('UP_')).length,neg=rel.filter((x:any)=>String(x.type).includes('DOWN_')).length;positive+=pos;negative+=neg;if(rel.length)details.push({player:p.name,team:p.team,position:p.position,signals:rel})}return{positive,negative,details}};const rawReg=support(rawOnly),chReg=support(chOnly);
 const sd=(s.candidate_diagnostics||[]).find((x:any)=>x.profile===raw.profile)||{},cd=(s.candidate_diagnostics||[]).find((x:any)=>x.profile===challenger.profile)||{},fdRaw=(f.candidate_diagnostics||[]).find((x:any)=>x.profile===raw.profile)||{},fdCh=(f.candidate_diagnostics||[]).find((x:any)=>x.profile===challenger.profile)||{},odRaw=(o.candidate_diagnostics||[]).find((x:any)=>x.profile===raw.profile)||{},odCh=(o.candidate_diagnostics||[]).find((x:any)=>x.profile===challenger.profile)||{};
 const challenges:any[]=[],gap=N(raw.objective)-N(challenger.objective);if(e.ensemble_classification==='NEAR_EQUIVALENT_SENSITIVITY_REQUIRED')challenges.push({severity:'HIGH',code:'MULTI_FAMILY_NEAR_EQUIVALENCE',detail:`Top families separated by ${gap.toFixed(3)} points, within 2x model-error sensitivity band.`});if(s.adjudication==='RAW_OPTIMUM_STRUCTURALLY_CHALLENGED')challenges.push({severity:'HIGH',code:'STRUCTURAL_CHALLENGER_BEATS_RAW_ON_ROBUSTNESS',detail:`${challenger.profile} is structurally preferred despite lower raw objective.`});
 const rawRoleRisk=N(sd.role_risk_slots),chRoleRisk=N(cd.role_risk_slots);if(rawRoleRisk>chRoleRisk){const riskPlayers=rawOnly.filter((p:any)=>p.role_risk===true);const bestRisk=Math.max(0,...riskPlayers.map((p:any)=>N(p.horizon_score)));const pct=bestRisk>0?100*gap/bestRisk:null;if(pct!=null&&pct<=10)challenges.push({severity:'HIGH',code:'EDGE_FLIPS_UNDER_SMALL_ROLE_RISK_SENSITIVITY',detail:`Only ${pct.toFixed(1)}% attenuation of the raw-only role-risk asset's horizon contribution would erase the ${gap.toFixed(3)}-point family edge.`,required_attenuation_pct:+pct.toFixed(2),role_risk_players:riskPlayers.map((p:any)=>p.name)});else challenges.push({severity:'MEDIUM',code:'RAW_HAS_MORE_ROLE_RISK',raw_role_risk_slots:rawRoleRisk,challenger_role_risk_slots:chRoleRisk})}
 if(N(cd.uncertainty_counts?.HIGH)<N(sd.uncertainty_counts?.HIGH)||N(cd.uncertainty_counts?.MEDIUM)<N(sd.uncertainty_counts?.MEDIUM))challenges.push({severity:'MEDIUM',code:'CHALLENGER_HAS_BETTER_UNCERTAINTY_PROFILE',raw:sd.uncertainty_counts,challenger:cd.uncertainty_counts});
 const forwardMixed=N(fdCh.one_transfer_access_top5)>N(fdRaw.one_transfer_access_top5)||N(fdCh.fragile_slots)<N(fdRaw.fragile_slots);if(forwardMixed)challenges.push({severity:'MEDIUM',code:'FORWARD_PATH_FAVORS_CHALLENGER_ON_FLEXIBILITY',raw:{one_transfer_top5:fdRaw.one_transfer_access_top5,fragile_slots:fdRaw.fragile_slots},challenger:{one_transfer_top5:fdCh.one_transfer_access_top5,fragile_slots:fdCh.fragile_slots},counterpoint:'Raw family may retain direct ownership of a hard-to-reacquire premium.'});
 if(N(odCh.weighted_leverage_index)>N(odRaw.weighted_leverage_index))challenges.push({severity:'MEDIUM',code:'LEVERAGE_FAVORS_CHALLENGER_BUT_CANNOT_WIDEN_ERROR_BAND',raw_index:odRaw.weighted_leverage_index,challenger_index:odCh.weighted_leverage_index,rank_regime:o.rank_state?.regime});
 if(chReg.positive>rawReg.positive)challenges.push({severity:'MEDIUM',code:'SHADOW_TEAM_REGIME_SIGNALS_FAVOR_CHALLENGER_UNIQUE_ASSETS',raw_unique_signal_support:rawReg,challenger_unique_signal_support:chReg,numeric_effect:false});
 const prem=(sd.premium_defender_opportunity_costs||[]).length+(cd.premium_defender_opportunity_costs||[]).length;if(prem>0)challenges.push({severity:'MEDIUM',code:'PREMIUM_DEFENDER_MARGINAL_VALUE_NOT_FULLY_RESOLVED',raw:sd.premium_defender_opportunity_costs||[],challenger:cd.premium_defender_opportunity_costs||[]});if((cd.club_slot_saturation||[]).length>(sd.club_slot_saturation||[]).length)challenges.push({severity:'MEDIUM',code:'COUNTER_CHALLENGE_CHALLENGER_HAS_MORE_CLUB_SLOT_SATURATION',raw:sd.club_slot_saturation||[],challenger:cd.club_slot_saturation||[]});
 const high=challenges.filter(x=>x.severity==='HIGH').length,status=high>0?'EDGE_NOT_ROBUST':gap<=err?'CHALLENGED_BY_EQUIVALENT':'PASS';const blockers=status==='PASS'?[]:challenges.filter(x=>x.severity==='HIGH').map(x=>x.code);const result={ok:true,status:'RED_TEAM_READY',change_id:'C0233',version:VERSION,gameweek:gw,horizon:h,ensemble_run_id:N(er.data.id),structural_run_id:N(sr.data.id),forward_run_id:N(fr.data.id),or_utility_run_id:N(orr.data.id),team_regime_run_id:N(rr.data.id),raw_best:{profile:raw.profile,objective:N(raw.objective),unique_assets:rawOnly.map((p:any)=>p.name)},challenger:{profile:challenger.profile,objective:N(challenger.objective),gap_to_raw_best:+gap.toFixed(3),unique_assets:chOnly.map((p:any)=>p.name)},challenges,red_team_status:status,blocking_reasons:blockers,recommended_profile_after_red_team:status==='PASS'?raw.profile:null,policy:{adversarial_not_blended_score:true,shadow_regime_has_zero_numeric_effect:true,leverage_does_not_widen_error_band:true,sensitivity_diagnostics_do_not_rewrite_xpts:true,pass_requires_no_high_severity_challenge:true},historical_forecasts_rewritten:false,decisioning:false};const sig=await sha({VERSION,ensemble:er.data.input_signature,structural:sr.data.input_signature,forward:fr.data.input_signature,or:orr.data.input_signature,regime:rr.data.input_signature,status,challenges:challenges.map(x=>[x.code,x.severity])});const{data:old,error:oe}=await sb.from('fpl_red_team_runs').select('id').eq('input_signature',sig).maybeSingle();if(oe)throw oe;let id=old?.id?N(old.id):null;if(!id){const{data:ins,error:ie}=await sb.from('fpl_red_team_runs').insert({gameweek:gw,horizon:h,ensemble_run_id:er.data.id,structural_run_id:sr.data.id,forward_run_id:fr.data.id,or_utility_run_id:orr.data.id,team_regime_run_id:rr.data.id,input_signature:sig,result,historical_forecasts_rewritten:false}).select('id').single();if(ie)throw ie;id=N(ins.id)}return Response.json({...result,red_team_run_id:id,input_signature:sig});
}catch(e){return Response.json({ok:false,status:'RED_TEAM_ERROR',error:e instanceof Error?e.message:String(e),decisioning:false},{status:500})}});