import { createClient } from 'supabase';

const H={'content-type':'application/json; charset=utf-8','cache-control':'no-store'};
const API='https://www.fotmob.com/api/data/matchDetails?matchId=';
const norm=(s:any)=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'').trim();
const n=(v:any)=>v===null||v===undefined||v===''?null:Number(v);
const i=(v:any)=>{const x=n(v);return x===null||!Number.isFinite(x)?null:Math.round(x)};
const chunks=<T>(a:T[],z=200)=>{const o:T[][]=[];for(let k=0;k<a.length;k+=z)o.push(a.slice(k,k+z));return o};
async function sha(s:string){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function band(y:number|null){if(y===null)return null;if(y<.18)return 'GOALKEEPER_LINE';if(y<.39)return 'DEFENSIVE_LINE';if(y<.59)return 'MIDFIELD_LINE';if(y<.80)return 'ATTACKING_MIDFIELD_LINE';return 'FORWARD_LINE'}
function width(x:number|null){if(x===null)return null;return Math.abs(x-.5)>=.22?'WIDE':'CENTRAL'}
function role(b:string|null,w:string|null){if(!b)return null;if(b==='GOALKEEPER_LINE')return 'GOALKEEPER';if(b==='DEFENSIVE_LINE')return w==='WIDE'?'WIDE_BACK':'CENTRE_BACK';if(b==='MIDFIELD_LINE')return w==='WIDE'?'WING_BACK':'HOLDING_MIDFIELDER';if(b==='ATTACKING_MIDFIELD_LINE')return w==='WIDE'?'WIDE_ATTACKER':'CREATOR_10';if(b==='FORWARD_LINE')return w==='WIDE'?'WIDE_FORWARD':'CENTRAL_STRIKER';return null}
function playerAliases(p:any){return new Set([norm(`${p.first_name||''} ${p.second_name||''}`),norm(p.web_name),norm(p.second_name)].filter(Boolean))}
function mapPlayer(src:any,teamId:number,players:any[]){const full=norm(src.name),first=norm(src.firstName),last=norm(src.lastName);const exactFull=players.filter(p=>norm(`${p.first_name||''} ${p.second_name||''}`)===full);if(exactFull.length===1)return {p:exactFull[0],status:'EXACT_FULL_NAME_GLOBAL'};const team=players.filter(p=>Number(p.team_id)===teamId);const exactTeam=team.filter(p=>playerAliases(p).has(full));if(exactTeam.length===1)return {p:exactTeam[0],status:'EXACT_NAME_TEAM'};const surname=team.filter(p=>norm(p.second_name)===last && (!first||norm(p.first_name).startsWith(first.slice(0,1))));if(surname.length===1)return {p:surname[0],status:'UNIQUE_SURNAME_FIRST_INITIAL_TEAM'};return {p:null,status:'UNMAPPED'} }

Deno.serve(async(req)=>{try{
  if(req.method!=='POST')return new Response(JSON.stringify({ok:false,error:'POST required'}),{status:405,headers:H});
  const keys=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')||'{}');const key=keys.default||Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!key)throw new Error('Missing service credential');
  const sb=createClient(Deno.env.get('SUPABASE_URL')!,key,{auth:{persistSession:false}});
  const {data:tok,error:ae}=await sb.rpc('get_backend_secret',{secret_name:'FOOTBALL_ENGINE_ADMIN_TOKEN'});if(ae||!tok||req.headers.get('x-engine-token')!==tok)return new Response(JSON.stringify({ok:false,error:'unauthorized'}),{status:401,headers:H});
  const body=await req.json().catch(()=>({}));const gw=body.gameweek==null?null:Number(body.gameweek);const force=body.force===true;const now=new Date().toISOString();
  let mq=sb.from('matches').select('id,gameweek,kickoff_time,home_team_id,away_team_id,finished').eq('source','fpl').eq('finished',true).lt('kickoff_time',now).order('gameweek',{ascending:true}).order('kickoff_time',{ascending:true});if(Number.isInteger(gw))mq=mq.eq('gameweek',gw);const {data:matches,error:me}=await mq;if(me)throw me;if(!matches?.length)return new Response(JSON.stringify({ok:true,processed_matches:0,inserted:0,message:'No finished matches'}),{headers:H});
  const ids=matches.map((m:any)=>Number(m.id));const [{data:done,error:de},{data:tmi,error:te},{data:players,error:pe}]=await Promise.all([
    sb.from('realized_player_role_observations').select('match_id').in('match_id',ids),
    sb.from('team_match_intelligence').select('match_id,source_match_id,raw,captured_at').eq('source','fpl_core_insights_premier_league').in('match_id',ids).order('captured_at',{ascending:false}),
    sb.from('players').select('id,team_id,first_name,second_name,web_name,position')
  ]);if(de)throw de;if(te)throw te;if(pe)throw pe;
  const completed=new Set((done||[]).map((x:any)=>Number(x.match_id)));const tmap=new Map<number,any>();for(const x of tmi||[]){const mid=Number(x.match_id);if(!tmap.has(mid))tmap.set(mid,x)}
  const rows:any[]=[];const perMatch:any[]=[];let fetched=0,skippedExisting=0,skippedNoSource=0,skippedIncomplete=0,fetchErrors=0;
  for(const m of matches){const mid=Number(m.id);if(!force&&completed.has(mid)){skippedExisting++;continue}const src=tmap.get(mid),raw=src?.raw||{};const fid=i(raw.fotmob_id);if(!fid){skippedNoSource++;continue}let j:any;try{const r=await fetch(`${API}${fid}`,{cache:'no-store',headers:{'user-agent':'FootballIntelligence/0.7','accept':'application/json'}});if(!r.ok)throw new Error(`HTTP ${r.status}`);j=await r.json();fetched++}catch(e){fetchErrors++;perMatch.push({match_id:mid,fotmob_id:fid,status:'FETCH_ERROR',error:e instanceof Error?e.message:String(e)});continue}
    const lineup=j?.content?.lineup;const hs=lineup?.homeTeam?.starters||[],as=lineup?.awayTeam?.starters||[];const all=[...hs,...as];const coordCount=all.filter((p:any)=>n(p?.verticalLayout?.x)!==null&&n(p?.verticalLayout?.y)!==null).length;if(all.length<18||coordCount<16){skippedIncomplete++;perMatch.push({match_id:mid,fotmob_id:fid,status:'INCOMPLETE_LINEUP',starters:all.length,coords:coordCount});continue}
    const before=rows.length;for(const [side,node,teamId] of [['home',lineup.homeTeam,Number(m.home_team_id)],['away',lineup.awayTeam,Number(m.away_team_id)]] as any[]){const formation=String(node?.formation||'').trim()||null;for(const psrc of node?.starters||[]){const x=n(psrc?.verticalLayout?.x),y=n(psrc?.verticalLayout?.y),tb=band(y),wb=width(x),rr=role(tb,wb),mapped=mapPlayer(psrc,teamId,players||[]),ip=mapped.p;const payload={change_id:'C0212',source:'fotmob_match_details',fotmob_match_id:fid,fotmob_player_id:i(psrc.id),match_id:mid,gameweek:Number(m.gameweek),team_id:teamId,formation,position_id:i(psrc.positionId),usual_playing_position_id:i(psrc.usualPlayingPositionId),layout_x:x,layout_y:y,tactical_band:tb,width_band:wb,realized_role:rr};const oh=await sha(JSON.stringify(payload));rows.push({change_id:'C0212',source_key:'fotmob_match_details',source_url:`${API}${fid}`,source_fotmob_match_id:fid,source_fotmob_player_id:i(psrc.id),match_id:mid,gameweek:Number(m.gameweek),kickoff_time:m.kickoff_time,team_id:teamId,player_id:ip?Number(ip.id):null,player_name:String(psrc.name||'Unknown'),fpl_position:ip?.position||null,usual_playing_position_id:i(psrc.usualPlayingPositionId),formation,is_starting:true,position_id:i(psrc.positionId),layout_x:x,layout_y:y,tactical_band:tb,width_band:wb,realized_role:rr,role_confidence:x!==null&&y!==null&&formation?0.98:x!==null&&y!==null?0.90:null,mapping_status:mapped.status,source_payload:{team_side:side,starter:psrc,lineup_source:lineup?.source||null},captured_at:now,evidence_cutoff:now,observation_hash:oh,production_role_enabled:true,model_effect_enabled:false})}}
    perMatch.push({match_id:mid,fotmob_id:fid,status:'READY',rows:rows.length-before});
  }
  let inserted=0;for(const c of chunks(rows)){const {data,error}=await sb.from('realized_player_role_observations').upsert(c,{onConflict:'observation_hash',ignoreDuplicates:true}).select('id');if(error)throw new Error(`realized roles insert: ${error.message}`);inserted+=(data||[]).length}
  let stateRefresh:any=null;if(rows.length&&body.refresh_state!==false){try{const r=await fetch(`${Deno.env.get('SUPABASE_URL')}/functions/v1/refresh-current-player-state`,{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${key}`,'x-engine-token':String(tok)},body:'{}'});stateRefresh={status:r.status,body:await r.json().catch(()=>null)}}catch(e){stateRefresh={status:'error',error:e instanceof Error?e.message:String(e)}}}
  const mapped=rows.filter(r=>r.player_id!==null).length,unmapped=rows.length-mapped;
  return new Response(JSON.stringify({ok:true,change_id:'C0212',requested_gameweek:gw,finished_matches_considered:matches.length,fetched,processed_matches:perMatch.filter(x=>x.status==='READY').length,rows_candidate:rows.length,inserted,mapped,unmapped,skipped_existing:skippedExisting,skipped_no_source:skippedNoSource,skipped_incomplete:skippedIncomplete,fetch_errors:fetchErrors,per_match:perMatch,state_refresh:stateRefresh,role_fact_scope:'realized tactical position only; FPL classification unchanged; no numeric role uplift coefficient enabled',historical_forecasts_rewritten:false}),{headers:H});
}catch(e){return new Response(JSON.stringify({ok:false,error:e instanceof Error?e.message:String(e)}),{status:500,headers:H})}});
