import { createClient } from 'supabase';

const clamp=(x:number,a=0,b=1)=>Math.max(a,Math.min(b,x));
const num=(v:any,d=0)=>v===null||v===undefined||v===''?d:Number(v);
const emsg=(e:any)=>e instanceof Error?e.message:typeof e==='string'?e:JSON.stringify(e);
async function sha(s:string){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join('')}
const hardUnavailable=(s:string)=>s==='i'||s==='s'||s==='u';
const currentAvailability=(p:any)=>{if(hardUnavailable(String(p.status||'')))return 0;const c=p.chance_of_playing_next_round;if(c!==null&&c!==undefined)return clamp(Number(c)>1?Number(c)/100:Number(c));return p.status==='a'?1:p.status==='d'?.75:p.status==='n'?.3:.8};
async function pagedActuals(sb:any,runIds:number[]){const out:any[]=[];for(let from=0;;from+=1000){const {data,error}=await sb.from('player_gameweek_actuals').select('result_run_id,player_id,fixture_ids,minutes,starts,xg,xa').in('result_run_id',runIds).range(from,from+999);if(error)throw error;out.push(...(data||[]));if((data||[]).length<1000)break}return out}

Deno.serve(async(req)=>{try{
  if(req.method!=='POST')return Response.json({ok:false,error:'POST required'},{status:405});
  const keys=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')||'{}');const key=keys.default||Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!key)throw new Error('Missing service credential');
  const sb=createClient(Deno.env.get('SUPABASE_URL')!,key,{auth:{persistSession:false}});
  const {data:adminToken,error:authError}=await sb.rpc('get_backend_secret',{secret_name:'FOOTBALL_ENGINE_ADMIN_TOKEN'});if(authError||!adminToken||req.headers.get('x-engine-token')!==adminToken)return Response.json({ok:false,error:'unauthorized'},{status:401});
  const at=new Date().toISOString();
  const [{data:mv,error:mve},{data:players,error:pe},{data:baseRows,error:be},{data:latestRows,error:le},{data:finished,error:fe}]=await Promise.all([
    sb.from('model_versions').select('id,version').eq('version','0.1.2').single(),
    sb.from('players').select('id,team_id,status,chance_of_playing_next_round'),
    sb.from('current_player_state_base').select('*'),
    sb.from('current_player_state_latest').select('id,player_id,as_of,state'),
    sb.from('matches').select('id,gameweek,home_team_id,away_team_id').eq('source','fpl').eq('finished',true).lt('kickoff_time',at)
  ]);
  if(mve)throw mve;if(pe)throw pe;if(be)throw be;if(le)throw le;if(fe)throw fe;
  const maxGw=Math.max(0,...(finished||[]).map((m:any)=>Number(m.gameweek||0)));if(!maxGw)return Response.json({ok:true,inserted:0,players_considered:0,message:'No completed current-season fixtures'});
  const runQueries=[] as Promise<any>[];for(let gw=1;gw<=maxGw;gw++)runQueries.push(sb.from('gameweek_result_runs').select('id,gameweek,observed_at,is_final,metadata').eq('gameweek',gw).eq('source','official_fpl').order('is_final',{ascending:false}).order('observed_at',{ascending:false}).limit(1).maybeSingle());
  const runResults=await Promise.all(runQueries);const runs:any[]=[];for(const r of runResults){if(r.error)throw r.error;if(r.data)runs.push(r.data)}if(!runs.length)return Response.json({ok:true,inserted:0,players_considered:0,message:'No official result snapshots'});
  const runMap=new Map<number,Set<number>>();for(const r of runs)runMap.set(Number(r.id),new Set((r.metadata?.finished_fixture_ids||[]).map(Number)));
  const actuals=await pagedActuals(sb,runs.map(r=>Number(r.id)));const agg=new Map<number,any>();
  for(const a of actuals){const fids=(a.fixture_ids||[]).map(Number).filter(Number.isFinite),done=runMap.get(Number(a.result_run_id))||new Set<number>();if(!fids.length||fids.some((id:number)=>!done.has(id)))continue;let x=agg.get(Number(a.player_id));if(!x){x={games:0,starts:0,apps:0,minutes:0,single_starts:0,single_start_minutes:0,single_sub_apps:0,single_sub_minutes:0,xg:0,xg_minutes:0,xa:0,xa_minutes:0};agg.set(Number(a.player_id),x)}x.games+=fids.length;x.starts+=num(a.starts);x.apps+=num(a.minutes)>0?fids.length:0;x.minutes+=num(a.minutes);if(fids.length===1){if(num(a.starts)>0){x.single_starts++;x.single_start_minutes+=num(a.minutes)}else if(num(a.minutes)>0){x.single_sub_apps++;x.single_sub_minutes+=num(a.minutes)}}if(a.xg!==null&&a.xg!==undefined){x.xg+=Number(a.xg);x.xg_minutes+=num(a.minutes)}if(a.xa!==null&&a.xa!==undefined){x.xa+=Number(a.xa);x.xa_minutes+=num(a.minutes)}}
  const pmap=new Map((players||[]).map((p:any)=>[Number(p.id),p])),latestMap=new Map((latestRows||[]).map((x:any)=>[Number(x.player_id),x]));const rows:any[]=[];let unchanged=0;
  for(const b of baseRows||[]){const p=pmap.get(Number(b.player_id));if(!p)continue;const a=agg.get(Number(b.player_id))||{games:0,starts:0,apps:0,minutes:0,single_starts:0,single_start_minutes:0,single_sub_apps:0,single_sub_minutes:0,xg:0,xg_minutes:0,xa:0,xa_minutes:0};const priorAvailRaw=Number(b.state?.availability);const priorAvail=Number.isFinite(priorAvailRaw)&&priorAvailRaw>0?priorAvailRaw:1;const latentStart=clamp(num(b.start_probability)/priorAvail),latentApp=clamp(num(b.appearance_probability,b.start_probability)/priorAvail);const priorEq=6;let latentStartNew=a.games?(latentStart*priorEq+a.starts)/(priorEq+a.games):latentStart;let latentAppNew=a.games?(latentApp*priorEq+a.apps)/(priorEq+a.games):latentApp;latentStartNew=clamp(latentStartNew);latentAppNew=clamp(Math.max(latentStartNew,latentAppNew));const avail=currentAvailability(p);const sp=clamp(latentStartNew*avail),ap=clamp(Math.max(sp,latentAppNew*avail));const baseSm=num(b.starter_minutes_estimate,70);const sm=a.single_starts?(baseSm*3+a.single_start_minutes)/(3+a.single_starts):baseSm;const subM=a.single_sub_apps?(18*3+a.single_sub_minutes)/(3+a.single_sub_apps):18;const xmin=sp*sm+Math.max(0,ap-sp)*subM;const xg90=a.xg_minutes>0?(num(b.xg90)*450+a.xg*90)/(450+a.xg_minutes):num(b.xg90);const xa90=a.xa_minutes>0?(num(b.xa90)*450+a.xa*90)/(450+a.xa_minutes):num(b.xa90);const evidence={base_state_id:b.id,current_games:a.games,current_starts:a.starts,current_apps:a.apps,current_minutes:a.minutes,current_xg:a.xg,current_xa:a.xa,status:p.status,chance:p.chance_of_playing_next_round};const evidenceHash=await sha(JSON.stringify(evidence));const latest=latestMap.get(Number(b.player_id));if(latest?.state?.refresh_family==='current_season_official'&&latest?.state?.evidence_hash===evidenceHash){unchanged++;continue}rows.push({player_id:b.player_id,as_of:at,model_version_id:mv.id,sample_matches:num(b.sample_matches)+a.games,expected_minutes:+xmin.toFixed(2),start_probability:+sp.toFixed(4),appearance_probability:+ap.toFixed(4),starter_minutes_estimate:+sm.toFixed(2),role:b.role,formation:b.formation,xg90:+xg90.toFixed(4),xa90:+xa90.toFixed(4),xgi90:+(xg90+xa90).toFixed(4),shots_box90:b.shots_box90,big_chances90:b.big_chances90,cbit90:b.cbit90,cbirt90:b.cbirt90,dc_probability:b.dc_probability,state:{...(b.state||{}),refresh_family:'current_season_official',refresh_version:'0.1',evidence_hash:evidenceHash,base_state_id:b.id,base_state_as_of:b.as_of,current_season:{games:a.games,starts:a.starts,apps:a.apps,minutes:a.minutes,xg:a.xg,xa:a.xa,prior_equivalent_games:priorEq,xg_xa_prior_minutes:450},availability:avail,known_at:at,model_effect_scope:'future_player_state_only',historical_forecasts_rewritten:false}})}
  for(let k=0;k<rows.length;k+=200){const {error}=await sb.from('player_state').insert(rows.slice(k,k+200));if(error)throw new Error(`player_state insert: ${emsg(error)}`)}
  const noBase=(players||[]).length-(baseRows||[]).length;
  return Response.json({ok:true,state_model_version:mv.version,consumer_model_note:'v0.1.3 consumes v0.1.2 player_state plus role intelligence',finished_gameweeks:maxGw,result_runs:runs.length,valid_actual_players:[...agg.keys()].length,players_considered:(baseRows||[]).length,inserted:rows.length,unchanged,no_base_state:noBase,as_of:at,historical_forecasts_rewritten:false});
}catch(e){return Response.json({ok:false,error:emsg(e)},{status:500})}});
