import { createClient } from 'npm:@supabase/supabase-js@2.112.3';

const H={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, content-type, x-engine-token','Content-Type':'application/json','Cache-Control':'no-store'};
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
const hasPath=(obj:any,path:string)=>path.split('.').reduce((v,k)=>v!=null&&Object.prototype.hasOwnProperty.call(v,k)?v[k]:undefined,obj)!==undefined;
const getPath=(obj:any,path:string)=>path.split('.').reduce((v,k)=>v==null?undefined:v[k],obj);
const sha256=async(text:string)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)))).map(b=>b.toString(16).padStart(2,'0')).join('');
const n=(v:any):number|null=>{if(v==null||v==='')return null;if(typeof v==='object'&&Object.prototype.hasOwnProperty.call(v,'value'))return n(v.value);if(typeof v==='number')return Number.isFinite(v)?v:null;const s=String(v).trim().replace(/,/g,'');const m=s.match(/-?\d+(?:\.\d+)?/);return m&&Number.isFinite(Number(m[0]))?Number(m[0]):null};
const clean=(s:string)=>String(s||'').toLowerCase().replace(/&/g,'and').replace(/[^a-z0-9]+/g,' ').trim().replace(/\b(fc|afc)\b/g,'').replace(/\s+/g,' ').trim();
const aliases:Record<string,string>={'manchester city':'man city','manchester united':'man utd','tottenham hotspur':'spurs','tottenham':'spurs','nottingham forest':'nott m forest','nott m forest':'nott m forest','brighton and hove albion':'brighton','newcastle united':'newcastle','leeds united':'leeds','coventry':'coventry city','hull':'hull city','ipswich':'ipswich town'};
const canon=(s:string)=>aliases[clean(s)]||clean(s);
const shape=(v:any)=>{if(Array.isArray(v))return{type:'array',length:v.length,first_item_keys:v.length&&v[0]&&typeof v[0]==='object'?Object.keys(v[0]).slice(0,30):[]};if(v&&typeof v==='object')return{type:'object',keys:Object.keys(v).slice(0,40),array_children:Object.fromEntries(Object.entries(v).filter(([,x])=>Array.isArray(x)).slice(0,10).map(([k,x])=>[k,(x as any[]).length]))};return{type:typeof v}};
const inferCount=(json:any,countPath?:string)=>{if(countPath){const v=getPath(json,countPath);if(Array.isArray(v))return v.length;if(typeof v==='number')return v}for(const v of [json?.statsData,json?.statsData?.stats,json?.statsData?.items,json?.statsData?.players,json?.statsData?.teams,json?.events,json?.shotmap])if(Array.isArray(v))return v.length;return null};

type ProbeSpec={source_key:string;endpoint_kind:string;url:string;provider_object_id?:string;gameweek?:number;provider_match_id?:string;evidence_class?:'direct'|'derived'|'proxy'|'metadata';checks?:string[];countPath?:string;notes?:string};

Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:H});try{
  const ks=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')||'{}');const sb=createClient(Deno.env.get('SUPABASE_URL')!,ks.default||Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false}});
  const {data:adminToken,error:authError}=await sb.rpc('get_backend_secret',{secret_name:'FOOTBALL_ENGINE_ADMIN_TOKEN'});if(authError||!adminToken||req.headers.get('x-engine-token')!==adminToken)return new Response(JSON.stringify({ok:false,error:'Unauthorized'}),{status:401,headers:H});
  const body=await req.json().catch(()=>({}));const mode=String(body.mode||'catalog');const capturedAt=new Date().toISOString();const results:any[]=[];
  const fetchJson=async(url:string)=>{const u=new URL(url);if(u.protocol!=='https:'||!['www.fotmob.com','api.sofascore.com'].includes(u.hostname))throw new Error(`Blocked probe host: ${u.hostname}`);const headers:Record<string,string>={'user-agent':'Mozilla/5.0 football-intelligence-engine-source-proof/0.5','accept':'application/json,text/plain,*/*'};headers['referer']=u.hostname==='www.fotmob.com'?'https://www.fotmob.com/':'https://www.sofascore.com/';const res=await fetch(url,{headers,redirect:'follow'});const text=await res.text();let json:any=null,parseOk=false,errorNote:string|null=null;try{json=JSON.parse(text);parseOk=true}catch(e){errorNote=`json_parse:${e instanceof Error?e.message:String(e)}`};return{res,text,json,parseOk,errorNote,payloadHash:text?await sha256(text):null}};
  const runProbe=async(spec:ProbeSpec)=>{let status:number|null=null,contentType:string|null=null,text='',json:any=null,parseOk=false,errorNote:string|null=null,payloadHash:string|null=null;try{const r=await fetchJson(spec.url);status=r.res.status;contentType=r.res.headers.get('content-type');text=r.text;json=r.json;parseOk=r.parseOk;errorNote=r.errorNote;payloadHash=r.payloadHash}catch(e){errorNote=`fetch:${e instanceof Error?e.message:String(e)}`};const checks=Object.fromEntries((spec.checks||[]).map(p=>[p,parseOk?hasPath(json,p):false]));const recordCount=parseOk?inferCount(json,spec.countPath):null;const row={change_id:'C0139',source_key:spec.source_key,endpoint_kind:spec.endpoint_kind,source_url:spec.url,provider_object_id:spec.provider_object_id||null,gameweek:spec.gameweek??null,provider_match_id:spec.provider_match_id||null,http_status:status,ok:status!=null&&status>=200&&status<300,parse_ok:parseOk,content_type:contentType,payload_bytes:new TextEncoder().encode(text).length,payload_sha256:payloadHash,top_level_keys:parseOk&&json&&typeof json==='object'&&!Array.isArray(json)?Object.keys(json).slice(0,100):[],field_presence:checks,record_count:recordCount,evidence_class:spec.evidence_class||'metadata',actual_data_used:true,evidence_cutoff:capturedAt,captured_at:capturedAt,research_only:true,model_effect_enabled:false,notes:[spec.notes,errorNote].filter(Boolean).join(' | ')||null};const{error}=await sb.from('research_source_access_probes').insert(row);if(error)throw new Error(`probe insert: ${error.message}`);const out={source_key:spec.source_key,endpoint_kind:spec.endpoint_kind,url:spec.url,http_status:status,ok:row.ok,parse_ok:parseOk,record_count:recordCount,field_presence:checks,top_level_shape:shape(json),statsData_shape:parseOk?shape(json?.statsData):null,error:errorNote};results.push(out);return{json,out,payloadHash}};

  const metricSpecs=[
    {stat_key:'phys_tdc_team',entity_type:'team',endpoint_kind:'fotmob_team_distance',evidence_class:'direct' as const},
    {stat_key:'phys_tdc',entity_type:'player',endpoint_kind:'fotmob_player_distance',evidence_class:'direct' as const},
    {stat_key:'phys_tdc_per_90',entity_type:'player',endpoint_kind:'fotmob_player_distance_per90',evidence_class:'direct' as const},
    {stat_key:'phys_sprints',entity_type:'player',endpoint_kind:'fotmob_player_sprints',evidence_class:'direct' as const},
    {stat_key:'phys_ts',entity_type:'player',endpoint_kind:'fotmob_player_top_speed',evidence_class:'direct' as const},
    {stat_key:'poss_won_att_3rd_team',entity_type:'team',endpoint_kind:'fotmob_final_third_wins',evidence_class:'proxy' as const}
  ];

  if(mode==='catalog'||mode==='fotmob_metrics'){for(const x of metricSpecs.filter(x=>['phys_tdc_team','phys_sprints','poss_won_att_3rd_team'].includes(x.stat_key))){const type=x.entity_type==='team'?'teams':'players';const url=`https://www.fotmob.com/api/data/leagueseasondeepstats?id=47&season=36781&type=${type}&stat=${x.stat_key}`;await runProbe({source_key:'fotmob_public',endpoint_kind:x.endpoint_kind,url,provider_object_id:`47:36781:${x.stat_key}`,evidence_class:x.evidence_class,checks:['statsData','currentSeasonId','currentStatName'],notes:x.evidence_class==='proxy'?'Pressing-output proxy only; never label true pressure.':'Current EPL physical metric coverage probe; research-only.'});await sleep(120)}}

  if(mode==='catalog'||mode==='fotmob_league')await runProbe({source_key:'fotmob_public',endpoint_kind:'fotmob_league_2026_27',url:'https://www.fotmob.com/api/data/leagues?id=47&ccode3=ENG&season=2026%2F2027',provider_object_id:'47:2026/2027',evidence_class:'metadata',checks:['fixtures','details'],notes:'Current EPL league/fixture discovery probe.'});

  if(mode==='fotmob_ingest'){
    const {data:teams,error:te}=await sb.from('teams').select('id,name');if(te)throw te;const teamByName=new Map((teams||[]).map((t:any)=>[canon(t.name),t.id]));const providerTeamMap=new Map<string,number>();const ingestion:any[]=[];
    for(const x of metricSpecs){const type=x.entity_type==='team'?'teams':'players';const url=`https://www.fotmob.com/api/data/leagueseasondeepstats?id=47&season=36781&type=${type}&stat=${x.stat_key}`;const r=await fetchJson(url);const status=r.res.status;if(status<200||status>=300||!r.parseOk||!Array.isArray(r.json?.statsData)){await runProbe({source_key:'fotmob_public',endpoint_kind:x.endpoint_kind,url,provider_object_id:`47:36781:${x.stat_key}`,evidence_class:x.evidence_class,checks:['statsData'],notes:'Normalization ingest preflight failed; no metric rows written.'});ingestion.push({stat_key:x.stat_key,http_status:status,inserted:0,error:'unavailable_or_unparseable'});continue}
      const sourceRows=r.json.statsData as any[];if(x.entity_type==='team'){for(const it of sourceRows){const pid=String(it.teamId??it.id??'');const iid=teamByName.get(canon(it.name));if(pid&&iid)providerTeamMap.set(pid,iid)}}
      const rows=[];for(const it of sourceRows){const providerEntityId=String(it.id??it.teamId??'');if(!providerEntityId)continue;const providerTeamId=it.teamId==null?null:String(it.teamId);const internalTeamId=x.entity_type==='team'?teamByName.get(canon(it.name))??null:(providerTeamId?providerTeamMap.get(providerTeamId)??null:null);const statValue=n(it.statValue),substatValue=n(it.substatValue);const statFormat=it.statValue&&typeof it.statValue==='object'?String(it.statValue.format??'')||null:null;const statFractions=it.statValue&&typeof it.statValue==='object'?n(it.statValue.fractions):null;const substatFormat=it.substatValue&&typeof it.substatValue==='object'?String(it.substatValue.format??'')||null:null;const substatFractions=it.substatValue&&typeof it.substatValue==='object'?n(it.substatValue.fractions):null;const observationHash=await sha256(`${r.payloadHash}|${x.stat_key}|${providerEntityId}|${statValue}|${statFormat}|${substatValue}|${substatFormat}`);rows.push({change_id:'C0139',source_key:'fotmob_public',league_id:47,season_id:36781,entity_type:x.entity_type,stat_key:x.stat_key,provider_entity_id:providerEntityId,provider_team_id:providerTeamId,internal_team_id:internalTeamId,entity_name:String(it.name||providerEntityId),position:it.position==null?null:String(it.position),stat_value:statValue,substat_value:substatValue,rank:n(it.rank),stat_format:statFormat,stat_fractions:statFractions,substat_format:substatFormat,substat_fractions:substatFractions,source_url:url,payload_sha256:r.payloadHash,observation_hash:observationHash,actual_data_used:true,evidence_cutoff:capturedAt,captured_at:capturedAt,research_only:true,model_effect_enabled:false,mapping_method:internalTeamId?(x.entity_type==='team'?'canonical_team_name':'fotmob_team_id_via_team_metric'):null,notes:x.evidence_class==='proxy'?'Pressing-output proxy only; not true pressure.':'Post-match/current-season research snapshot; provider-native numeric value and format preserved; not pre-kickoff forecast evidence.'})}
      let inserted=0;if(rows.length){const {data,error}=await sb.from('research_fotmob_metric_observations').upsert(rows,{onConflict:'observation_hash',ignoreDuplicates:true}).select('id');if(error)throw new Error(`metric upsert ${x.stat_key}: ${error.message}`);inserted=(data||[]).length}ingestion.push({stat_key:x.stat_key,http_status:status,source_rows:sourceRows.length,inserted,usable_value_rows:rows.filter((z:any)=>z.stat_value!=null).length,mapped_internal_team_rows:rows.filter((z:any)=>z.internal_team_id!=null).length,formats:[...new Set(rows.map((z:any)=>z.stat_format).filter(Boolean))]});await sleep(120)
    }
    return new Response(JSON.stringify({ok:true,mode,ingestion,provider_team_map_size:providerTeamMap.size,model_effect_enabled:false,note:'Normalized post-match/public-source research snapshots only. Provider-native numeric values and format metadata are preserved. These rows are outcome-known current-season evidence and are not eligible to rewrite frozen forecasts.'}),{headers:H});
  }

  if(mode==='catalog'||mode==='sofascore_gw1'){await runProbe({source_key:'sofascore_public',endpoint_kind:'sofascore_seasons',url:'https://api.sofascore.com/api/v1/unique-tournament/17/seasons',provider_object_id:'17',evidence_class:'metadata',checks:['seasons'],countPath:'seasons',notes:'Season-discovery endpoint proof.'});const round=await runProbe({source_key:'sofascore_public',endpoint_kind:'sofascore_round_events',url:'https://api.sofascore.com/api/v1/unique-tournament/17/season/96668/events/round/1',provider_object_id:'17:96668:1',gameweek:1,evidence_class:'metadata',checks:['events'],countPath:'events',notes:'2026/27 EPL round-1 event discovery proof.'});if(mode==='sofascore_gw1'&&round.json&&Array.isArray(round.json.events)){for(const ev of round.json.events.slice(0,10)){const id=String(ev.id),base=`https://api.sofascore.com/api/v1/event/${id}`;await runProbe({source_key:'sofascore_public',endpoint_kind:'sofascore_lineups',url:`${base}/lineups`,provider_object_id:id,provider_match_id:id,gameweek:1,evidence_class:'direct',checks:['home.players','away.players'],notes:'Source-backed lineups/formation proof; no FPL-shape substitution.'});await sleep(200);await runProbe({source_key:'sofascore_public',endpoint_kind:'sofascore_average_positions',url:`${base}/average-positions`,provider_object_id:id,provider_match_id:id,gameweek:1,evidence_class:'direct',checks:['home','away'],notes:'Average positions are aggregate spatial evidence, not continuous tracking.'});await sleep(200);await runProbe({source_key:'sofascore_public',endpoint_kind:'sofascore_shotmap',url:`${base}/shotmap`,provider_object_id:id,provider_match_id:id,gameweek:1,evidence_class:'direct',checks:['shotmap'],countPath:'shotmap',notes:'Shot-coordinate/context proof for chance-origin research.'});await sleep(250)}}}
  return new Response(JSON.stringify({ok:true,mode,probes:results,model_effect_enabled:false,note:'Coverage/source proof only. No raw third-party payload is persisted, no source is production-ready, and no forecast cohort is mutated.'}),{headers:H});
}catch(e){return new Response(JSON.stringify({ok:false,error:e instanceof Error?e.message:String(e),model_effect_enabled:false}),{status:500,headers:H})}});