(function(){
  // C0165 — compact fixture page, no-clear-edge semantics, balanced human modal, scroll lock.
  const FACT_API='https://knooiwezzsxcwhtjtdap.supabase.co/functions/v1/fixture-facts-api';
  const NO_EDGE=0.05;
  let factsGw=null,factsPayload=null,factsPromise=null,requestSeq=0,lockY=0;
  const bundles=new Map();
  const priorOpenDrawer17=openDrawer,priorCloseDrawer17=closeDrawer;
  const n=v=>num(v),pc=(v,d=0)=>n(v)==null?'—':`${(Number(v)*100).toFixed(d)}%`;
  const disp=s=>String(s||'—').replace('-', '–');

  function setBundles(j){bundles.clear();for(const f of j?.fixtures||[])bundles.set(Number(f.match_id),f)}
  async function ensureFacts(gw){
    gw=Number(gw||0);if(!gw)return null;
    if(factsGw===gw&&factsPayload)return factsPayload;
    if(factsPromise?.gw===gw)return factsPromise.promise;
    if(factsGw!==gw){factsGw=null;factsPayload=null;bundles.clear()}
    const promise=(async()=>{const r=await fetch(`${FACT_API}?gw=${gw}`,{cache:'no-store'}),j=await r.json();if(!r.ok||!j?.ok)throw new Error(j?.error||`HTTP ${r.status}`);if(Number(state.gw)!==gw)return null;factsPayload=j;factsGw=gw;setBundles(j);if(state.route==='fixtures')render();return j})();
    factsPromise={gw,promise};try{return await promise}finally{if(factsPromise?.promise===promise)factsPromise=null}
  }
  function thesis(ff){
    const mk=ff?.prediction?.markets||{},rows=[['H',n(mk.home_win)],['D',n(mk.draw)],['A',n(mk.away_win)]].filter(x=>x[1]!=null).sort((a,b)=>b[1]-a[1]);
    return rows.length===3?{outcome:rows[0][0],prob:rows[0][1],secondOutcome:rows[1][0],second:rows[1][1],margin:rows[0][1]-rows[1][1],home:n(mk.home_win),draw:n(mk.draw),away:n(mk.away_win)}:null;
  }
  const weak=th=>!!th&&th.margin<NO_EDGE;
  function sideName(o,f,b,short=false){const h=b?.home||f?.home_team||{},a=b?.away||f?.away_team||{};if(o==='H')return short?(h.short_name||h.name||'HOME'):(h.name||'Home');if(o==='A')return short?(a.short_name||a.name||'AWAY'):(a.name||'Away');return 'Draw'}
  function actualOutcome(f,ff){const h=ff?.home_score??f?.home_score,a=ff?.away_score??f?.away_score;if(h==null||a==null)return null;return Number(h)>Number(a)?'H':Number(h)<Number(a)?'A':'D'}
  function done(f,ff){return Boolean(f?.finished||ff?.finished)}
  function scoreCall(ff){return ff?.prediction?.headline_score||modelScore(ff)}
  function scoreProb(ff){return n(ff?.prediction?.headline_score_probability??ff?.prediction?.top_scoreline_probability)}

  function family(x){const t=String(x?.fact_type||'');if(t==='MODEL_SCORING_EDGE')return'MODEL';if(t==='ATTACK_DEFENCE_XG_CONTRAST')return'MATCHUP_XG';if(t==='SCORING_VS_CLEAN_SHEET')return'SCORE_DEFENCE';if(t==='FAV_ATTACK_XG'||t==='FAV_GOAL_OUTPUT')return'ATTACK_PROCESS';if(t==='FAV_SHOT_VOLUME')return'SHOT_VOLUME';if(t==='OPP_GOALS_CONCEDED')return'OPP_DEFENCE';if(['WINNING_STREAK','UNBEATEN_STREAK','WINLESS_STREAK','LOSING_STREAK'].includes(t))return'RESULT_STREAK';if(['SCORING_STREAK','FAILED_TO_SCORE_STREAK','CONCEDING_STREAK','CLEAN_SHEET_STREAK'].includes(t))return'SCORING_STREAK';if(t==='HOME_AWAY_FORM')return'VENUE_FORM';return t||'OTHER'}
  function distinct(rows,max=5){const fam=new Set(),txt=new Set(),out=[];for(const x of [...(rows||[])].sort((a,b)=>Number(b.usefulness_score)-Number(a.usefulness_score))){const f=family(x),t=String(x.one_liner||'').trim().replace(/\s+/g,' ').toLowerCase();if(!t||fam.has(f)||txt.has(t))continue;fam.add(f);txt.add(t);out.push(x);if(out.length>=max)break}return out}
  function cardFacts(bundle,th){if(!bundle)return[];if(!weak(th))return [...(bundle.card_facts||[])].sort((a,b)=>Number(a.card_rank||99)-Number(b.card_rank||99)).slice(0,3);const all=bundle.modal_facts||[],sup=distinct(all.filter(x=>x.alignment==='SUPPORTS'),1),opp=distinct(all.filter(x=>x.alignment==='CONTRADICTS'),3);return [...sup,...opp].slice(0,3)}
  function resultLabel(team,r){const opp=r?.opponent_name||r?.opponent_short||'Opponent';return `${team?.name||'Team'} ${r.goals_for}–${r.goals_against} ${opp}`}
  function formDots(team,recent){const rows=(recent||[]).slice(0,5),dots=rows.map(r=>`<button type="button" class="c0162-form-dot ${String(r.result||'').toLowerCase()}" data-c0162-dot="1" data-label="${esc(resultLabel(team,r))}" data-date="${esc(dateOnly(r.fixture_kickoff))}" aria-label="${esc(resultLabel(team,r))}"></button>`);while(dots.length<5)dots.push('<span class="c0162-form-dot empty" aria-hidden="true"></span>');return `<div class="c0162-form">${dots.join('')}</div>`}
  function team(team,recent,away=false){return `<div class="c0165-team ${away?'away':''}"><strong>${esc(team?.short_name||team?.name||'—')}</strong><span>${esc(team?.name||'—')}</span>${formDots(team,recent)}</div>`}
  function probabilityStrip(f,th,b,finished,hit){if(!th)return'';const h=b?.home||f.home_team,a=b?.away||f.away_team,label=weak(th)?'NO CLEAR 1X2 EDGE':`${esc(sideName(th.outcome,f,b,true))} LEAN`;return `<div class="c0165-prob-strip ${weak(th)?'weak':''}"><div class="c0165-call-state"><strong>${label}</strong>${!weak(th)&&finished&&hit?'<i>✓</i>':''}</div><div class="c0165-threeway"><span class="${!weak(th)&&th.outcome==='H'?'active':''}">${esc(h?.short_name||'H')} ${pc(th.home)}</span><span class="${!weak(th)&&th.outcome==='D'?'active':''}">D ${pc(th.draw)}</span><span class="${!weak(th)&&th.outcome==='A'?'active':''}">${esc(a?.short_name||'A')} ${pc(th.away)}</span></div></div>`}

  renderFixtureCard=function(f){
    ensureFacts(Number(state.gw||0)).catch(()=>{});
    const ff=fixtureFpl(f.match_id);if(!ff?.prediction)return `<article class="fixture-card fixture-card-v17" data-fixture="${f.match_id}"><div class="c0165-match-row">${team(f.home_team,[],false)}<div class="c0165-score"><strong>—</strong></div>${team(f.away_team,[],true)}</div></article>`;
    const b=bundles.get(Number(f.match_id))||null,th=thesis(ff),isDone=done(f,ff),act=actualOutcome(f,ff),hit=isDone&&th&&act===th.outcome,score=scoreCall(ff),sp=scoreProb(ff),facts=cardFacts(b,th),exact=isDone&&String(ff?.home_score??f?.home_score)+'-'+String(ff?.away_score??f?.away_score)===String(score).replace('–','-');
    return `<article class="fixture-card fixture-card-v15 fixture-card-v17 ${weak(th)?'no-edge':''}" data-fixture="${f.match_id}">
      ${probabilityStrip(f,th,b,isDone,hit)}
      <div class="c0165-match-row">${team(b?.home||f.home_team,b?.home?.recent||[],false)}<div class="c0165-score"><span>Score call${sp!=null?` · ${pc(sp,1)}`:''}</span><strong>${esc(disp(score))}${exact?'<i>✓</i>':''}</strong>${isDone?`<small>Actual ${esc(disp(`${ff?.home_score??f?.home_score}-${ff?.away_score??f?.away_score}`))}</small>`:''}</div>${team(b?.away||f.away_team,b?.away?.recent||[],true)}</div>
      ${facts.length?`<button type="button" class="c0162-toggle c0165-toggle" data-c0162-toggle="1" aria-expanded="false">${weak(th)?'Why no clear edge?':'Why this call?'} <span>⌄</span></button><div class="c0162-expand"><div class="c0162-fact-list">${facts.map((x,i)=>`<div class="c0162-fact c0165-fact ${x.alignment==='CONTRADICTS'?'risk':'support'}"><i>${i+1}</i><span>${esc(x.one_liner)}</span></div>`).join('')}</div></div>`:''}
    </article>`;
  };

  function callAccuracy(fixtures){let settled=0,hits=0,noEdge=0;for(const f of fixtures.filter(x=>x.finished)){const ff=fixtureFpl(f.match_id),th=thesis(ff);if(!th)continue;if(weak(th)){noEdge++;continue}const act=actualOutcome(f,ff);if(!act)continue;settled++;if(act===th.outcome)hits++}return{settled,hits,noEdge,rate:settled?hits/settled:null}}
  renderFixtures=function(){
    const fi=state.fixtures;if(!fi)return errorBlock('Fixture intelligence unavailable',state.errors.fixtures);ensureFacts(Number(state.gw||0)).catch(()=>{});
    const fixtures=[...(fi.fixtures||[])].sort((a,b)=>new Date(a.kickoff_time)-new Date(b.kickoff_time)),finished=fixtures.filter(x=>x.finished).length,a=callAccuracy(fixtures);
    return `<div class="c0165-summary">${stat('Finished matches',`${finished}/${fixtures.length||10}`,finished===fixtures.length?'Gameweek complete':'Live gameweek progress')}${stat('1X2 call accuracy',a.rate==null?'—':pc(a.rate),a.settled?`${a.hits}/${a.settled} settled calls correct${a.noEdge?` · ${a.noEdge} no-edge`:''}`:(a.noEdge?`${a.noEdge} no-edge result${a.noEdge===1?'':'s'} · no categorical calls settled`:'No finished categorical calls yet'))}</div><div class="section c0165-fixture-section">${sectionHead(`GW${state.gw} fixtures`,'Tap a fixture for the full matchup story and evidence')}<div class="fixture-grid">${fixtures.map(f=>renderFixtureCard(f)).join('')||'<div class="empty-state">No fixtures.</div>'}</div></div>`;
  };

  function group(title,rows,klass=''){if(!rows?.length)return'';return `<div class="c0162-evidence-group ${klass}"><h4>${esc(title)}</h4>${rows.map(x=>`<div class="c0162-modal-fact"><span>${esc(x.one_liner)}</span></div>`).join('')}</div>`}
  function weakStory(fi,ff,b,th){const all=b?.modal_facts||[],sup=distinct(all.filter(x=>x.alignment==='SUPPORTS'),3),opp=distinct(all.filter(x=>x.alignment==='CONTRADICTS'),4),lead=sideName(th.outcome,fi,b),second=sideName(th.secondOutcome,fi,b),parts=[`There is no clear 1X2 edge. ${lead} are only the narrow probability leader at ${pc(th.prob)}, versus ${pc(th.second)} for ${second.toLowerCase()} and ${pc(th.draw)} for the draw.`];const s=sup[0];if(s?.fact_type==='ATTACK_DEFENCE_XG_CONTRAST')parts.push(`${lead}'s main positive is a modest recent chance-quality matchup edge, but it is not strong enough to separate the sides decisively.`);else if(s)parts.push(`There is some evidence supporting the ${lead} lean, but it is limited.`);if(opp.some(x=>x.fact_type==='HOME_AWAY_FORM'))parts.push(`The home/away results profile points the other way, while recent form also weakens the lean.`);else if(opp.length)parts.push(`Several recent-form indicators point the other way.`);parts.push(`That combination is why the engine does not issue a categorical winner call here.`);return parts.join(' ')}
  function strongStory(fi,ff,b,th){const all=b?.modal_facts||[],sup=distinct(all.filter(x=>x.alignment==='SUPPORTS'),5),risk=distinct(all.filter(x=>x.alignment==='CONTRADICTS'),2),fav=sideName(th.outcome,fi,b),second=sideName(th.secondOutcome,fi,b),parts=[`${fav} hold a meaningful 1X2 edge at ${pc(th.prob)}, compared with ${pc(th.second)} for ${second.toLowerCase()}.`];const model=sup.find(x=>x.fact_type==='MODEL_SCORING_EDGE'),contrast=sup.find(x=>x.fact_type==='ATTACK_DEFENCE_XG_CONTRAST'),attack=sup.find(x=>x.fact_type==='FAV_ATTACK_XG');if(model){const a=n(model.payload?.fav_lambda),d=n(model.payload?.dog_lambda);if(a!=null&&d!=null)parts.push(`The clearest structural reason is the projected scoring gap: about ${a.toFixed(2)} expected goals versus ${d.toFixed(2)}.`)}if(contrast)parts.push(`Recent chance creation and opponent defensive allowance point in the same direction.`);else if(attack)parts.push(`Recent underlying attacking output also supports the call.`);if(risk.length)parts.push(`There are still counter-signals, so the prediction should not be read as certainty.`);return parts.join(' ')}
  function modalHtml(fi,ff,mk,b){const th=thesis(ff),isWeak=weak(th),all=b?.modal_facts||[],sup=distinct(all.filter(x=>x.alignment==='SUPPORTS'),isWeak?3:5),opp=distinct(all.filter(x=>x.alignment==='CONTRADICTS'),isWeak?4:Math.min(2,sup.length)),home=fi?.home_team||b?.home||{name:ff?.home_team||mk?.home_team},away=fi?.away_team||b?.away||{name:ff?.away_team||mk?.away_team},finished=Boolean(fi?.finished||ff?.finished),story=th?(isWeak?weakStory(fi,ff,b,th):strongStory(fi,ff,b,th)):'';return `<div class="drawer-kicker">GW${state.gw} fixture intelligence</div><h2 class="drawer-title">${esc(home?.name||'—')} vs ${esc(away?.name||'—')}</h2><div class="drawer-sub">${dateTime(fi?.kickoff_time||ff?.kickoff_time||mk?.kickoff_time)}</div><div class="hero-meta"><span class="chip ${finished?'green':'blue'}">${finished?'Finished':isWeak?'No clear 1X2 edge':'Live pre-match'}</span><span class="chip">Score call ${esc(disp(scoreCall(ff)))}</span>${finished?`<span class="chip green">Actual ${actualScore(fi)}</span>`:''}</div>${story?`<div class="c0162-story"><span>Match story</span><p>${esc(story)}</p></div>`:''}<div class="c0162-modal-evidence"><h3>${isWeak?'Why there is no clear edge':'Evidence behind the call'}</h3>${group(isWeak?'Evidence for the slight lean':'Supporting evidence',sup,'support')}${group(isWeak?'Evidence the other way':'Risks to the call',opp,'risk')}<small>Fact snapshot after GW${factsPayload?.snapshot_run?.as_of_gameweek??'—'} · no target-fixture results used.</small></div>`}
  openFixture=async function(id){const seq=++requestSeq,gw=Number(state.gw||0);try{await ensureFacts(gw)}catch(e){console.warn('C0165 fact preload failed',e)}if(seq!==requestSeq||Number(state.gw)!==gw)return;const fi=fixtureIntel(id),ff=fixtureFpl(id),mk=fixtureMarket(id);if(!fi&&!ff&&!mk)return;const root=$('drawerContent');if(!root)return;root.innerHTML=modalHtml(fi,ff,mk,bundles.get(Number(id))||null);openDrawer()};

  openDrawer=function(){if(!document.body.classList.contains('c0165-modal-open')){lockY=window.scrollY||0;document.body.classList.add('c0165-modal-open');document.body.style.top=`-${lockY}px`}priorOpenDrawer17()};
  closeDrawer=function(){const was=document.body.classList.contains('c0165-modal-open');priorCloseDrawer17();if(was){document.body.classList.remove('c0165-modal-open');document.body.style.top='';window.scrollTo(0,lockY)}};

  const boot=setInterval(()=>{const gw=Number(state.gw||0);if(gw&&factsGw!==gw&&!factsPromise)ensureFacts(gw).catch(()=>{});if(gw&&factsGw===gw)clearInterval(boot)},500);setTimeout(()=>clearInterval(boot),45000);
})();
