import { createClient } from 'jsr:@supabase/supabase-js@2';
const VERSION='C0248_SEQUENTIAL_PLANNER_V04_WILDCARD_ROOT';
const N=(x:any,d=0)=>Number.isFinite(Number(x))?Number(x):d;
const POS=['GKP','DEF','MID','FWD']; const NEED:any={GKP:2,DEF:5,MID:5,FWD:3};
const FORM=[[3,4,3],[3,5,2],[4,3,3],[4,4,2],[4,5,1],[5,2,3],[5,3,2],[5,4,1]];
function sell(now:number,buy:number){return now<=buy?now:buy+Math.floor((now-buy)/2)}
function skey(ids:number[],bank:number,ft:number){return [...ids].sort((a,b)=>a-b).join('-')+'|'+bank+'|'+ft}
async function sha(x:any){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(x)));return[...new Uint8Array(b)].map(v=>v.toString(16).padStart(2,'0')).join('')}
function bestXI(sq:any[],gw:number){let best:any=null;for(const[d,m,f]of FORM){const pick=(p:string,n:number)=>sq.filter(x=>x.position===p).sort((a,b)=>N(b.pred.get(gw)?.expected_points)-N(a.pred.get(gw)?.expected_points)).slice(0,n);const xi=[...pick('GKP',1),...pick('DEF',d),...pick('MID',m),...pick('FWD',f)];if(xi.length!==11)continue;const xp=xi.reduce((s,p)=>s+N(p.pred.get(gw)?.expected_points),0);const capScore=(p:any)=>{const q=p.pred.get(gw);return N(q.expected_points)+N(q.p_5_plus)+2.5*N(q.p_10_plus)+4*N(q.p_15_plus)+6*N(q.p_20_plus)-.5*N(q.p_blank)};const caps=[...xi].sort((a,b)=>capScore(b)-capScore(a)||N(b.pred.get(gw)?.expected_points)-N(a.pred.get(gw)?.expected_points));const xiIds=new Set(xi.map(x=>x.id));const bench=sq.filter(x=>!xiIds.has(x.id));const bg=bench.filter(x=>x.position==='GKP').sort((a,b)=>N(b.pred.get(gw)?.expected_points)-N(a.pred.get(gw)?.expected_points));const bo=bench.filter(x=>x.position!=='GKP').sort((a,b)=>N(b.pred.get(gw)?.expected_points)-N(a.pred.get(gw)?.expected_points));const gk=xi.find(x=>x.position==='GKP');let autosub=Math.max(0,Math.min(1,1-N(gk?.pred.get(gw)?.p_start,.9)))*(bg.length?N(bg[0].pred.get(gw)?.expected_points):0);const miss=Math.min(3,xi.filter(x=>x.position!=='GKP').reduce((s,p)=>s+Math.max(0,Math.min(1,1-N(p.pred.get(gw)?.p_start,.9))),0));for(let i=0;i<Math.min(3,bo.length);i++)autosub+=Math.max(0,Math.min(1,miss-i))*N(bo[i].pred.get(gw)?.expected_points);const z={formation:`${d}-${m}-${f}`,xi,bench:[...bg,...bo],xiPts:xp,captain:caps[0],vice:caps[1],autosub};if(!best||xp>best.xiPts)best=z}return best}
Deno.serve(async(req:Request)=>{try{
 const keys=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')||'{}'),sk=keys.default||Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!sk)return Response.json({ok:false,error:'service credential missing'},{status:500});const sb=createClient(Deno.env.get('SUPABASE_URL')!,sk,{auth:{persistSession:false}});const{data:tok,error:ae}=await sb.rpc('get_backend_secret',{secret_name:'FOOTBALL_ENGINE_ADMIN_TOKEN'});if(ae||!tok||req.headers.get('x-engine-token')!==tok)return Response.json({ok:false,error:'unauthorized'},{status:401});
 const b=await req.json().catch(()=>({})),gw=N(b.gameweek),h=Math.max(1,Math.min(5,N(b.horizon,5))),branchBeam=Math.max(4,Math.min(20,N(b.branch_beam_width,8))),maxActions=Math.max(20,Math.min(180,N(b.max_actions_per_state,100))),weights=(Array.isArray(b.weights)?b.weights:[1,.82,.68,.56,.46]).slice(0,h).map((x:any)=>Math.max(0,N(x)));if(!gw)return Response.json({ok:false,status:'INVALID_REQUEST'},{status:400});const gws=Array.from({length:h},(_,i)=>gw+i);
 const{data:mv,error:mve}=await sb.from('model_versions').select('id').eq('is_active',true).order('created_at',{ascending:false}).limit(1).single();if(mve)throw mve;const{data:runs,error:re}=await sb.from('gameweek_prediction_runs').select('id,gameweek,generated_at').eq('model_version_id',mv.id).in('gameweek',gws).order('generated_at',{ascending:false});if(re)throw re;const latest=new Map<number,any>();for(const r of runs||[])if(!latest.has(N(r.gameweek)))latest.set(N(r.gameweek),r);if(gws.some(x=>!latest.has(x)))return Response.json({ok:false,status:'HORIZON_PROJECTION_MISSING'},{status:409});
 const preds:any[]=[];for(const g of gws){const{data,error}=await sb.from('model_predictions').select('player_id,gameweek,expected_points,expected_minutes,p_start,p_blank,p_5_plus,p_10_plus,p_15_plus,p_20_plus').eq('prediction_run_id',N(latest.get(g).id)).range(0,999);if(error)throw error;preds.push(...(data||[]))}const roles:any[]=[];for(const g of gws){const{data,error}=await sb.from('current_player_fixture_roles').select('player_id,gameweek,primary_role,confidence').eq('gameweek',g).range(0,999);if(error)throw error;roles.push(...(data||[]))}
 const[{data:players,error:pe},{data:ms,error:mse},{data:adv,error:ade},{data:ens,error:ene},{data:regs,error:rge}]=await Promise.all([sb.from('players').select('id,team_id,web_name,position,now_cost,status'),sb.from('fpl_manager_state_snapshots').select('id,free_transfers,bank_tenths,evidence').eq('gameweek',gw).order('captured_at',{ascending:false}).limit(1).single(),sb.from('fpl_final_adversarial_runs').select('id,result').eq('gameweek',gw).eq('horizon',h).order('captured_at',{ascending:false}).limit(1).maybeSingle(),sb.from('fpl_squad_ensemble_runs').select('id,result').eq('gameweek',gw).eq('horizon',h).order('captured_at',{ascending:false}).limit(1).maybeSingle(),sb.from('fpl_named_challenger_registry').select('id,challenger_key,required_player_ids').eq('gameweek',gw).eq('horizon',h).eq('active',true)]);if(pe||mse||ade||ene||rge)throw pe||mse||ade||ene||rge;
 const pm=new Map<number,Map<number,any>>();for(const q of preds){const id=N(q.player_id),g=N(q.gameweek);if(!pm.has(id))pm.set(id,new Map());pm.get(id)!.set(g,q)}const rm=new Map<string,any>();for(const r of roles)rm.set(`${N(r.player_id)}:${N(r.gameweek)}`,r);const CONTROL=new Set(['HOLDING_MIDFIELDER','CENTRE_BACK','HYBRID_DEFENDER','WIDE_BACK','GOALKEEPER']);const pool:any[]=[];for(const p of players||[]){if(!POS.includes(String(p.position))||!pm.has(N(p.id))||gws.some(g=>!pm.get(N(p.id))!.has(g)))continue;let rr=false;if(['MID','FWD'].includes(String(p.position))){let seen=0,risk=0;for(const g of gws){const r=rm.get(`${N(p.id)}:${g}`);if(r){seen++;if(N(r.confidence)>=.7&&CONTROL.has(String(r.primary_role)))risk++}}rr=seen>0&&risk/seen>=.5}if(rr)continue;pool.push({id:N(p.id),team:N(p.team_id),name:String(p.web_name),position:String(p.position),price:N(p.now_cost),pred:pm.get(N(p.id))!})}const pmap=new Map(pool.map(p=>[p.id,p]));
 const assets=Array.isArray(ms.evidence?.squad)?ms.evidence.squad:[];if(assets.length!==15)return Response.json({ok:false,status:'MANAGER_SQUAD_EVIDENCE_INVALID'},{status:409});const initIds=assets.map((x:any)=>N(x.player_id));if(initIds.some((id:number)=>!pmap.has(id)))return Response.json({ok:false,status:'CURRENT_SQUAD_PLAYER_MISSING_FROM_POOL'},{status:409});const initBuy=new Map<number,number>(assets.map((x:any)=>[N(x.player_id),N(x.purchase_price_tenths,pmap.get(N(x.player_id))?.price)]));
 const byPos:any={};for(const pos of POS)byPos[pos]=pool.filter(p=>p.position===pos).sort((a,b)=>gws.reduce((s,g,i)=>s+weights[i]*(N(b.pred.get(g)?.expected_points)-N(a.pred.get(g)?.expected_points)),0)).slice(0,pos==='GKP'?12:pos==='DEF'?28:pos==='MID'?34:24);
 function legal(ids:number[]){if(ids.length!==15||new Set(ids).size!==15)return false;const pc:any={},tc:any={};for(const id of ids){const p=pmap.get(id);if(!p)return false;pc[p.position]=(pc[p.position]||0)+1;tc[p.team]=(tc[p.team]||0)+1;if(tc[p.team]>3)return false}return POS.every(p=>pc[p]===NEED[p])}
 function apply(st:any,outs:number[],ins:number[]){if(outs.length!==ins.length)return null;let ids=[...st.ids],buy=new Map(st.buy),bank=st.bank;for(let i=0;i<outs.length;i++){const oi=outs[i],ni=ins[i],idx=ids.indexOf(oi);if(idx<0||ids.includes(ni))return null;const op=pmap.get(oi),np=pmap.get(ni);if(!op||!np||op.position!==np.position)return null;bank+=sell(op.price,N(buy.get(oi),op.price))-np.price;ids[idx]=ni;buy.delete(oi);buy.set(ni,np.price)}if(bank<0||!legal(ids))return null;return{...st,ids,buy,bank}}
 function util(st:any,g:number,used:number){const z=bestXI(st.ids.map((id:number)=>pmap.get(id)),g);if(!z)return null;const hit=Math.max(0,used-st.ft)*4,cap=N(z.captain.pred.get(g)?.expected_points);return{u:z.xiPts+cap+z.autosub-hit,hit,z}}
 function forcedTransfers(xs:any){return (xs||[]).map((x:any)=>[N(x.out_player_id),N(x.in_player_id)]).filter((x:any)=>x[0]&&x[1])}
 function diffToTarget(target:number[]){const t=new Set(target),c=new Set(initIds);return{outs:initIds.filter(x=>!t.has(x)),ins:target.filter(x=>!c.has(x))}}
 function actionsFor(st:any,g:number){const selected=new Set(st.ids),singles:any[]=[];for(const oid of st.ids){const op=pmap.get(oid)!;for(const np of byPos[op.position].slice(0,10)){if(selected.has(np.id))continue;singles.push({outs:[oid],ins:[np.id],gain:N(np.pred.get(g)?.expected_points)-N(op.pred.get(g)?.expected_points),tag:'1FT'})}}singles.sort((a,b)=>b.gain-a.gain);const top=singles.slice(0,18),acts:any[]=[{outs:[],ins:[],tag:'ROLL'},...top];for(let i=0;i<top.length&&acts.length<maxActions;i++)for(let j=i+1;j<top.length&&acts.length<maxActions;j++){const a=top[i],c=top[j];if(a.outs[0]===c.outs[0]||a.ins[0]===c.ins[0]||a.ins[0]===c.outs[0]||c.ins[0]===a.outs[0])continue;acts.push({outs:[a.outs[0],c.outs[0]],ins:[a.ins[0],c.ins[0]],tag:'2FT'})}return acts}
 function stepState(st:any,g:number,w:number,a:any){const ns=apply(st,a.outs,a.ins);if(!ns)return null;const ev=util(ns,g,a.outs.length);if(!ev)return null;const ftNext=Math.min(5,Math.max(0,st.ft-a.outs.length)+1),z=ev.z;return{...ns,root:st.root,ft:ftNext,score:st.score+w*ev.u,path:[...st.path,{gameweek:g,tag:a.tag,root:st.root,chip:'NONE',outs:a.outs,ins:a.ins,free_transfers_before:st.ft,free_transfers_after:ftNext,bank_after:ns.bank,hit_points:ev.hit,gw_utility:+ev.u.toFixed(3),xi_expected_points:+z.xiPts.toFixed(3),expected_autosub_points:+z.autosub.toFixed(3),captain_player_id:z.captain.id,vice_player_id:z.vice.id,starting_xi:z.xi.map((p:any)=>p.id),bench_order:z.bench.map((p:any)=>p.id),formation:z.formation}]}}
 function wildcardState(st:any,target:number[],g:number,w:number){if(!legal(target))return null;const cur=new Set(st.ids),tar=new Set(target),outs=st.ids.filter((x:number)=>!tar.has(x)),ins=target.filter((x:number)=>!cur.has(x));let bank=st.bank,buy=new Map(st.buy);for(const oid of outs){const op=pmap.get(oid);if(!op)return null;bank+=sell(op.price,N(buy.get(oid),op.price));buy.delete(oid)}for(const ni of ins){const np=pmap.get(ni);if(!np)return null;bank-=np.price;buy.set(ni,np.price)}if(bank<0)return null;const ns={...st,ids:[...target],buy,bank};const ev=util(ns,g,0);if(!ev)return null;const z=ev.z;const ftNext=st.ft;return{...ns,root:'WILDCARD_FRESH',ft:ftNext,score:st.score+w*ev.u,path:[...st.path,{gameweek:g,tag:'ROOT_WILDCARD_FRESH',root:'WILDCARD_FRESH',chip:'WILDCARD',outs,ins,free_transfers_before:st.ft,free_transfers_after:ftNext,bank_after:bank,hit_points:0,gw_utility:+ev.u.toFixed(3),xi_expected_points:+z.xiPts.toFixed(3),expected_autosub_points:+z.autosub.toFixed(3),captain_player_id:z.captain.id,vice_player_id:z.vice.id,starting_xi:z.xi.map((p:any)=>p.id),bench_order:z.bench.map((p:any)=>p.id),formation:z.formation}]}}
 const forcedLegacy=forcedTransfers(adv?.result?.survivor?.transfers),forcedBase=forcedTransfers(ens?.result?.best_no_chip?.transfers);const init:any={ids:initIds,buy:initBuy,bank:N(ms.bank_tenths),ft:N(ms.free_transfers,1),score:0,path:[],root:'UNSET'};const firstActs=actionsFor(init,gw);const best1=[...firstActs].filter(x=>x.outs.length===1).sort((a,b)=>b.gain-a.gain)[0]||null;const pairCandidates=firstActs.filter(x=>x.outs.length===2),pairScored=pairCandidates.map(a=>({a,s:stepState({...init,root:'TMP'},gw,weights[0],a)?.score??-1e9})).sort((x,y)=>y.s-x.s);const best2=pairScored[0]?.a||null;
 const roots:any[]=[{name:'ROLL',type:'NORMAL',a:{outs:[],ins:[],tag:'ROOT_ROLL'}}];if(forcedBase.length)roots.push({name:'C0228_BASELINE',type:'NORMAL',a:{outs:forcedBase.map((x:any)=>x[0]),ins:forcedBase.map((x:any)=>x[1]),tag:'ROOT_C0228_BASELINE'}});if(forcedLegacy.length)roots.push({name:'C0240_LEGACY',type:'NORMAL',a:{outs:forcedLegacy.map((x:any)=>x[0]),ins:forcedLegacy.map((x:any)=>x[1]),tag:'ROOT_C0240_LEGACY'}});if(best1)roots.push({name:'BEST_GENERATED_1FT',type:'NORMAL',a:{...best1,tag:'ROOT_BEST_GENERATED_1FT'}});if(best2)roots.push({name:'BEST_GENERATED_2FT',type:'NORMAL',a:{...best2,tag:'ROOT_BEST_GENERATED_2FT'}});for(const r of regs||[]){const target=(r.required_player_ids||[]).map(Number);if(target.length!==15)continue;const d=diffToTarget(target);if(d.outs.length===d.ins.length&&d.outs.length<=5)roots.push({name:`NAMED:${r.challenger_key}`,type:'NORMAL',a:{outs:d.outs,ins:d.ins,tag:`ROOT_NAMED:${r.challenger_key}`}})}
 const fresh=(ens?.result?.candidates||[])[0];const freshTarget=(fresh?.squad||[]).map((x:any)=>N(x.player_id));if(freshTarget.length===15)roots.push({name:'WILDCARD_FRESH',type:'WILDCARD',target:freshTarget,profile:fresh?.profile});
 const branchMap=new Map<string,any[]>();for(const rt of roots){let s0:any=null;if(rt.type==='WILDCARD')s0=wildcardState({...init,root:rt.name},rt.target,gw,weights[0]);else s0=stepState({...init,root:rt.name},gw,weights[0],rt.a);if(s0)branchMap.set(rt.name,[s0])}if(!branchMap.size)return Response.json({ok:false,status:'NO_VALID_ROOT_BRANCHES'},{status:409});
 for(let step=1;step<h;step++){const g=gws[step],w=weights[step];for(const [root,states] of [...branchMap.entries()]){const next:any[]=[];for(const st of states){for(const a of actionsFor(st,g)){const ns=stepState(st,g,w,a);if(ns)next.push(ns)}}const ded=new Map<string,any>();for(const s of next){const k=skey(s.ids,s.bank,s.ft),o=ded.get(k);if(!o||s.score>o.score)ded.set(k,s)}const kept=[...ded.values()].sort((a,b)=>b.score-a.score).slice(0,branchBeam);if(!kept.length)branchMap.delete(root);else branchMap.set(root,kept)}}
 const branchResults=[...branchMap.entries()].map(([root,states])=>{const bb=states[0];return{root,score:+bb.score.toFixed(3),edge_vs_roll_root:0,final_ft:bb.ft,final_bank_tenths:bb.bank,first_action:bb.path[0],path:bb.path,final_squad:bb.ids}}).sort((a,b)=>b.score-a.score);const rollRoot=branchResults.find(x=>x.root==='ROLL');if(rollRoot)for(const x of branchResults)x.edge_vs_roll_root=+(x.score-rollRoot.score).toFixed(3);const best=branchResults[0];
 const result={ok:true,status:'SEQUENTIAL_PLANNER_WILDCARD_ROOT_SHADOW_READY',change_id:'C0248',planner_version:VERSION,shadow_only:true,production_selected:false,summary:{best_root:best.root,best_weighted_utility:best.score,roll_root_utility:rollRoot?.score??null,edge_vs_roll_root:best.edge_vs_roll_root,first_action:best.first_action,final_ft:best.final_ft,final_bank_tenths:best.final_bank_tenths},branch_results:branchResults,search:{branch_beam_width:branchBeam,max_actions_per_state:maxActions,root_count:branchResults.length,root_preservation:true,max_generated_normal_transfers_per_gw:2,wildcard_root_included:true,wildcard_saved_ft_policy:'RETAIN_CURRENT_BANKED_FT_COUNT_IN_FOLLOWING_GW',price_assumption:'STATIC_CURRENT_PRICES_NO_FORECAST',bb_tc_fh_actions:false},bench_policy:{type:'EXPECTED_AUTOSUB_V01',flat_bench_weight:false,starter_miss_proxy:'1-p_start',formation_legality_approximate:true},no_clairvoyance:{future_actions_are_policy_under_current_information:true,reoptimize_each_real_gameweek:true},historical_forecasts_rewritten:false};
 const sig=await sha({VERSION,gw,h,branchBeam,maxActions,weights,manager_state_id:ms.id,runs:gws.map(g=>N(latest.get(g).id)),prices:pool.map(p=>[p.id,p.price]),roots:roots.map(r=>[r.name,r.type,r.a?.outs||[],r.a?.ins||[],r.target||[]])});const{data:old,error:oe}=await sb.from('fpl_sequential_planner_runs').select('id').eq('input_signature',sig).maybeSingle();if(oe)throw oe;let id=old?.id?N(old.id):null;if(!id){const{data:ins,error:ie}=await sb.from('fpl_sequential_planner_runs').insert({gameweek:gw,horizon:h,manager_state_id:ms.id,prediction_run_ids:gws.map(g=>N(latest.get(g).id)),planner_version:VERSION,search_config:{branch_beam_width:branchBeam,max_actions_per_state:maxActions,weights,root_preservation:true,wildcard_root_included:true},input_signature:sig,result,shadow_only:true,production_selected:false,historical_forecasts_rewritten:false}).select('id').single();if(ie)throw ie;id=N(ins.id)}return Response.json({...result,planner_run_id:id,input_signature:sig});
}catch(e){return Response.json({ok:false,status:'SEQUENTIAL_PLANNER_ERROR',error:e instanceof Error?e.message:String(e),decisioning:false},{status:500})}});