import { createClient } from 'jsr:@supabase/supabase-js@2';
const VERSION='C0248_SEQUENTIAL_PLANNER_V06_CUTOVER_CANDIDATE';
const N=(x:any,d=0)=>Number.isFinite(Number(x))?Number(x):d;
const POS=['GKP','DEF','MID','FWD'];const NEED:any={GKP:2,DEF:5,MID:5,FWD:3};const FORM=[[3,4,3],[3,5,2],[4,3,3],[4,4,2],[4,5,1],[5,2,3],[5,3,2],[5,4,1]];const MIN:any={DEF:3,MID:2,FWD:1};
function sell(now:number,buy:number){return now<=buy?now:buy+Math.floor((now-buy)/2)}
function skey(ids:number[],bank:number,ft:number,chips:string[]){return [...ids].sort((a,b)=>a-b).join('-')+'|'+bank+'|'+ft+'|'+[...chips].sort().join(',')}
async function sha(x:any){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(x)));return[...new Uint8Array(b)].map(v=>v.toString(16).padStart(2,'0')).join('')}
function capScore(p:any,gw:number){const q=p.pred.get(gw);return N(q?.expected_points)+N(q?.p_5_plus)+2.5*N(q?.p_10_plus)+4*N(q?.p_15_plus)+6*N(q?.p_20_plus)-.5*N(q?.p_blank)}
function dist(ps:any[],gw:number){let d=[1];for(const p of ps){const a=Math.max(0,Math.min(1,N(p.pred.get(gw)?.p_start,.9))),n=new Array(d.length+1).fill(0);for(let k=0;k<d.length;k++){n[k]+=d[k]*(1-a);n[k+1]+=d[k]*a}d=n}return d}
function legalAutosubEV(xi:any[],bench:any[],gw:number){
 const gk=xi.find(p=>p.position==='GKP'),bg=bench.find(p=>p.position==='GKP');let ev=0;const pg=Math.max(0,Math.min(1,N(gk?.pred.get(gw)?.p_start,.9)));if(bg)ev+=(1-pg)*N(bg.pred.get(gw)?.expected_points);
 const out=xi.filter(p=>p.position!=='GKP'),bo=bench.filter(p=>p.position!=='GKP');const ds=dist(out.filter(p=>p.position==='DEF'),gw),ms=dist(out.filter(p=>p.position==='MID'),gw),fs=dist(out.filter(p=>p.position==='FWD'),gw);
 for(let dd=0;dd<ds.length;dd++)for(let mm=0;mm<ms.length;mm++)for(let ff=0;ff<fs.length;ff++){const ps=ds[dd]*ms[mm]*fs[ff];if(ps<1e-8)continue;const missing=10-(dd+mm+ff);if(missing<=0)continue;for(let mask=0;mask<(1<<bo.length);mask++){let pb=1;const av:number[]=[];for(let i=0;i<bo.length;i++){const a=Math.max(0,Math.min(1,N(bo[i].pred.get(gw)?.p_start,.85))),on=(mask>>i)&1;pb*=on?a:1-a;if(on)av.push(i)}if(pb<1e-8||av.length<missing)continue;let chosen:number[]|null=null;const combos=(arr:number[],need:number,start=0,cur:number[]=[]):number[][]=>{if(cur.length===need)return[[...cur]];const z:number[][]=[];for(let i=start;i<arr.length;i++)z.push(...combos(arr,need,i+1,[...cur,arr[i]]));return z};for(const c of combos(av,missing)){const cc:any={DEF:dd,MID:mm,FWD:ff};for(const i of c)cc[bo[i].position]++;if(cc.DEF>=MIN.DEF&&cc.MID>=MIN.MID&&cc.FWD>=MIN.FWD){chosen=c;break}}if(!chosen)continue;let pts=0;for(const i of chosen){const a=Math.max(.01,Math.min(1,N(bo[i].pred.get(gw)?.p_start,.85)));pts+=N(bo[i].pred.get(gw)?.expected_points)/a}ev+=ps*pb*pts}}
 return ev;
}
function bestXI(sq:any[],gw:number){let best:any=null;for(const[d,m,f]of FORM){const pick=(p:string,n:number)=>sq.filter(x=>x.position===p).sort((a,b)=>N(b.pred.get(gw)?.expected_points)-N(a.pred.get(gw)?.expected_points)).slice(0,n);const xi=[...pick('GKP',1),...pick('DEF',d),...pick('MID',m),...pick('FWD',f)];if(xi.length!==11)continue;const xp=xi.reduce((s,p)=>s+N(p.pred.get(gw)?.expected_points),0);const caps=[...xi].sort((a,b)=>capScore(b,gw)-capScore(a,gw)||N(b.pred.get(gw)?.expected_points)-N(a.pred.get(gw)?.expected_points));const set=new Set(xi.map(x=>x.id));const bench=sq.filter(x=>!set.has(x.id));const bg=bench.filter(x=>x.position==='GKP').sort((a,b)=>N(b.pred.get(gw)?.expected_points)-N(a.pred.get(gw)?.expected_points));const bo=bench.filter(x=>x.position!=='GKP').sort((a,b)=>N(b.pred.get(gw)?.expected_points)-N(a.pred.get(gw)?.expected_points));const z={formation:`${d}-${m}-${f}`,xi,bench:[...bg,...bo],xiPts:xp,captain:caps[0],vice:caps[1]};if(!best||xp>best.xiPts)best=z}if(!best)return null;best.autosub=legalAutosubEV(best.xi,best.bench,gw);best.benchPts=best.bench.reduce((s:any,p:any)=>s+N(p.pred.get(gw)?.expected_points),0);return best}
Deno.serve(async(req:Request)=>{try{
 const keys=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')||'{}'),sk=keys.default||Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!sk)return Response.json({ok:false,error:'service credential missing'},{status:500});const sb=createClient(Deno.env.get('SUPABASE_URL')!,sk,{auth:{persistSession:false}});const{data:tok,error:ae}=await sb.rpc('get_backend_secret',{secret_name:'FOOTBALL_ENGINE_ADMIN_TOKEN'});if(ae||!tok||req.headers.get('x-engine-token')!==tok)return Response.json({ok:false,error:'unauthorized'},{status:401});
 const b=await req.json().catch(()=>({})),gw=N(b.gameweek),h=Math.max(1,Math.min(5,N(b.horizon,5))),beam=Math.max(3,Math.min(12,N(b.branch_beam_width,6))),weights=(Array.isArray(b.weights)?b.weights:[1,.82,.68,.56,.46]).slice(0,h).map((x:any)=>Math.max(0,N(x)));if(!gw)return Response.json({ok:false,status:'INVALID_REQUEST'},{status:400});const gws=Array.from({length:h},(_,i)=>gw+i);
 const{data:mv,error:mve}=await sb.from('model_versions').select('id').eq('is_active',true).order('created_at',{ascending:false}).limit(1).single();if(mve)throw mve;const{data:runs,error:re}=await sb.from('gameweek_prediction_runs').select('id,gameweek,generated_at').eq('model_version_id',mv.id).in('gameweek',gws).order('generated_at',{ascending:false});if(re)throw re;const latest=new Map<number,any>();for(const r of runs||[])if(!latest.has(N(r.gameweek)))latest.set(N(r.gameweek),r);if(gws.some(x=>!latest.has(x)))return Response.json({ok:false,status:'HORIZON_PROJECTION_MISSING'},{status:409});
 const preds:any[]=[];for(const g of gws){const{data,error}=await sb.from('model_predictions').select('player_id,gameweek,expected_points,expected_minutes,p_start,p_blank,p_5_plus,p_10_plus,p_15_plus,p_20_plus').eq('prediction_run_id',N(latest.get(g).id)).range(0,999);if(error)throw error;preds.push(...(data||[]))}const roles:any[]=[];for(const g of gws){const{data,error}=await sb.from('current_player_fixture_roles').select('player_id,gameweek,primary_role,confidence').eq('gameweek',g).range(0,999);if(error)throw error;roles.push(...(data||[]))}
 const[{data:players,error:pe},{data:ms,error:mse},{data:adv,error:ade},{data:ens,error:ene},{data:regs,error:rge}]=await Promise.all([sb.from('players').select('id,team_id,web_name,position,now_cost,status'),sb.from('fpl_manager_state_snapshots').select('id,free_transfers,bank_tenths,evidence').eq('gameweek',gw).order('captured_at',{ascending:false}).limit(1).single(),sb.from('fpl_final_adversarial_runs').select('id,result').eq('gameweek',gw).eq('horizon',h).order('captured_at',{ascending:false}).limit(1).maybeSingle(),sb.from('fpl_squad_ensemble_runs').select('id,result,model_error_margin_points').eq('gameweek',gw).eq('horizon',h).order('captured_at',{ascending:false}).limit(1).maybeSingle(),sb.from('fpl_named_challenger_registry').select('id,challenger_key,required_player_ids').eq('gameweek',gw).eq('horizon',h).eq('active',true)]);if(pe||mse||ade||ene||rge)throw pe||mse||ade||ene||rge;
 const pm=new Map<number,Map<number,any>>();for(const q of preds){const id=N(q.player_id),g=N(q.gameweek);if(!pm.has(id))pm.set(id,new Map());pm.get(id)!.set(g,q)}const rm=new Map<string,any>();for(const r of roles)rm.set(`${N(r.player_id)}:${N(r.gameweek)}`,r);const CONTROL=new Set(['HOLDING_MIDFIELDER','CENTRE_BACK','HYBRID_DEFENDER','WIDE_BACK','GOALKEEPER']);const pool:any[]=[];for(const p of players||[]){if(!POS.includes(String(p.position))||!pm.has(N(p.id))||gws.some(g=>!pm.get(N(p.id))!.has(g)))continue;let rr=false;if(['MID','FWD'].includes(String(p.position))){let seen=0,risk=0;for(const g of gws){const r=rm.get(`${N(p.id)}:${g}`);if(r){seen++;if(N(r.confidence)>=.7&&CONTROL.has(String(r.primary_role)))risk++}}rr=seen>0&&risk/seen>=.5}if(rr)continue;pool.push({id:N(p.id),team:N(p.team_id),name:String(p.web_name),position:String(p.position),price:N(p.now_cost),pred:pm.get(N(p.id))!})}const pmap=new Map(pool.map(p=>[p.id,p]));
 const assets=Array.isArray(ms.evidence?.squad)?ms.evidence.squad:[];if(assets.length!==15)return Response.json({ok:false,status:'MANAGER_SQUAD_EVIDENCE_INVALID'},{status:409});const initIds=assets.map((x:any)=>N(x.player_id));if(initIds.some((id:number)=>!pmap.has(id)))return Response.json({ok:false,status:'CURRENT_SQUAD_PLAYER_MISSING_FROM_POOL'},{status:409});const initBuy=new Map<number,number>(assets.map((x:any)=>[N(x.player_id),N(x.purchase_price_tenths,pmap.get(N(x.player_id))?.price)]));
 const byPos:any={};for(const pos of POS)byPos[pos]=pool.filter(p=>p.position===pos).sort((a,b)=>gws.reduce((s,g,i)=>s+weights[i]*(N(b.pred.get(g)?.expected_points)-N(a.pred.get(g)?.expected_points)),0)).slice(0,pos==='GKP'?10:pos==='DEF'?24:pos==='MID'?28:20);
 function legal(ids:number[]){if(ids.length!==15||new Set(ids).size!==15)return false;const pc:any={},tc:any={};for(const id of ids){const p=pmap.get(id);if(!p)return false;pc[p.position]=(pc[p.position]||0)+1;tc[p.team]=(tc[p.team]||0)+1;if(tc[p.team]>3)return false}return POS.every(p=>pc[p]===NEED[p])}
 function apply(st:any,outs:number[],ins:number[]){if(outs.length!==ins.length)return null;let ids=[...st.ids],buy=new Map(st.buy),bank=st.bank;for(let i=0;i<outs.length;i++){const oi=outs[i],ni=ins[i],idx=ids.indexOf(oi);if(idx<0||ids.includes(ni))return null;const op=pmap.get(oi),np=pmap.get(ni);if(!op||!np||op.position!==np.position)return null;bank+=sell(op.price,N(buy.get(oi),op.price))-np.price;ids[idx]=ni;buy.delete(oi);buy.set(ni,np.price)}if(bank<0||!legal(ids))return null;return{...st,ids,buy,bank}}
 function util(st:any,g:number,used:number,chip='NONE'){const z=bestXI(st.ids.map((id:number)=>pmap.get(id)),g);if(!z)return null;const hit=['WILDCARD','FREE_HIT'].includes(chip)?0:Math.max(0,used-st.ft)*4,cap=N(z.captain.pred.get(g)?.expected_points);let u=z.xiPts+cap+z.autosub-hit;if(chip==='BENCH_BOOST')u=z.xiPts+cap+z.benchPts-hit;if(chip==='TRIPLE_CAPTAIN')u=z.xiPts+2*cap+z.autosub-hit;return{u,hit,z}}
 function forcedTransfers(xs:any){return (xs||[]).map((x:any)=>[N(x.out_player_id),N(x.in_player_id)]).filter((x:any)=>x[0]&&x[1])}
 function diffToTarget(target:number[]){const t=new Set(target),c=new Set(initIds);return{outs:initIds.filter(x=>!t.has(x)),ins:target.filter(x=>!c.has(x))}}
 function actionsFor(st:any,g:number){const selected=new Set(st.ids),singles:any[]=[];for(const oid of st.ids){const op=pmap.get(oid)!;for(const np of byPos[op.position].slice(0,8)){if(selected.has(np.id))continue;singles.push({outs:[oid],ins:[np.id],gain:N(np.pred.get(g)?.expected_points)-N(op.pred.get(g)?.expected_points),tag:'1FT'})}}singles.sort((a,b)=>b.gain-a.gain);const top=singles.slice(0,12),acts:any[]=[{outs:[],ins:[],tag:'ROLL'},...top.slice(0,10)];for(let n=2;n<=5;n++){const out:number[]=[],ins:number[]=[];for(const a of top){if(out.length===n)break;if(out.includes(a.outs[0])||ins.includes(a.ins[0])||ins.includes(a.outs[0])||out.includes(a.ins[0]))continue;out.push(a.outs[0]);ins.push(a.ins[0])}if(out.length===n)acts.push({outs:out,ins,gain:0,tag:`${n}FT_GREEDY`})}for(let i=0;i<Math.min(7,top.length);i++)for(let j=i+1;j<Math.min(7,top.length);j++){const a=top[i],c=top[j];if(a.outs[0]===c.outs[0]||a.ins[0]===c.ins[0]||a.ins[0]===c.outs[0]||c.ins[0]===a.outs[0])continue;acts.push({outs:[a.outs[0],c.outs[0]],ins:[a.ins[0],c.ins[0]],tag:'2FT_PAIR'})}return acts.slice(0,40)}
 function stepState(st:any,g:number,w:number,a:any,chip='NONE'){const ns=apply(st,a.outs,a.ins);if(!ns)return null;const ev=util(ns,g,a.outs.length,chip);if(!ev)return null;const ftNext=['WILDCARD','FREE_HIT'].includes(chip)?st.ft:Math.min(5,Math.max(0,st.ft-a.outs.length)+1),z=ev.z;const chips=[...st.chips];if(chip!=='NONE')chips.push(chip);return{...ns,root:st.root,ft:ftNext,chips,score:st.score+w*ev.u,path:[...st.path,{gameweek:g,tag:a.tag,root:st.root,chip,outs:a.outs,ins:a.ins,free_transfers_before:st.ft,free_transfers_after:ftNext,bank_after:ns.bank,hit_points:ev.hit,gw_utility:+ev.u.toFixed(3),xi_expected_points:+z.xiPts.toFixed(3),expected_autosub_points:+z.autosub.toFixed(3),bench_expected_points:+z.benchPts.toFixed(3),captain_player_id:z.captain.id,vice_player_id:z.vice.id,starting_xi:z.xi.map((p:any)=>p.id),bench_order:z.bench.map((p:any)=>p.id),formation:z.formation,price_stress:{current_price_feasible:true,one_tenth_adverse_event_feasible:ns.bank>=1,bank_headroom_tenths:ns.bank}}]}}
 async function optimizerFresh(hh:number){const r=await fetch(`${Deno.env.get('SUPABASE_URL')}/functions/v1/fpl-full-pool-optimizer`,{method:'POST',headers:{'content-type':'application/json','x-engine-token':String(tok),'authorization':`Bearer ${sk}`},body:JSON.stringify({gameweek:gw,horizon:hh})});const j=await r.json().catch(()=>null);if(!r.ok||!j?.ok)return null;const q=j.wildcard_benchmark||j.fresh_ensemble?.[0];const ids=(q?.squad||[]).map((x:any)=>N(x.player_id));return ids.length===15?{ids,source:j.role_safe_adapter_version||j.version||'FULL_POOL_OPTIMIZER',objective:q?.objective??null}:null}
 const [wcFresh,fhFresh]=await Promise.all([optimizerFresh(h),optimizerFresh(1)]);if(!wcFresh||!fhFresh)return Response.json({ok:false,status:'CANONICAL_FRESH_SQUAD_UNAVAILABLE',wildcard:!!wcFresh,free_hit:!!fhFresh},{status:409});
 const forcedLegacy=forcedTransfers(adv?.result?.survivor?.transfers),forcedBase=forcedTransfers(ens?.result?.best_no_chip?.transfers);const init:any={ids:initIds,buy:initBuy,bank:N(ms.bank_tenths),ft:N(ms.free_transfers,1),chips:[],score:0,path:[],root:'UNSET'};const firstActs=actionsFor(init,gw);const baseRoots:any[]=[{name:'ROLL',a:{outs:[],ins:[],tag:'ROOT_ROLL'}}];if(forcedBase.length)baseRoots.push({name:'C0228_BASELINE',a:{outs:forcedBase.map((x:any)=>x[0]),ins:forcedBase.map((x:any)=>x[1]),tag:'ROOT_C0228_BASELINE'}});if(forcedLegacy.length)baseRoots.push({name:'C0240_LEGACY',a:{outs:forcedLegacy.map((x:any)=>x[0]),ins:forcedLegacy.map((x:any)=>x[1]),tag:'ROOT_C0240_LEGACY'}});for(const n of [1,2,3,4,5]){const a=firstActs.find(x=>x.outs.length===n);if(a)baseRoots.push({name:`BEST_GENERATED_${n}FT`,a:{...a,tag:`ROOT_BEST_GENERATED_${n}FT`}})}for(const r of regs||[]){const target=(r.required_player_ids||[]).map(Number);if(target.length!==15)continue;const d=diffToTarget(target);if(d.outs.length===d.ins.length&&d.outs.length<=7)baseRoots.push({name:`NAMED:${r.challenger_key}`,a:{outs:d.outs,ins:d.ins,tag:`ROOT_NAMED:${r.challenger_key}`}})}
 const branchMap=new Map<string,any[]>();for(const rt of baseRoots){for(const chip of ['NONE','BENCH_BOOST','TRIPLE_CAPTAIN']){const name=chip==='NONE'?rt.name:`${chip}:${rt.name}`,s0=stepState({...init,root:name},gw,weights[0],rt.a,chip);if(s0)branchMap.set(name,[s0])}}
 function freshRoot(st:any,target:number[],chip:string,w:number){if(!legal(target))return null;const cur=new Set(st.ids),tar=new Set(target),outs=st.ids.filter((x:number)=>!tar.has(x)),ins=target.filter((x:number)=>!cur.has(x));let bank=st.bank,buy=new Map(st.buy);for(const oid of outs){const op=pmap.get(oid);if(!op)return null;bank+=sell(op.price,N(buy.get(oid),op.price));buy.delete(oid)}for(const ni of ins){const np=pmap.get(ni);if(!np)return null;bank-=np.price;buy.set(ni,np.price)}if(bank<0)return null;const ns={...st,ids:[...target],buy,bank};const ev=util(ns,gw,0,chip);if(!ev)return null;const z=ev.z,name=chip==='WILDCARD'?'WILDCARD_FRESH':'FREE_HIT_FRESH';const out={...ns,root:name,ft:st.ft,chips:[...st.chips,chip],score:st.score+w*ev.u,path:[...st.path,{gameweek:gw,tag:`ROOT_${chip}_FRESH`,root:name,chip,outs,ins,free_transfers_before:st.ft,free_transfers_after:st.ft,bank_after:bank,hit_points:0,gw_utility:+ev.u.toFixed(3),xi_expected_points:+z.xiPts.toFixed(3),expected_autosub_points:+z.autosub.toFixed(3),bench_expected_points:+z.benchPts.toFixed(3),captain_player_id:z.captain.id,vice_player_id:z.vice.id,starting_xi:z.xi.map((p:any)=>p.id),bench_order:z.bench.map((p:any)=>p.id),formation:z.formation,price_stress:{current_price_feasible:true,temporary_free_hit_prices:chip==='FREE_HIT'}}]};if(chip==='FREE_HIT'){out.ids=st.ids;out.buy=st.buy;out.bank=st.bank}return out}
 const wc=freshRoot({...init,root:'WILDCARD_FRESH'},wcFresh.ids,'WILDCARD',weights[0]);if(wc)branchMap.set('WILDCARD_FRESH',[wc]);const fh=freshRoot({...init,root:'FREE_HIT_FRESH'},fhFresh.ids,'FREE_HIT',weights[0]);if(fh)branchMap.set('FREE_HIT_FRESH',[fh]);if(!branchMap.size)return Response.json({ok:false,status:'NO_VALID_ROOT_BRANCHES'},{status:409});
 for(let step=1;step<h;step++){const g=gws[step],w=weights[step];for(const [root,states] of [...branchMap.entries()]){const next:any[]=[];for(const st of states)for(const a of actionsFor(st,g)){const ns=stepState(st,g,w,a,'NONE');if(ns)next.push(ns)}const ded=new Map<string,any>();for(const s of next){const k=skey(s.ids,s.bank,s.ft,s.chips),o=ded.get(k);if(!o||s.score>o.score)ded.set(k,s)}const kept=[...ded.values()].sort((a,b)=>b.score-a.score).slice(0,beam);if(!kept.length)branchMap.delete(root);else branchMap.set(root,kept)}}
 const branchResults=[...branchMap.entries()].map(([root,states])=>{const bb=states[0];return{root,score:+bb.score.toFixed(3),edge_vs_roll_root:0,final_ft:bb.ft,final_bank_tenths:bb.bank,chips_used:bb.chips,first_action:bb.path[0],path:bb.path,final_squad:bb.ids}}).sort((a,b)=>b.score-a.score);const roll=branchResults.find(x=>x.root==='ROLL');if(roll)for(const x of branchResults)x.edge_vs_roll_root=+(x.score-roll.score).toFixed(3);
 const normal=branchResults.filter(x=>!x.chips_used.length),c0240=normal.find(x=>x.root==='C0240_LEGACY'),named=normal.filter(x=>x.root.startsWith('NAMED:')),bestNormal=[...normal].sort((a,b)=>b.score-a.score)[0],err=Math.max(.25,N(ens?.model_error_margin_points,1));let selected=bestNormal;if(c0240&&bestNormal&&bestNormal.root!=='C0240_LEGACY'&&bestNormal.score-c0240.score<err)selected=c0240;const regression={c0240_present:!!c0240,named_challenger_count:named.length,best_normal_root:bestNormal?.root||null,selected_normal_root:selected?.root||null,edge_selected_vs_c0240:c0240&&selected?+(selected.score-c0240.score).toFixed(3):null,model_error_margin_points:err,noise_control_applied:true};
 const result={ok:true,status:'SEQUENTIAL_PLANNER_V06_CUTOVER_CANDIDATE_READY',change_id:'C0248',planner_version:VERSION,shadow_only:true,production_selected:false,summary:{best_root:branchResults[0]?.root,best_weighted_utility:branchResults[0]?.score,roll_root_utility:roll?.score??null,selected_normal_root:selected?.root||null,selected_normal_path:selected||null},branch_results:branchResults,canonical_fresh_squads:{wildcard:{source:wcFresh.source,player_ids:wcFresh.ids,objective:wcFresh.objective,horizon:h},free_hit:{source:fhFresh.source,player_ids:fhFresh.ids,objective:fhFresh.objective,horizon:1}},regression,search:{branch_beam_width:beam,root_count:branchResults.length,root_preservation:true,max_generated_normal_transfers_per_gw:5,wildcard_root_included:true,current_chip_actions:['WILDCARD','FREE_HIT','BENCH_BOOST','TRIPLE_CAPTAIN'],bb_tc_transfer_combinations:true,price_assumption:'EXACT_CURRENT_PRICE_PLUS_ONE_TENTH_HEADROOM_DIAGNOSTIC_NO_XPTS_EFFECT'},bench_policy:{type:'LEGAL_AUTOSUB_CONSERVATIVE_V03',flat_bench_weight:false,starter_and_bench_appearance_proxy:'p_start',formation_legality_approximate:false,formation_legality_exact_when_full_substitution_set_exists:true,multi_absence_unfillable_scenarios_conservatively_score_zero_autosub:true},chip_policy:{saved_free_transfers_retained_on_wildcard_and_free_hit:true,no_new_ft_added_when_wildcard_or_free_hit_active:true,one_chip_per_gameweek:true,free_hit_squad_reverts_after_gameweek:true},no_clairvoyance:{future_actions_are_policy_under_current_information:true,reoptimize_each_real_gameweek:true},historical_forecasts_rewritten:false};
 const sig=await sha({VERSION,gw,h,beam,weights,manager_state_id:ms.id,runs:gws.map(g=>N(latest.get(g).id)),prices:pool.map(p=>[p.id,p.price]),wc:wcFresh.ids,fh:fhFresh.ids,roots:baseRoots.map(r=>[r.name,r.a?.outs||[],r.a?.ins||[]])});const{data:old,error:oe}=await sb.from('fpl_sequential_planner_runs').select('id').eq('input_signature',sig).maybeSingle();if(oe)throw oe;let id=old?.id?N(old.id):null;if(!id){const{data:ins,error:ie}=await sb.from('fpl_sequential_planner_runs').insert({gameweek:gw,horizon:h,manager_state_id:ms.id,prediction_run_ids:gws.map(g=>N(latest.get(g).id)),planner_version:VERSION,search_config:{branch_beam_width:beam,weights,root_preservation:true,wildcard_root_included:true,max_generated_normal_transfers_per_gw:5,current_chip_actions:true,bb_tc_transfer_combinations:true,legal_autosub:true,bounded_price_headroom_diagnostic:true},input_signature:sig,result,shadow_only:true,production_selected:false,historical_forecasts_rewritten:false}).select('id').single();if(ie)throw ie;id=N(ins.id)}return Response.json({...result,planner_run_id:id,input_signature:sig});
}catch(e){return Response.json({ok:false,status:'SEQUENTIAL_PLANNER_ERROR',error:e instanceof Error?e.message:String(e),decisioning:false},{status:500})}});