import { createClient } from 'supabase';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'GET, OPTIONS','Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'};
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{
  if(req.method!=='GET')return new Response(JSON.stringify({ok:false,error:'GET required'}),{status:405,headers:cors});
  const keys=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')||'{}');const serviceKey=keys.default||Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!serviceKey)throw new Error('Missing Supabase service credential');
  const sb=createClient(Deno.env.get('SUPABASE_URL')!,serviceKey,{auth:{persistSession:false}});
  const u=new URL(req.url),requested=Number(u.searchParams.get('gw')||0),now=new Date();
  const {data:allMatches,error:me}=await sb.from('matches').select('id,gameweek,kickoff_time,home_team_id,away_team_id,home_score,away_score,finished').eq('source','fpl').not('gameweek','is',null).order('kickoff_time');if(me)throw me;
  const gws=[...new Set((allMatches||[]).map((m:any)=>Number(m.gameweek)).filter(Number.isFinite))].sort((a,b)=>a-b);
  let gw=requested>=1&&requested<=38?requested:0;if(!gw){const future=(allMatches||[]).find((m:any)=>new Date(m.kickoff_time)>now);gw=future?Number(future.gameweek):(gws.at(-1)||1)}
  const matches=(allMatches||[]).filter((m:any)=>Number(m.gameweek)===gw);
  const [{data:teams},{data:players},{data:tactics},{data:matchups},{data:availability},{data:roles},{data:replacements}]=await Promise.all([
    sb.from('teams').select('id,name,short_name'),
    sb.from('players').select('id,web_name,position,team_id'),
    sb.from('current_team_fixture_tactics').select('id,match_id,gameweek,team_id,opponent_team_id,kickoff_time,captured_at,profile_observed_at,taxonomy_version,style_label,possession_control_score,directness_score,width_score,box_pressure_score,set_piece_score,defensive_block_score,confidence,evidence,model_effect_enabled').eq('gameweek',gw),
    sb.from('current_fixture_tactical_matchups').select('id,match_id,gameweek,team_id,opponent_team_id,kickoff_time,captured_at,evidence_cutoff,signal_family,signal_key,score_type,score,direction,attacking_component,resistance_component,confidence,data_coverage,evidence,model_effect_enabled').eq('gameweek',gw),
    sb.from('current_player_fixture_availability').select('id,match_id,gameweek,team_id,opponent_team_id,player_id,kickoff_time,captured_at,availability_status,chance_of_playing,base_start_probability,base_expected_minutes,expected_xi,confidence,evidence,model_effect_enabled').eq('gameweek',gw),
    sb.from('current_player_fixture_roles').select('id,match_id,gameweek,team_id,opponent_team_id,player_id,kickoff_time,captured_at,taxonomy_version,primary_role,secondary_role,primary_score,secondary_score,expected_xi,availability_status,confidence,evidence,model_effect_enabled').eq('gameweek',gw).eq('taxonomy_version','event_role_v0.2.1'),
    sb.from('current_player_replacement_quality').select('id,match_id,gameweek,team_id,opponent_team_id,target_player_id,candidate_player_id,kickoff_time,captured_at,target_primary_role,candidate_primary_role,role_fit_score,production_continuity_score,composite_score,candidate_rank,quality_status,confidence,evidence,model_effect_enabled').eq('gameweek',gw)
  ]);
  const tm=new Map((teams||[]).map((x:any)=>[Number(x.id),x])),pm=new Map((players||[]).map((x:any)=>[Number(x.id),x]));
  const group=(rows:any[]|null|undefined,key:(x:any)=>string)=>{const m=new Map<string,any[]>();for(const x of rows||[]){const k=key(x);if(!m.has(k))m.set(k,[]);m.get(k)!.push(x)}return m};
  const tactG=group(tactics,x=>`${x.match_id}:${x.team_id}`),matchG=group(matchups,x=>`${x.match_id}:${x.team_id}`),avG=group(availability,x=>`${x.match_id}:${x.team_id}`),roleG=group(roles,x=>`${x.match_id}:${x.team_id}:${x.player_id}`),repG=group(replacements,x=>`${x.match_id}:${x.team_id}`);
  const side=(matchId:number,teamId:number)=>{
    const tactic=(tactG.get(`${matchId}:${teamId}`)||[])[0]||null;
    const signals=(matchG.get(`${matchId}:${teamId}`)||[]).map((x:any)=>({signal_family:x.signal_family,signal_key:x.signal_key,score_type:x.score_type,score:x.score,direction:x.direction,attacking_component:x.attacking_component,resistance_component:x.resistance_component,confidence:x.confidence,data_coverage:x.data_coverage,captured_at:x.captured_at,evidence_cutoff:x.evidence_cutoff,technical_evidence:x.evidence,model_effect_enabled:false}));
    const xi=(avG.get(`${matchId}:${teamId}`)||[]).filter((x:any)=>x.expected_xi===true).map((a:any)=>{const p=pm.get(Number(a.player_id));const r=(roleG.get(`${matchId}:${teamId}:${a.player_id}`)||[])[0]||null;return{player_id:a.player_id,name:p?.web_name||null,position:p?.position||null,availability_status:a.availability_status,chance_of_playing:a.chance_of_playing,p_start:a.base_start_probability,xmin:a.base_expected_minutes,availability_confidence:a.confidence,role:r?{taxonomy_version:r.taxonomy_version,primary:r.primary_role,secondary:r.secondary_role,primary_score:r.primary_score,secondary_score:r.secondary_score,confidence:r.confidence}:null}});
    const reps=(repG.get(`${matchId}:${teamId}`)||[]).map((r:any)=>({target_player_id:r.target_player_id,target_name:pm.get(Number(r.target_player_id))?.web_name||null,candidate_player_id:r.candidate_player_id,candidate_name:pm.get(Number(r.candidate_player_id))?.web_name||null,candidate_rank:r.candidate_rank,target_role:r.target_primary_role,candidate_role:r.candidate_primary_role,role_fit_score:r.role_fit_score,production_continuity_score:r.production_continuity_score,composite_score:r.composite_score,quality_status:r.quality_status,confidence:r.confidence,captured_at:r.captured_at,technical_evidence:r.evidence,model_effect_enabled:false})).sort((a:any,b:any)=>Number(a.target_player_id)-Number(b.target_player_id)||Number(a.candidate_rank)-Number(b.candidate_rank));
    return{tactical_profile:tactic?{taxonomy_version:tactic.taxonomy_version,style_label:tactic.style_label,possession_control:tactic.possession_control_score,directness:tactic.directness_score,width:tactic.width_score,attacking_box_occupation:tactic.box_pressure_score,set_piece:tactic.set_piece_score,defensive_block:tactic.defensive_block_score,confidence:tactic.confidence,captured_at:tactic.captured_at,technical_evidence:tactic.evidence,model_effect_enabled:false}:null,matchup_signals:signals,expected_xi:xi,replacement_research:reps,research_only:true,model_effect_enabled:false};
  };
  const fixtures=matches.map((m:any)=>{const h=tm.get(Number(m.home_team_id)),a=tm.get(Number(m.away_team_id));return{match_id:m.id,gameweek:m.gameweek,kickoff_time:m.kickoff_time,frozen:new Date(m.kickoff_time)<=now,finished:Boolean(m.finished),home_score:m.home_score,away_score:m.away_score,home_team:{id:m.home_team_id,name:h?.name||null,short_name:h?.short_name||null,...side(Number(m.id),Number(m.home_team_id))},away_team:{id:m.away_team_id,name:a?.name||null,short_name:a?.short_name||null,...side(Number(m.id),Number(m.away_team_id))}}});
  return new Response(JSON.stringify({ok:true,gameweek:gw,available_gameweeks:gws,research_only:true,model_effect_enabled:false,contract_version:'fixture_intelligence_v0.1',limitations:['no exact tactical formation','no left/right flank assignment','no defensive pressing intensity','no defensive line height','replacement ability/tactical consequence not validated'],fixtures}),{headers:cors});
}catch(e){return new Response(JSON.stringify({ok:false,error:e instanceof Error?e.message:String(e)}),{status:500,headers:cors})}});
