import { createClient } from 'npm:@supabase/supabase-js@2.112.3';
import Papa from 'npm:papaparse@5.5.3';
const REPO='vibedatascience/understat_players_aggregated',COMMIT='768b7ca0b977a5e6b4b429c7b0cf750e8269f2fc',FILE='understat_players_aggregated_2014_2024.csv',BLOB='ddf4327251bb781f88b6edc4662bf20e5379ff3f';
const URL=`https://raw.githubusercontent.com/${REPO}/${COMMIT}/${FILE}`,FPL_REPO='vaastav/Fantasy-Premier-League',FPL_COMMIT='9779cdbc0c07f6c900c2d0c181ddf6bb9c800f88',FPL_ROOT=`https://raw.githubusercontent.com/${FPL_REPO}/${FPL_COMMIT}/data`;
const SUPPORTED=new Set(['La_Liga','Bundesliga','Serie_A','Ligue_1']),LN:any={La_Liga:'La Liga',Bundesliga:'Bundesliga',Serie_A:'Serie A',Ligue_1:'Ligue 1'};
const clean=(v:any)=>v==null?null:String(v).trim(),num=(v:any)=>{const s=clean(v);if(!s)return null;const n=Number(s);return Number.isFinite(n)?n:null},fplPos=(v:any)=>Number(v)===2?'DEF':Number(v)===3?'MID':Number(v)===4?'FWD':null;
const strip=(s:any)=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/ø/g,'o').replace(/ð/g,'d').replace(/þ/g,'th').replace(/ł/g,'l').replace(/ß/g,'ss').replace(/[^a-z0-9]+/g,' ').trim(),tokens=(s:any)=>strip(s).split(/\s+/).filter(Boolean);
const clubKey=(s:any)=>{const x=strip(s),m:any={'manchester city':'man city','manchester united':'man utd','tottenham':'spurs','tottenham hotspur':'spurs','wolverhampton wanderers':'wolves','newcastle united':'newcastle','nottingham forest':'nottm forest','leicester':'leicester city','leicester city':'leicester city','west ham united':'west ham','brighton and hove albion':'brighton','ipswich town':'ipswich'};return m[x]||x};
const chunks=<T,>(a:T[],n=200)=>{const z:T[][]=[];for(let i=0;i<a.length;i+=n)z.push(a.slice(i,i+n));return z},err=(e:any)=>e instanceof Error?e.message:String(e);
async function csv(url:string){const r=await fetch(url);if(!r.ok)throw new Error(`${r.status} ${url}`);const p=Papa.parse(await r.text(),{header:true,skipEmptyLines:true});if(p.errors.length>25)throw new Error(`CSV parse errors ${p.errors.length}`);return p.data as any[]}
function nameMatch(us:string,f:any){const u=tokens(us),full=tokens(`${clean(f.first_name)||''} ${clean(f.second_name)||''}`),a=strip(us),b=strip(`${clean(f.first_name)||''} ${clean(f.second_name)||''}`),w=strip(f.web_name);return !!u.length&&(a===b||a===w||(u.length>=2&&u.every(t=>full.includes(t))))}
Deno.serve(async(req)=>{try{if(req.method!=='POST')return Response.json({ok:false,error:'POST required'},{status:405});const keys=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')||'{}'),key=keys.default||Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!key)throw new Error('Missing service credential');const sb=createClient(Deno.env.get('SUPABASE_URL')!,key,{auth:{persistSession:false}}),{data:token,error:ae}=await sb.rpc('get_backend_secret',{secret_name:'FOOTBALL_ENGINE_ADMIN_TOKEN'});if(ae||!token||req.headers.get('x-engine-token')!==token)return Response.json({ok:false,error:'unauthorized'},{status:401});
const body=await req.json().catch(()=>({})),cohort=String(body.cohort||'').toUpperCase(),dry=body.dry_run!==false,cfg=cohort==='VALIDATION'?{sy:2023,dy:2024,sl:'2023-2024',dl:'2024-2025',dest:'2024-25',split:'VALIDATION'}:cohort==='TRAIN'?{sy:2022,dy:2023,sl:'2022-2023',dl:'2023-2024',dest:'2023-24',split:'TRAIN'}:null;if(!cfg)return Response.json({ok:false,error:'cohort must be VALIDATION or TRAIN'},{status:400});
const [all,fp,ft]=await Promise.all([csv(URL),csv(`${FPL_ROOT}/${cfg.dest}/players_raw.csv`),csv(`${FPL_ROOT}/${cfg.dest}/teams.csv`)]);const teamNames=new Map<number,string>();for(const t of ft){const id=Number(t.id);if(id)teamNames.set(id,String(clean(t.name)||clean(t.short_name)||id))}const by=new Map<string,any[]>();for(const r of all){const id=clean(r.id),y=num(r.year);if(!id||y==null||(y!==cfg.sy&&y!==cfg.dy))continue;const k=`${id}:${y}`;if(!by.has(k))by.set(k,[]);by.get(k)!.push(r)}
const source:any[]=[],dest=new Map<string,any>();let sm=0,dm=0,sc=0,dc=0;for(const [k,rows] of by){const y=Number(k.split(':').pop());if(rows.length!==1){y===cfg.sy?sm++:dm++;continue}const r=rows[0],league=clean(r.league)||'',mins=num(r.time),xg=num(r.xG),xa=num(r.xA),id=String(r.id),clubs=clean(r.team_title)||'';if(clubs.includes(',')){y===cfg.sy?sc++:dc++;continue}if(mins==null||mins<450||xg==null||xa==null)continue;if(y===cfg.sy&&SUPPORTED.has(league))source.push({id,r,league,mins,xg,xa});if(y===cfg.dy&&league==='EPL')dest.set(id,{id,r,mins,xg,xa})}
const fplByTeam=new Map<string,any[]>();for(const f of fp){if(!fplPos(f.element_type))continue;const tn=teamNames.get(Number(f.team));if(!tn)continue;const k=clubKey(tn);if(!fplByTeam.has(k))fplByTeam.set(k,[]);fplByTeam.get(k)!.push(f)}
const pairs:any[]=[];let unmatched=0,amb=0;for(const a of source){const b=dest.get(a.id);if(!b)continue;const pn=String(clean(b.r.player_name)||clean(a.r.player_name)||`understat:${a.id}`),src=clean(a.r.team_title),dst=clean(b.r.team_title);if(!src||!dst)continue;const cand=(fplByTeam.get(clubKey(dst))||[]).filter(f=>nameMatch(pn,f));if(cand.length===0){unmatched++;continue}if(cand.length!==1){amb++;continue}const f=cand[0],position=fplPos(f.element_type);if(!position)continue;pairs.push({pair_key:`C0206_${cfg.split}_${cfg.sy}_${cfg.dy}_UNDERSTAT_${a.league}_PL_${a.id}`,player_name:pn,player_identity_key:`understat_player_id:${a.id}`,source_season:cfg.sl,destination_season:cfg.dl,source_competition:LN[a.league],destination_competition:'Premier League',source_club:src,destination_club:dst,position_group:position,source_minutes:Math.round(a.mins),destination_minutes:Math.round(b.mins),source_xg:a.xg,source_xa:a.xa,destination_xg:b.xg,destination_xa:b.xa,source_provenance:{metric_source:'Understat aggregate archive',repository:REPO,repository_commit:COMMIT,file:FILE,file_blob_sha:BLOB,understat_player_id:a.id,league_code:a.league,year:cfg.sy,identity_method:'stable Understat player id',season_record_count:1,team_title_single_club:true,minutes_field:'time',xg_field:'xG',xa_field:'xA',same_provider_source_destination:true},destination_provenance:{metric_source:'Understat aggregate archive',repository:REPO,repository_commit:COMMIT,file:FILE,file_blob_sha:BLOB,understat_player_id:a.id,league_code:'EPL',year:cfg.dy,identity_method:'stable Understat player id',season_record_count:1,team_title_single_club:true,minutes_field:'time',xg_field:'xG',xa_field:'xA',same_provider_source_destination:true,fpl_position_repository:FPL_REPO,fpl_position_commit:FPL_COMMIT,fpl_destination_element_id:Number(f.id),fpl_destination_player_code:Number(f.code),fpl_element_type:Number(f.element_type),fpl_position_match_method:'unique normalized player-name tokens within exact normalized destination club'},cohort_split:cfg.split,pair_quality_status:'ELIGIBLE',evidence:{change_id:'C0206',cohort:`${cfg.sl}_to_${cfg.dl}`,cohort_role:cfg.split==='TRAIN'?'historical training foreign-to-PL':'pre-test validation foreign-to-PL',used_for_fitting:cfg.split==='TRAIN',used_for_transform_scale:cfg.split==='TRAIN',source_minute_gate:450,destination_minute_gate:450,source_preferred_900:a.mins>=900,destination_preferred_900:b.mins>=900,single_record_each_season_required:true,comma_separated_multi_club_rejected:true,same_understat_provider_both_sides:true,destination_position_source:'official FPL archive element_type',source_league:LN[a.league],goalkeepers_excluded:true,missing_data_is_not_zero:true,current_2026_27_target_outcomes_used:false,historical_forecasts_rewritten:false},research_only:true,model_effect_enabled:false})}
const lc:any={},pc:any={};for(const p of pairs){lc[p.source_competition]=(lc[p.source_competition]||0)+1;const k=`${p.source_competition}|${p.position_group}`;pc[k]=(pc[k]||0)+1}let inserted=0;if(!dry)for(const c of chunks(pairs)){const {data,error}=await sb.from('research_c0206_foreign_translation_pairs').upsert(c,{onConflict:'pair_key',ignoreDuplicates:true}).select('pair_key');if(error)throw error;inserted+=(data||[]).length}return Response.json({ok:true,change_id:'C0206',cohort:cfg.split,dry_run:dry,archive_rows:all.length,candidate_pairs:pairs.length,league_counts:lc,league_position_counts:pc,source_multirow_excluded:sm,destination_multirow_excluded:dm,source_comma_multiclub_excluded:sc,destination_comma_multiclub_excluded:dc,fpl_position_unmatched:unmatched,fpl_position_ambiguous:amb,sample:pairs.slice(0,25).map(p=>({player:p.player_name,source_league:p.source_competition,source_club:p.source_club,destination_club:p.destination_club,position:p.position_group,source_minutes:p.source_minutes,destination_minutes:p.destination_minutes,fpl_code:p.destination_provenance.fpl_destination_player_code})),inserted_or_returned:inserted,repository:REPO,repository_commit:COMMIT,file_blob_sha:BLOB,fpl_repository:FPL_REPO,fpl_commit:FPL_COMMIT,model_effect_enabled:false,historical_forecasts_rewritten:false})}catch(e){return Response.json({ok:false,error:err(e)},{status:500})}});