import type { AppView } from '../components/layout/AppShell';
import { Button } from '../components/primitives/Button';
import { Surface } from '../components/primitives/Surface';
import { chipLabel, decisionLabel, findPlayer, percent, useHomeData } from '../lib/home';

export function HomePage({ requestedGameweek, onNavigate }: { requestedGameweek: number; onNavigate: (view: AppView) => void }) {
  const { fpl, fixtures } = useHomeData(requestedGameweek);
  const fplData = fpl.data;
  const fixtureData = fixtures.data;
  const gameweek = fplData?.gameweek ?? fixtureData?.gameweek ?? (requestedGameweek || null);
  if (fpl.isPending && fixtures.isPending) return <CommandSkeleton />;
  if (fpl.isError && fixtures.isError) return <section className="state-panel" aria-live="polite"><span className="page-eyebrow">Command center</span><h1>Live decision data is temporarily unavailable.</h1><p>The interface will not invent a decision when authoritative API contracts fail.</p><Button onClick={() => { void fpl.refetch(); void fixtures.refetch(); }}>Retry live data</Button></section>;
  const captain = findPlayer(fplData, fplData?.decision?.captain_player_id);
  const vice = findPlayer(fplData, fplData?.decision?.vice_player_id);
  const fixtureList = fixtureData?.fixtures ?? [];
  const finished = fixtureList.filter((fixture) => fixture.finished).length;
  const nextFixture = [...fixtureList].filter((fixture) => !fixture.finished).sort((a, b) => new Date(a.kickoff_time).getTime() - new Date(b.kickoff_time).getTime())[0];
  const partial = fpl.isError || fixtures.isError;
  return <div className="home-page">
    <header className="page-intro"><div><span className="page-eyebrow">{gameweek ? `Gameweek ${gameweek}` : 'Current gameweek'}</span><h1>Command Center</h1><p>Weekly action first. Supporting intelligence stays one layer down.</p></div><span className={`sync-badge${partial ? ' is-warning' : ''}`} role="status"><span aria-hidden="true" />{partial ? 'Partial live data' : 'Live data synced'}</span></header>
    <section className="decision-hero" aria-labelledby="weekly-action-title"><div className="decision-main"><span className="decision-label">Weekly action</span><h2 id="weekly-action-title">{decisionLabel(fplData)}</h2><p>{fplData?.decision?.status ? humanizeStatus(fplData.decision.status) : 'Preserve flexibility unless a later verified update creates a meaningful edge.'}</p><div className="decision-actions"><Button onClick={() => onNavigate('fpl')}>Open FPL workspace</Button><Button variant="secondary" onClick={() => onNavigate('fixtures')}>Scan fixtures</Button></div></div><div className="decision-grid" aria-label="Weekly decision summary"><DecisionMetric label="Captain" value={captain?.name ?? '—'} detail={captain?.expected_points == null ? undefined : `${captain.expected_points.toFixed(2)} xPts · ${percent(captain.p_10_plus)} P10+`} /><DecisionMetric label="Vice" value={vice?.name ?? '—'} detail={vice?.expected_points == null ? undefined : `${vice.expected_points.toFixed(2)} xPts`} /><DecisionMetric label="Chip" value={chipLabel(fplData?.decision?.chip)} /><DecisionMetric label="Risk" value={fplData?.decision?.risk_level ?? '—'} /></div></section>
    <section className="home-grid" aria-label="Gameweek pulse"><Surface className="pulse-card"><div className="card-heading"><span>Gameweek pulse</span><strong>{finished}/{fixtureList.length || '—'}</strong></div><p className="card-copy">Fixtures finished</p>{nextFixture ? <div className="next-fixture"><span>Next</span><strong>{nextFixture.home_team.name} vs {nextFixture.away_team.name}</strong><small>{formatKickoff(nextFixture.kickoff_time)}</small></div> : <div className="next-fixture"><span>State</span><strong>{fixtureList.length ? 'Gameweek complete' : 'Fixture feed unavailable'}</strong></div>}</Surface><Surface className="pulse-card"><div className="card-heading"><span>Captaincy</span><strong>{captain ? percent(captain.p_10_plus) : '—'}</strong></div><p className="card-copy">P10+ for the current captain</p><div className="next-fixture"><span>Current call</span><strong>{captain?.name ?? 'Awaiting captain snapshot'}</strong><small>{captain?.expected_minutes == null ? 'Minutes unavailable' : `${Math.round(captain.expected_minutes)} expected minutes`}</small></div></Surface></section>
    <section className="focus-section" aria-labelledby="focus-heading"><div className="section-heading"><span className="page-eyebrow">Next actions</span><h2 id="focus-heading">Go deeper only where the decision needs it.</h2></div><div className="focus-grid"><button className="focus-card" type="button" onClick={() => onNavigate('fixtures')}><span>Fixtures</span><strong>Match calls & evidence</strong><small>C0171 will build the compact scan surface here.</small></button><button className="focus-card" type="button" onClick={() => onNavigate('fpl')}><span>FPL</span><strong>Squad decision workspace</strong><small>C0173 will expose XI, bench, transfers and haul distributions.</small></button></div></section>
  </div>;
}
function DecisionMetric({ label, value, detail }: { label: string; value: string; detail: string | undefined }) { return <div className="decision-metric"><span>{label}</span><strong>{value}</strong>{detail ? <small>{detail}</small> : null}</div>; }
function CommandSkeleton() { return <div className="command-skeleton" aria-busy="true" aria-label="Loading command center"><div className="skeleton-line is-short" /><div className="skeleton-line is-title" /><div className="skeleton-panel" /><div className="skeleton-grid"><div /><div /></div></div>; }
function formatKickoff(value: string): string { return new Intl.DateTimeFormat(undefined, { weekday: 'short', day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' }).format(new Date(value)); }
function humanizeStatus(value: string): string { return value.toLowerCase().replaceAll('_', ' ').replace(/^./, (character) => character.toUpperCase()); }
