import { createClient } from 'supabase';
import Papa from 'papaparse';

const H={'content-type':'application/json; charset=utf-8','cache-control':'no-store'};
const REPO='olbauday/FPL-Core-Insights';
const SOURCE='fpl_core_insights_github';
const n=(v:any)=>v===undefined||v===null||String(v).trim()===''?null:Number(v);
const i=(v:any)=>{const x=n(v);return x===null||!Number.isFinite(x)?null:Math.round(x)};
const b=(v:any)=>String(v).toLowerCase()==='true';
const chunks=<T>(a:T[],z=200)=>{const out:T[][]=[];for(let k=0;k<a.length;k+=z)out.push(a.slice(k,k+z));return out};
const enc=new TextEncoder();
async function sha256(s:string){const d=await crypto.subtle.digest('SHA-256',enc.encode(s));return Array.from(new Uint8Array(d)).map(x=>x.toString(16).padStart(2,'0')).join('')}
async function fetchText(url:string){const r=await fetch(url,{cache:'no-store',headers:{'user-agent':'FootballIntelligence/0.5','accept':'text/plain'}});if(!r.ok)throw new Error(`${url} ${r.status}`);return await r.text()}
async function csv(url:string){const text=await fetchText(url);const rows=Papa.parse(text,{header:true,skipEmptyLines:true,transformHeader:(h:string)=>h.trim().replace(/^\uFEFF/,'')}).data as any[];return {text,rows}}
async function resolveCommit(asOf:string){const url=`https://api.github.com/repos/${REPO}/commits?sha=main&until=${encodeURIComponent(asOf)}&per_page=1`;const r=await fetch(url,{cache:'no-store',headers:{'user-agent':'FootballIntelligence/0.5','accept':'application/vnd.github+json'}});if(!r.ok)throw new Error(`GitHub commit resolution ${r.status}`);const a=await r.json();if(!Array.isArray(a)||!a[0]?.sha)throw new Error(`No source commit at/before ${asOf}`);return {sha:String(a[0].sha),at:String(a[0]?.commit?.committer?.date||a[0]?.commit?.author?.date||'')}}
function rawUrl(sha:string,path:string){return `https://raw.githubusercontent.com/${REPO}/${sha}/${path.split('/').map(encodeURIComponent).join('/')}`}
function kickoff(v:any){if(v===null||v===undefined||String(v).trim()==='')return null;const s=String(v).trim();const z=/Z$|[+-]\d\d:?\d\d$/.test(s)?s:s.replace(' ','T')+'Z';const d=new Date(z);return Number.isNaN(d.getTime())?null:d.toISOString()}
function paths(season:string,gw:number){if(season==='2025-2026'){const base=`data/${season}/By Tournament/Premier League/GW${gw}`;return {matches:`${base}/matches.csv`,players:`${base}/players.csv`,playermatchstats:`${base}/playermatchstats.csv`,shots:`${base}/shots.csv`,playersCaptureGw:gw}}if(season==='2024-2025'){return {matches:`data/${season}/matches/GW${gw}/matches.csv`,players:`data/${season}/players/players.csv`,playermatchstats:`data/${season}/playermatchstats/GW${gw}/playermatchstats.csv`,shots:null,playersCaptureGw:0}}throw new Error('Only 2024-2025 and 2025-2026 supported')}

Deno.serve(async(req)=>{try{
 if(req.method!=='POST')return new Response(JSON.stringify({ok:false,error:'POST required'}),{status:405,headers:H});
 const ks=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')||'{}'),key=ks.default||Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!key)throw new Error('Missing service credential');
 const sb=createClient(Deno.env.get('SUPABASE_URL')!,key,{auth:{persistSession:false}});const {data:tok,error:ae}=await sb.rpc('get_backend_secret',{secret_name:'FOOTBALL_ENGINE_ADMIN_TOKEN'});if(ae||!tok||req.headers.get('x-engine-token')!==tok)return new Response(JSON.stringify({ok:false,error:'unauthorized'}),{status:401,headers:H});
 const body=await req.json().catch(()=>({}));const season=String(body.season||'');if(!['2024-2025','2025-2026'].includes(season))throw new Error('Unsupported season');const gameweeks=(Array.isArray(body.gameweeks)?body.gameweeks:[body.gameweek]).map(Number).filter((x:number)=>Number.isInteger(x)&&x>=1&&x<=38);if(!gameweeks.length||gameweeks.length>5)throw new Error('Provide 1-5 gameweeks in range 1..38');const sourceAsOf=new Date(body.as_of||new Date().toISOString()).toISOString();const commit=await resolveCommit(sourceAsOf);if(!commit.at)throw new Error('Source commit timestamp missing');
 const [{data:teams,error:te},{data:currentPlayers,error:pe}]=await Promise.all([sb.from('teams').select('id,team_code,name'),sb.from('players').select('id,player_code')]);if(te)throw te;if(pe)throw pe;const teamMap=new Map((teams||[]).map((x:any)=>[Number(x.team_code),x]));const currentPlayerMap=new Map((currentPlayers||[]).filter((x:any)=>x.player_code!==null).map((x:any)=>[Number(x.player_code),Number(x.id)]));
 const totals:any={team:0,player:0,shots:0,captures:0};const perGw:any[]=[];const sharedPlayerCache=new Map<string,any>();
 async function ensureCapture(fileKind:string,capGw:number,path:string,text:string,rowCount:number){const payload=await sha256(text);const oh=await sha256([SOURCE,season,capGw,fileKind,commit.sha,payload].join('|'));const row={source_key:SOURCE,season,gameweek:capGw,file_kind:fileKind,source_repo:REPO,source_path:path,source_url:rawUrl(commit.sha,path),source_commit_sha:commit.sha,source_commit_at:commit.at,source_as_of:sourceAsOf,payload_sha256:payload,row_count:rowCount,observation_hash:oh,notes:'C0197 historical free-source actual evidence; source-native identities retained; no model effect.'};const {data,error}=await sb.from('research_c0197_source_file_captures').upsert(row,{onConflict:'observation_hash',ignoreDuplicates:true}).select('id');if(error)throw new Error(`capture ${fileKind}: ${error.message}`);if(data?.[0]?.id){totals.captures++;return Number(data[0].id)}const {data:e,error:ee}=await sb.from('research_c0197_source_file_captures').select('id').eq('observation_hash',oh).single();if(ee)throw ee;return Number(e.id)}
 for(const gw of gameweeks){const p=paths(season,gw);const [mf,pf]=await Promise.all([csv(rawUrl(commit.sha,p.matches)),csv(rawUrl(commit.sha,p.playermatchstats))]);let plf=sharedPlayerCache.get(p.players);if(!plf){plf=await csv(rawUrl(commit.sha,p.players));sharedPlayerCache.set(p.players,plf)}const sf=p.shots?await csv(rawUrl(commit.sha,p.shots)):null;
   const capM=await ensureCapture('matches',gw,p.matches,mf.text,mf.rows.length);const capP=await ensureCapture('playermatchstats',gw,p.playermatchstats,pf.text,pf.rows.length);await ensureCapture('players',p.playersCaptureGw,p.players,plf.text,plf.rows.length);const capS=sf&&p.shots?await ensureCapture('shots',gw,p.shots,sf.text,sf.rows.length):null;
   const srcPlayers=new Map<number,any>();for(const r of plf.rows){const sid=i(r.player_id),code=i(r.player_code);if(sid===null)continue;srcPlayers.set(sid,{code,teamCode:i(r.team_code),position:String(r.position||'')||null,name:String(r.web_name||`${r.first_name||''} ${r.second_name||''}`).trim()||null,currentId:code===null?null:(currentPlayerMap.get(code)||null)})}
   const matchSides=new Map<string,{home:number|null,away:number|null}>();const teamRows:any[]=[];for(const r of mf.rows){if(!b(r.finished))continue;const sm=String(r.match_id);const homeCode=i(r.home_team),awayCode=i(r.away_team);matchSides.set(sm,{home:homeCode,away:awayCode});const ko=kickoff(r.kickoff_time);if(!ko)continue;const side=(home:boolean)=>{const teamCode=home?homeCode:awayCode,internal=teamCode===null?null:teamMap.get(teamCode);return {source_key:SOURCE,source_file_capture_id:capM,source_commit_sha:commit.sha,season,gameweek:gw,source_match_id:sm,match_id:null,team_id:internal?.id||null,source_team_code:teamCode,source_team_name:internal?.name||null,mapping_status:internal?'mapped':'historical_source_only',venue:home?'home':'away',fixture_kickoff:ko,goals_for:n(home?r.home_score:r.away_score),goals_against:n(home?r.away_score:r.home_score),xg_for:n(home?r.home_expected_goals_xg:r.away_expected_goals_xg),xg_against:n(home?r.away_expected_goals_xg:r.home_expected_goals_xg),shots_for:n(home?r.home_total_shots:r.away_total_shots),shots_against:n(home?r.away_total_shots:r.home_total_shots),shots_on_target_for:n(home?r.home_shots_on_target:r.away_shots_on_target),shots_on_target_against:n(home?r.away_shots_on_target:r.home_shots_on_target),xgot_for:n(home?r.home_xg_on_target_xgot:r.away_xg_on_target_xgot),xgot_against:n(home?r.away_xg_on_target_xgot:r.home_xg_on_target_xgot),big_chances_for:n(home?r.home_big_chances:r.away_big_chances),big_chances_against:n(home?r.away_big_chances:r.home_big_chances),big_chances_missed_for:n(home?r.home_big_chances_missed:r.away_big_chances_missed),big_chances_missed_against:n(home?r.away_big_chances_missed:r.home_big_chances_missed),keeper_saves_for:n(home?r.home_keeper_saves:r.away_keeper_saves),keeper_saves_against:n(home?r.away_keeper_saves:r.home_keeper_saves),source_row:r}};teamRows.push(side(true),side(false))}
   let ti=0;for(const c of chunks(teamRows)){const {data,error}=await sb.from('research_c0197_team_match_evidence').upsert(c,{onConflict:'source_file_capture_id,source_match_id,source_team_code',ignoreDuplicates:true}).select('id');if(error)throw new Error(`historical team: ${error.message}`);ti+=(data||[]).length}totals.team+=ti;
   const playerRows:any[]=[];for(const r of pf.rows){const sid=i(r.player_id);if(sid===null)continue;const sp=srcPlayers.get(sid);const currentId=sp?.currentId||null;const mins=i(r.minutes_played);playerRows.push({source_key:SOURCE,source_file_capture_id:capP,source_commit_sha:commit.sha,season,gameweek:gw,source_match_id:String(r.match_id),match_id:null,source_player_id:sid,source_player_code:sp?.code||null,source_team_code:sp?.teamCode||null,source_position:sp?.position||null,source_player_name:sp?.name||null,player_id:currentId,minutes:mins,started:mins!==null&&mins>0&&i(r.start_min)===0,goals:i(r.goals),assists:i(r.assists),xg:n(r.xg),xa:n(r.xa),xgot:n(r.xgot),shots:i(r.total_shots),shots_on_target:i(r.shots_on_target),big_chances_missed:i(r.big_chances_missed),touches_opposition_box:i(r.touches_opposition_box),xgot_faced:n(r.xgot_faced),goals_prevented:n(r.goals_prevented),penalties_scored:i(r.penalties_scored),penalties_missed:i(r.penalties_missed),mapping_status:currentId?'historical_player_mapped_current':'historical_source_only',source_row:r})}
   let pi=0;for(const c of chunks(playerRows)){const {data,error}=await sb.from('research_c0197_player_match_evidence').upsert(c,{onConflict:'source_file_capture_id,source_match_id,source_player_id',ignoreDuplicates:true}).select('id');if(error)throw new Error(`historical player: ${error.message}`);pi+=(data||[]).length}totals.player+=pi;
   let si=0;if(sf&&capS){const shotRows:any[]=[];for(const r of sf.rows){const sid=i(r.player_id),sp=sid===null?null:srcPlayers.get(sid),currentId=sp?.currentId||null,sides=matchSides.get(String(r.match_id));const homeFlag=r.is_home===undefined||r.is_home===null||String(r.is_home).trim()===''?null:b(r.is_home);const sourceTeamCode=sp?.teamCode ?? (homeFlag===null?null:(homeFlag?sides?.home:sides?.away)) ?? null;shotRows.push({source_key:SOURCE,source_file_capture_id:capS,source_commit_sha:commit.sha,season,gameweek:gw,source_match_id:String(r.match_id),match_id:null,shot_index:i(r.shot_index),minute:i(r.minute),added_time:i(r.added_time),is_home:homeFlag,source_player_id:sid,source_player_code:sp?.code||null,source_team_code:sourceTeamCode,player_id:currentId,outcome:String(r.outcome||'')||null,situation:String(r.situation||'')||null,body_part:String(r.body_part||'')||null,xg:n(r.xg),xgot:n(r.xgot),start_x:n(r.start_x),start_y:n(r.start_y),goal_mouth_y:n(r.goal_mouth_y),goal_mouth_z:n(r.goal_mouth_z),goal_mouth_location:String(r.goal_mouth_location||'')||null,mapping_status:sid===null?'historical_no_player':currentId?'historical_player_mapped_current':'historical_source_only',source_row:r})}for(const c of chunks(shotRows)){const {data,error}=await sb.from('research_c0197_shot_events').upsert(c,{onConflict:'source_file_capture_id,source_match_id,shot_index',ignoreDuplicates:true}).select('id');if(error)throw new Error(`historical shots: ${error.message}`);si+=(data||[]).length}totals.shots+=si}
   perGw.push({gameweek:gw,source_rows:{matches:mf.rows.length,players:pf.rows.length,shots:sf?.rows.length||0},inserted:{team:ti,player:pi,shots:si}})
 }
 return new Response(JSON.stringify({ok:true,change_id:'C0197',season,gameweeks,source_as_of:sourceAsOf,source_commit_sha:commit.sha,source_commit_at:commit.at,totals,per_gameweek:perGw,research_only:true,model_effect_enabled:false}),{headers:H});
}catch(e){return new Response(JSON.stringify({ok:false,error:e instanceof Error?e.message:String(e)}),{status:500,headers:H})}});
