import { createClient } from 'jsr:@supabase/supabase-js@2';
const VERSION='C0225_RANK_AWARE_LEVERAGE_V01';
const N=(x:any,d=0)=>Number.isFinite(Number(x))?Number(x):d;
const ATTACK=new Set(['CREATOR_10','WIDE_ATTACKER','WIDE_FORWARD','LINK_FORWARD','TARGET_FORWARD','CENTRAL_STRIKER','WING_BACK']);
const CONTROL=new Set(['HOLDING_MIDFIELDER','CENTRE_BACK','HYBRID_DEFENDER','WIDE_BACK','GOALKEEPER']);
function roleFamily(r:any){const x=String(r||'');return ATTACK.has(x)?'ATTACKING':CONTROL.has(x)?'CONTROL_DEFENSIVE':x==='BOX_TO_BOX'?'BALANCED':'UNKNOWN'}
function rankRegime(gw:number,rank:number|null){
  if(gw<=8)return{name:'EARLY_SEASON_EV',leverage_priority:'AFTER_ROBUSTNESS',fixed_error_band:true,force_differential:false};
  if(rank==null)return{name:'RANK_UNAVAILABLE_CONSERVATIVE',leverage_priority:'AFTER_ROBUSTNESS',fixed_error_band:true,force_differential:false};
  if(gw<=25){if(rank<=100000)return{name:'MID_SEASON_PROTECT',leverage_priority:'AFTER_ROBUSTNESS',fixed_error_band:true,force_differential:false};if(rank>1000000)return{name:'MID_SEASON_CHASE',leverage_priority:'BEFORE_SECONDARY_ROBUSTNESS',fixed_error_band:true,force_differential:false};return{name:'MID_SEASON_BALANCED',leverage_priority:'AFTER_PRIMARY_ROBUSTNESS',fixed_error_band:true,force_differential:false}}
  if(gw<=33){if(rank<=25000)return{name:'LATE_SEASON_PROTECT',leverage_priority:'AFTER_ROBUSTNESS',fixed_error_band:true,force_differential:false};return{name:'LATE_SEASON_CHASE',leverage_priority:'BEFORE_SECONDARY_ROBUSTNESS',fixed_error_band:true,force_differential:false}}
  if(rank<=5000)return{name:'RUN_IN_PROTECT',leverage_priority:'AFTER_ROBUSTNESS',fixed_error_band:true,force_differential:false};
  return{name:'RUN_IN_CHASE',leverage_priority:'BEFORE_SECONDARY_ROBUSTNESS',fixed_error_band:true,force_differential:false};
}
function perGwRoleRisk(p:any,role:any){return ['MID','FWD'].includes(String(p.position))&&N(p.penalties_order,99)!==1&&roleFamily(role?.primary_role)==='CONTROL_DEFENSIVE'&&N(role?.confidence)>=0.7}
function leverageMetric(p:any,q:any,role:any){
  const own=p.selected_by_percent==null?null:N(p.selected_by_percent,NaN);if(own==null||!Number.isFinite(own)||!q)return{index:0,tier:'NONE',qualifies:false,ownership_proxy:null,reliability:0,haul_signal:0,role_risk:false};
  const xmins=N(q.expected_minutes),pstart=N(q.p_start),rr=perGwRoleRisk(p,role),reliability=Math.min(1,Math.max(0,xmins)/75)*(pstart>=.65?1:.75)*(rr?.25:1);
  const haul=2*N(q.p_10_plus)+4*N(q.p_15_plus)+6*N(q.p_20_plus),scarcity=Math.max(0,1-Math.min(100,Math.max(0,own))/100),index=scarcity*haul*reliability;
  const structural=xmins>=60&&pstart>=.55&&N(q.p_10_plus)>=.09&&!rr;
  const tier=structural&&own<=5?'EXPLOSIVE_DIFFERENTIAL':structural&&own<=10?'DIFFERENTIAL':structural&&own<=15?'SEMI_DIFFERENTIAL':'NONE';
  return{index:+index.toFixed(6),tier,qualifies:tier!=='NONE',ownership_proxy:+own.toFixed(2),reliability:+reliability.toFixed(4),haul_signal:+haul.toFixed(6),role_risk:rr};
}
async function sha(x:any){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(x)));return[...new Uint8Array(b)].map(v=>v.toString(16).padStart(2,'0')).join('')}
Deno.serve(async(req:Request)=>{try{
  const keys=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')||'{}'),key=keys.default||Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!key)return Response.json({ok:false,error:'service credential missing'},{status:500});
  const sb=createClient(Deno.env.get('SUPABASE_URL')!,key,{auth:{persistSession:false}});const{data:tok,error:ae}=await sb.rpc('get_backend_secret',{secret_name:'FOOTBALL_ENGINE_ADMIN_TOKEN'});if(ae||!tok||req.headers.get('x-engine-token')!==tok)return Response.json({ok:false,error:'unauthorized'},{status:401});
  const body=await req.json().catch(()=>({})),gw=Number(body.gameweek||0),h=Math.max(1,Math.min(5,Number(body.horizon||3))),err=Math.max(.25,Math.min(5,N(body.model_error_margin_points,1))),weights=(Array.isArray(body.weights)?body.weights:[1,.82,.68,.56,.46]).slice(0,h).map((x:any)=>Math.max(0,N(x)));if(!gw)return Response.json({ok:false,error:'gameweek invalid'},{status:400});
  const baseR=await fetch(`${Deno.env.get('SUPABASE_URL')}/functions/v1/fpl-full-pool-optimizer`,{method:'POST',headers:{'content-type':'application/json','x-engine-token':String(tok),'authorization':`Bearer ${key}`},body:JSON.stringify({...body,gameweek:gw,horizon:h,model_error_margin_points:err})});const base=await baseR.json().catch(()=>null);if(!baseR.ok||!base?.ok)return Response.json({ok:false,status:'BASE_OPTIMIZER_FAILED',base_status:baseR.status,base_result:base},{status:502});
  const managerStateId=N(base.manager_state_id);const{data:ms,error:mse}=await sb.from('fpl_manager_state_snapshots').select('id,evidence').eq('id',managerStateId).single();if(mse)throw mse;const entryId=N(ms?.evidence?.entry_id,3559923);
  let overallRank:number|null=null,overallPoints:number|null=null,rankSource='UNAVAILABLE';try{const er=await fetch(`https://fantasy.premierleague.com/api/entry/${entryId}/`,{headers:{'User-Agent':'FootballIntelligence/0.5'}});if(er.ok){const ej=await er.json();overallRank=ej?.summary_overall_rank==null?null:N(ej.summary_overall_rank);overallPoints=ej?.summary_overall_points==null?null:N(ej.summary_overall_points);rankSource='PUBLIC_FPL_ENTRY'}}catch{}
  const regime=rankRegime(gw,overallRank),gws:Array<number>=Array.isArray(base.gws)?base.gws.map(Number):Array.from({length:h},(_,i)=>gw+i),runIds=(base.prediction_runs||[]).map((x:any)=>N(x.run_id));
  const preds:any[]=[];for(const rid of runIds){const{data,error}=await sb.from('model_predictions').select('player_id,gameweek,expected_points,expected_minutes,p_start,p_blank,p_5_plus,p_10_plus,p_15_plus,p_20_plus').eq('prediction_run_id',rid).range(0,999);if(error)throw error;preds.push(...(data||[]))}
  const roles:any[]=[];for(const g of gws){const{data,error}=await sb.from('current_player_fixture_roles').select('player_id,gameweek,primary_role,confidence').eq('gameweek',g).range(0,999);if(error)throw error;roles.push(...(data||[]))}
  const{data:players,error:pe}=await sb.from('players').select('id,web_name,position,status,selected_by_percent,penalties_order,updated_at').range(0,999);if(pe)throw pe;
  const pmap=new Map((players||[]).map((p:any)=>[N(p.id),p])),qmap=new Map<string,any>();for(const q of preds)qmap.set(`${N(q.player_id)}:${N(q.gameweek)}`,q);const rmap=new Map<string,any>();for(const r of roles)rmap.set(`${N(r.player_id)}:${N(r.gameweek)}`,r);
  const opportunities:any={};for(const g of gws){const xs:any[]=[];for(const p of players||[]){if(String(p.status)!=='a')continue;const q=qmap.get(`${N(p.id)}:${g}`);if(!q)continue;const m=leverageMetric(p,q,rmap.get(`${N(p.id)}:${g}`));if(m.tier==='NONE')continue;xs.push({player_id:N(p.id),name:p.web_name,position:p.position,ownership_proxy:m.ownership_proxy,expected_points:+N(q.expected_points).toFixed(3),expected_minutes:+N(q.expected_minutes).toFixed(1),p10:+N(q.p_10_plus).toFixed(3),p15:+N(q.p_15_plus).toFixed(3),p20:+N(q.p_20_plus).toFixed(3),role:rmap.get(`${N(p.id)}:${g}`)?.primary_role??null,tier:m.tier,leverage_index:m.index})}xs.sort((a,b)=>b.leverage_index-a.leverage_index||b.expected_points-a.expected_points);opportunities[g]=xs.slice(0,8)}
  const enrich=(s:any)=>{if(!s)return null;let weighted=0,expGws=0,diffGws=0;const per:any[]=[];for(let i=0;i<gws.length;i++){const g=gws[i],plan=(s.gameweeks||[]).find((x:any)=>N(x.gameweek)===g),ids:Array<number>=(plan?.starting_xi||[]).map(Number),arr:any[]=[];for(const id of ids){const p=pmap.get(id),q=qmap.get(`${id}:${g}`);if(!p||!q)continue;const m=leverageMetric(p,q,rmap.get(`${id}:${g}`));arr.push({player_id:id,name:p.web_name,tier:m.tier,ownership_proxy:m.ownership_proxy,leverage_index:m.index,p10:+N(q.p_10_plus).toFixed(3),expected_minutes:+N(q.expected_minutes).toFixed(1)})}arr.sort((a,b)=>b.leverage_index-a.leverage_index);const li=arr.reduce((z,x)=>z+N(x.leverage_index),0),bestDiff=arr.find(x=>x.tier!=='NONE')||null,hasExp=arr.some(x=>x.tier==='EXPLOSIVE_DIFFERENTIAL'),hasDiff=arr.some(x=>x.tier==='EXPLOSIVE_DIFFERENTIAL'||x.tier==='DIFFERENTIAL');weighted+=weights[i]*li;if(hasExp)expGws++;if(hasDiff)diffGws++;per.push({gameweek:g,weight:weights[i],starting_xi_leverage_index:+li.toFixed(4),explosive_differential_present:hasExp,differential_present:hasDiff,best_selected_differential:bestDiff})}
    return{...s,decision_control:{weighted_leverage_index:+weighted.toFixed(4),gws_with_explosive_differential:expGws,gws_with_differential:diffGws,per_gameweek:per}}};
  const scenarios=(base.transfer_scenarios||[]).map(enrich),roll=enrich(base.roll);if(!roll)return Response.json({ok:false,status:'ROLL_MISSING_FROM_BASE'},{status:409});const maxObj=Math.max(...scenarios.map((x:any)=>N(x.objective))),near=scenarios.filter((x:any)=>maxObj-N(x.objective)<=err&&N(x.objective)-N(roll.objective)>=err);
  const cmp=(a:any,b:any)=>{const sa=a.strategic||{},sb=b.strategic||{},la=a.decision_control||{},lb=b.decision_control||{};const primary=()=>N(sa.role_risk_slots)-N(sb.role_risk_slots)||N(sa.role_unknown_slots)-N(sb.role_unknown_slots);const robustness=()=>N(sa.weak_slots_under_55_xmins)-N(sb.weak_slots_under_55_xmins)||N(sb.mean_min_xmins)-N(sa.mean_min_xmins);const leverage=()=>N(lb.gws_with_explosive_differential)-N(la.gws_with_explosive_differential)||N(lb.weighted_leverage_index)-N(la.weighted_leverage_index)||N(lb.gws_with_differential)-N(la.gws_with_differential);const tail=()=>N(a.transfers_in)-N(b.transfers_in)||N(b.objective)-N(a.objective);if(regime.leverage_priority==='BEFORE_SECONDARY_ROBUSTNESS')return primary()||leverage()||robustness()||tail();if(regime.leverage_priority==='AFTER_PRIMARY_ROBUSTNESS')return primary()||robustness()||leverage()||tail();return primary()||robustness()||leverage()||tail()};near.sort(cmp);const controlled=maxObj-N(roll.objective)>=err?(near[0]||[...scenarios].sort((a:any,b:any)=>N(b.objective)-N(a.objective))[0]):roll;
  const wc=enrich(base.wildcard_benchmark),compactBase={optimizer_version:base.optimizer_version,gameweek:base.gameweek,horizon:base.horizon,gws:base.gws,weights:base.weights,manager_state_id:base.manager_state_id,model_error_margin_points:base.model_error_margin_points,roll:base.roll,transfer_scenarios:base.transfer_scenarios,wildcard_benchmark:base.wildcard_benchmark,wildcard_classification:base.wildcard_classification};
  const result={ok:true,status:'DECISION_CONTROL_READ_ONLY',change_id:'C0225',decision_control_version:VERSION,optimizer_version:base.optimizer_version,gameweek:gw,horizon:h,gws,weights,manager_state_id:managerStateId,rank_state:{entry_id:entryId,overall_rank:overallRank,overall_points:overallPoints,source:rankSource,regime},ownership_semantics:{field:'players.selected_by_percent',meaning:'ownership proxy; not effective ownership',numeric_xpts_adjustment:false,forced_differential:false},model_error_margin_points:err,raw_best_objective:maxObj,roll_objective:N(roll.objective),recommended_by_leverage_control:controlled,transfer_scenarios:scenarios,wildcard_benchmark:wc,differential_opportunities:opportunities,policy:{leverage_only_inside_fixed_model_error_band:true,rank_never_widens_band_in_v01:true,structural_gate:'xMins>=60, pStart>=0.55, P10+>=0.09, no control-role risk; ownership tiers <=15/10/5%',leverage_index:'scarcity × haul-tail signal × minutes/start/role reliability; used only as Decision-Control tiebreak',captaincy_not_forced_by_ownership:true,wildcard_internal_search_not_reordered_by_c0225:true},historical_forecasts_rewritten:false};
  const sig=await sha({VERSION,optimizer:base.optimizer_version,gw,h,gws,runIds,managerStateId,rank:overallRank,points:overallPoints,playerUpdated:(players||[]).reduce((m:any,p:any)=>String(p.updated_at||'')>m?String(p.updated_at||''):m,''),objectives:(base.transfer_scenarios||[]).map((x:any)=>[x.scenario,x.objective]),wc:base.wildcard_benchmark?.objective});
  const{data:existing,error:ee}=await sb.from('fpl_decision_control_runs').select('id').eq('input_signature',sig).maybeSingle();if(ee)throw ee;let runId=existing?.id?N(existing.id):null;if(!runId){const{data:ins,error:ie}=await sb.from('fpl_decision_control_runs').insert({gameweek:gw,horizon:h,manager_state_id:managerStateId,overall_rank:overallRank,overall_points:overallPoints,rank_regime:regime.name,optimizer_version:String(base.optimizer_version),decision_control_version:VERSION,model_error_margin_points:err,input_signature:sig,raw_optimizer_result:compactBase,decision_control_result:result,historical_forecasts_rewritten:false}).select('id').single();if(ie)throw ie;runId=N(ins.id)}
  return Response.json({...result,decision_control_run_id:runId,input_signature:sig});
}catch(e){const detail=typeof e==='object'&&e?JSON.stringify(e):String(e);return Response.json({ok:false,error:e instanceof Error?e.message:detail,error_detail:detail,decisioning:false},{status:500})}});