import { createClient } from 'jsr:@supabase/supabase-js@2';
const VERSION='C0234_AUTONOMOUS_FINAL_GATE_V05_C0248_SEQUENTIAL_CONTROL';
const N=(x:any,d=0)=>Number.isFinite(Number(x))?Number(x):d;
async function sha(x:any){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(x)));return[...new Uint8Array(b)].map(v=>v.toString(16).padStart(2,'0')).join('')}
Deno.serve(async(req:Request)=>{try{
 const keys=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')||'{}'),key=keys.default||Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');
 if(!key)return Response.json({ok:false,error:'service credential missing'},{status:500});
 const sb=createClient(Deno.env.get('SUPABASE_URL')!,key,{auth:{persistSession:false}});
 const{data:tok,error:ae}=await sb.rpc('get_backend_secret',{secret_name:'FOOTBALL_ENGINE_ADMIN_TOKEN'});
 if(ae||!tok||req.headers.get('x-engine-token')!==tok)return Response.json({ok:false,error:'unauthorized'},{status:401});
 const b=await req.json().catch(()=>({})),gw=N(b.gameweek),h=Math.max(1,Math.min(5,N(b.horizon,5)));
 if(!gw)return Response.json({ok:false,error:'gameweek invalid'},{status:400});
 const [er,sr,fr,orr,rr,tr,ar,msr,fxr,prr,readyR,cr,c248r]=await Promise.all([
  sb.from('fpl_squad_ensemble_runs').select('id,result,input_signature,model_error_margin_points').eq('gameweek',gw).eq('horizon',h).order('captured_at',{ascending:false}).limit(1).single(),
  sb.from('fpl_structural_control_runs').select('id,result,input_signature').eq('gameweek',gw).eq('horizon',h).order('captured_at',{ascending:false}).limit(1).single(),
  sb.from('fpl_forward_management_runs').select('id,result,input_signature').eq('gameweek',gw).eq('horizon',h).order('captured_at',{ascending:false}).limit(1).single(),
  sb.from('fpl_or_utility_runs').select('id,result,input_signature').eq('gameweek',gw).eq('horizon',h).order('captured_at',{ascending:false}).limit(1).single(),
  sb.from('fpl_red_team_runs').select('id,result,input_signature').eq('gameweek',gw).eq('horizon',h).order('captured_at',{ascending:false}).limit(1).single(),
  sb.from('fpl_team_regime_diagnostic_runs').select('id,result,input_signature').eq('gameweek',gw).order('captured_at',{ascending:false}).limit(1).single(),
  sb.from('fpl_final_adversarial_runs').select('id,result,input_signature,stability_status,ensemble_run_id,structural_run_id,forward_run_id,or_utility_run_id,red_team_run_id,manager_state_id').eq('gameweek',gw).eq('horizon',h).order('captured_at',{ascending:false}).limit(1).single(),
  sb.from('fpl_manager_state_snapshots').select('id,free_transfers,bank_tenths,evidence').eq('gameweek',gw).order('captured_at',{ascending:false}).limit(1).single(),
  sb.from('matches').select('kickoff_time').eq('source','fpl').eq('gameweek',gw).order('kickoff_time',{ascending:true}).limit(1).single(),
  sb.from('gameweek_prediction_runs').select('id,generated_at').eq('gameweek',gw).order('generated_at',{ascending:false}).limit(1).single(),
  sb.rpc('c0234_c0213_readiness_bridge_v01',{p_gameweek:gw}),
  sb.rpc('c0242_consistency_status_bridge_v01',{p_gameweek:gw,p_horizon:h}),
  sb.rpc('c0248_decision_control_status_bridge_v01',{p_gameweek:gw,p_horizon:h})
 ]);
 for(const x of [er,sr,fr,orr,rr,tr,ar,msr,fxr,prr,readyR,cr,c248r])if(x.error)throw x.error;
 const e:any=er.data.result,s:any=sr.data.result,f:any=fr.data.result,o:any=orr.data.result,red:any=rr.data.result,team:any=tr.data.result,adv:any=ar.data.result,ready:any=readyR.data,consistency:any=cr.data,c248:any=c248r.data;
 if(!e?.ok||!s?.ok||!f?.ok||!o?.ok||!red?.ok||!team?.ok||!adv?.ok||!consistency?.ok||!c248?.ok)return Response.json({ok:false,status:'UPSTREAM_AUTONOMY_LAYER_NOT_READY',decisioning:false},{status:409});
 const decisionLineageGreen=N(ar.data.ensemble_run_id)===N(er.data.id)&&N(ar.data.structural_run_id)===N(sr.data.id)&&N(ar.data.forward_run_id)===N(fr.data.id)&&N(ar.data.or_utility_run_id)===N(orr.data.id)&&N(ar.data.red_team_run_id)===N(rr.data.id)&&N(ar.data.manager_state_id)===N(msr.data.id);
 const predictionLineageGreen=N(adv.current_prediction_run_id)===N(prr.data.id),lineageGreen=decisionLineageGreen&&predictionLineageGreen;
 const cov=adv.coverage||{},advStable=ar.data.stability_status==='STABLE_NO_MEANINGFUL_EDGE'&&lineageGreen&&N(cov.slot_attack_count)===15&&N(cov.structure_attack_count)>=8&&N(cov.path_attack_count)>=3&&cov.baseline_exact_same_horizon===true&&cov.transfer_path_complete===true&&cov.sensitivity_complete===true&&cov.repeat_cycle_no_new_edge===true&&N(cov.failed_tasks)===0;
 const now=new Date(),kick=new Date(fxr.data.kickoff_time),deadline=new Date(kick.getTime()-90*60*1000),finalThreshold=new Date(deadline.getTime()-2*60*60*1000),latestProj=new Date(prr.data.generated_at),finalWindowOpen=now>=finalThreshold,finalRefreshGreen=finalWindowOpen&&latestProj>=finalThreshold;
 const entry=N(msr.data?.evidence?.entry_id,3559923);let chipHistory:any[]=[],chipHistoryVerified=false;try{const hr=await fetch(`https://fantasy.premierleague.com/api/entry/${entry}/history/`,{headers:{'User-Agent':'FootballIntelligence/1.0'}});if(hr.ok){const hj=await hr.json();chipHistory=Array.isArray(hj?.chips)?hj.chips:[];chipHistoryVerified=true}}catch{}
 const wildcardUsedThisHalf=chipHistory.filter((c:any)=>String(c.name||'').toLowerCase().includes('wildcard')&&N(c.event)<=19).length,wildcardAvailable=gw<=19?chipHistoryVerified&&wildcardUsedThisHalf===0:chipHistoryVerified&&chipHistory.filter((c:any)=>String(c.name||'').toLowerCase().includes('wildcard')&&N(c.event)>=20).length===0;
 const err=N(er.data.model_error_margin_points,1),roll=N(e.roll?.objective),survivor:any=adv.survivor||e.best_no_chip,survivorObj=N(survivor?.objective,N(e.best_no_chip?.objective)),roleSafeStructObj=N(adv.best_role_safe_structure?.objective,Math.max(...(e.candidates||[]).map((x:any)=>N(x.objective)))),freshGain=roleSafeStructObj-survivorObj,wildcardCandidate=freshGain>=Math.max(4,2*err);
 const redEvaluated=['PASS','EDGE_NOT_ROBUST','CHALLENGED_BY_EQUIVALENT'].includes(String(red.red_team_status));
 const consistencyReady=consistency?.decision_consistency_ready===true,c248Ready=c248?.decision_control_ready===true;
 const chipChoice=String(c248?.current_chip?.recommended_current_chip||'UNRESOLVED'),currentNoChipRobust=c248?.current_chip?.current_no_chip_robust===true;
 const gates:any[]=[
  {gate:'C0213_DECISION_READINESS',pass:ready?.decision_ready===true,detail:ready?.contract_version||null},
  {gate:'TARGET_PROJECTIONS_AND_ROLES',pass:ready?.projection_ready===true,detail:`latest_projection_run=${prr.data.id}`},
  {gate:'ENSEMBLE_GENERATED',pass:e.status==='ENSEMBLE_READY'&&N(e.convergence?.unique_family_signatures)>=2,detail:e.ensemble_classification},
  {gate:'UNCERTAINTY_STATE_AND_SENSITIVITY',pass:cov.sensitivity_complete===true,detail:{c0240_sensitivity_complete:cov.sensitivity_complete}},
  {gate:'STRUCTURAL_ENSEMBLE_EVALUATED',pass:s.status==='STRUCTURAL_CONTROL_READY',detail:s.adjudication},
  {gate:'RANK_LEVERAGE_CONTROL',pass:o.status==='OR_UTILITY_READY'&&o.policy?.numeric_xpts_adjustment===false,detail:o.rank_state?.regime||null},
  {gate:'FORWARD_MANAGEMENT',pass:f.status==='FORWARD_MANAGEMENT_READY',detail:'burden explicitly evaluated'},
  {gate:'C0233_RED_TEAM_EVALUATED',pass:redEvaluated,detail:{status:red.red_team_status,blocking_reasons:red.blocking_reasons||[],adjudicator:'C0240'}},
  {gate:'C0240_FINAL_ADVERSARIAL_OPTIMIZATION',pass:advStable,detail:{run_id:ar.data.id,stability_status:ar.data.stability_status,decision_lineage_green:decisionLineageGreen,prediction_lineage_green:predictionLineageGreen,current_prediction_run_id:adv.current_prediction_run_id,latest_prediction_run_id:prr.data.id,coverage:cov,edge_vs_provisional:adv.best_role_safe_reachable_path?.edge_vs_provisional??null}},
  {gate:'C0242_DECISION_CONSISTENCY',pass:consistencyReady,detail:{contract_version:consistency?.contract_version,named_challengers:consistency?.named_challengers,captaincy_decision_class:consistency?.captaincy?.decision_class,nominal_mean_leader:consistency?.captaincy?.nominal_mean_leader,tail_leader:consistency?.captaincy?.tail_leader,equivalent_candidates:consistency?.captaincy?.equivalent_candidates}},
  {gate:'C0248_SEQUENTIAL_DECISION_CONTROL',pass:c248Ready,detail:{planner_run_id:c248?.planner_run_id,planner_version:c248?.planner_version,required_root_set_present:c248?.required_root_set_present,best_normal_root:c248?.best_normal_root?.root,normal_path_alignment:c248?.normal_path_alignment,wildcard_raw_edge:c248?.terminal_sensitivity?.raw_exact_horizon_wildcard_edge,wildcard_break_even_ft_value:c248?.terminal_sensitivity?.break_even_value_per_extra_ft_ignoring_bank_and_unused_wc_option}},
  {gate:'ROLL_COMPARISON',pass:survivorObj-roll>=err,detail:{roll:+roll.toFixed(3),survivor:+survivorObj.toFixed(3),gain:+(survivorObj-roll).toFixed(3)}},
  {gate:'FINAL_T_MINUS_2H_REFRESH',pass:finalRefreshGreen,detail:{deadline_at:deadline.toISOString(),final_refresh_threshold:finalThreshold.toISOString(),latest_projection_at:latestProj.toISOString(),window_open:finalWindowOpen}},
  {gate:'CHIP_AVAILABILITY',pass:chipChoice==='NONE'||chipHistoryVerified,detail:{recommended_current_chip:chipChoice,history_verified:chipHistoryVerified,wildcard_available:wildcardAvailable,wildcards_used_this_half:wildcardUsedThisHalf}},
  {gate:'C0248_CURRENT_CHIP_ACTION',pass:currentNoChipRobust&&chipChoice==='NONE',detail:{recommended_current_chip:chipChoice,current_no_chip_robust:currentNoChipRobust,bench_boost:c248?.current_chip?.bench_boost,triple_captain:c248?.current_chip?.triple_captain,free_hit:c248?.current_chip?.free_hit,wildcard:c248?.current_chip?.wildcard,season_best_chip_weeks_resolved:c248?.current_chip?.season_best_chip_weeks_resolved}}
 ];
 const blockers=gates.filter(g=>!g.pass).map(g=>g.gate),finalStatus=blockers.length?'DECISION_NOT_READY':'FINAL_AUTONOMOUS_DECISION';let action:any={type:'NONE',authorized:false};
 if(finalStatus==='FINAL_AUTONOMOUS_DECISION'){
   if(chipChoice==='WILDCARD'&&wildcardAvailable)action={type:'WILDCARD',details:c248?.wildcard_root?.first_action||null,authorized:false};
   else if(chipChoice==='NONE'&&survivorObj-roll>=err)action={type:'NORMAL_TRANSFERS',details:survivor,authorized:false};
   else if(chipChoice==='NONE')action={type:'ROLL',authorized:false};
 }
 const result={ok:true,status:'AUTONOMOUS_GATE_EVALUATED',change_id:'C0234',version:VERSION,gameweek:gw,horizon:h,final_status:finalStatus,action,gate_summary:{passed:gates.filter(g=>g.pass).length,total:gates.length,blockers},gates,decision_context:{ensemble_classification:e.ensemble_classification,c0240_run_id:ar.data.id,c0240_status:ar.data.stability_status,c0240_decision_lineage_green:decisionLineageGreen,c0240_prediction_lineage_green:predictionLineageGreen,c0240_current_prediction_run_id:adv.current_prediction_run_id,latest_prediction_run_id:prr.data.id,survivor_objective:+survivorObj.toFixed(3),roll_objective:+roll.toFixed(3),role_safe_structure_objective:+roleSafeStructObj.toFixed(3),fresh_edge_vs_survivor:+freshGain.toFixed(3),wildcard_candidate_legacy_metric:wildcardCandidate,red_team_status:red.red_team_status,rank_regime:o.rank_state?.regime,structural_adjudication:s.adjudication,c0242_decision_consistency_ready:consistencyReady,captaincy_decision_class:consistency?.captaincy?.decision_class,captaincy_nominal_mean_leader:consistency?.captaincy?.nominal_mean_leader,captaincy_tail_leader:consistency?.captaincy?.tail_leader,captaincy_floor_leader:consistency?.captaincy?.floor_leader,captaincy_equivalent_candidates:consistency?.captaincy?.equivalent_candidates,named_challengers:consistency?.named_challengers,c0248_decision_control_ready:c248Ready,c0248_best_normal_root:c248?.best_normal_root?.root,c0248_current_chip:chipChoice,c0248_price_all_wait:c248?.current_chip?.price_timing?.all_current_roots_wait_for_information,c0248_wildcard_raw_edge:c248?.terminal_sensitivity?.raw_exact_horizon_wildcard_edge,c0248_wildcard_break_even_ft_value:c248?.terminal_sensitivity?.break_even_value_per_extra_ft_ignoring_bank_and_unused_wc_option},fallback_reference:{c0240_survivor:survivor,c0248_best_normal_root:c248?.best_normal_root,not_authorized:true},chip_state:{source:'PUBLIC_FPL_ENTRY_HISTORY_LIVE',verified:chipHistoryVerified,wildcard_available:wildcardAvailable,used:chipHistory,current_action:c248?.current_chip},deadline_state:{first_kickoff:kick.toISOString(),deadline_at:deadline.toISOString(),final_refresh_threshold:finalThreshold.toISOString(),latest_projection_at:latestProj.toISOString()},policy:{read_only:true,writes_manager_plan:false,executes_transfers:false,final_can_refuse:true,c0233_negative_must_be_adjudicated_by_c0240:true,c0240_stable_fresh_decision_and_prediction_lineage_required:true,c0242_named_challengers_must_be_resolved:true,c0242_captaincy_no_meaningful_edge_must_not_be_described_as_edge:true,c0248_sequential_root_preservation_required:true,c0248_current_chip_action_must_be_robust:true,no_chip_does_not_require_future_best_chip_week_to_be_known:true,price_signal_cannot_create_transfer:true,standing_final_t_minus_2h_refresh_required:true,historical_forecasts_append_only:true},historical_forecasts_rewritten:false,decisioning:false};
 const sig=await sha({VERSION,ensemble:er.data.input_signature,structural:sr.data.input_signature,forward:fr.data.input_signature,or:orr.data.input_signature,red:rr.data.input_signature,team:tr.data.input_signature,c0240:ar.data.input_signature,c0240Status:ar.data.stability_status,c0240DecisionLineage:decisionLineageGreen,c0240PredictionLineage:predictionLineageGreen,c0242:consistency,c0248:{run_id:c248?.planner_run_id,ready:c248Ready,current_chip:c248?.current_chip,terminal:c248?.terminal_sensitivity},ready:ready?.decision_ready,projection:prr.data.id,finalRefreshGreen,chipHistory});
 const{data:old,error:oe}=await sb.from('fpl_autonomous_gate_runs').select('id').eq('input_signature',sig).maybeSingle();if(oe)throw oe;let id=old?.id?N(old.id):null;
 if(!id){const{data:ins,error:ie}=await sb.from('fpl_autonomous_gate_runs').insert({gameweek:gw,horizon:h,ensemble_run_id:er.data.id,structural_run_id:sr.data.id,forward_run_id:fr.data.id,or_utility_run_id:orr.data.id,red_team_run_id:rr.data.id,team_regime_run_id:tr.data.id,input_signature:sig,result,final_status:finalStatus,historical_forecasts_rewritten:false}).select('id').single();if(ie)throw ie;id=N(ins.id)}
 return Response.json({...result,autonomous_gate_run_id:id,input_signature:sig});
}catch(e){return Response.json({ok:false,status:'AUTONOMOUS_GATE_ERROR',error:e instanceof Error?e.message:String(e),decisioning:false},{status:500})}});