import { createClient } from 'supabase';
const H={'content-type':'application/json; charset=utf-8','cache-control':'no-store'};
const errText=(e:any)=>e instanceof Error?e.message:e?.message?String(e.message):JSON.stringify(e);
Deno.serve(async(req)=>{try{
  if(req.method!=='POST')return new Response(JSON.stringify({ok:false,error:'POST required'}),{status:405,headers:H});
  const ks=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')||'{}');const key=ks.default||Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!key)throw new Error('Missing service credential');
  const sb=createClient(Deno.env.get('SUPABASE_URL')!,key,{auth:{persistSession:false}});
  const {data:tok,error:ae}=await sb.rpc('get_backend_secret',{secret_name:'FOOTBALL_ENGINE_ADMIN_TOKEN'});if(ae||!tok||req.headers.get('x-engine-token')!==tok)return new Response(JSON.stringify({ok:false,error:'unauthorized'}),{status:401,headers:H});
  const body=await req.json().catch(()=>({}));const gw=body.gameweek==null?null:Number(body.gameweek);
  const call=async(name:string,args?:Record<string,unknown>)=>{const {data,error}=await sb.rpc(name,args);if(error)throw new Error(`${name}: ${error.message}`);return data};
  const safe=async(name:string,args?:Record<string,unknown>)=>{try{return {status:'success',data:await call(name,args),error:null}}catch(e){return {status:'error',data:null,error:errText(e)}}};
  const rawProfiles=await call('refresh_player_role_profiles_v02');
  const calibratedProfiles=await call('refresh_player_role_profiles_v021');
  const teamProfiles=await call('refresh_team_tactical_profiles_v011');
  const playerFixtures=await call('refresh_player_fixture_role_snapshots',{p_gameweek:gw});
  const teamFixtures=await call('refresh_team_fixture_tactical_snapshots',{p_gameweek:gw});
  const replacement=await safe('refresh_replacement_quality_v011',{p_gameweek:gw});
  const matchups=await safe('refresh_fixture_tactical_matchups_v011',{p_gameweek:gw});
  const validation=await safe('refresh_role_forward_validation_v02');
  return new Response(JSON.stringify({ok:true,gameweek:gw,player_profiles_raw:rawProfiles,player_profiles_calibrated:calibratedProfiles,team_profiles:teamProfiles,player_fixture_roles:playerFixtures,team_fixture_tactics:teamFixtures,replacement_quality:replacement,tactical_matchups:matchups,forward_role_validation:validation,model_effect_enabled:false,note:'Role/Tactical v5 adds fixture-specific observational matchup intelligence after replacement refresh. Tactical matchup scores are research only: no left/right flank assignment, no defensive pressing intensity, no defensive line height, and no validated replacement ability effect.'}),{headers:H});
}catch(e){return new Response(JSON.stringify({ok:false,error:errText(e)}),{status:500,headers:H})}});
