import { createClient } from 'supabase';

type PlayerRow={id:number;fpl_player_id:number;team_id:number;position:string;web_name:string};
type StateRow={player_id:number;as_of:string;start_probability:number|null;expected_minutes:number|null};
const formations:[[number,number,number],string][]=[[[3,4,3],'3-4-3'],[[3,5,2],'3-5-2'],[[4,3,3],'4-3-3'],[[4,4,2],'4-4-2'],[[4,5,1],'4-5-1'],[[5,2,3],'5-2-3'],[[5,3,2],'5-3-2'],[[5,4,1],'5-4-1']];
const clamp=(x:number,a=0,b=1)=>Math.max(a,Math.min(b,x));
const normChance=(v:any)=>v===null||v===undefined?null:clamp(Number(v)>1?Number(v)/100:Number(v));
const availability=(s:string)=>s==='a'?'AVAILABLE':s==='d'?'DOUBTFUL':s==='i'?'INJURED':s==='s'?'SUSPENDED':s==='u'?'UNAVAILABLE':'UNKNOWN';
const hardUnavailable=(s:string)=>s==='i'||s==='s'||s==='u';
const emsg=(e:any)=>e instanceof Error?e.message:typeof e==='string'?e:JSON.stringify(e);
async function sha(s:string){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join('')}
function chooseXI(players:any[]){let best:any=null;for(const [counts,label] of formations){const [d,m,f]=counts;const pick=(pos:string,n:number)=>players.filter(x=>x.position===pos&&!hardUnavailable(x.fpl_status)).sort((a,b)=>b.xi_score-a.xi_score||a.player_id-b.player_id).slice(0,n);const g=pick('GKP',1),ds=pick('DEF',d),ms=pick('MID',m),fs=pick('FWD',f);if(g.length<1||ds.length<d||ms.length<m||fs.length<f)continue;const xi=[...g,...ds,...ms,...fs],score=xi.reduce((z,x)=>z+x.xi_score,0);if(!best||score>best.score)best={formation:label,score,ids:new Set(xi.map(x=>x.player_id))}}return best||{formation:'UNRESOLVED',score:0,ids:new Set<number>()}}
Deno.serve(async(req)=>{try{
  if(req.method!=='POST')return Response.json({ok:false,error:'POST required'},{status:405});
  const keys=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')||'{}');const key=keys.default||Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!key)throw new Error('Missing service credential');
  const sb=createClient(Deno.env.get('SUPABASE_URL')!,key,{auth:{persistSession:false}});const {data:adminToken,error:authError}=await sb.rpc('get_backend_secret',{secret_name:'FOOTBALL_ENGINE_ADMIN_TOKEN'});if(authError||!adminToken||req.headers.get('x-engine-token')!==adminToken)return Response.json({ok:false,error:'unauthorized'},{status:401});
  const body=await req.json().catch(()=>({}));const observedAt=new Date().toISOString();let gw=Number(body.gameweek||0);if(!gw){const {data:nxt,error}=await sb.from('matches').select('gameweek,kickoff_time').eq('source','fpl').gt('kickoff_time',observedAt).not('gameweek','is',null).order('kickoff_time',{ascending:true}).limit(1).maybeSingle();if(error)throw error;gw=Number(nxt?.gameweek||0)}if(!gw)return Response.json({ok:true,gameweek:null,fixtures:0,inserted:0,message:'No future FPL fixture'});
  const {data:fixtures,error:fe}=await sb.from('matches').select('id,gameweek,kickoff_time,home_team_id,away_team_id').eq('source','fpl').eq('gameweek',gw).gt('kickoff_time',observedAt).order('kickoff_time',{ascending:true});if(fe)throw fe;if(!fixtures?.length)return Response.json({ok:true,gameweek:gw,fixtures:0,inserted:0,message:'No pre-kickoff fixtures'});
  const br=await fetch('https://fantasy.premierleague.com/api/bootstrap-static/',{headers:{'User-Agent':'FootballIntelligence/0.3'}});if(!br.ok)throw new Error(`FPL bootstrap ${br.status}`);const bootstrap=await br.json();
  const [{data:dbTeams,error:te}]=await Promise.all([sb.from('teams').select('id,fpl_team_id')]);if(te)throw te;const teamMap=new Map((dbTeams||[]).map((t:any)=>[Number(t.fpl_team_id),Number(t.id)]));const posMap=new Map((bootstrap.element_types||[]).map((p:any)=>[Number(p.id),String(p.singular_name_short)]));
  const meta=(bootstrap.elements||[]).map((p:any)=>({fpl_player_id:Number(p.id),player_code:p.code??null,team_id:teamMap.get(Number(p.team))??null,first_name:p.first_name??null,second_name:p.second_name??null,web_name:String(p.web_name||p.second_name||p.first_name||`FPL-${p.id}`),position:posMap.get(Number(p.element_type))??null,status:p.status,now_cost:p.now_cost??null,selected_by_percent:p.selected_by_percent==null?null:Number(p.selected_by_percent),chance_of_playing_next_round:normChance(p.chance_of_playing_next_round),news:String(p.news||'').trim()||null,penalties_order:p.penalties_order??null,direct_freekicks_order:p.direct_freekicks_order??null,corners_and_indirect_freekicks_order:p.corners_and_indirect_freekicks_order??null,updated_at:observedAt}));for(let k=0;k<meta.length;k+=200){const {error}=await sb.from('players').upsert(meta.slice(k,k+200),{onConflict:'fpl_player_id'});if(error)throw new Error(`player metadata upsert: ${emsg(error)}`)}
  const {data:dbPlayers,error:pe}=await sb.from('players').select('id,fpl_player_id,team_id,position,web_name');if(pe)throw pe;const players=dbPlayers as PlayerRow[];const fplMeta=new Map((bootstrap.elements||[]).map((p:any)=>[Number(p.id),p]));const teamIds=[...new Set(fixtures.flatMap((f:any)=>[Number(f.home_team_id),Number(f.away_team_id)]))];const relevant=players.filter(p=>teamIds.includes(Number(p.team_id)));const pids=relevant.map(p=>p.id);
  const {data:states,error:se}=await sb.from('player_state').select('player_id,as_of,start_probability,expected_minutes').in('player_id',pids).lte('as_of',observedAt).order('as_of',{ascending:false}).limit(2000);if(se)throw new Error(`player_state: ${emsg(se)}`);const latest=new Map<number,StateRow>();for(const s of (states||[]) as StateRow[])if(!latest.has(Number(s.player_id)))latest.set(Number(s.player_id),s);
  const rows:any[]=[];for(const f of fixtures){for(const teamId of [Number(f.home_team_id),Number(f.away_team_id)]){const opp=teamId===Number(f.home_team_id)?Number(f.away_team_id):Number(f.home_team_id);const teamPlayers=relevant.filter(p=>Number(p.team_id)===teamId).map(p=>{const fm:any=fplMeta.get(Number(p.fpl_player_id))||{},st=latest.get(Number(p.id));const sc=hardUnavailable(String(fm.status||''))?0:Number(st?.start_probability||0);return{player_id:p.id,fpl_player_id:p.fpl_player_id,position:p.position,web_name:p.web_name,fpl_status:String(fm.status||''),chance:normChance(fm.chance_of_playing_next_round),news:String(fm.news||'').trim()||null,state:st,xi_score:sc}});const chosen=chooseXI(teamPlayers);const ranks=new Map<number,number>();for(const pos of ['GKP','DEF','MID','FWD'])teamPlayers.filter(x=>x.position===pos).sort((a,b)=>b.xi_score-a.xi_score||a.player_id-b.player_id).forEach((x,i)=>ranks.set(x.player_id,i+1));for(const x of teamPlayers){const st=x.state,ageH=st?.as_of?(Date.parse(observedAt)-Date.parse(st.as_of))/36e5:null;const sourceConf=x.fpl_status==='i'||x.fpl_status==='s'||x.fpl_status==='u'?0.98:x.fpl_status==='d'?0.75:x.fpl_status==='a'?0.85:0.4;const stateConf=ageH===null?0.35:ageH<=48?0.9:ageH<=168?0.7:0.45;const conf=hardUnavailable(x.fpl_status)?sourceConf:Math.min(sourceConf,stateConf);const ev={source:'official_fpl_bootstrap',source_item_timestamp_available:false,fetch_time:observedAt,state_age_hours:ageH===null?null:+ageH.toFixed(2),xi_method:'max_start_probability_under_valid_fpl_formation',formation_is_candidate_shape_not_tactical_prediction:true,replacement_quality_status:'NOT_MODELED_NO_RELIABLE_ROLE_MAP',model_effect_enabled:false};const hashInput={match_id:f.id,player_id:x.player_id,status:x.fpl_status,chance:x.chance,news:x.news,state_as_of:st?.as_of||null,start:st?.start_probability??null,mins:st?.expected_minutes??null,xi:chosen.ids.has(x.player_id),formation:chosen.formation,rank:ranks.get(x.player_id)||null};rows.push({match_id:f.id,gameweek:gw,team_id:teamId,opponent_team_id:opp,player_id:x.player_id,kickoff_time:f.kickoff_time,captured_at:observedAt,source:'official_fpl',source_updated_at:observedAt,fpl_status_code:x.fpl_status,availability_status:availability(x.fpl_status),chance_of_playing:x.chance,news:x.news,player_state_as_of:st?.as_of||null,base_start_probability:st?.start_probability??null,base_expected_minutes:st?.expected_minutes??null,xi_score:x.xi_score,expected_xi:chosen.ids.has(x.player_id),expected_xi_formation:chosen.formation,xi_rank_within_position:ranks.get(x.player_id)||null,confidence:+conf.toFixed(3),observation_hash:await sha(JSON.stringify(hashInput)),evidence:ev,model_effect_enabled:false})}}}
  let inserted=0;for(let k=0;k<rows.length;k+=200){const {data,error}=await sb.from('player_fixture_availability_observations').upsert(rows.slice(k,k+200),{onConflict:'match_id,player_id,observation_hash',ignoreDuplicates:true}).select('id');if(error)throw new Error(`availability insert: ${emsg(error)}`);inserted+=(data||[]).length}return Response.json({ok:true,gameweek:gw,fixtures:fixtures.length,candidates:rows.length,inserted,player_dimension:players.length,observed_at:observedAt,replacement_quality:'NOT_MODELED_NO_RELIABLE_ROLE_MAP',model_effect_enabled:false});
}catch(e){return Response.json({ok:false,error:emsg(e)},{status:500})}});
