import { createClient } from 'jsr:@supabase/supabase-js@2';
const VERSION='C0229_STRUCTURAL_CONTROL_V01';
const N=(x:any,d=0)=>Number.isFinite(Number(x))?Number(x):d;
async function sha(x:any){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(x)));return[...new Uint8Array(b)].map(v=>v.toString(16).padStart(2,'0')).join('')}
function sevRank(s:string){return s==='CRITICAL'?4:s==='HIGH'?3:s==='MEDIUM'?2:1}
Deno.serve(async(req:Request)=>{try{
 const keys=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')||'{}'),key=keys.default||Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!key)return Response.json({ok:false,error:'service credential missing'},{status:500});const sb=createClient(Deno.env.get('SUPABASE_URL')!,key,{auth:{persistSession:false}});const{data:tok,error:ae}=await sb.rpc('get_backend_secret',{secret_name:'FOOTBALL_ENGINE_ADMIN_TOKEN'});if(ae||!tok||req.headers.get('x-engine-token')!==tok)return Response.json({ok:false,error:'unauthorized'},{status:401});
 const b=await req.json().catch(()=>({})),gw=N(b.gameweek),h=Math.max(1,Math.min(5,N(b.horizon,5)));if(!gw)return Response.json({ok:false,error:'gameweek invalid'},{status:400});
 const{data:e,error:ee}=await sb.from('fpl_squad_ensemble_runs').select('id,result,model_error_margin_points,input_signature').eq('gameweek',gw).eq('horizon',h).order('captured_at',{ascending:false}).limit(1).single();if(ee||!e)return Response.json({ok:false,status:'ENSEMBLE_MISSING',decisioning:false},{status:409});const er:any=e.result,err=N(e.model_error_margin_points,1);if(!er?.ok||er?.status!=='ENSEMBLE_READY')return Response.json({ok:false,status:'ENSEMBLE_NOT_READY',decisioning:false},{status:409});
 const candidates:Array<any>=(Array.isArray(er.near_equivalence_class)&&er.near_equivalence_class.length>=2)?er.near_equivalence_class:er.candidates;if(!Array.isArray(candidates)||!candidates.length)return Response.json({ok:false,status:'NO_CANDIDATES',decisioning:false},{status:409});
 const ids=[...new Set(candidates.flatMap((c:any)=>(c.squad||[]).map((p:any)=>N(p.player_id))))];const{data:u,error:ue}=await sb.from('current_fpl_projection_uncertainty_v01').select('player_id,uncertainty_class,minutes_risk,role_uncertainty,regression_dependency,low_legacy_confidence').eq('gameweek',gw).in('player_id',ids);if(ue)throw ue;const um=new Map((u||[]).map((x:any)=>[N(x.player_id),x]));
 const analyse=(c:any)=>{const sq=c.squad||[],flags:any[]=[];const uc:any={LOW:0,MEDIUM:0,HIGH:0,UNKNOWN:0};for(const p of sq){const z:any=um.get(N(p.player_id));uc[z?.uncertainty_class||'UNKNOWN']=(uc[z?.uncertainty_class||'UNKNOWN']||0)+1}
  const defs=sq.filter((p:any)=>p.position==='DEF'),defSpend=defs.reduce((s:number,p:any)=>s+N(p.budget_price_tenths),0),attackSpend=sq.filter((p:any)=>p.position==='MID'||p.position==='FWD').reduce((s:number,p:any)=>s+N(p.budget_price_tenths),0);const premDef:any[]=[];for(const p of defs.filter((x:any)=>N(x.now_price_tenths)>=70)){const cheap=defs.filter((x:any)=>N(x.now_price_tenths)<=N(p.now_price_tenths)-15).sort((a:any,b:any)=>Math.abs(N(p.horizon_score)-N(a.horizon_score))-Math.abs(N(p.horizon_score)-N(b.horizon_score)))[0];if(cheap){const saving=N(p.now_price_tenths)-N(cheap.now_price_tenths),gap=N(p.horizon_score)-N(cheap.horizon_score);if(saving>=15&&gap<=3)premDef.push({premium_player_id:p.player_id,premium_name:p.name,premium_price_tenths:N(p.now_price_tenths),cheaper_player_id:cheap.player_id,cheaper_name:cheap.name,cheaper_price_tenths:N(cheap.now_price_tenths),cash_saving_tenths:saving,horizon_points_gain_for_premium:+gap.toFixed(3),marginal_points_per_extra_million:+(gap/(saving/10)).toFixed(3)})}}
  const clubs:any={};for(const p of sq){if(!clubs[p.team])clubs[p.team]=[];clubs[p.team].push(p)}const sat:any[]=[];for(const [team,ps] of Object.entries(clubs) as any){if(ps.length===3){const dc=ps.filter((p:any)=>p.position==='DEF').length,attack=ps.filter((p:any)=>['MID','FWD'].includes(p.position)),premiumAttack=attack.some((p:any)=>N(p.now_price_tenths)>=90);if(dc>=2&&attack.length>=1)sat.push({team,players:ps.map((p:any)=>p.name),defenders:dc,premium_attacker_present:premiumAttack})}}
  const roleRisk=N(c.strategic?.role_risk_slots),roleUnknown=N(c.strategic?.role_unknown_slots),weak=N(c.strategic?.weak_slots_under_55_xmins),bench=(c.gameweeks||[]).reduce((s:number,g:any)=>s+N(g.weight)*N(g.bench_expected_points),0);if(roleRisk>0)flags.push({severity:'HIGH',code:'ROLE_RISK_SLOT',count:roleRisk});if(roleUnknown>0)flags.push({severity:'HIGH',code:'ROLE_UNKNOWN_SLOT',count:roleUnknown});if(weak>0)flags.push({severity:'HIGH',code:'WEAK_XMINS_SLOT',count:weak});if(uc.HIGH>0)flags.push({severity:'HIGH',code:'HIGH_MODEL_UNCERTAINTY',count:uc.HIGH});if(premDef.length)flags.push({severity:'MEDIUM',code:'PREMIUM_DEFENDER_OPPORTUNITY_COST',count:premDef.length,details:premDef});if(sat.length)flags.push({severity:sat.some(x=>x.premium_attacker_present)?'HIGH':'MEDIUM',code:'CLUB_SLOT_SATURATION',count:sat.length,details:sat});
  const maxSev=Math.max(0,...flags.map(f=>sevRank(f.severity)));return{profile:c.profile,family_signature:c.family_signature,objective:N(c.objective),gap_to_raw_best:N(c.gap_to_best),squad:c.squad,gameweeks:c.gameweeks,strategic:c.strategic,uncertainty_counts:uc,defence_spend_tenths:defSpend,attack_spend_tenths:attackSpend,weighted_bench_leakage:+bench.toFixed(3),premium_defender_opportunity_costs:premDef,club_slot_saturation:sat,flags,max_flag_severity:maxSev}}
 const a=candidates.map(analyse),raw=[...a].sort((x,y)=>y.objective-x.objective)[0];const cmp=(x:any,y:any)=>N(x.strategic?.role_risk_slots)-N(y.strategic?.role_risk_slots)||N(x.uncertainty_counts.HIGH)-N(y.uncertainty_counts.HIGH)||N(x.strategic?.role_unknown_slots)-N(y.strategic?.role_unknown_slots)||N(x.strategic?.weak_slots_under_55_xmins)-N(y.strategic?.weak_slots_under_55_xmins)||N(x.uncertainty_counts.MEDIUM)-N(y.uncertainty_counts.MEDIUM)||N(x.max_flag_severity)-N(y.max_flag_severity)||N(x.premium_defender_opportunity_costs.length)-N(y.premium_defender_opportunity_costs.length)||N(x.club_slot_saturation.length)-N(y.club_slot_saturation.length)||N(x.weighted_bench_leakage)-N(y.weighted_bench_leakage)||N(y.strategic?.itb_tenths)-N(x.strategic?.itb_tenths)||y.objective-x.objective;const structural=[...a].sort(cmp)[0];const rawGap=raw.objective-structural.objective;const adjudication=raw.profile===structural.profile?'RAW_OPTIMUM_STRUCTURALLY_SUPPORTED':rawGap<=2*err?'RAW_OPTIMUM_STRUCTURALLY_CHALLENGED':'STRUCTURAL_CHALLENGER_OUTSIDE_SENSITIVITY_BAND';
 const result={ok:true,status:'STRUCTURAL_CONTROL_READY',change_id:'C0229',version:VERSION,gameweek:gw,horizon:h,ensemble_run_id:N(e.id),model_error_margin_points:err,raw_best:{profile:raw.profile,family_signature:raw.family_signature,objective:+raw.objective.toFixed(3)},structural_preferred:{profile:structural.profile,family_signature:structural.family_signature,objective:+structural.objective.toFixed(3),gap_to_raw_best:+rawGap.toFixed(3),flags:structural.flags,uncertainty_counts:structural.uncertainty_counts,defence_spend_tenths:structural.defence_spend_tenths,attack_spend_tenths:structural.attack_spend_tenths,weighted_bench_leakage:structural.weighted_bench_leakage,premium_defender_opportunity_costs:structural.premium_defender_opportunity_costs,club_slot_saturation:structural.club_slot_saturation,squad:structural.squad,gameweeks:structural.gameweeks},candidate_diagnostics:a.map(x=>({profile:x.profile,family_signature:x.family_signature,objective:+x.objective.toFixed(3),gap_to_raw_best:+x.gap_to_raw_best.toFixed(3),role_risk_slots:N(x.strategic?.role_risk_slots),role_unknown_slots:N(x.strategic?.role_unknown_slots),weak_xmins_slots:N(x.strategic?.weak_slots_under_55_xmins),uncertainty_counts:x.uncertainty_counts,defence_spend_tenths:x.defence_spend_tenths,attack_spend_tenths:x.attack_spend_tenths,weighted_bench_leakage:x.weighted_bench_leakage,premium_defender_opportunity_costs:x.premium_defender_opportunity_costs,club_slot_saturation:x.club_slot_saturation,flags:x.flags})),adjudication,policy:{lexicographic_not_points_multiplier:true,only_candidates_inside_2x_error_sensitivity_band_compared:true,premium_defender_test_generic:true,club_slot_test_generic:true,xpts_rewritten:false},historical_forecasts_rewritten:false,decisioning:false};
 const sig=await sha({VERSION,ensemble:e.id,input:e.input_signature,candidates:a.map(x=>[x.profile,x.objective,x.flags.map((f:any)=>f.code)])});const{data:old,error:oe}=await sb.from('fpl_structural_control_runs').select('id').eq('input_signature',sig).maybeSingle();if(oe)throw oe;let id=old?.id?N(old.id):null;if(!id){const{data:ins,error:ie}=await sb.from('fpl_structural_control_runs').insert({gameweek:gw,horizon:h,ensemble_run_id:e.id,input_signature:sig,result,historical_forecasts_rewritten:false}).select('id').single();if(ie)throw ie;id=N(ins.id)}return Response.json({...result,structural_run_id:id,input_signature:sig});
}catch(e){return Response.json({ok:false,status:'STRUCTURAL_CONTROL_ERROR',error:e instanceof Error?e.message:String(e),decisioning:false},{status:500})}});