import { createClient } from 'jsr:@supabase/supabase-js@2';
const H={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, content-type','Content-Type':'application/json','Cache-Control':'no-store'};
const clean=(s:string)=>String(s||'').toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,' ').replace(/\b(fc|afc)\b/g,'').replace(/\s+/g,' ').trim();
const aliases:Record<string,string>={'man utd':'manchester united','man united':'manchester united','man city':'manchester city','nott m forest':'nottingham forest','nottingham':'nottingham forest','spurs':'tottenham hotspur','tottenham':'tottenham hotspur','wolves':'wolverhampton wanderers','wolverhampton':'wolverhampton wanderers','brighton':'brighton and hove albion','brighton hove albion':'brighton and hove albion','newcastle':'newcastle united','west ham':'west ham united'};
const canon=(s:string)=>aliases[clean(s)]||clean(s);
const num=(v:any)=>v==null||v===''?null:Number.isFinite(Number(v))?Number(v):null;
async function understat(season:number){const url=`https://understat.com/getLeagueData/EPL/${season}`;const r=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0 FootballIntelligence/0.1','Referer':'https://understat.com/league/EPL','X-Requested-With':'XMLHttpRequest','Accept':'application/json,text/plain,*/*'}});if(!r.ok)throw Error(`Understat ${r.status}`);const j=await r.json();const dates=j?.dates||j?.data?.dates||j;if(!Array.isArray(dates))throw Error('Understat schema changed');return dates.map((m:any)=>({source:'understat',source_match_id:String(m.id??`${m.datetime}|${m.h?.title}|${m.a?.title}`),kickoff:m.datetime||m.date,home:m.h?.title||m.home?.title||m.home_team,away:m.a?.title||m.away?.title||m.away_team,hg:num(m.goals?.h??m.home_goals),ag:num(m.goals?.a??m.away_goals),hxg:num(m.xG?.h??m.home_xg),axg:num(m.xG?.a??m.away_xg),raw:m})).filter((m:any)=>m.kickoff&&m.home&&m.away&&m.hxg!=null&&m.axg!=null)}
async function githubFallback(season:number){const label=`${season}-${String(season+1).slice(-2)}`;const urls=[`https://raw.githubusercontent.com/FPLYogi/FPL-Data/main/data/${label}/matches.csv`,`https://raw.githubusercontent.com/darutto/FPL-Elo-Insights/main/data/${label}/matches.csv`];for(const url of urls){try{const r=await fetch(url);if(!r.ok)continue;const text=await r.text(),lines=text.trim().split(/\r?\n/),heads=lines[0].split(',').map(x=>x.replace(/^"|"$/g,''));const rows=lines.slice(1).map(line=>{const vals=line.match(/("(?:[^"]|"")*"|[^,]*)(?:,|$)/g)?.map(x=>x.replace(/,$/,'').replace(/^"|"$/g,'').replace(/""/g,'"'))||[];return Object.fromEntries(heads.map((h,i)=>[h,vals[i]??'']))});const out=rows.map((m:any)=>({source:'github_fpl_dataset',source_match_id:String(m.match_id||`${m.kickoff_time}|${m.home_team_name||m.home_team}|${m.away_team_name||m.away_team}`),kickoff:m.kickoff_time,home:m.home_team_name||m.home_team,away:m.away_team_name||m.away_team,hg:num(m.home_score),ag:num(m.away_score),hxg:num(m.home_expected_goals_xg),axg:num(m.away_expected_goals_xg),raw:m})).filter((m:any)=>m.kickoff&&m.home&&m.away&&m.hxg!=null&&m.axg!=null);if(out.length)return out}catch(_){}}throw Error('All xG fallback sources unavailable')}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:H});try{const b=await req.json().catch(()=>({})),season=Number(b.season||2025),gw=b.gameweek==null?null:Number(b.gameweek),sb=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false}});const {data:teams,error:te}=await sb.from('teams').select('id,name,short_name');if(te)throw te;const teamMap=new Map<string,any>();for(const t of teams||[]){teamMap.set(canon(t.name),t);if(t.short_name)teamMap.set(canon(t.short_name),t)}let rows:any[],primaryError:string|null=null;try{rows=await understat(season)}catch(e){primaryError=e instanceof Error?e.message:String(e);rows=await githubFallback(season)}let inserted=0,unmatched:any[]=[],invalid=0;for(const m of rows){const ht=teamMap.get(canon(m.home)),at=teamMap.get(canon(m.away));if(!ht||!at){unmatched.push({home:m.home,away:m.away,home_canon:canon(m.home),away_canon:canon(m.away)});continue}if(m.hxg==null||m.axg==null||m.hxg<0||m.axg<0||m.hxg>10||m.axg>10){invalid++;continue}const kick=new Date(m.kickoff);if(Number.isNaN(+kick)){invalid++;continue}const base={fixture_kickoff:kick.toISOString(),captured_at:new Date().toISOString(),source:m.source,source_match_id:m.source_match_id,competition:'Premier League',raw:m.raw};const recs=[{...base,team_id:ht.id,venue:'home',goals_for:m.hg,goals_against:m.ag,xg_for:m.hxg,xg_against:m.axg},{...base,team_id:at.id,venue:'away',goals_for:m.ag,goals_against:m.hg,xg_for:m.axg,xg_against:m.hxg}];const {data,error}=await sb.from('team_match_intelligence').upsert(recs,{onConflict:'source,source_match_id,team_id',ignoreDuplicates:true}).select('id');if(error)throw error;inserted+=(data||[]).length}
let signals=null;if(gw!=null){const {data,error}=await sb.rpc('generate_observational_intelligence',{p_gameweek:gw});signals=error?{error:error.message}:{inserted:data}}
return new Response(JSON.stringify({ok:true,season,provider:rows[0]?.source||null,primary_error:primaryError,source_matches:rows.length,new_team_rows:inserted,unmatched_count:unmatched.length,unmatched:unmatched.slice(0,30),invalid,signals,model_effect_enabled:false}),{headers:H})}catch(e){return new Response(JSON.stringify({ok:false,error:e instanceof Error?e.message:String(e)}),{status:500,headers:H})}});