import { createClient } from 'jsr:@supabase/supabase-js@2';
const VERSION='C0228_ENSEMBLE_AGGREGATOR_V01';
const OPT='C0228_DISTRIBUTED_ENSEMBLE_OPTIMIZER_V02';
const N=(x:any,d=0)=>Number.isFinite(Number(x))?Number(x):d;
async function sha(x:any){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(x)));return[...new Uint8Array(b)].map(v=>v.toString(16).padStart(2,'0')).join('')}
function squadKey(s:any){return (s?.squad||[]).map((p:any)=>N(p.player_id)).sort((a:number,b:number)=>a-b).join('-')}
function counts(s:any){const c:any={GKP:0,DEF:0,MID:0,FWD:0},clubs:any={};let cost=0;for(const p of s?.squad||[]){c[p.position]=(c[p.position]||0)+1;clubs[p.team]=(clubs[p.team]||0)+1;cost+=N(p.budget_price_tenths)}return{positions:c,max_club:Math.max(0,...Object.values(clubs).map((x:any)=>N(x))),cost}}
function family(s:any){const pf=(s?.squad||[]).filter((p:any)=>p.position==='FWD'&&N(p.now_price_tenths)>=90).length,pm=(s?.squad||[]).filter((p:any)=>p.position==='MID'&&N(p.now_price_tenths)>=90).length,pd=(s?.squad||[]).filter((p:any)=>p.position==='DEF'&&N(p.now_price_tenths)>=70).length;return`PF${pf}_PM${pm}_PD${pd}`}
function validCandidate(s:any,budget:number,profile:string){if(!s||!Array.isArray(s.squad)||s.squad.length!==15)return{ok:false,reason:'SQUAD_SIZE'};const c=counts(s);if(c.positions.GKP!==2||c.positions.DEF!==5||c.positions.MID!==5||c.positions.FWD!==3)return{ok:false,reason:'POSITION_COMPOSITION'};if(c.max_club>3)return{ok:false,reason:'CLUB_LIMIT'};if(c.cost>budget)return{ok:false,reason:'BUDGET'};if(profile==='PREMIUM_FORWARD'&&!s.squad.some((p:any)=>p.position==='FWD'&&N(p.now_price_tenths)>=90))return{ok:false,reason:'PROFILE_ANCHOR_LOST'};if(profile==='DUAL_PREMIUM_MID_VALUE'){const pm=s.squad.filter((p:any)=>p.position==='MID'&&N(p.now_price_tenths)>=90).length,pf=s.squad.filter((p:any)=>p.position==='FWD'&&N(p.now_price_tenths)>=90).length;if(pm<2||pf>0)return{ok:false,reason:'PROFILE_ANCHOR_LOST'}}return{ok:true}}
Deno.serve(async(req:Request)=>{try{
 const keys=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')||'{}'),key=keys.default||Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!key)return Response.json({ok:false,error:'service credential missing'},{status:500});
 const sb=createClient(Deno.env.get('SUPABASE_URL')!,key,{auth:{persistSession:false}});const{data:tok,error:ae}=await sb.rpc('get_backend_secret',{secret_name:'FOOTBALL_ENGINE_ADMIN_TOKEN'});if(ae||!tok||req.headers.get('x-engine-token')!==tok)return Response.json({ok:false,error:'unauthorized'},{status:401});
 const b=await req.json().catch(()=>({})),gw=N(b.gameweek),h=Math.max(1,Math.min(5,N(b.horizon,5))),err=Math.max(.25,Math.min(5,N(b.model_error_margin_points,1))),ft=Math.max(0,Math.min(5,N(b.free_transfers,3)));if(!gw)return Response.json({ok:false,error:'gameweek invalid'},{status:400});
 const baseBody={gameweek:gw,horizon:h,free_transfers:ft,model_error_margin_points:err,weights:b.weights};
 const call=async(extra:any)=>{const r=await fetch(`${Deno.env.get('SUPABASE_URL')}/functions/v1/fpl-full-pool-optimizer`,{method:'POST',headers:{'content-type':'application/json','x-engine-token':String(tok),'authorization':`Bearer ${key}`},body:JSON.stringify({...baseBody,...extra})});const j=await r.json().catch(()=>null);return{http:r.status,ok:r.ok&&j?.ok,result:j}};
 const [base,mid,durable]=await Promise.all([
   call({}),
   call({ensemble_profile:'DUAL_PREMIUM_MID_VALUE',profile_only:true}),
   call({ensemble_profile:'HIGH_MINUTES_DURABLE',profile_only:true})
 ]);
 const calls=[{name:'BASE_BALANCED_PREMIUM',x:base},{name:'DUAL_PREMIUM_MID_VALUE',x:mid},{name:'HIGH_MINUTES_DURABLE',x:durable}];
 const failures=calls.filter(z=>!z.x.ok).map(z=>({profile:z.name,http:z.x.http,status:z.x.result?.status||null,error:z.x.result?.error||null}));if(failures.length)return Response.json({ok:false,status:'ENSEMBLE_PROFILE_FAILURE',failures,decisioning:false},{status:502});
 if(base.result.optimizer_version!==OPT||mid.result.optimizer_version!==OPT||durable.result.optimizer_version!==OPT)return Response.json({ok:false,status:'OPTIMIZER_VERSION_MISMATCH',versions:[base.result.optimizer_version,mid.result.optimizer_version,durable.result.optimizer_version],decisioning:false},{status:409});
 const budget=N(base.result.budget_tenths),raw:any[]=[];
 for(const x of base.result.fresh_ensemble||[])raw.push({...x,source_profile:x.profile||'BASE'});
 if(mid.result.wildcard_benchmark)raw.push({...mid.result.wildcard_benchmark,source_profile:'DUAL_PREMIUM_MID_VALUE'});
 if(durable.result.wildcard_benchmark)raw.push({...durable.result.wildcard_benchmark,source_profile:'HIGH_MINUTES_DURABLE'});
 const accepted:any[]=[],rejected:any[]=[];for(const x of raw){const v=validCandidate(x,budget,String(x.source_profile));if(!v.ok)rejected.push({profile:x.source_profile,reason:v.reason,objective:N(x.objective)});else accepted.push({...x,family_signature:family(x)})}
 const dedup=new Map<string,any>();for(const x of accepted){const k=squadKey(x),o=dedup.get(k);if(!o||N(x.objective)>N(o.objective))dedup.set(k,x)}const xs=[...dedup.values()].sort((a,b)=>N(b.objective)-N(a.objective));if(xs.length<2)return Response.json({ok:false,status:'ENSEMBLE_DIVERSITY_INSUFFICIENT',accepted:xs.length,rejected,decisioning:false},{status:409});
 const top=N(xs[0].objective),second=N(xs[1].objective),families=[...new Set(xs.map(x=>x.family_signature))],eq=xs.filter(x=>top-N(x.objective)<=err),near=xs.filter(x=>top-N(x.objective)<=2*err),classification=eq.some(x=>x.family_signature!==xs[0].family_signature)?'MULTI_FAMILY_EQUIVALENCE':near.some(x=>x.family_signature!==xs[0].family_signature)?'NEAR_EQUIVALENT_SENSITIVITY_REQUIRED':'SINGLE_FAMILY_EDGE';
 const compact=(x:any)=>({profile:x.source_profile,family_signature:x.family_signature,objective:+N(x.objective).toFixed(3),gap_to_best:+(top-N(x.objective)).toFixed(3),equivalent_to_best:top-N(x.objective)<=err,near_best_2x_error:top-N(x.objective)<=2*err,cost_tenths:N(x.cost_tenths),itb_tenths:N(x.itb_tenths),strategic:x.strategic,squad:x.squad,gameweeks:x.gameweeks});
 const result={ok:true,status:'ENSEMBLE_READY',change_id:'C0228',ensemble_version:VERSION,optimizer_version:OPT,gameweek:gw,horizon:h,model_error_margin_points:err,manager_state_id:base.result.manager_state_id,budget_tenths:budget,roll:{objective:N(base.result.roll?.objective),scenario:base.result.roll?.scenario},best_no_chip:{objective:N(base.result.recommended_by_noise_gate?.objective),scenario:base.result.recommended_by_noise_gate?.scenario,transfers:base.result.recommended_by_noise_gate?.transfers},candidates:xs.map(compact),equivalence_class:eq.map(compact),near_equivalence_class:near.map(compact),convergence:{profiles_requested:['BALANCED_VALUE','PREMIUM_FORWARD','DUAL_PREMIUM_MID_VALUE','HIGH_MINUTES_DURABLE'],profile_calls_green:true,accepted_candidates:accepted.length,rejected_candidates:rejected,unique_squads:xs.length,unique_family_signatures:families.length,families,top_second_gap_points:+(top-second).toFixed(3),equivalent_squads:eq.length,near_equivalent_squads_2x_error:near.length},ensemble_classification:classification,policy:{one_canonical_optimizer:true,distributed_workers:true,low_defender_profile_excluded_until_constraint_survives_local_improvement:true,false_precision_prohibited:true,xpts_rewritten:false},historical_forecasts_rewritten:false,decisioning:false};
 const sig=await sha({VERSION,OPT,gw,h,err,ft,manager:base.result.manager_state_id,runs:base.result.prediction_runs,candidates:xs.map(x=>[squadKey(x),N(x.objective),x.source_profile])});const{data:old,error:oe}=await sb.from('fpl_squad_ensemble_runs').select('id').eq('input_signature',sig).maybeSingle();if(oe)throw oe;let id=old?.id?N(old.id):null;if(!id){const{data:ins,error:ie}=await sb.from('fpl_squad_ensemble_runs').insert({gameweek:gw,horizon:h,optimizer_version:OPT,ensemble_version:VERSION,model_error_margin_points:err,input_signature:sig,result,historical_forecasts_rewritten:false}).select('id').single();if(ie)throw ie;id=N(ins.id)}
 return Response.json({...result,ensemble_run_id:id,input_signature:sig});
}catch(e){return Response.json({ok:false,status:'ENSEMBLE_ERROR',error:e instanceof Error?e.message:String(e),decisioning:false},{status:500})}});