create table if not exists public.research_c0197_shootout_replay_runs (
  run_key text primary key,
  change_id text not null default 'C0197',
  replay_type text not null,
  definition jsonb not null default '{}'::jsonb,
  conclusion text not null,
  research_only boolean not null default true check (research_only),
  model_effect_enabled boolean not null default false check (not model_effect_enabled),
  created_at timestamptz not null default clock_timestamp()
);

create table if not exists public.research_c0197_shootout_replay_rows (
  id bigint generated by default as identity primary key,
  run_key text not null references public.research_c0197_shootout_replay_runs(run_key),
  gameweek integer not null,
  cutoff timestamptz not null,
  replay_status text not null,
  match_id bigint not null,
  fixture text not null,
  score text,
  total_goals integer,
  actual_shootout boolean,
  base_rank integer,
  combined_rank integer,
  structural_v01_rank integer,
  structural_v02_rank integer,
  btts_rank integer,
  over25_rank integer,
  base_score numeric,
  combined_score numeric,
  structural_v01_score numeric,
  structural_v02_score numeric,
  confidence_note text,
  evidence jsonb not null default '{}'::jsonb,
  research_only boolean not null default true check (research_only),
  model_effect_enabled boolean not null default false check (not model_effect_enabled),
  created_at timestamptz not null default clock_timestamp(),
  unique(run_key,gameweek,match_id)
);

alter table public.research_c0197_shootout_replay_runs enable row level security;
alter table public.research_c0197_shootout_replay_rows enable row level security;
revoke all on public.research_c0197_shootout_replay_runs from anon,authenticated;
revoke all on public.research_c0197_shootout_replay_rows from anon,authenticated;
revoke all on sequence public.research_c0197_shootout_replay_rows_id_seq from anon,authenticated;

create or replace function private.block_c0197_shootout_replay_mutation_v01()
returns trigger language plpgsql set search_path=public,private,pg_temp as $$
begin raise exception 'C0197 shootout replay evidence is append-only'; end $$;
revoke all on function private.block_c0197_shootout_replay_mutation_v01() from public,anon,authenticated;

drop trigger if exists research_c0197_shootout_replay_runs_append_only on public.research_c0197_shootout_replay_runs;
create trigger research_c0197_shootout_replay_runs_append_only before update or delete on public.research_c0197_shootout_replay_runs for each row execute function private.block_c0197_shootout_replay_mutation_v01();
drop trigger if exists research_c0197_shootout_replay_rows_append_only on public.research_c0197_shootout_replay_rows;
create trigger research_c0197_shootout_replay_rows_append_only before update or delete on public.research_c0197_shootout_replay_rows for each row execute function private.block_c0197_shootout_replay_mutation_v01();

insert into public.research_c0197_shootout_replay_runs(run_key,replay_type,definition,conclusion)
values (
'C0197_SHOOTOUT_REPLAY_GW1_GW2_20260904_V01',
'RETROSPECTIVE_AS_OF_REPLAY',
jsonb_build_object(
 'formula','exact frozen C0197_SHOOTOUT_FORWARD_20260904_V01 V01/V02; no retuning',
 'gw1_cutoff','2026-08-21T18:59:59Z',
 'gw2_cutoff','2026-08-28T18:59:59Z',
 'same_gameweek_leakage','prohibited: single freeze before first kickoff',
 'gw1_limitation','exact V01/V02 unavailable because stored H2H odds begin after GW1 first kickoff; structural-only diagnostic persisted',
 'gw2_status','exact replay with complete pre-first-kickoff H2H/BTTS/O2.5 archive',
 'future_hypothesis_only','early-season regime assimilation may need faster response to strong current-process evidence; do not retune from GW2 outcomes'
),
'GW2 exact replay was mixed: V02 ranked Man Utd-Ipswich 5-2 third but Chelsea-Brighton 4-3 tenth. V01 ranked them sixth and tenth. Market O2.5 ranked them second and fifth and therefore outperformed the shootout score on this tiny replay. GW1 had no 6+ shootout and cannot be exact-replayed due missing pre-GW H2H archive. No model promotion or retuning.'
) on conflict do nothing;

insert into public.research_c0197_shootout_replay_rows(run_key,gameweek,cutoff,replay_status,match_id,fixture,score,total_goals,actual_shootout,base_rank,combined_rank,btts_rank,over25_rank,base_score,combined_score,confidence_note,evidence)
values
('C0197_SHOOTOUT_REPLAY_GW1_GW2_20260904_V01',2,'2026-08-28 18:59:59+00','EXACT',12,'Liverpool vs Nott''m Forest','2-2',4,false,1,1,7,1,.995,.597,'FULL_PRIOR_HISTORY','{}'),
('C0197_SHOOTOUT_REPLAY_GW1_GW2_20260904_V01',2,'2026-08-28 18:59:59+00','EXACT',13,'Bournemouth vs Everton','1-1',2,false,2,2,4,8,.865,.523,'FULL_PRIOR_HISTORY','{}'),
('C0197_SHOOTOUT_REPLAY_GW1_GW2_20260904_V01',2,'2026-08-28 18:59:59+00','EXACT',19,'Man Utd vs Ipswich Town','5-2',7,true,6,3,9,2,.337,.470,'LOW_HISTORY_IPSWICH',jsonb_build_object('home_history_n',10,'away_history_n',1,'home_breadth_n',10,'away_breadth_n',0)),
('C0197_SHOOTOUT_REPLAY_GW1_GW2_20260904_V01',2,'2026-08-28 18:59:59+00','EXACT',20,'Aston Villa vs Arsenal','0-1',1,false,4,4,10,6,.386,.434,'FULL_PRIOR_HISTORY','{}'),
('C0197_SHOOTOUT_REPLAY_GW1_GW2_20260904_V01',2,'2026-08-28 18:59:59+00','EXACT',14,'Coventry City vs Hull City','0-1',1,false,7,5,6,7,.163,.182,'LOW_HISTORY_BOTH_PROMOTED',jsonb_build_object('home_history_n',1,'away_history_n',1,'home_breadth_n',1,'away_breadth_n',1)),
('C0197_SHOOTOUT_REPLAY_GW1_GW2_20260904_V01',2,'2026-08-28 18:59:59+00','EXACT',15,'Spurs vs Newcastle','0-2',2,false,3,6,1,4,.463,.162,'FULL_PRIOR_HISTORY','{}'),
('C0197_SHOOTOUT_REPLAY_GW1_GW2_20260904_V01',2,'2026-08-28 18:59:59+00','EXACT',18,'Sunderland vs Fulham','1-0',1,false,8,7,8,10,.084,.108,'FULL_PRIOR_HISTORY','{}'),
('C0197_SHOOTOUT_REPLAY_GW1_GW2_20260904_V01',2,'2026-08-28 18:59:59+00','EXACT',11,'Crystal Palace vs Man City','1-4',5,false,9,8,5,3,-.182,-.154,'FULL_PRIOR_HISTORY','{}'),
('C0197_SHOOTOUT_REPLAY_GW1_GW2_20260904_V01',2,'2026-08-28 18:59:59+00','EXACT',17,'Leeds vs Brentford','1-1',2,false,5,9,3,9,.359,-.190,'FULL_PRIOR_HISTORY','{}'),
('C0197_SHOOTOUT_REPLAY_GW1_GW2_20260904_V01',2,'2026-08-28 18:59:59+00','EXACT',16,'Chelsea vs Brighton','4-3',7,true,10,10,2,5,-.376,-.482,'FULL_PRIOR_HISTORY',jsonb_build_object('gw1_brighton',jsonb_build_object('sot',6,'xg',3.77,'xgot',3.59,'big_chances',6,'goals',4),'gw1_chelsea',jsonb_build_object('sot',6,'xg',2.24,'xgot',2.02,'big_chances',4,'goals',3),'diagnosis','rigid last-10 history under-reacted to strong current-regime process'))
on conflict do nothing;

insert into public.research_c0197_shootout_replay_rows(run_key,gameweek,cutoff,replay_status,match_id,fixture,score,total_goals,actual_shootout,structural_v01_rank,structural_v02_rank,structural_v01_score,structural_v02_score,confidence_note,evidence)
values
('C0197_SHOOTOUT_REPLAY_GW1_GW2_20260904_V01',1,'2026-08-21 18:59:59+00','STRUCTURAL_ONLY_NO_PRE_GW_H2H',9,'Newcastle vs Liverpool','2-2',4,false,1,1,1.375,1.179,'FULL_PRIOR_HISTORY','{}'),
('C0197_SHOOTOUT_REPLAY_GW1_GW2_20260904_V01',1,'2026-08-21 18:59:59+00','STRUCTURAL_ONLY_NO_PRE_GW_H2H',2,'Hull City vs Man Utd','2-0',2,false,3,2,.847,.803,'LOW_HISTORY_HULL','{}'),
('C0197_SHOOTOUT_REPLAY_GW1_GW2_20260904_V01',1,'2026-08-21 18:59:59+00','STRUCTURAL_ONLY_NO_PRE_GW_H2H',8,'Man City vs Bournemouth','2-1',3,false,4,3,.651,.798,'FULL_PRIOR_HISTORY','{}'),
('C0197_SHOOTOUT_REPLAY_GW1_GW2_20260904_V01',1,'2026-08-21 18:59:59+00','STRUCTURAL_ONLY_NO_PRE_GW_H2H',7,'Brighton vs Aston Villa','4-0',4,false,2,4,.872,.735,'FULL_PRIOR_HISTORY','{}'),
('C0197_SHOOTOUT_REPLAY_GW1_GW2_20260904_V01',1,'2026-08-21 18:59:59+00','STRUCTURAL_ONLY_NO_PRE_GW_H2H',1,'Arsenal vs Coventry City','3-0',3,false,6,5,.395,.437,'LOW_HISTORY_COVENTRY','{}'),
('C0197_SHOOTOUT_REPLAY_GW1_GW2_20260904_V01',1,'2026-08-21 18:59:59+00','STRUCTURAL_ONLY_NO_PRE_GW_H2H',4,'Ipswich Town vs Sunderland','2-1',3,false,7,6,.303,.294,'LOW_HISTORY_IPSWICH','{}'),
('C0197_SHOOTOUT_REPLAY_GW1_GW2_20260904_V01',1,'2026-08-21 18:59:59+00','STRUCTURAL_ONLY_NO_PRE_GW_H2H',5,'Nott''m Forest vs Leeds','0-1',1,false,5,7,.454,.223,'FULL_PRIOR_HISTORY','{}'),
('C0197_SHOOTOUT_REPLAY_GW1_GW2_20260904_V01',1,'2026-08-21 18:59:59+00','STRUCTURAL_ONLY_NO_PRE_GW_H2H',3,'Everton vs Crystal Palace','2-0',2,false,8,8,.272,-.169,'FULL_PRIOR_HISTORY','{}'),
('C0197_SHOOTOUT_REPLAY_GW1_GW2_20260904_V01',1,'2026-08-21 18:59:59+00','STRUCTURAL_ONLY_NO_PRE_GW_H2H',6,'Brentford vs Spurs','3-0',3,false,9,9,-.129,-.592,'FULL_PRIOR_HISTORY','{}'),
('C0197_SHOOTOUT_REPLAY_GW1_GW2_20260904_V01',1,'2026-08-21 18:59:59+00','STRUCTURAL_ONLY_NO_PRE_GW_H2H',10,'Fulham vs Chelsea','2-3',5,false,10,10,-.823,-.771,'FULL_PRIOR_HISTORY','{}')
on conflict do nothing;

create or replace function private.c0197_shootout_replay_status_v01()
returns jsonb language sql stable set search_path=public,private,pg_temp as $$
select jsonb_build_object(
 'change_id','C0197',
 'runs',(select count(*) from public.research_c0197_shootout_replay_runs),
 'rows',(select count(*) from public.research_c0197_shootout_replay_rows),
 'gw1_rows',(select count(*) from public.research_c0197_shootout_replay_rows where gameweek=1),
 'gw2_rows',(select count(*) from public.research_c0197_shootout_replay_rows where gameweek=2),
 'gw2_actual_shootouts',(select count(*) from public.research_c0197_shootout_replay_rows where gameweek=2 and actual_shootout),
 'model_effect_enabled',false
); $$;
revoke all on function private.c0197_shootout_replay_status_v01() from public,anon,authenticated;