create table if not exists public.research_c0197_shootout_forward_market_checks (
  id bigint generated by default as identity primary key,
  run_key text not null references public.research_c0197_shootout_forward_runs(run_key),
  snapshot_id bigint not null references public.research_c0197_shootout_forward_snapshots(id),
  match_id bigint not null references public.matches(id),
  gameweek integer not null,
  btts_yes_probability numeric,
  over25_probability numeric,
  btts_rank integer,
  over25_rank integer,
  combined_rank integer,
  combined_minus_btts_rank integer,
  combined_minus_over25_rank integer,
  evidence jsonb not null default '{}'::jsonb,
  research_only boolean not null default true check (research_only),
  model_effect_enabled boolean not null default false check (not model_effect_enabled),
  created_at timestamptz not null default clock_timestamp(),
  unique(run_key,snapshot_id)
);
alter table public.research_c0197_shootout_forward_market_checks enable row level security;
revoke all on public.research_c0197_shootout_forward_market_checks from anon, authenticated;
revoke all on sequence public.research_c0197_shootout_forward_market_checks_id_seq from anon, authenticated;
drop trigger if exists research_c0197_shootout_forward_market_checks_append_only on public.research_c0197_shootout_forward_market_checks;
create trigger research_c0197_shootout_forward_market_checks_append_only before update or delete on public.research_c0197_shootout_forward_market_checks for each row execute function private.block_c0197_shootout_forward_mutation_v01();

create or replace function private.c0197_capture_shootout_market_checks_v01(p_gameweek integer)
returns jsonb language plpgsql set search_path=public,private,pg_temp as $$
declare v_inserted integer:=0; v_run_key constant text:='C0197_SHOOTOUT_FORWARD_20260904_V01';
begin
 with snaps as (
   select distinct on (s.match_id) s.*
   from public.research_c0197_shootout_forward_snapshots s
   where s.run_key=v_run_key and s.gameweek=p_gameweek
   order by s.match_id,s.snapshot_as_of asc,s.id asc
 ), oq as (
   select * from (
     select o.*,s.snapshot_as_of,
       row_number() over(partition by o.match_id,o.provider,o.bookmaker,o.market_key,o.selection_key,o.line order by o.captured_at asc,o.source_timestamp asc,o.id asc) rn
     from public.odds_market_selections o join snaps s on s.match_id=o.match_id
     where ((o.market_key='btts' and o.selection_key in ('yes','no')) or (o.market_key='totals' and o.line=2.5 and o.selection_key in ('over','under')))
       and o.decimal_odds>1 and o.captured_at<=s.snapshot_as_of
   ) z where rn=1
 ), books as (
   select match_id,provider,bookmaker,market_key,line,
     max(decimal_odds) filter(where selection_key in ('yes','over')) yes_over,
     max(decimal_odds) filter(where selection_key in ('no','under')) no_under
   from oq group by match_id,provider,bookmaker,market_key,line
 ), norm as (
   select match_id,market_key,avg((1/yes_over)/((1/yes_over)+(1/no_under))) p
   from books where yes_over is not null and no_under is not null group by match_id,market_key
 ), probs as (
   select match_id,max(p) filter(where market_key='btts') btts_yes,max(p) filter(where market_key='totals') over25
   from norm group by match_id
 ), ranked as (
   select s.*,p.btts_yes,p.over25,
     rank() over(order by p.btts_yes desc nulls last)::integer btts_rank,
     rank() over(order by p.over25 desc nulls last)::integer over25_rank
   from snaps s left join probs p using(match_id)
 ), ins as (
   insert into public.research_c0197_shootout_forward_market_checks(run_key,snapshot_id,match_id,gameweek,btts_yes_probability,over25_probability,btts_rank,over25_rank,combined_rank,combined_minus_btts_rank,combined_minus_over25_rank,evidence)
   select v_run_key,id,match_id,gameweek,btts_yes,over25,btts_rank,over25_rank,combined_rank,
     combined_rank-btts_rank,combined_rank-over25_rank,
     jsonb_build_object('policy','earliest captured pre-snapshot BTTS and 2.5-total quotes per bookmaker, devigged then averaged','model_input',false)
   from ranked
   on conflict(run_key,snapshot_id) do nothing returning id
 ) select count(*) into v_inserted from ins;
 return jsonb_build_object('run_key',v_run_key,'gameweek',p_gameweek,'inserted',v_inserted,'model_effect_enabled',false);
end $$;
revoke all on function private.c0197_capture_shootout_market_checks_v01(integer) from public,anon,authenticated;

create or replace function private.c0197_shootout_forward_status_v01()
returns jsonb language sql stable set search_path=public,private,pg_temp as $$
select jsonb_build_object(
  'change_id','C0197',
  'run_key','C0197_SHOOTOUT_FORWARD_20260904_V01',
  'runs',(select count(*) from public.research_c0197_shootout_forward_runs),
  'scalers',(select count(*) from public.research_c0197_shootout_forward_scalers),
  'snapshots',(select count(*) from public.research_c0197_shootout_forward_snapshots),
  'market_checks',(select count(*) from public.research_c0197_shootout_forward_market_checks),
  'evaluations',(select count(*) from public.research_c0197_shootout_forward_evaluations),
  'gameweeks',(select coalesce(jsonb_agg(distinct gameweek order by gameweek),'[]'::jsonb) from public.research_c0197_shootout_forward_snapshots),
  'model_effect_enabled',false
); $$;
revoke all on function private.c0197_shootout_forward_status_v01() from public,anon,authenticated;