create table if not exists private.c0213_p2_lineage_snapshots(
  id bigint generated by default as identity primary key,
  gameweek integer not null,
  captured_at timestamptz not null default clock_timestamp(),
  projection_ready boolean not null,
  decision_ready boolean not null,
  lineage jsonb not null,
  blockers jsonb not null default '[]'::jsonb,
  source_manifest jsonb not null default '{}'::jsonb,
  change_id text not null default 'C0213',
  phase text not null default 'P2_ORCHESTRATION_READINESS_LINEAGE'
);

create or replace function private.block_c0213_p2_lineage_mutation_v01()
returns trigger language plpgsql set search_path='private','pg_temp' as $$
begin
  raise exception 'C0213 P2 lineage snapshots are append-only';
end $$;

drop trigger if exists trg_block_c0213_p2_lineage_update_delete on private.c0213_p2_lineage_snapshots;
create trigger trg_block_c0213_p2_lineage_update_delete
before update or delete on private.c0213_p2_lineage_snapshots
for each row execute function private.block_c0213_p2_lineage_mutation_v01();

revoke all on table private.c0213_p2_lineage_snapshots from public,anon,authenticated;
grant select,insert on private.c0213_p2_lineage_snapshots to service_role;
grant usage,select on sequence private.c0213_p2_lineage_snapshots_id_seq to service_role;
