create table if not exists public.betting_edge_observations (
  id bigint generated by default as identity primary key,
  gameweek integer not null,
  match_id bigint not null,
  raw_snapshot_id bigint not null references public.odds_raw_snapshots(id),
  odds_selection_id bigint not null references public.odds_market_selections(id),
  prediction_snapshot_id bigint not null references public.fixture_prediction_snapshots(id),
  bookmaker text not null,
  market_key text not null,
  selection_key text not null,
  selection_name text not null,
  decimal_odds numeric not null,
  bookmaker_implied_probability numeric not null,
  market_overround numeric not null,
  market_selection_count integer not null,
  devig_method text not null default 'proportional_offered_set',
  market_fair_conditional_probability numeric not null,
  model_probability numeric not null,
  model_offered_mass numeric not null,
  model_conditional_probability numeric not null,
  conditional_edge numeric not null,
  expected_value numeric not null,
  bookmaker_source_timestamp timestamptz,
  odds_captured_at timestamptz not null,
  model_captured_at timestamptz not null,
  kickoff_time timestamptz not null,
  computed_at timestamptz not null default now(),
  chronology_valid boolean not null,
  research_classification text not null default 'UNVALIDATED',
  model_effect_enabled boolean not null default false,
  evidence jsonb not null default '{}'::jsonb
);

alter table public.betting_edge_observations enable row level security;
revoke all on table public.betting_edge_observations from anon, authenticated;
grant select, insert, update, delete on table public.betting_edge_observations to service_role;
grant usage, select on sequence public.betting_edge_observations_id_seq to service_role;

create unique index if not exists betting_edge_obs_uidx
  on public.betting_edge_observations(odds_selection_id,prediction_snapshot_id,devig_method);
create index if not exists betting_edge_obs_match_idx
  on public.betting_edge_observations(match_id,odds_captured_at desc);
create index if not exists betting_edge_obs_ev_idx
  on public.betting_edge_observations(expected_value desc);

create or replace function public.generate_correct_score_edge_observations(p_gameweek integer)
returns integer
language plpgsql
security invoker
set search_path=public,pg_temp
as $$
declare
  n integer:=0;
begin
  with eligible_raw as (
    select r.*
    from public.odds_raw_snapshots r
    where r.gameweek=p_gameweek
      and r.pre_kickoff=true
      and r.captured_at<r.event_kickoff
      and r.event_kickoff>now()
  ), priced as (
    select
      r.gameweek,r.match_id,r.id raw_snapshot_id,r.bookmaker,r.captured_at odds_captured_at,
      r.event_kickoff kickoff_time,
      o.id odds_selection_id,o.market_key,o.selection_key,o.selection_name,o.decimal_odds,
      coalesce(o.implied_probability,1/o.decimal_odds) bookmaker_implied_probability,
      o.source_timestamp bookmaker_source_timestamp,
      p.id prediction_snapshot_id,p.captured_at model_captured_at,p.score_matrix,
      case when o.selection_name ~ '^[0-9]+-[0-9]+$'
        then nullif(p.score_matrix->>o.selection_name,'')::numeric
        else null end model_probability
    from eligible_raw r
    join public.odds_market_selections o on o.raw_snapshot_id=r.id
    join lateral (
      select fp.*
      from public.fixture_prediction_snapshots fp
      where fp.match_id=r.match_id
        and fp.is_pre_kickoff=true
        and fp.captured_at<=r.captured_at
        and fp.captured_at<fp.kickoff_time
      order by fp.captured_at desc,fp.id desc
      limit 1
    ) p on true
    where o.market_key='correct_score'
      and o.decimal_odds>1
      and (o.source_timestamp is null or o.source_timestamp<r.event_kickoff)
  ), usable as (
    select * from priced where model_probability is not null and model_probability>=0
  ), calc as (
    select u.*,
      sum(bookmaker_implied_probability) over(partition by raw_snapshot_id) market_overround,
      count(*) over(partition by raw_snapshot_id)::integer market_selection_count,
      sum(model_probability) over(partition by raw_snapshot_id) model_offered_mass
    from usable u
  )
  insert into public.betting_edge_observations(
    gameweek,match_id,raw_snapshot_id,odds_selection_id,prediction_snapshot_id,
    bookmaker,market_key,selection_key,selection_name,decimal_odds,
    bookmaker_implied_probability,market_overround,market_selection_count,devig_method,
    market_fair_conditional_probability,model_probability,model_offered_mass,
    model_conditional_probability,conditional_edge,expected_value,
    bookmaker_source_timestamp,odds_captured_at,model_captured_at,kickoff_time,
    chronology_valid,research_classification,model_effect_enabled,evidence
  )
  select
    gameweek,match_id,raw_snapshot_id,odds_selection_id,prediction_snapshot_id,
    bookmaker,market_key,selection_key,selection_name,decimal_odds,
    bookmaker_implied_probability,market_overround,market_selection_count,'proportional_offered_set',
    bookmaker_implied_probability/nullif(market_overround,0),
    model_probability,model_offered_mass,
    model_probability/nullif(model_offered_mass,0),
    (model_probability/nullif(model_offered_mass,0))-(bookmaker_implied_probability/nullif(market_overround,0)),
    model_probability*decimal_odds-1,
    bookmaker_source_timestamp,odds_captured_at,model_captured_at,kickoff_time,
    (model_captured_at<=odds_captured_at and odds_captured_at<kickoff_time and (bookmaker_source_timestamp is null or bookmaker_source_timestamp<kickoff_time)),
    'UNVALIDATED',false,
    jsonb_build_object(
      'market_scope','offered_correct_scores_only',
      'devig_note','Proportional de-vig conditional on bookmaker offered exact-score set',
      'ev_note','EV uses unconditional model score probability',
      'generated_live_pre_kickoff',true
    )
  from calc
  where market_overround>0 and model_offered_mass>0
  on conflict (odds_selection_id,prediction_snapshot_id,devig_method) do nothing;

  get diagnostics n=row_count;
  return n;
end $$;

revoke all on function public.generate_correct_score_edge_observations(integer) from public,anon,authenticated;
grant execute on function public.generate_correct_score_edge_observations(integer) to service_role;