create table if not exists public.research_c0197_high_score_reverse_runs (
  run_key text primary key,
  change_id text not null default 'C0197',
  experiment_name text not null,
  definition jsonb not null default '{}'::jsonb,
  decision text not null,
  conclusion text not null,
  research_only boolean not null default true check (research_only),
  model_effect_enabled boolean not null default false check (not model_effect_enabled),
  created_at timestamptz not null default clock_timestamp()
);

create table if not exists public.research_c0197_high_score_reverse_evaluations (
  id bigint generated by default as identity primary key,
  run_key text not null references public.research_c0197_high_score_reverse_runs(run_key),
  season text,
  archetype text not null,
  selector text not null,
  sample_n integer not null,
  hits integer not null,
  precision_rate numeric,
  recall_rate numeric,
  evidence jsonb not null default '{}'::jsonb,
  research_only boolean not null default true check (research_only),
  model_effect_enabled boolean not null default false check (not model_effect_enabled),
  created_at timestamptz not null default clock_timestamp(),
  unique(run_key,season,archetype,selector)
);

alter table public.research_c0197_high_score_reverse_runs enable row level security;
alter table public.research_c0197_high_score_reverse_evaluations enable row level security;
revoke all on public.research_c0197_high_score_reverse_runs from anon, authenticated;
revoke all on public.research_c0197_high_score_reverse_evaluations from anon, authenticated;
revoke all on sequence public.research_c0197_high_score_reverse_evaluations_id_seq from anon, authenticated;

create or replace function private.block_c0197_high_score_reverse_mutation_v01()
returns trigger language plpgsql set search_path=public,private,pg_temp as $$
begin raise exception 'C0197 high-score reverse-engineering evidence is append-only'; end $$;
revoke all on function private.block_c0197_high_score_reverse_mutation_v01() from public,anon,authenticated;

drop trigger if exists research_c0197_high_score_reverse_runs_append_only on public.research_c0197_high_score_reverse_runs;
create trigger research_c0197_high_score_reverse_runs_append_only before update or delete on public.research_c0197_high_score_reverse_runs for each row execute function private.block_c0197_high_score_reverse_mutation_v01();
drop trigger if exists research_c0197_high_score_reverse_evaluations_append_only on public.research_c0197_high_score_reverse_evaluations;
create trigger research_c0197_high_score_reverse_evaluations_append_only before update or delete on public.research_c0197_high_score_reverse_evaluations for each row execute function private.block_c0197_high_score_reverse_mutation_v01();

insert into public.research_c0197_high_score_reverse_runs(run_key,experiment_name,definition,decision,conclusion)
values ('C0197_HIGHSCORE_RE_20260903_V01','High-score fixture reverse engineering v01',
jsonb_build_object(
 'foundation','Football-Data EPL 2020/21-2025/26, 2280 matches',
 'primary_target','6+ total goals',
 'archetypes',jsonb_build_object('SHOOTOUT','6+ total and both teams >=2','DEMOLITION','6+ total and one team <=1'),
 'primary_pre_match_window','last 10 team matches',
 'rich_layer','FPL-Core 2024/25-2025/26 gated through C0197_XSRC_V01',
 'market_control','opening O/U 2.5 implied Poisson mean plus 1X2 favorite strength',
 'shootout_score','equal-weight standardized min SOT, min goals scored, BTTS rate, inverse favorite probability; scaling frozen from 2020/21-2022/23',
 'demolition_score','equal-weight standardized favorite probability, max attack, favorite SOT, underdog SOT allowed; scaling frozen from 2020/21-2022/23',
 'status','shadow hypothesis only; feature selection is exploratory and later seasons are not a pristine untouched holdout'
),
'PROMISING_SHOOTOUT_SHADOW_ONLY',
'Reverse engineering separates 6+ matches into two regimes. The shootout regime shows a repeatable pre-match two-sided attacking-floor signal and beats the old Chaos ranking across 2023/24-2025/26. The demolition regime does not yet beat market expectation. No production effect.'
) on conflict do nothing;

insert into public.research_c0197_high_score_reverse_evaluations(run_key,season,archetype,selector,sample_n,hits,precision_rate,recall_rate,evidence)
values
('C0197_HIGHSCORE_RE_20260903_V01','2023-2024','SHOOTOUT','SHOOTOUT_SCORE_TOP10',38,3,.079,.125,'{"total_shootouts":24,"market_top10_hits":3,"chaos_top10_hits":2}'::jsonb),
('C0197_HIGHSCORE_RE_20260903_V01','2024-2025','SHOOTOUT','SHOOTOUT_SCORE_TOP10',38,3,.079,.167,'{"total_shootouts":18,"market_top10_hits":2,"chaos_top10_hits":0}'::jsonb),
('C0197_HIGHSCORE_RE_20260903_V01','2025-2026','SHOOTOUT','SHOOTOUT_SCORE_TOP10',38,4,.105,.286,'{"total_shootouts":14,"market_top10_hits":2,"chaos_top10_hits":1,"top20_hits":6,"top20_precision":0.080}'::jsonb),
('C0197_HIGHSCORE_RE_20260903_V01',null,'SHOOTOUT','ARCHETYPE_COUNT',158,114,.722,null,'{"scope":"all 158 six-plus matches across six seasons"}'::jsonb),
('C0197_HIGHSCORE_RE_20260903_V01',null,'DEMOLITION','ARCHETYPE_COUNT',158,44,.278,null,'{"scope":"all 158 six-plus matches across six seasons"}'::jsonb),
('C0197_HIGHSCORE_RE_20260903_V01',null,'DEMOLITION','DEMOLITION_SCORE_TOP10_2024_2026',75,2,.027,null,'{"market_top10_hits":2,"chaos_top10_hits":0,"base_rate":0.011}'::jsonb),
('C0197_HIGHSCORE_RE_20260903_V01',null,'SHOOTOUT','RICH_NEAREST_CONTROL_CLUE',35,23,null,null,'{"feature":"weaker_side_rolling_sot_player_count","positive_high_matches":23,"mean_delta_2024_25":0.2898,"mean_delta_2025_26":0.1947,"second_feature":"weaker_side_rolling_sot","second_positive_high_matches":22}'::jsonb)
on conflict do nothing;

create or replace function private.c0197_high_score_reverse_status_v01()
returns jsonb language sql stable set search_path=public,private,pg_temp as $$
select jsonb_build_object(
 'change_id','C0197',
 'runs',(select count(*) from public.research_c0197_high_score_reverse_runs),
 'latest_run',(select run_key from public.research_c0197_high_score_reverse_runs order by created_at desc limit 1),
 'decision',(select decision from public.research_c0197_high_score_reverse_runs order by created_at desc limit 1),
 'evaluation_rows',(select count(*) from public.research_c0197_high_score_reverse_evaluations),
 'model_effect_enabled',false
); $$;
revoke all on function private.c0197_high_score_reverse_status_v01() from public,anon,authenticated;
