-- C0213 P1 debt consolidation: cron duplicate, tactical selector, fail-closed decision writes.
-- No historical forecast mutation. No model coefficient changes.

-- 1) Remove the obsolete twice-daily duplicate competitive-core schedule.
do $$
begin
  if exists (select 1 from cron.job where jobname='football_intelligence_competitive_core_ingest' and active) then
    perform cron.unschedule('football_intelligence_competitive_core_ingest');
  end if;
end $$;

-- 2) Make calibrated v0.1.1 the canonical tactical row when both v0.1 and v0.1.1 exist.
create or replace view public.current_fixture_tactical_matchups as
select distinct on (match_id,team_id,signal_key)
  id,match_id,gameweek,team_id,opponent_team_id,kickoff_time,captured_at,evidence_cutoff,
  signal_family,signal_key,score_type,score,direction,attacking_component,resistance_component,
  confidence,data_coverage,team_tactical_observation_id,opponent_tactical_observation_id,
  evidence,observation_hash,model_effect_enabled
from public.fixture_tactical_matchup_observations
order by match_id,team_id,signal_key,
  case evidence->>'method'
    when 'fixture_tactical_matchup_v0.1.1' then 0
    when 'fixture_tactical_matchup_v0.1' then 1
    else 2
  end,
  captured_at desc,id desc;

-- 3) One explicit decision-readiness contract. Projection generation may remain green while decisions are red.
create or replace function private.c0213_decision_readiness_v01(p_gameweek integer)
returns jsonb
language plpgsql
security definer
set search_path='private','public','pg_temp'
as $$
declare
  v_prod jsonb;
  v_dec jsonb;
  v_ok boolean;
begin
  v_prod:=private.c0166_production_evidence_audit_v01(p_gameweek);
  v_dec:=private.c0167_decision_evidence_audit_v01(p_gameweek);
  v_ok:=coalesce((v_prod->>'ok')::boolean,false) and coalesce((v_dec->>'ok')::boolean,false);
  return jsonb_build_object(
    'ok',v_ok,
    'gameweek',p_gameweek,
    'projection_ready',true,
    'decision_ready',v_ok,
    'c0166_production_evidence',v_prod,
    'c0167_decision_evidence',v_dec,
    'contract_version','C0213_DECISION_READINESS_V01'
  );
end $$;
revoke all on function private.c0213_decision_readiness_v01(integer) from public,anon,authenticated;
grant execute on function private.c0213_decision_readiness_v01(integer) to service_role;

create table if not exists private.c0213_decision_write_blocks(
  id bigint generated by default as identity primary key,
  attempted_at timestamptz not null default clock_timestamp(),
  gameweek integer not null,
  snapshot_type text,
  prediction_run_id bigint,
  readiness jsonb not null,
  reason text not null default 'DECISION_READINESS_BLOCKED'
);

create or replace function private.c0213_guard_decision_snapshot_insert_v01()
returns trigger
language plpgsql
security definer
set search_path='private','public','pg_temp'
as $$
declare v_ready jsonb;
begin
  if coalesce(new.valid_for_backtest,false)=true
     or coalesce(new.snapshot_type,'') in ('rolling_pre_deadline','deadline') then
    v_ready:=private.c0213_decision_readiness_v01(new.gameweek);
    if not coalesce((v_ready->>'ok')::boolean,false) then
      insert into private.c0213_decision_write_blocks(gameweek,snapshot_type,prediction_run_id,readiness)
      values(new.gameweek,new.snapshot_type,new.prediction_run_id,v_ready);
      return null;
    end if;
  end if;
  return new;
end $$;

revoke all on function private.c0213_guard_decision_snapshot_insert_v01() from public,anon,authenticated;

drop trigger if exists trg_c0213_guard_decision_snapshot_insert on public.decision_snapshots;
create trigger trg_c0213_guard_decision_snapshot_insert
before insert on public.decision_snapshots
for each row execute function private.c0213_guard_decision_snapshot_insert_v01();

-- Surface whether a decision was actually persisted after the legacy projection core runs.
create or replace function private.generate_upcoming_fpl_snapshot_v01(p_gameweek integer default null, p_force boolean default false)
returns jsonb
language plpgsql
security definer
set search_path='private','public','pg_temp'
as $$
declare
  v_now timestamptz := clock_timestamp();
  v_gw integer;
  v_cov jsonb;
  v_reconcile jsonb;
  v_res jsonb;
  v_run_id bigint;
  v_decision_saved boolean:=false;
  v_readiness jsonb;
begin
  if p_gameweek is null then
    select x.gameweek into v_gw
    from (
      select m.gameweek,min(m.kickoff_time)-interval '90 minutes' deadline_at
      from public.matches m where m.source='fpl' and m.gameweek between 1 and 38
      group by m.gameweek
    ) x
    where x.deadline_at>v_now order by x.gameweek limit 1;
  else
    v_gw:=p_gameweek;
  end if;
  if v_gw is null then
    return jsonb_build_object('ok',false,'status','NO_FUTURE_GAMEWEEK','change_id','C0204');
  end if;

  v_cov:=private.c0204_projection_coverage_summary_v01(v_gw,v_now);
  if coalesce((v_cov->>'ungoverned_missing_count')::integer,0)>0 then
    v_reconcile:=private.c0204_reconcile_projection_coverage_v02(v_gw,v_now);
    v_cov:=private.c0204_projection_coverage_summary_v01(v_gw,v_now);
  else
    v_reconcile:=jsonb_build_object('ok',true,'change_id','C0204','reconciliation_version','C0204_V02_CONTINUOUS','gameweek',v_gw,'new_governed_exclusions',0,'player_ids','[]'::jsonb,'missing_data_is_not_zero',true,'validated_prior_created',false,'historical_forecasts_rewritten',false);
  end if;

  if coalesce((v_cov->>'ungoverned_missing_count')::integer,0)>0 then
    insert into public.fpl_projection_coverage_audits(prediction_run_id,gameweek,captured_at,projectable_count,governed_excluded_count,ungoverned_missing_count,total_fpl_players,coverage)
    values(null,v_gw,clock_timestamp(),(v_cov->>'projectable_count')::integer,(v_cov->>'governed_excluded_count')::integer,(v_cov->>'ungoverned_missing_count')::integer,(v_cov->>'total_fpl_players')::integer,v_cov || jsonb_build_object('coverage_reconciliation',v_reconcile));
    return jsonb_build_object('ok',false,'status','C0204_PROJECTION_COVERAGE_BLOCKED','gameweek',v_gw,'projection_coverage',v_cov,'coverage_reconciliation',v_reconcile,'historical_forecasts_rewritten',false);
  end if;

  v_res:=private.generate_upcoming_fpl_snapshot_c0160_legacy_v01(v_gw,p_force);
  if v_res ? 'run_id' then v_run_id:=(v_res->>'run_id')::bigint; end if;

  if v_run_id is not null then
    select exists(select 1 from public.decision_snapshots d where d.prediction_run_id=v_run_id) into v_decision_saved;
  end if;
  v_readiness:=private.c0213_decision_readiness_v01(v_gw);

  insert into public.fpl_projection_coverage_audits(prediction_run_id,gameweek,captured_at,projectable_count,governed_excluded_count,ungoverned_missing_count,total_fpl_players,coverage)
  values(v_run_id,v_gw,clock_timestamp(),(v_cov->>'projectable_count')::integer,(v_cov->>'governed_excluded_count')::integer,(v_cov->>'ungoverned_missing_count')::integer,(v_cov->>'total_fpl_players')::integer,v_cov || jsonb_build_object('coverage_reconciliation',v_reconcile));

  return v_res || jsonb_build_object(
    'change_id','C0204',
    'projection_coverage',v_cov,
    'coverage_reconciliation',v_reconcile,
    'decision_readiness',v_readiness,
    'decision_saved',v_decision_saved,
    'decision_status',case when v_decision_saved then 'SAVED' else 'BLOCKED_NOT_READY' end,
    'historical_forecasts_rewritten',false
  );
end $$;
