create table if not exists public.research_c0202_directional_matchup_snapshots (
  id bigint generated by default as identity primary key,
  run_key text not null references public.research_c0202_validation_runs(run_key),
  evidence_cutoff timestamptz not null,
  gameweek integer not null,
  match_id bigint not null references public.matches(id),
  kickoff_time timestamptz not null,
  attacking_team_id bigint not null references public.teams(id),
  defending_team_id bigint not null references public.teams(id),
  attacker_player_id bigint not null references public.players(id),
  attacker_role text not null,
  attacker_side text not null check (attacker_side in ('ATT_LEFT','ATT_RIGHT')),
  attacker_side_confidence_band text not null check (attacker_side_confidence_band in ('HIGH','MEDIUM')),
  attacker_side_empirical_accuracy numeric not null check (attacker_side_empirical_accuracy between 0 and 1),
  faced_defensive_side text not null check (faced_defensive_side in ('DEF_LEFT','DEF_RIGHT')),
  expected_defender_player_id bigint references public.players(id),
  expected_defender_role text,
  defender_side_confidence_band text check (defender_side_confidence_band is null or defender_side_confidence_band in ('HIGH','MEDIUM')),
  defender_side_empirical_accuracy numeric check (defender_side_empirical_accuracy is null or defender_side_empirical_accuracy between 0 and 1),
  defender_pair_status text not null check (defender_pair_status in ('PAIRED_EXACT_SIDE','UNRESOLVED_EXACT_OPPONENT')),
  mapping_quality text not null check (mapping_quality in ('HIGH','MEDIUM','UNRESOLVED')),
  attacker_role_captured_at timestamptz not null,
  defender_role_captured_at timestamptz,
  wide_context_score numeric,
  wide_context_direction text,
  wide_context_confidence numeric check (wide_context_confidence is null or wide_context_confidence between 0 and 1),
  wide_context_captured_at timestamptz,
  defending_team_personnel_score numeric,
  defending_team_personnel_direction text,
  defending_team_personnel_confidence numeric check (defending_team_personnel_confidence is null or defending_team_personnel_confidence between 0 and 1),
  defending_team_personnel_captured_at timestamptz,
  effect_direction text not null default 'UNRESOLVED' check (effect_direction in ('ATTACK_ADVANTAGE','DEFENSIVE_ADVANTAGE','BALANCED','UNRESOLVED')),
  effect_magnitude numeric,
  effect_confidence numeric check (effect_confidence is null or effect_confidence between 0 and 1),
  evidence jsonb not null default '{}'::jsonb,
  research_only boolean not null default true check (research_only),
  model_effect_enabled boolean not null default false check (not model_effect_enabled),
  created_at timestamptz not null default clock_timestamp(),
  unique(run_key,match_id,attacker_player_id),
  check (attacker_role_captured_at <= evidence_cutoff),
  check (defender_role_captured_at is null or defender_role_captured_at <= evidence_cutoff),
  check (wide_context_captured_at is null or wide_context_captured_at <= evidence_cutoff),
  check (defending_team_personnel_captured_at is null or defending_team_personnel_captured_at <= evidence_cutoff),
  check ((effect_direction='UNRESOLVED' and effect_magnitude is null and effect_confidence is null) or effect_direction<>'UNRESOLVED')
);

alter table public.research_c0202_directional_matchup_snapshots enable row level security;
revoke all on public.research_c0202_directional_matchup_snapshots from public,anon,authenticated;
revoke all on sequence public.research_c0202_directional_matchup_snapshots_id_seq from public,anon,authenticated;

drop trigger if exists research_c0202_directional_matchup_snapshots_append_only on public.research_c0202_directional_matchup_snapshots;
create trigger research_c0202_directional_matchup_snapshots_append_only
before update or delete on public.research_c0202_directional_matchup_snapshots
for each row execute function private.block_c0202_research_mutation_v01();

insert into public.research_c0202_validation_runs(run_key,evidence_cutoff,definition,benchmark,decision)
values (
 'C0202_V03_STRUCTURAL_DIRECTIONAL_20260904',
 '2026-09-04T17:30:00Z',
 jsonb_build_object(
   'scope','structural directional matchup evidence after exact-side V02',
   'historical_population','2025/26 MID/FWD starters >=60 minutes; previous-three exact side unanimous; prior-three median avg_x >=55',
   'target','next-match xGI/90 residual versus own previous-five-start xGI/90 baseline',
   'pre_kickoff_features',jsonb_build_array('opponent same-flank personnel instability','formation instability','opposing flank defender avg_x','opposing flank defender dribbled-past/90','ground-duel vulnerability','attacker-defender dribble mismatch','back-three rate'),
   'oracle_diagnostic','actual target defender/formation used only as post-match upper-bound diagnostic; never a forward feature',
   'forward_semantics','store explicit attacking team/player, attack side, faced defensive side and expected opposing player; effect direction remains unresolved until validated',
   'chronology','GW3 forward snapshot must use observations captured at or before 2026-09-04T17:30:00Z',
   'missing_data_rule','unmatched opposing player remains unresolved; never imputed'
 ),
 jsonb_build_object(
   'pre_kickoff_train_holdout',jsonb_build_object(
     'train_n',302,'holdout_n',163,
     'personnel_instability_corr',jsonb_build_object('train',-0.046,'holdout',-0.047),
     'formation_instability_corr',jsonb_build_object('train',0.133,'holdout',0.008),
     'flank_defender_avg_x_corr',jsonb_build_object('train',-0.069,'holdout',-0.030),
     'dribbled_past90_corr',jsonb_build_object('train',-0.050,'holdout',0.082),
     'ground_duel_vulnerability_corr',jsonb_build_object('train',-0.143,'holdout',-0.041),
     'dribble_mismatch_corr',jsonb_build_object('train',-0.078,'holdout',-0.003),
     'duel_mismatch_corr',jsonb_build_object('train',-0.061,'holdout',-0.021),
     'back3_rate_corr',jsonb_build_object('train',-0.060,'holdout',0.069)
   ),
   'oracle_ceiling',jsonb_build_object(
     'actual_flank_defender_change',jsonb_build_object('train_n',298,'train_changed_residual',0.092,'train_same_residual',-0.015,'holdout_n',156,'holdout_changed_residual',-0.060,'holdout_same_residual',-0.041),
     'actual_formation_change',jsonb_build_object('train_n',302,'train_changed_residual',0.080,'train_same_residual',-0.014,'holdout_n',163,'holdout_changed_residual',-0.036,'holdout_same_residual',-0.056)
   ),
   'conclusion','generic formation/personnel/flank-defender effects do not survive holdout; even oracle target-match changes fail to show stable uplift'
 ),
 'PROMOTE_STRUCTURED_DIRECTIONAL_EVIDENCE_TO_FORWARD_SHADOW; REJECT_GENERIC_PERSONNEL_FORMATION_XPTS_EFFECT'
) on conflict do nothing;

with cutoff as (select '2026-09-04T17:30:00Z'::timestamptz ts),
sp as (select * from private.c0202_current_side_prior_v01()),
role_pre as (
  select distinct on (match_id,player_id)
    id,match_id,gameweek,team_id,opponent_team_id,player_id,kickoff_time,captured_at,primary_role,secondary_role,expected_xi,availability_status,confidence,evidence
  from public.player_fixture_role_observations,cutoff
  where gameweek=3 and captured_at<=cutoff.ts
  order by match_id,player_id,captured_at desc,id desc
),
matchup_pre as (
  select distinct on (match_id,team_id,signal_key)
    id,match_id,gameweek,team_id,opponent_team_id,captured_at,signal_key,score,direction,confidence,evidence
  from public.fixture_tactical_matchup_observations,cutoff
  where gameweek=3 and captured_at<=cutoff.ts and signal_key in ('wide_channel_pressure','personnel_disruption')
  order by match_id,team_id,signal_key,captured_at desc,id desc
),
atk as (
 select r.*,p.web_name,sp.inferred_attack_side,sp.confidence_band,sp.empirical_holdout_accuracy
 from role_pre r join public.players p on p.id=r.player_id join sp on sp.player_id=r.player_id
 where r.expected_xi=true and r.availability_status='AVAILABLE'
   and r.primary_role in ('WIDE_ATTACKER','WIDE_FORWARD','WING_BACK','WIDE_BACK')
   and sp.inferred_attack_side in ('ATT_LEFT','ATT_RIGHT')
),
defc as (
 select r.*,p.web_name,sp.inferred_attack_side,sp.confidence_band,sp.empirical_holdout_accuracy
 from role_pre r join public.players p on p.id=r.player_id join sp on sp.player_id=r.player_id
 where r.expected_xi=true and r.availability_status='AVAILABLE'
   and r.primary_role in ('WIDE_BACK','WING_BACK')
   and sp.inferred_attack_side in ('ATT_LEFT','ATT_RIGHT')
),
pairs as (
 select a.*,
   d.id defender_role_observation_id,d.player_id expected_defender_player_id,d.primary_role expected_defender_role,d.captured_at defender_role_captured_at,
   d.confidence defender_role_confidence,d.confidence_band defender_side_confidence_band,d.empirical_holdout_accuracy defender_side_empirical_accuracy,
   row_number() over(partition by a.match_id,a.player_id order by case d.confidence_band when 'HIGH' then 2 when 'MEDIUM' then 1 else 0 end desc,d.confidence desc nulls last,d.player_id) rn
 from atk a
 left join defc d on d.match_id=a.match_id and d.team_id=a.opponent_team_id
   and d.inferred_attack_side=case when a.inferred_attack_side='ATT_LEFT' then 'ATT_RIGHT' else 'ATT_LEFT' end
),
final as (
 select p.*,
   w.id wide_obs_id,w.score wide_score,w.direction wide_direction,w.confidence wide_confidence,w.captured_at wide_captured_at,
   per.id personnel_obs_id,per.score personnel_score,per.direction personnel_direction,per.confidence personnel_confidence,per.captured_at personnel_captured_at
 from pairs p
 left join matchup_pre w on w.match_id=p.match_id and w.team_id=p.team_id and w.signal_key='wide_channel_pressure'
 left join matchup_pre per on per.match_id=p.match_id and per.team_id=p.opponent_team_id and per.signal_key='personnel_disruption'
 where p.rn=1
)
insert into public.research_c0202_directional_matchup_snapshots(
 run_key,evidence_cutoff,gameweek,match_id,kickoff_time,attacking_team_id,defending_team_id,attacker_player_id,attacker_role,
 attacker_side,attacker_side_confidence_band,attacker_side_empirical_accuracy,faced_defensive_side,
 expected_defender_player_id,expected_defender_role,defender_side_confidence_band,defender_side_empirical_accuracy,defender_pair_status,mapping_quality,
 attacker_role_captured_at,defender_role_captured_at,wide_context_score,wide_context_direction,wide_context_confidence,wide_context_captured_at,
 defending_team_personnel_score,defending_team_personnel_direction,defending_team_personnel_confidence,defending_team_personnel_captured_at,
 effect_direction,effect_magnitude,effect_confidence,evidence
)
select
 'C0202_V03_STRUCTURAL_DIRECTIONAL_20260904','2026-09-04T17:30:00Z',gameweek,match_id,kickoff_time,team_id,opponent_team_id,player_id,primary_role,
 inferred_attack_side,confidence_band,empirical_holdout_accuracy,
 case when inferred_attack_side='ATT_LEFT' then 'DEF_RIGHT' else 'DEF_LEFT' end,
 expected_defender_player_id,expected_defender_role,defender_side_confidence_band,defender_side_empirical_accuracy,
 case when expected_defender_player_id is null then 'UNRESOLVED_EXACT_OPPONENT' else 'PAIRED_EXACT_SIDE' end,
 case when expected_defender_player_id is null then 'UNRESOLVED'
      when confidence_band='HIGH' and defender_side_confidence_band='HIGH' and confidence>=0.65 and defender_role_confidence>=0.65 then 'HIGH'
      else 'MEDIUM' end,
 captured_at,defender_role_captured_at,wide_score,wide_direction,wide_confidence,wide_captured_at,
 personnel_score,personnel_direction,personnel_confidence,personnel_captured_at,
 'UNRESOLVED',null,null,
 jsonb_build_object(
   'evidence_cutoff','2026-09-04T17:30:00Z',
   'attacker_role_observation_id',id,
   'defender_role_observation_id',defender_role_observation_id,
   'wide_context_observation_id',wide_obs_id,
   'defending_team_personnel_observation_id',personnel_obs_id,
   'attacker_role_confidence',confidence,
   'defender_role_confidence',defender_role_confidence,
   'effect_semantics','UNRESOLVED means no validated attacking or defensive advantage is claimed',
   'wide_context_scope','TEAM_LEVEL_CONTEXT_NOT_LEFT_RIGHT_EFFECT',
   'personnel_context_scope','DEFENDING_TEAM_LEVEL_CONTEXT_NOT_FLANK_EFFECT',
   'historical_generic_effect_decision','REJECTED_AFTER_HOLDOUT_AND_ORACLE_DIAGNOSTIC',
   'missing_opponent_player_not_imputed',expected_defender_player_id is null,
   'chronology_verified',true,
   'model_effect_enabled',false
 )
from final
on conflict do nothing;

create or replace function private.c0202_directional_status_v03()
returns jsonb
language sql
stable
security definer
set search_path=public,private,pg_temp
as $$
select jsonb_build_object(
 'change_id','C0202',
 'run_key','C0202_V03_STRUCTURAL_DIRECTIONAL_20260904',
 'rows',(select count(*) from public.research_c0202_directional_matchup_snapshots where run_key='C0202_V03_STRUCTURAL_DIRECTIONAL_20260904'),
 'paired_exact_side',(select count(*) from public.research_c0202_directional_matchup_snapshots where run_key='C0202_V03_STRUCTURAL_DIRECTIONAL_20260904' and defender_pair_status='PAIRED_EXACT_SIDE'),
 'unresolved_exact_opponent',(select count(*) from public.research_c0202_directional_matchup_snapshots where run_key='C0202_V03_STRUCTURAL_DIRECTIONAL_20260904' and defender_pair_status='UNRESOLVED_EXACT_OPPONENT'),
 'high_mapping_quality',(select count(*) from public.research_c0202_directional_matchup_snapshots where run_key='C0202_V03_STRUCTURAL_DIRECTIONAL_20260904' and mapping_quality='HIGH'),
 'effect_direction_counts',(select coalesce(jsonb_object_agg(effect_direction,n),'{}'::jsonb) from (select effect_direction,count(*) n from public.research_c0202_directional_matchup_snapshots where run_key='C0202_V03_STRUCTURAL_DIRECTIONAL_20260904' group by effect_direction) x),
 'latest_role_source',(select max(attacker_role_captured_at) from public.research_c0202_directional_matchup_snapshots where run_key='C0202_V03_STRUCTURAL_DIRECTIONAL_20260904'),
 'latest_context_source',(select greatest(max(wide_context_captured_at),max(defending_team_personnel_captured_at)) from public.research_c0202_directional_matchup_snapshots where run_key='C0202_V03_STRUCTURAL_DIRECTIONAL_20260904'),
 'evidence_cutoff','2026-09-04T17:30:00Z',
 'generic_structural_xpts_effect','REJECTED',
 'model_effect_enabled',false,
 'append_only',true
);
$$;
revoke all on function private.c0202_directional_status_v03() from public,anon,authenticated;
