create table if not exists public.research_c0197_long_history_captures (
  id bigint generated by default as identity primary key,
  source_key text not null,
  competition text not null,
  season text not null,
  source_url text not null,
  captured_at timestamptz not null default now(),
  content_sha256 text not null,
  source_bytes integer not null,
  source_row_count integer not null,
  header_field_count integer not null,
  regime_key text not null,
  source_content_type text,
  research_only boolean not null default true,
  model_effect_enabled boolean not null default false,
  notes text,
  unique (source_key, competition, season, content_sha256),
  check (research_only = true),
  check (model_effect_enabled = false)
);

create table if not exists public.research_c0197_long_history_matches (
  id bigint generated by default as identity primary key,
  capture_id bigint not null references public.research_c0197_long_history_captures(id),
  source_key text not null,
  competition text not null,
  season text not null,
  source_match_id text not null,
  source_row_number integer not null,
  match_date date not null,
  kickoff_time_local time,
  provider_timezone text not null default 'Europe/London',
  home_team text not null,
  away_team text not null,
  full_time_home_goals integer,
  full_time_away_goals integer,
  full_time_result text,
  half_time_home_goals integer,
  half_time_away_goals integer,
  half_time_result text,
  referee text,
  home_shots integer,
  away_shots integer,
  home_shots_on_target integer,
  away_shots_on_target integer,
  home_fouls integer,
  away_fouls integer,
  home_corners integer,
  away_corners integer,
  home_yellow_cards integer,
  away_yellow_cards integer,
  home_red_cards integer,
  away_red_cards integer,
  avg_open_home_odds numeric,
  avg_open_draw_odds numeric,
  avg_open_away_odds numeric,
  avg_open_over25_odds numeric,
  avg_open_under25_odds numeric,
  avg_close_home_odds numeric,
  avg_close_draw_odds numeric,
  avg_close_away_odds numeric,
  avg_close_over25_odds numeric,
  avg_close_under25_odds numeric,
  regime_key text not null,
  raw_row jsonb not null,
  research_only boolean not null default true,
  model_effect_enabled boolean not null default false,
  created_at timestamptz not null default now(),
  unique (capture_id, source_match_id),
  check (research_only = true),
  check (model_effect_enabled = false)
);

alter table public.research_c0197_long_history_captures enable row level security;
alter table public.research_c0197_long_history_matches enable row level security;
revoke all on public.research_c0197_long_history_captures from anon, authenticated;
revoke all on public.research_c0197_long_history_matches from anon, authenticated;

create or replace function private.c0197_safe_int_v01(p_value text)
returns integer
language sql
immutable
set search_path = pg_catalog
as $$
  select case when btrim(coalesce(p_value,'')) ~ '^-?[0-9]+$' then btrim(p_value)::integer else null end;
$$;

create or replace function private.c0197_safe_numeric_v01(p_value text)
returns numeric
language sql
immutable
set search_path = pg_catalog
as $$
  select case when btrim(coalesce(p_value,'')) ~ '^-?[0-9]+([.][0-9]+)?$' then btrim(p_value)::numeric else null end;
$$;

create or replace function private.c0197_block_long_history_mutation_v01()
returns trigger
language plpgsql
set search_path = pg_catalog
as $$
begin
  raise exception 'C0197 long-history evidence is append-only';
end;
$$;

create trigger c0197_block_long_history_capture_mutation
before update or delete on public.research_c0197_long_history_captures
for each row execute function private.c0197_block_long_history_mutation_v01();

create trigger c0197_block_long_history_match_mutation
before update or delete on public.research_c0197_long_history_matches
for each row execute function private.c0197_block_long_history_mutation_v01();

create or replace function private.c0197_ingest_football_data_csv_v01(
  p_season text,
  p_source_url text,
  p_content text,
  p_regime_key text default 'STANDARD'
)
returns jsonb
language plpgsql
security invoker
set search_path = pg_catalog, public, private, extensions
as $$
declare
  v_lines text[];
  v_headers text[];
  v_values text[];
  v_line text;
  v_hash text;
  v_capture_id bigint;
  v_existing integer;
  v_inserted integer := 0;
  v_header_count integer;
  v_date date;
  v_time time;
  v_home text;
  v_away text;
  v_source_match_id text;
  v_raw jsonb;
  i integer;
  idx_date integer;
  idx_time integer;
  idx_home integer;
  idx_away integer;
  idx_fthg integer;
  idx_ftag integer;
  idx_ftr integer;
  idx_hthg integer;
  idx_htag integer;
  idx_htr integer;
  idx_ref integer;
  idx_hs integer;
  idx_as integer;
  idx_hst integer;
  idx_ast integer;
  idx_hf integer;
  idx_af integer;
  idx_hc integer;
  idx_ac integer;
  idx_hy integer;
  idx_ay integer;
  idx_hr integer;
  idx_ar integer;
  idx_avgh integer;
  idx_avgd integer;
  idx_avga integer;
  idx_avgo integer;
  idx_avgu integer;
  idx_avgch integer;
  idx_avgcd integer;
  idx_avgca integer;
  idx_avgco integer;
  idx_avgcu integer;
begin
  if p_season not in ('2020-2021','2021-2022','2022-2023','2023-2024','2024-2025','2025-2026') then
    raise exception 'Season % is outside the approved C0197 six-season block', p_season;
  end if;
  if p_source_url not like 'https://www.football-data.co.uk/mmz4281/%/E0.csv' then
    raise exception 'Unapproved Football-Data source URL';
  end if;
  if p_content is null or length(p_content) < 1000 then
    raise exception 'Source content missing or unexpectedly small';
  end if;

  v_lines := string_to_array(replace(p_content, E'\r', ''), E'\n');
  v_headers := string_to_array(v_lines[1], ',');
  v_header_count := array_length(v_headers, 1);
  for i in 1..v_header_count loop
    v_headers[i] := replace(v_headers[i], chr(65279), '');
  end loop;

  idx_date := array_position(v_headers,'Date');
  idx_time := array_position(v_headers,'Time');
  idx_home := array_position(v_headers,'HomeTeam');
  idx_away := array_position(v_headers,'AwayTeam');
  idx_fthg := array_position(v_headers,'FTHG');
  idx_ftag := array_position(v_headers,'FTAG');
  idx_ftr := array_position(v_headers,'FTR');
  idx_hthg := array_position(v_headers,'HTHG');
  idx_htag := array_position(v_headers,'HTAG');
  idx_htr := array_position(v_headers,'HTR');
  idx_ref := array_position(v_headers,'Referee');
  idx_hs := array_position(v_headers,'HS');
  idx_as := array_position(v_headers,'AS');
  idx_hst := array_position(v_headers,'HST');
  idx_ast := array_position(v_headers,'AST');
  idx_hf := array_position(v_headers,'HF');
  idx_af := array_position(v_headers,'AF');
  idx_hc := array_position(v_headers,'HC');
  idx_ac := array_position(v_headers,'AC');
  idx_hy := array_position(v_headers,'HY');
  idx_ay := array_position(v_headers,'AY');
  idx_hr := array_position(v_headers,'HR');
  idx_ar := array_position(v_headers,'AR');
  idx_avgh := array_position(v_headers,'AvgH');
  idx_avgd := array_position(v_headers,'AvgD');
  idx_avga := array_position(v_headers,'AvgA');
  idx_avgo := array_position(v_headers,'Avg>2.5');
  idx_avgu := array_position(v_headers,'Avg<2.5');
  idx_avgch := array_position(v_headers,'AvgCH');
  idx_avgcd := array_position(v_headers,'AvgCD');
  idx_avgca := array_position(v_headers,'AvgCA');
  idx_avgco := array_position(v_headers,'AvgC>2.5');
  idx_avgcu := array_position(v_headers,'AvgC<2.5');

  if idx_date is null or idx_home is null or idx_away is null or idx_fthg is null or idx_ftag is null or idx_hs is null or idx_as is null or idx_hst is null or idx_ast is null then
    raise exception 'Required Football-Data columns are missing';
  end if;

  v_hash := encode(extensions.digest(convert_to(p_content,'UTF8'),'sha256'),'hex');
  select id into v_capture_id
  from public.research_c0197_long_history_captures
  where source_key='football_data_uk' and competition='EPL' and season=p_season and content_sha256=v_hash;

  if v_capture_id is null then
    insert into public.research_c0197_long_history_captures(
      source_key,competition,season,source_url,content_sha256,source_bytes,source_row_count,header_field_count,regime_key,source_content_type,notes
    ) values (
      'football_data_uk','EPL',p_season,p_source_url,v_hash,octet_length(p_content),
      (select count(*) from unnest(v_lines[2:array_length(v_lines,1)]) x where btrim(x)<>''),
      v_header_count,p_regime_key,'text/csv','C0197 homogeneous six-season long-history baseline'
    ) returning id into v_capture_id;
  end if;

  select count(*) into v_existing from public.research_c0197_long_history_matches where capture_id=v_capture_id;
  if v_existing > 0 then
    return jsonb_build_object('ok',true,'season',p_season,'capture_id',v_capture_id,'content_sha256',v_hash,'rows',v_existing,'idempotent',true,'model_effect_enabled',false);
  end if;

  for i in 2..array_length(v_lines,1) loop
    v_line := v_lines[i];
    if btrim(coalesce(v_line,''))='' then continue; end if;
    v_values := string_to_array(v_line, ',');
    if array_length(v_values,1) <> v_header_count then
      raise exception 'CSV field-count mismatch in season %, row %: expected %, got %', p_season, i, v_header_count, array_length(v_values,1);
    end if;

    v_date := to_date(v_values[idx_date], 'DD/MM/YYYY');
    v_time := case when idx_time is not null and btrim(v_values[idx_time]) ~ '^[0-9]{1,2}:[0-9]{2}$' then v_values[idx_time]::time else null end;
    v_home := nullif(btrim(v_values[idx_home]),'');
    v_away := nullif(btrim(v_values[idx_away]),'');
    if v_date is null or v_home is null or v_away is null then
      raise exception 'Missing core match identity in season %, row %', p_season, i;
    end if;
    v_source_match_id := p_season || ':' || to_char(v_date,'YYYY-MM-DD') || ':' || v_home || ':' || v_away;
    v_raw := jsonb_object(v_headers, v_values);

    insert into public.research_c0197_long_history_matches(
      capture_id,source_key,competition,season,source_match_id,source_row_number,match_date,kickoff_time_local,home_team,away_team,
      full_time_home_goals,full_time_away_goals,full_time_result,half_time_home_goals,half_time_away_goals,half_time_result,referee,
      home_shots,away_shots,home_shots_on_target,away_shots_on_target,home_fouls,away_fouls,home_corners,away_corners,
      home_yellow_cards,away_yellow_cards,home_red_cards,away_red_cards,
      avg_open_home_odds,avg_open_draw_odds,avg_open_away_odds,avg_open_over25_odds,avg_open_under25_odds,
      avg_close_home_odds,avg_close_draw_odds,avg_close_away_odds,avg_close_over25_odds,avg_close_under25_odds,
      regime_key,raw_row
    ) values (
      v_capture_id,'football_data_uk','EPL',p_season,v_source_match_id,i-1,v_date,v_time,v_home,v_away,
      private.c0197_safe_int_v01(v_values[idx_fthg]),private.c0197_safe_int_v01(v_values[idx_ftag]),case when idx_ftr is null then null else nullif(v_values[idx_ftr],'') end,
      case when idx_hthg is null then null else private.c0197_safe_int_v01(v_values[idx_hthg]) end,
      case when idx_htag is null then null else private.c0197_safe_int_v01(v_values[idx_htag]) end,
      case when idx_htr is null then null else nullif(v_values[idx_htr],'') end,
      case when idx_ref is null then null else nullif(v_values[idx_ref],'') end,
      private.c0197_safe_int_v01(v_values[idx_hs]),private.c0197_safe_int_v01(v_values[idx_as]),private.c0197_safe_int_v01(v_values[idx_hst]),private.c0197_safe_int_v01(v_values[idx_ast]),
      case when idx_hf is null then null else private.c0197_safe_int_v01(v_values[idx_hf]) end,
      case when idx_af is null then null else private.c0197_safe_int_v01(v_values[idx_af]) end,
      case when idx_hc is null then null else private.c0197_safe_int_v01(v_values[idx_hc]) end,
      case when idx_ac is null then null else private.c0197_safe_int_v01(v_values[idx_ac]) end,
      case when idx_hy is null then null else private.c0197_safe_int_v01(v_values[idx_hy]) end,
      case when idx_ay is null then null else private.c0197_safe_int_v01(v_values[idx_ay]) end,
      case when idx_hr is null then null else private.c0197_safe_int_v01(v_values[idx_hr]) end,
      case when idx_ar is null then null else private.c0197_safe_int_v01(v_values[idx_ar]) end,
      case when idx_avgh is null then null else private.c0197_safe_numeric_v01(v_values[idx_avgh]) end,
      case when idx_avgd is null then null else private.c0197_safe_numeric_v01(v_values[idx_avgd]) end,
      case when idx_avga is null then null else private.c0197_safe_numeric_v01(v_values[idx_avga]) end,
      case when idx_avgo is null then null else private.c0197_safe_numeric_v01(v_values[idx_avgo]) end,
      case when idx_avgu is null then null else private.c0197_safe_numeric_v01(v_values[idx_avgu]) end,
      case when idx_avgch is null then null else private.c0197_safe_numeric_v01(v_values[idx_avgch]) end,
      case when idx_avgcd is null then null else private.c0197_safe_numeric_v01(v_values[idx_avgcd]) end,
      case when idx_avgca is null then null else private.c0197_safe_numeric_v01(v_values[idx_avgca]) end,
      case when idx_avgco is null then null else private.c0197_safe_numeric_v01(v_values[idx_avgco]) end,
      case when idx_avgcu is null then null else private.c0197_safe_numeric_v01(v_values[idx_avgcu]) end,
      p_regime_key,v_raw
    );
    v_inserted := v_inserted + 1;
  end loop;

  return jsonb_build_object('ok',true,'season',p_season,'capture_id',v_capture_id,'content_sha256',v_hash,'rows',v_inserted,'idempotent',false,'model_effect_enabled',false);
end;
$$;

create or replace view private.c0197_long_history_latest_matches_v01
with (security_invoker = true)
as
with latest_capture as (
  select distinct on (source_key,competition,season) id,source_key,competition,season,captured_at,content_sha256
  from public.research_c0197_long_history_captures
  order by source_key,competition,season,captured_at desc,id desc
)
select m.*,
       (coalesce(m.full_time_home_goals,0)+coalesce(m.full_time_away_goals,0)) as total_goals,
       ((coalesce(m.full_time_home_goals,0)+coalesce(m.full_time_away_goals,0)) >= 4) as goals_4_plus,
       ((coalesce(m.full_time_home_goals,0)+coalesce(m.full_time_away_goals,0)) >= 5) as goals_5_plus,
       ((coalesce(m.full_time_home_goals,0)+coalesce(m.full_time_away_goals,0)) >= 6) as goals_6_plus,
       ((coalesce(m.full_time_home_goals,0)+coalesce(m.full_time_away_goals,0)) >= 7) as goals_7_plus,
       c.content_sha256 as pinned_content_sha256,
       c.captured_at as source_captured_at
from public.research_c0197_long_history_matches m
join latest_capture c on c.id=m.capture_id;

revoke all on private.c0197_long_history_latest_matches_v01 from public, anon, authenticated;
grant select on private.c0197_long_history_latest_matches_v01 to service_role;

create or replace function private.c0197_long_history_status_v01()
returns jsonb
language sql
security invoker
set search_path = pg_catalog, public, private
as $$
with season_stats as (
  select season,
         count(*) as matches,
         min(match_date) as first_match,
         max(match_date) as last_match,
         count(*) filter (where full_time_home_goals is not null and full_time_away_goals is not null) as score_rows,
         count(*) filter (where home_shots is not null and away_shots is not null) as shot_rows,
         count(*) filter (where home_shots_on_target is not null and away_shots_on_target is not null) as sot_rows,
         count(*) filter (where goals_4_plus) as goals_4_plus,
         count(*) filter (where goals_5_plus) as goals_5_plus,
         count(*) filter (where goals_6_plus) as goals_6_plus,
         count(*) filter (where goals_7_plus) as goals_7_plus,
         min(regime_key) as regime_key
  from private.c0197_long_history_latest_matches_v01
  group by season
)
select jsonb_build_object(
  'change_id','C0197',
  'model_effect_enabled',false,
  'seasons',coalesce(jsonb_agg(to_jsonb(season_stats) order by season),'[]'::jsonb),
  'total_matches',coalesce(sum(matches),0),
  'min_season',min(season),
  'max_season',max(season)
)
from season_stats;
$$;

revoke all on function private.c0197_long_history_status_v01() from public, anon, authenticated;
grant execute on function private.c0197_long_history_status_v01() to service_role;
