alter view public.correct_score_price_summary rename column opening_raw_snapshot_id to first_observed_raw_snapshot_id;
alter view public.correct_score_price_summary rename column opening_decimal_odds to first_observed_decimal_odds;
alter view public.correct_score_price_summary rename column opening_implied_probability to first_observed_implied_probability;
alter view public.correct_score_price_summary rename column opening_captured_at to first_observed_captured_at;
alter view public.correct_score_price_summary rename column opening_seconds_before_kickoff to first_observed_seconds_before_kickoff;
alter view public.correct_score_price_summary rename column opening_to_latest_odds_return to first_observed_to_latest_odds_return;
alter view public.correct_score_price_summary rename column opening_to_latest_implied_probability_move to first_observed_to_latest_implied_probability_move;
