create table if not exists public.research_c0197_regime_shadow_ablations (
  id bigint generated by default as identity primary key,
  run_key text not null references public.research_c0197_regime_shadow_runs(run_key),
  gameweek integer not null,
  fixture text not null,
  score text,
  actual_shootout boolean,
  full_rank integer,
  no_process_rank integer,
  no_tactical_rank integer,
  no_xgi_rank integer,
  no_personnel_rank integer,
  no_coach_rank integer,
  evidence jsonb not null default '{}'::jsonb,
  research_only boolean not null default true check (research_only),
  model_effect_enabled boolean not null default false check (not model_effect_enabled),
  created_at timestamptz not null default clock_timestamp(),
  unique(run_key,gameweek,fixture)
);

alter table public.research_c0197_regime_shadow_ablations enable row level security;
revoke all on public.research_c0197_regime_shadow_ablations from anon,authenticated;
revoke all on sequence public.research_c0197_regime_shadow_ablations_id_seq from anon,authenticated;

drop trigger if exists research_c0197_regime_shadow_ablations_append_only on public.research_c0197_regime_shadow_ablations;
create trigger research_c0197_regime_shadow_ablations_append_only before update or delete on public.research_c0197_regime_shadow_ablations for each row execute function private.block_c0197_regime_shadow_mutation_v03();

insert into public.research_c0197_regime_shadow_ablations(run_key,gameweek,fixture,score,actual_shootout,full_rank,no_process_rank,no_tactical_rank,no_xgi_rank,no_personnel_rank,no_coach_rank,evidence)
values
('C0197_REGIME_SHADOW_20260904_V03',2,'Chelsea vs Brighton','4-3',true,5,8,5,4,5,5,'{"interpretation":"current attack-process shock is the material rescue component"}'::jsonb),
('C0197_REGIME_SHADOW_20260904_V03',2,'Man Utd vs Ipswich Town','5-2',true,1,1,1,1,2,1,'{"interpretation":"robust across ablations; personnel change contributes but is not sole driver"}'::jsonb),
('C0197_REGIME_SHADOW_20260904_V03',2,'Crystal Palace vs Man City','1-4',false,2,2,2,2,1,2,'{"interpretation":"regime layer also identifies high-score non-shootout risk"}'::jsonb)
on conflict do nothing;