-- C0277 P3 — robust cross-chip action selector and Noise/Decision-Control gate.
create or replace function private.c0277_robust_chip_action_selector_v01(p_gameweek integer, p_exact_decision_horizon integer default 3, p_seasonal_chip_end_gameweek integer default 19)
returns jsonb language plpgsql security definer set search_path='' as $$
declare v_s jsonb; v_r jsonb; v_exact jsonb; v_best boolean; v_nochip boolean; v_rec text; v_auth text; v_non jsonb; v_out jsonb;
begin
 v_s:=private.c0277_future_opportunity_scenarios_v01(p_gameweek,p_exact_decision_horizon,p_seasonal_chip_end_gameweek); v_r:=private.c0277_reservation_value_status_v01(p_gameweek,p_exact_decision_horizon,p_seasonal_chip_end_gameweek);
 if not coalesce((v_s->>'ok')::boolean,false) or not coalesce((v_r->>'ok')::boolean,false) then return jsonb_build_object('ok',false,'status','C0277_P3_INPUT_NOT_READY','change_id','C0277','selector_class','UNRESOLVED_FAIL_CLOSED','historical_forecasts_rewritten',false); end if;
 v_exact:=private.c0277_dual_horizon_chip_option_status_v01(p_gameweek,p_exact_decision_horizon,p_seasonal_chip_end_gameweek); v_best:=coalesce((v_exact->>'season_best_chip_weeks_resolved')::boolean,false); v_nochip:=coalesce((v_exact->>'bounded_current_no_chip_robust')::boolean,false); v_rec:=coalesce(v_exact->>'recommended_current_chip','NONE'); v_auth:=coalesce(v_exact->>'authorization_class','PRESERVE'); v_non:=coalesce(v_s->'observed_structure'->'confirmed_nonstandard_gameweeks','[]'::jsonb);
 v_out:=jsonb_build_object('ok',true,'status','C0277_ROBUST_CHIP_SELECTOR_V01_EVALUATED','change_id','C0277','gameweek',p_gameweek,'exact_decision_horizon',p_exact_decision_horizon,'seasonal_chip_end_gameweek',p_seasonal_chip_end_gameweek,'selector_class',case when v_rec='NONE' and v_nochip then 'RESERVE_FOR_FUTURE' when v_rec<>'NONE' and v_best and v_auth='PLAY' then 'PLAY_NOW' when v_rec<>'NONE' and not v_best then 'UNRESOLVED_FAIL_CLOSED' else 'NO_MEANINGFUL_EDGE' end,'recommended_current_chip',case when v_rec='NONE' then 'NONE' when v_best and v_auth='PLAY' then v_rec else 'NONE' end,'play_now_authorized',case when v_rec<>'NONE' and v_best and v_auth='PLAY' then true else false end,'cross_chip_collision_gate',jsonb_build_object('confirmed_nonstandard_windows',v_non,'season_numeric_collision_rank_authorized',v_best,'collision_resolved',v_best,'rule','A chip cannot consume a shared scarce window until competing chip opportunity cost is decision-grade; unresolved collision preserves all affected options'),'noise_control',jsonb_build_object('multiple_independent_support_required',true,'structural_signal_required',true,'single_model_output_sufficient',false,'reasonable_assumption_flip_blocks_action',true,'within_model_error_blocks_action',true,'current_no_chip_robust',v_nochip),'decision_control',jsonb_build_object('whole_squad_reoptimization_required_before_spend',true,'expected_minutes_and_role_gates_required',true,'future_transfer_burden_required',true,'chip_opportunity_cost_required',true,'red_team_required',true),'reservation_evidence',v_r->'chips','scenario_control',v_s->'scenario_control','policy',jsonb_build_object('c0248_selected_path_authority_unchanged',true,'p3_is_supporting_gate_not_second_optimizer',true,'future_uncertainty_never_converted_to_zero',true,'structural_only_evidence_cannot_authorize_spend',true,'only_robust_play_can_pass',true,'does_not_execute',true),'historical_forecasts_rewritten',false); return v_out;
end $$;
revoke all on function private.c0277_robust_chip_action_selector_v01(integer,integer,integer) from public;
grant execute on function private.c0277_robust_chip_action_selector_v01(integer,integer,integer) to service_role;
