create table if not exists public.research_c0197_regime_shadow_runs (
  run_key text primary key,
  change_id text not null default 'C0197',
  experiment_name text not null,
  definition jsonb not null,
  decision text not null,
  conclusion text not null,
  research_only boolean not null default true check (research_only),
  model_effect_enabled boolean not null default false check (not model_effect_enabled),
  created_at timestamptz not null default clock_timestamp()
);

create table if not exists public.research_c0197_regime_shadow_replay (
  id bigint generated by default as identity primary key,
  run_key text not null references public.research_c0197_regime_shadow_runs(run_key),
  gameweek integer not null,
  match_id bigint references public.matches(id),
  fixture text not null,
  score text,
  total_goals integer,
  actual_shootout boolean,
  v02_rank integer,
  v02_score numeric,
  regime_overlay numeric,
  rank_w25 integer,
  rank_w50 integer,
  rank_w75 integer,
  v03_w25 numeric,
  v03_w50 numeric,
  v03_w75 numeric,
  features jsonb not null default '{}'::jsonb,
  research_only boolean not null default true check (research_only),
  model_effect_enabled boolean not null default false check (not model_effect_enabled),
  created_at timestamptz not null default clock_timestamp(),
  unique(run_key,gameweek,match_id)
);

create table if not exists public.research_c0197_regime_shadow_forward_snapshots (
  id bigint generated by default as identity primary key,
  run_key text not null references public.research_c0197_regime_shadow_runs(run_key),
  observation_hash text not null,
  snapshot_as_of timestamptz not null,
  gameweek integer not null,
  match_id bigint references public.matches(id),
  fixture text not null,
  v02_rank integer,
  v02_score numeric,
  regime_overlay numeric,
  rank_w25 integer,
  rank_w50 integer,
  rank_w75 integer,
  v03_w25 numeric,
  v03_w50 numeric,
  v03_w75 numeric,
  confidence text,
  features jsonb not null default '{}'::jsonb,
  research_only boolean not null default true check (research_only),
  model_effect_enabled boolean not null default false check (not model_effect_enabled),
  created_at timestamptz not null default clock_timestamp(),
  unique(run_key,match_id,observation_hash)
);

alter table public.research_c0197_regime_shadow_runs enable row level security;
alter table public.research_c0197_regime_shadow_replay enable row level security;
alter table public.research_c0197_regime_shadow_forward_snapshots enable row level security;
revoke all on public.research_c0197_regime_shadow_runs from anon,authenticated;
revoke all on public.research_c0197_regime_shadow_replay from anon,authenticated;
revoke all on public.research_c0197_regime_shadow_forward_snapshots from anon,authenticated;
revoke all on sequence public.research_c0197_regime_shadow_replay_id_seq from anon,authenticated;
revoke all on sequence public.research_c0197_regime_shadow_forward_snapshots_id_seq from anon,authenticated;

create or replace function private.block_c0197_regime_shadow_mutation_v03()
returns trigger language plpgsql set search_path=public,private,pg_temp as $$
begin raise exception 'C0197 regime shadow evidence is append-only'; end $$;
revoke all on function private.block_c0197_regime_shadow_mutation_v03() from public,anon,authenticated;

drop trigger if exists research_c0197_regime_shadow_runs_append_only on public.research_c0197_regime_shadow_runs;
create trigger research_c0197_regime_shadow_runs_append_only before update or delete on public.research_c0197_regime_shadow_runs for each row execute function private.block_c0197_regime_shadow_mutation_v03();
drop trigger if exists research_c0197_regime_shadow_replay_append_only on public.research_c0197_regime_shadow_replay;
create trigger research_c0197_regime_shadow_replay_append_only before update or delete on public.research_c0197_regime_shadow_replay for each row execute function private.block_c0197_regime_shadow_mutation_v03();
drop trigger if exists research_c0197_regime_shadow_forward_append_only on public.research_c0197_regime_shadow_forward_snapshots;
create trigger research_c0197_regime_shadow_forward_append_only before update or delete on public.research_c0197_regime_shadow_forward_snapshots for each row execute function private.block_c0197_regime_shadow_mutation_v03();

insert into public.research_c0197_regime_shadow_runs(run_key,experiment_name,definition,decision,conclusion)
values (
 'C0197_REGIME_SHADOW_20260904_V03',
 'Shootout regime-change overlay v03',
 jsonb_build_object(
  'base','frozen C0197 V02 shootout score',
  'replay_cutoff','2026-08-28T18:59:59Z',
  'forward_snapshot','2026-09-03T23:46:36.498520Z',
  'components',jsonb_build_array(
    'weaker-side current attack-process index',
    'weaker-side attacking box-occupation score',
    'weaker-side projected expected-XI MID/FWD xGI load',
    'larger-side share of projected attacking xGI from players at different/no EPL club in 2025/26',
    'either-side new head coach appointed after 2025/26 season'
  ),
  'scaling','within-Gameweek z-standardization across 10 fixtures; equal component weights',
  'overlay_sensitivity',jsonb_build_array(0.25,0.50,0.75),
  'coach_source','PremierLeague.com Manager line-up complete for 2026/27 season, 2026-08-05',
  'personnel_identity','current canonical team vs dominant 2025/26 source_team_code per stable player_code',
  'noise_control','do not choose an overlay weight from GW2; freeze all three for GW3',
  'production_effect',false
 ),
 'PROMISING_RETROSPECTIVE_WEIGHT_SENSITIVE_FORWARD_TEST_REQUIRED',
 'GW2 retrospective replay materially improves ranking of both 7-goal shootouts at 50-75% regime weight, but feature selection followed the observed miss and ranks remain weight-sensitive. Freeze all three weights for GW3; no production effect.'
) on conflict do nothing;

with v(fixture,score,total_goals,actual_shootout,v02_rank,v02_score,overlay,r25,r50,r75,w25,w50,w75,features) as (values
 ('Man Utd vs Ipswich Town','5-2',7,true,3,.470,.641,1,1,2,.513,.555,.598,'{"attack_floor":0.962,"box_floor":0.670,"xgi_floor":0.843,"personnel_change":1.000,"coach_change_any":1,"z_attack":0.678,"z_box":1.063,"z_xgi":-0.925,"z_personnel":1.766,"z_coach":0.621}'::jsonb),
 ('Crystal Palace vs Man City','1-4',5,false,8,-.154,1.035,5,2,1,.143,.440,.738,'{"attack_floor":1.007,"box_floor":0.713,"xgi_floor":1.831,"personnel_change":0.411,"coach_change_any":1,"z_attack":0.847,"z_box":1.331,"z_xgi":2.257,"z_personnel":0.117,"z_coach":0.621}'::jsonb),
 ('Bournemouth vs Everton','1-1',2,false,2,.523,-.025,3,3,4,.386,.249,.112,'{"attack_floor":0.600,"box_floor":0.500,"xgi_floor":1.422,"personnel_change":0.000,"coach_change_any":1}'::jsonb),
 ('Liverpool vs Nott''m Forest','2-2',4,false,1,.597,-.142,2,4,5,.412,.228,.043,'{"attack_floor":0.600,"box_floor":0.488,"xgi_floor":1.264,"personnel_change":0.000,"coach_change_any":1}'::jsonb),
 ('Chelsea vs Brighton','4-3',7,true,10,-.482,.558,9,5,3,-.222,.038,.298,'{"attack_floor":1.399,"box_floor":0.552,"xgi_floor":1.050,"personnel_change":0.303,"coach_change_any":1,"z_attack":2.291,"z_box":0.323,"z_xgi":-0.258,"z_personnel":-0.184,"z_coach":0.621}'::jsonb),
 ('Sunderland vs Fulham','1-0',1,false,7,.108,-.047,6,6,6,.069,.030,-.009,'{"attack_floor":0.806,"box_floor":0.481,"xgi_floor":0.915,"personnel_change":0.314,"coach_change_any":1}'::jsonb),
 ('Spurs vs Newcastle','0-2',2,false,6,.162,-.250,7,7,7,.059,-.044,-.147,'{"attack_floor":0.603,"box_floor":0.550,"xgi_floor":0.817,"personnel_change":0.178,"coach_change_any":1}'::jsonb),
 ('Aston Villa vs Arsenal','0-1',1,false,4,.434,-.709,4,8,10,.148,-.138,-.424,'{"attack_floor":0.600,"box_floor":0.391,"xgi_floor":0.967,"personnel_change":0.282,"coach_change_any":0}'::jsonb),
 ('Coventry City vs Hull City','0-1',1,false,5,.182,-.602,8,9,9,-.014,-.210,-.406,'{"attack_floor":0.600,"box_floor":0.127,"xgi_floor":1.021,"personnel_change":1.000,"coach_change_any":0}'::jsonb),
 ('Leeds vs Brentford','1-1',2,false,9,-.190,-.458,10,10,8,-.257,-.324,-.391,'{"attack_floor":0.600,"box_floor":0.526,"xgi_floor":1.170,"personnel_change":0.198,"coach_change_any":0}'::jsonb)
), resolved as (
 select v.*,m.id match_id from v join public.matches m on m.gameweek=2 and (select ht.name from public.teams ht where ht.id=m.home_team_id)||' vs '||(select at.name from public.teams at where at.id=m.away_team_id)=v.fixture
)
insert into public.research_c0197_regime_shadow_replay(run_key,gameweek,match_id,fixture,score,total_goals,actual_shootout,v02_rank,v02_score,regime_overlay,rank_w25,rank_w50,rank_w75,v03_w25,v03_w50,v03_w75,features)
select 'C0197_REGIME_SHADOW_20260904_V03',2,match_id,fixture,score,total_goals,actual_shootout,v02_rank,v02_score,overlay,r25,r50,r75,w25,w50,w75,features from resolved
on conflict do nothing;

with v(fixture,v02_rank,v02_score,overlay,r25,r50,r75,w25,w50,w75,confidence,features) as (values
 ('Ipswich Town vs Liverpool',2,.861,.745,1,1,1,.832,.803,.774,'LOW','{"attack_floor":1.297,"box_floor":0.488,"xgi_floor":1.022,"personnel_change":1.000,"coach_change_any":1}'::jsonb),
 ('Everton vs Man Utd',1,.948,.280,2,2,2,.781,.614,.447,'MEDIUM','{"attack_floor":1.033,"box_floor":0.670,"xgi_floor":1.509,"personnel_change":0.158,"coach_change_any":0}'::jsonb),
 ('Newcastle vs Bournemouth',3,.825,.006,3,3,4,.620,.415,.211,'MEDIUM','{"attack_floor":0.836,"box_floor":0.500,"xgi_floor":1.192,"personnel_change":0.075,"coach_change_any":1}'::jsonb),
 ('Arsenal vs Chelsea',9,-.288,.609,8,4,3,-.064,.160,.384,'MEDIUM','{"attack_floor":0.879,"box_floor":0.552,"xgi_floor":1.759,"personnel_change":0.286,"coach_change_any":1}'::jsonb),
 ('Fulham vs Crystal Palace',7,-.054,.270,7,5,5,.027,.108,.189,'MEDIUM','{"attack_floor":0.834,"box_floor":0.622,"xgi_floor":1.177,"personnel_change":0.297,"coach_change_any":1}'::jsonb),
 ('Nott''m Forest vs Spurs',6,.086,-.135,6,6,6,.031,-.024,-.080,'MEDIUM','{"attack_floor":0.723,"box_floor":0.550,"xgi_floor":0.853,"personnel_change":0.323,"coach_change_any":1}'::jsonb),
 ('Hull City vs Aston Villa',5,.321,-.495,4,7,8,.117,-.087,-.291,'LOW','{"attack_floor":0.600,"box_floor":0.391,"xgi_floor":0.862,"personnel_change":1.000,"coach_change_any":0}'::jsonb),
 ('Brighton vs Leeds',4,.335,-.637,5,8,10,.092,-.151,-.394,'MEDIUM','{"attack_floor":0.600,"box_floor":0.526,"xgi_floor":1.019,"personnel_change":0.148,"coach_change_any":0}'::jsonb),
 ('Man City vs Coventry City',10,-.344,-.223,10,9,7,-.314,-.284,-.253,'LOW','{"attack_floor":0.600,"box_floor":0.127,"xgi_floor":1.208,"personnel_change":1.000,"coach_change_any":1}'::jsonb),
 ('Brentford vs Sunderland',8,-.277,-.420,9,10,9,-.313,-.348,-.384,'MEDIUM','{"attack_floor":1.015,"box_floor":0.481,"xgi_floor":0.923,"personnel_change":0.104,"coach_change_any":0}'::jsonb)
), resolved as (
 select v.*,m.id match_id from v join public.matches m on m.gameweek=3 and (select ht.name from public.teams ht where ht.id=m.home_team_id)||' vs '||(select at.name from public.teams at where at.id=m.away_team_id)=v.fixture
)
insert into public.research_c0197_regime_shadow_forward_snapshots(run_key,observation_hash,snapshot_as_of,gameweek,match_id,fixture,v02_rank,v02_score,regime_overlay,rank_w25,rank_w50,rank_w75,v03_w25,v03_w50,v03_w75,confidence,features)
select 'C0197_REGIME_SHADOW_20260904_V03',md5(concat_ws('|',match_id,v02_score,overlay,r25,r50,r75)),'2026-09-03T23:46:36.498520Z'::timestamptz,3,match_id,fixture,v02_rank,v02_score,overlay,r25,r50,r75,w25,w50,w75,confidence,features from resolved
on conflict do nothing;

create or replace function private.c0197_regime_shadow_status_v03()
returns jsonb language sql stable set search_path=public,private,pg_temp as $$
select jsonb_build_object(
 'change_id','C0197',
 'run_key',(select run_key from public.research_c0197_regime_shadow_runs order by created_at desc limit 1),
 'decision',(select decision from public.research_c0197_regime_shadow_runs order by created_at desc limit 1),
 'replay_rows',(select count(*) from public.research_c0197_regime_shadow_replay),
 'forward_rows',(select count(*) from public.research_c0197_regime_shadow_forward_snapshots),
 'forward_gameweeks',(select coalesce(jsonb_agg(distinct gameweek),'[]'::jsonb) from public.research_c0197_regime_shadow_forward_snapshots),
 'model_effect_enabled',false
); $$;
revoke all on function private.c0197_regime_shadow_status_v03() from public,anon,authenticated;