-- C0279 P2: bounded two-match acceleration/regime detection (shadow only)
-- Tail and uncertainty evidence only; canonical P1 baseline and production selectors remain unchanged.

CREATE OR REPLACE FUNCTION private.c0279_acceleration_classify_v01(p_current_sample integer, p_recent_match_sample integer, p_baseline_match_sample integer, p_recent_attack_process numeric, p_baseline_attack_process numeric, p_recent_defence_process numeric, p_baseline_defence_process numeric, p_recent_shots_for numeric, p_baseline_shots_for numeric, p_recent_goals_for numeric, p_baseline_goals_for numeric, p_recent_xg_for numeric, p_baseline_xg_for numeric, p_recent_opponent_weakness numeric, p_verified_regime_change boolean DEFAULT false)
 RETURNS TABLE(classification text, confidence numeric, attack_process_uplift numeric, defence_process_uplift numeric, shot_uplift numeric, goal_uplift numeric, finishing_residual_change numeric, weak_opponent_inflation boolean, persistent_process_change boolean, baseline_replacement_allowed boolean, tail_log_adjustment numeric, uncertainty_multiplier numeric, rationale text)
 LANGUAGE sql
 IMMUTABLE
 SET search_path TO ''
AS $function$
with m as (select case when p_baseline_attack_process is null or p_baseline_attack_process=0 then null else p_recent_attack_process/p_baseline_attack_process-1 end au,case when p_recent_defence_process is null or p_recent_defence_process=0 then null else p_baseline_defence_process/p_recent_defence_process-1 end du,case when p_baseline_shots_for is null or p_baseline_shots_for=0 then null else p_recent_shots_for/p_baseline_shots_for-1 end su,case when p_baseline_goals_for is null then null else p_recent_goals_for-p_baseline_goals_for end gu,case when p_recent_goals_for is null or p_recent_xg_for is null or p_baseline_goals_for is null or p_baseline_xg_for is null then null else (p_recent_goals_for-p_recent_xg_for)-(p_baseline_goals_for-p_baseline_xg_for) end fr),
flags as (select *,coalesce(p_recent_opponent_weakness>1.15,false) weak,coalesce((au>=0.18 and su>=0.10) or (au>=0.35 and su>=0.00),false) persistent from m),
label as (select *,case when p_current_sample is null or p_recent_match_sample<2 or p_baseline_match_sample<2 or au is null or du is null or su is null or fr is null then 'INSUFFICIENT_EVIDENCE' when p_verified_regime_change and au>=0.12 and su>=0.08 then 'TACTICAL_REGIME_CHANGE' when weak and au>=0.15 then 'WEAK_OPPONENT_INFLATION' when persistent then 'PROCESS_IMPROVEMENT' when coalesce(gu,0)>=0.75 and au<0.12 and fr>=0.60 then 'FINISHING_ONLY_SPIKE' else 'UNEXPLAINED_NOISE' end cls from flags)
select cls,case cls when 'INSUFFICIENT_EVIDENCE' then 0.00 when 'TACTICAL_REGIME_CHANGE' then least(0.80,0.55+greatest(au,0)*0.35) when 'WEAK_OPPONENT_INFLATION' then least(0.70,0.45+greatest(au,0)*0.25) when 'PROCESS_IMPROVEMENT' then least(0.75,0.50+greatest(au,0)*0.30) when 'FINISHING_ONLY_SPIKE' then least(0.80,0.55+greatest(fr,0)*0.15) else 0.35 end::numeric,au,du,su,gu,fr,weak,persistent,false,case cls when 'TACTICAL_REGIME_CHANGE' then least(0.040,greatest(0.010,au*0.040)) when 'PROCESS_IMPROVEMENT' then least(0.030,greatest(0.005,au*0.030)) when 'WEAK_OPPONENT_INFLATION' then least(0.010,greatest(0.000,au*0.010)) when 'FINISHING_ONLY_SPIKE' then 0.000 else 0.000 end::numeric,case cls when 'INSUFFICIENT_EVIDENCE' then 1.15 when 'TACTICAL_REGIME_CHANGE' then 1.10 when 'PROCESS_IMPROVEMENT' then 1.06 when 'WEAK_OPPONENT_INFLATION' then 1.12 when 'FINISHING_ONLY_SPIKE' then 1.15 else 1.10 end::numeric,case cls when 'INSUFFICIENT_EVIDENCE' then 'Fewer than two recent and two earlier current-season matches, or required process evidence is missing.' when 'TACTICAL_REGIME_CHANGE' then 'Verified tactical/personnel change coincides with persistent opponent-adjusted xG and shot improvement.' when 'WEAK_OPPONENT_INFLATION' then 'Recent process improved, but the recent opponent set was materially weaker; uplift is heavily damped.' when 'PROCESS_IMPROVEMENT' then 'Opponent-adjusted xG improved materially with non-declining shot volume; stronger confirmation applies when shot volume also rises by at least 10%.' when 'FINISHING_ONLY_SPIKE' then 'Goals rose without matching xG and shot-process improvement; treat as finishing variance.' else 'The two-match movement is mixed or below the persistence thresholds.' end from label;
$function$
;

CREATE OR REPLACE FUNCTION private.c0279_team_acceleration_asof_v01(p_team_id bigint, p_target_kickoff timestamp with time zone, p_season_start integer DEFAULT NULL::integer)
 RETURNS TABLE(contract_version text, team_id bigint, target_kickoff timestamp with time zone, season_start integer, current_season_sample integer, recent_match_sample integer, baseline_match_sample integer, recent_attack_process numeric, baseline_attack_process numeric, recent_defence_process numeric, baseline_defence_process numeric, recent_xg_for numeric, baseline_xg_for numeric, recent_goals_for numeric, baseline_goals_for numeric, recent_shots_for numeric, baseline_shots_for numeric, recent_opponent_weakness numeric, verified_regime_change boolean, regime_evidence_available boolean, classification text, confidence numeric, attack_process_uplift numeric, defence_process_uplift numeric, shot_uplift numeric, goal_uplift numeric, finishing_residual_change numeric, weak_opponent_inflation boolean, persistent_process_change boolean, baseline_replacement_allowed boolean, tail_log_adjustment numeric, uncertainty_multiplier numeric, chronology_valid boolean, lineage jsonb, evidence_hash text)
 LANGUAGE sql
 STABLE
 SET search_path TO ''
AS $function$
with season as (select coalesce(p_season_start,case when extract(month from p_target_kickoff)>=7 then extract(year from p_target_kickoff)::int else extract(year from p_target_kickoff)::int-1 end) sy),
hist0 as (select h.*,row_number() over(order by h.fixture_kickoff desc) rn from private.c0162_canonical_team_epl_matches_v01 h,season s where h.team_id=p_team_id and h.fixture_kickoff<p_target_kickoff and (case when extract(month from h.fixture_kickoff)>=7 then extract(year from h.fixture_kickoff)::int else extract(year from h.fixture_kickoff)::int-1 end)=s.sy),
hist as (select h.*,os.blended_xg_against_90 opponent_defence,os.blended_xg_for_90 opponent_attack from hist0 h left join lateral private.c0279_team_season_state_asof_v01(h.opponent_team_id,p_target_kickoff,(select sy from season)) os on h.opponent_team_id is not null),
league as (select avg(s.blended_xg_against_90) avg_xga from (select distinct opponent_team_id from hist where opponent_team_id is not null) o cross join lateral private.c0279_team_season_state_asof_v01(o.opponent_team_id,p_target_kickoff,(select sy from season)) s),
agg as (select count(*)::int current_n,count(*) filter(where rn<=2)::int recent_n,count(*) filter(where rn>2)::int base_n,avg(xg_for/nullif(opponent_defence,0)) filter(where rn<=2) recent_attack,avg(xg_for/nullif(opponent_defence,0)) filter(where rn>2) base_attack,avg(xg_against/nullif(opponent_attack,0)) filter(where rn<=2) recent_defence,avg(xg_against/nullif(opponent_attack,0)) filter(where rn>2) base_defence,avg(xg_for) filter(where rn<=2) recent_xg,avg(xg_for) filter(where rn>2) base_xg,avg(goals_for) filter(where rn<=2) recent_goals,avg(goals_for) filter(where rn>2) base_goals,avg(shots_for) filter(where rn<=2) recent_shots,avg(shots_for) filter(where rn>2) base_shots,(avg(opponent_defence) filter(where rn<=2))/(select avg_xga from league) recent_weakness,max(fixture_kickoff) latest_match,jsonb_agg(jsonb_build_object('kickoff',fixture_kickoff,'opponent_team_id',opponent_team_id,'rn',rn,'xg_for',xg_for,'xg_against',xg_against,'goals_for',goals_for,'shots_for',shots_for,'opponent_defence',opponent_defence,'opponent_attack',opponent_attack) order by fixture_kickoff desc) evidence from hist),
classified as (select a.*,c.* from agg a cross join lateral private.c0279_acceleration_classify_v01(a.current_n,a.recent_n,a.base_n,a.recent_attack,a.base_attack,a.recent_defence,a.base_defence,a.recent_shots,a.base_shots,a.recent_goals,a.base_goals,a.recent_xg,a.base_xg,a.recent_weakness,false) c)
select 'c0279_acceleration_v01',p_team_id,p_target_kickoff,(select sy from season),current_n,recent_n,base_n,recent_attack,base_attack,recent_defence,base_defence,recent_xg,base_xg,recent_goals,base_goals,recent_shots,base_shots,recent_weakness,false,false,classification,confidence,attack_process_uplift,defence_process_uplift,shot_uplift,goal_uplift,finishing_residual_change,weak_opponent_inflation,persistent_process_change,baseline_replacement_allowed,tail_log_adjustment,uncertainty_multiplier,coalesce(latest_match<p_target_kickoff,false),jsonb_build_object('contract_version','c0279_acceleration_v01','source_relation','private.c0162_canonical_team_epl_matches_v01','season_state_contract','c0279_season_state_v01','matches',evidence,'regime_evidence_available',false,'baseline_replacement_allowed',false,'tail_only',true,'shadow_only',true,'production_effect',false,'missing_is_not_zero',true),encode(extensions.digest(concat_ws('|','c0279_acceleration_v01',p_team_id,p_target_kickoff,(select sy from season),current_n,recent_n,base_n,coalesce(recent_attack::text,'UNKNOWN'),coalesce(base_attack::text,'UNKNOWN'),classification,confidence,tail_log_adjustment),'sha256'),'hex') from classified;
$function$
;

revoke execute on function private.c0279_acceleration_classify_v01(integer,integer,integer,numeric,numeric,numeric,numeric,numeric,numeric,numeric,numeric,numeric,numeric,numeric,boolean) from public,anon,authenticated;
revoke execute on function private.c0279_team_acceleration_asof_v01(bigint,timestamptz,integer) from public,anon,authenticated;

comment on function private.c0279_acceleration_classify_v01(integer,integer,integer,numeric,numeric,numeric,numeric,numeric,numeric,numeric,numeric,numeric,numeric,numeric,boolean)
is 'C0279 P2 bounded acceleration classifier. Tail/uncertainty only; never replaces canonical baseline.';
comment on function private.c0279_team_acceleration_asof_v01(bigint,timestamptz,integer)
is 'C0279 P2 chronology-safe two-match acceleration/regime shadow derived from the P1 season-state contract.';
