create table if not exists public.player_fixture_availability_observations (
  id bigint generated by default as identity primary key,
  match_id bigint not null references public.matches(id),
  gameweek integer not null,
  team_id bigint not null references public.teams(id),
  opponent_team_id bigint not null references public.teams(id),
  player_id bigint not null references public.players(id),
  kickoff_time timestamptz not null,
  captured_at timestamptz not null default now(),
  source text not null default 'official_fpl',
  source_updated_at timestamptz,
  fpl_status_code text,
  availability_status text not null check (availability_status in ('AVAILABLE','DOUBTFUL','INJURED','SUSPENDED','UNAVAILABLE','UNKNOWN')),
  chance_of_playing numeric check (chance_of_playing is null or (chance_of_playing >= 0 and chance_of_playing <= 1)),
  news text,
  player_state_as_of timestamptz,
  base_start_probability numeric check (base_start_probability is null or (base_start_probability >= 0 and base_start_probability <= 1)),
  base_expected_minutes numeric check (base_expected_minutes is null or base_expected_minutes >= 0),
  xi_score numeric check (xi_score is null or xi_score >= 0),
  expected_xi boolean not null default false,
  expected_xi_formation text,
  xi_rank_within_position integer,
  confidence numeric check (confidence is null or (confidence >= 0 and confidence <= 1)),
  observation_hash text not null,
  evidence jsonb not null default '{}'::jsonb,
  model_effect_enabled boolean not null default false,
  constraint player_fixture_availability_obs_unique unique (match_id, player_id, observation_hash),
  constraint player_fixture_availability_preko_check check (captured_at < kickoff_time),
  constraint player_fixture_availability_model_effect_check check (model_effect_enabled = false)
);

create index if not exists idx_pfao_match_capture on public.player_fixture_availability_observations(match_id,captured_at desc);
create index if not exists idx_pfao_player_capture on public.player_fixture_availability_observations(player_id,captured_at desc);
create index if not exists idx_pfao_team_match on public.player_fixture_availability_observations(team_id,match_id,captured_at desc);

alter table public.player_fixture_availability_observations enable row level security;
revoke all on public.player_fixture_availability_observations from anon, authenticated;
revoke update, delete, truncate on public.player_fixture_availability_observations from service_role;
grant select, insert on public.player_fixture_availability_observations to service_role;
grant usage, select on sequence public.player_fixture_availability_observations_id_seq to service_role;

create or replace function private.guard_player_fixture_availability_preko()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  v_kickoff timestamptz;
  v_home bigint;
  v_away bigint;
begin
  select m.kickoff_time,m.home_team_id,m.away_team_id into v_kickoff,v_home,v_away
  from public.matches m where m.id=new.match_id;
  if v_kickoff is null then raise exception 'Unknown match or kickoff'; end if;
  if clock_timestamp() >= v_kickoff then raise exception 'Fixture availability is frozen at kickoff'; end if;
  if new.kickoff_time <> v_kickoff then raise exception 'Kickoff mismatch'; end if;
  if new.team_id not in (v_home,v_away) or new.opponent_team_id not in (v_home,v_away) or new.team_id=new.opponent_team_id then
    raise exception 'Team/opponent mismatch for fixture';
  end if;
  if new.captured_at >= v_kickoff then raise exception 'Post-kickoff capture rejected'; end if;
  return new;
end;
$$;

revoke all on function private.guard_player_fixture_availability_preko() from public, anon, authenticated;

drop trigger if exists trg_guard_player_fixture_availability_preko on public.player_fixture_availability_observations;
create trigger trg_guard_player_fixture_availability_preko
before insert on public.player_fixture_availability_observations
for each row execute function private.guard_player_fixture_availability_preko();

create or replace view public.current_player_fixture_availability
with (security_invoker=true)
as
select distinct on (match_id,player_id)
  id,match_id,gameweek,team_id,opponent_team_id,player_id,kickoff_time,captured_at,source,source_updated_at,
  fpl_status_code,availability_status,chance_of_playing,news,player_state_as_of,base_start_probability,
  base_expected_minutes,xi_score,expected_xi,expected_xi_formation,xi_rank_within_position,confidence,
  evidence,model_effect_enabled
from public.player_fixture_availability_observations
order by match_id,player_id,captured_at desc,id desc;

revoke all on public.current_player_fixture_availability from anon, authenticated;
grant select on public.current_player_fixture_availability to service_role;

create or replace function public.refresh_current_season_team_intelligence()
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_rows integer := 0;
begin
  with src as (
    select m.id as match_id,m.fpl_fixture_id,m.gameweek,m.kickoff_time,m.home_team_id,m.away_team_id,m.home_score,m.away_score,m.updated_at,m.competition
    from public.matches m
    where m.source='fpl' and m.gameweek >= 1 and m.finished=true and m.kickoff_time < now()
      and m.home_team_id is not null and m.away_team_id is not null
      and m.home_score is not null and m.away_score is not null
  ), rows_to_insert as (
    select home_team_id team_id, match_id, kickoff_time, 'official_fpl_results'::text source,
           fpl_fixture_id::text source_match_id, 'home'::text venue,
           home_score::numeric goals_for, away_score::numeric goals_against,
           null::numeric xg_for, null::numeric xg_against, null::numeric shots_for, null::numeric shots_against,
           null::numeric big_chances_for, null::numeric big_chances_against,
           coalesce(competition,'Premier League') competition,
           jsonb_build_object('gameweek',gameweek,'fpl_fixture_id',fpl_fixture_id,'result_updated_at',updated_at,'evidence_scope','final_score_only','xg_missing_not_zero',true) raw
    from src
    union all
    select away_team_id, match_id, kickoff_time, 'official_fpl_results', fpl_fixture_id::text, 'away',
           away_score::numeric, home_score::numeric,
           null::numeric, null::numeric, null::numeric, null::numeric, null::numeric, null::numeric,
           coalesce(competition,'Premier League'),
           jsonb_build_object('gameweek',gameweek,'fpl_fixture_id',fpl_fixture_id,'result_updated_at',updated_at,'evidence_scope','final_score_only','xg_missing_not_zero',true)
    from src
  )
  insert into public.team_match_intelligence(team_id,match_id,fixture_kickoff,captured_at,source,source_match_id,venue,goals_for,goals_against,xg_for,xg_against,shots_for,shots_against,big_chances_for,big_chances_against,competition,raw)
  select team_id,match_id,kickoff_time,now(),source,source_match_id,venue,goals_for,goals_against,xg_for,xg_against,shots_for,shots_against,big_chances_for,big_chances_against,competition,raw
  from rows_to_insert
  on conflict (source,source_match_id,team_id) do nothing;
  get diagnostics v_rows = row_count;
  return v_rows;
end;
$$;

revoke all on function public.refresh_current_season_team_intelligence() from public, anon, authenticated;
grant execute on function public.refresh_current_season_team_intelligence() to service_role;

create or replace function private.invoke_engine_ingest(p_function text, p_body jsonb default '{}'::jsonb)
returns bigint
language plpgsql
security definer
set search_path to 'private','public','vault','net','pg_temp'
as $$
declare
  v_token text;
  v_url text;
  v_request_id bigint;
begin
  if p_function not in ('ingest-team-history','ingest-understat-xg','ingest-bookmaker-odds','refresh-availability-intelligence') then
    raise exception 'Function not allowed';
  end if;
  select decrypted_secret into v_token from vault.decrypted_secrets where name='FOOTBALL_ENGINE_ADMIN_TOKEN' order by created_at desc limit 1;
  if v_token is null then raise exception 'Engine admin token missing'; end if;
  v_url := 'https://knooiwezzsxcwhtjtdap.supabase.co/functions/v1/' || p_function;
  select net.http_post(url:=v_url,body:=coalesce(p_body,'{}'::jsonb),headers:=jsonb_build_object('Content-Type','application/json','x-engine-token',v_token),timeout_milliseconds:=60000) into v_request_id;
  return v_request_id;
end;
$$;
revoke all on function private.invoke_engine_ingest(text,jsonb) from public, anon, authenticated;
grant execute on function private.invoke_engine_ingest(text,jsonb) to service_role;
