create table public.research_c0197_esot_chaos_runs (
  run_key text primary key,
  change_id text not null default 'C0197' check (change_id='C0197'),
  experiment_name text not null,
  definition jsonb not null,
  selected_window text,
  selected_direction text,
  selected_scale numeric,
  decision text not null,
  conclusion text not null,
  research_only boolean not null default true check (research_only),
  model_effect_enabled boolean not null default false check (not model_effect_enabled),
  created_at timestamptz not null default clock_timestamp()
);
alter table public.research_c0197_esot_chaos_runs enable row level security;
revoke all on public.research_c0197_esot_chaos_runs from public, anon, authenticated;

create table public.research_c0197_esot_process_sensitivity (
  id bigint generated by default as identity primary key,
  run_key text not null references public.research_c0197_esot_chaos_runs(run_key),
  split text not null,
  window_key text not null,
  n integer not null,
  corr_next_sot_residual numeric,
  corr_total_goals numeric,
  positive_signal_next_residual numeric,
  nonpositive_signal_next_residual numeric,
  positive_signal_goals numeric,
  nonpositive_signal_goals numeric,
  research_only boolean not null default true check (research_only),
  model_effect_enabled boolean not null default false check (not model_effect_enabled),
  created_at timestamptz not null default clock_timestamp(),
  unique(run_key,split,window_key)
);
alter table public.research_c0197_esot_process_sensitivity enable row level security;
revoke all on public.research_c0197_esot_process_sensitivity from public, anon, authenticated;

create table public.research_c0197_esot_chaos_grid_results (
  id bigint generated by default as identity primary key,
  run_key text not null references public.research_c0197_esot_chaos_runs(run_key),
  split text not null,
  window_key text not null,
  direction text not null,
  scale numeric not null,
  n integer not null,
  total_goal_logloss numeric not null,
  research_only boolean not null default true check (research_only),
  model_effect_enabled boolean not null default false check (not model_effect_enabled),
  created_at timestamptz not null default clock_timestamp(),
  unique(run_key,split,window_key,direction,scale)
);
alter table public.research_c0197_esot_chaos_grid_results enable row level security;
revoke all on public.research_c0197_esot_chaos_grid_results from public, anon, authenticated;

create table public.research_c0197_esot_tail_evaluations (
  id bigint generated by default as identity primary key,
  run_key text not null references public.research_c0197_esot_chaos_runs(run_key),
  split text not null,
  window_key text not null,
  direction text not null,
  scale numeric not null,
  threshold integer not null check (threshold between 4 and 7),
  n integer not null,
  actual_rate numeric not null,
  baseline_probability numeric not null,
  candidate_probability numeric not null,
  brier_delta numeric not null,
  logloss_delta numeric not null,
  research_only boolean not null default true check (research_only),
  model_effect_enabled boolean not null default false check (not model_effect_enabled),
  created_at timestamptz not null default clock_timestamp(),
  unique(run_key,split,window_key,direction,scale,threshold)
);
alter table public.research_c0197_esot_tail_evaluations enable row level security;
revoke all on public.research_c0197_esot_tail_evaluations from public, anon, authenticated;

create table public.research_c0197_esot_external_checks (
  id bigint generated by default as identity primary key,
  run_key text not null references public.research_c0197_esot_chaos_runs(run_key),
  season text not null,
  gameweek integer not null,
  eligible_matches integer not null,
  corr_next_sot_residual numeric,
  corr_total_goals numeric,
  positive_signal_next_residual numeric,
  nonpositive_signal_next_residual numeric,
  note text not null,
  research_only boolean not null default true check (research_only),
  model_effect_enabled boolean not null default false check (not model_effect_enabled),
  created_at timestamptz not null default clock_timestamp(),
  unique(run_key,season,gameweek)
);
alter table public.research_c0197_esot_external_checks enable row level security;
revoke all on public.research_c0197_esot_external_checks from public, anon, authenticated;

create trigger research_c0197_esot_chaos_runs_append_only before update or delete on public.research_c0197_esot_chaos_runs for each row execute function private.block_c0197_research_mutation_v01();
create trigger research_c0197_esot_process_sensitivity_append_only before update or delete on public.research_c0197_esot_process_sensitivity for each row execute function private.block_c0197_research_mutation_v01();
create trigger research_c0197_esot_chaos_grid_results_append_only before update or delete on public.research_c0197_esot_chaos_grid_results for each row execute function private.block_c0197_research_mutation_v01();
create trigger research_c0197_esot_tail_evaluations_append_only before update or delete on public.research_c0197_esot_tail_evaluations for each row execute function private.block_c0197_research_mutation_v01();
create trigger research_c0197_esot_external_checks_append_only before update or delete on public.research_c0197_esot_external_checks for each row execute function private.block_c0197_research_mutation_v01();

revoke all on sequence public.research_c0197_esot_process_sensitivity_id_seq from public, anon, authenticated;
revoke all on sequence public.research_c0197_esot_chaos_grid_results_id_seq from public, anon, authenticated;
revoke all on sequence public.research_c0197_esot_tail_evaluations_id_seq from public, anon, authenticated;
revoke all on sequence public.research_c0197_esot_external_checks_id_seq from public, anon, authenticated;

create or replace function private.c0197_esot_chaos_status_v01()
returns jsonb language sql stable set search_path=public,private,pg_temp as $$
select jsonb_build_object(
 'change_id','C0197',
 'runs',(select count(*) from public.research_c0197_esot_chaos_runs),
 'latest_run',(select run_key from public.research_c0197_esot_chaos_runs order by created_at desc limit 1),
 'decision',(select decision from public.research_c0197_esot_chaos_runs order by created_at desc limit 1),
 'selected_window',(select selected_window from public.research_c0197_esot_chaos_runs order by created_at desc limit 1),
 'selected_scale',(select selected_scale from public.research_c0197_esot_chaos_runs order by created_at desc limit 1),
 'process_rows',(select count(*) from public.research_c0197_esot_process_sensitivity),
 'grid_rows',(select count(*) from public.research_c0197_esot_chaos_grid_results),
 'tail_rows',(select count(*) from public.research_c0197_esot_tail_evaluations),
 'external_rows',(select count(*) from public.research_c0197_esot_external_checks),
 'model_effect_enabled',false
);
$$;
revoke all on function private.c0197_esot_chaos_status_v01() from public, anon, authenticated;
