create table if not exists public.fotmob_player_identity_observations (
  id bigint generated by default as identity primary key,
  change_id text not null default 'C0212',
  source_fotmob_player_id bigint not null,
  player_id bigint not null references public.players(id),
  mapping_method text not null,
  confidence numeric not null check (confidence between 0 and 1),
  evidence jsonb not null default '{}'::jsonb,
  observed_at timestamptz not null default now(),
  observation_hash text not null unique
);
create index if not exists fotmob_player_identity_source_idx on public.fotmob_player_identity_observations(source_fotmob_player_id, observed_at desc, id desc);
alter table public.fotmob_player_identity_observations enable row level security;
revoke all on public.fotmob_player_identity_observations from anon, authenticated;
grant select, insert on public.fotmob_player_identity_observations to service_role;
grant usage, select on sequence public.fotmob_player_identity_observations_id_seq to service_role;

drop trigger if exists trg_c0212_fotmob_identity_append_only on public.fotmob_player_identity_observations;
create trigger trg_c0212_fotmob_identity_append_only
before update or delete on public.fotmob_player_identity_observations
for each row execute function private.block_c0212_realized_role_mutation();

insert into public.fotmob_player_identity_observations(change_id,source_fotmob_player_id,player_id,mapping_method,confidence,evidence,observation_hash)
select 'C0212',x.source_fotmob_player_id,x.player_id,'SEEDED_FROM_UNIQUE_REALIZED_ROLE_MAPPING',0.99,
       jsonb_build_object('source','realized_player_role_observations','mapping_status',x.mapping_status),
       md5('C0212|seed|'||x.source_fotmob_player_id::text||'|'||x.player_id::text)
from (
  select distinct on (source_fotmob_player_id) source_fotmob_player_id,player_id,mapping_status
  from public.realized_player_role_observations
  where player_id is not null
  order by source_fotmob_player_id,kickoff_time desc,id desc
) x
on conflict (observation_hash) do nothing;

insert into public.fotmob_player_identity_observations(change_id,source_fotmob_player_id,player_id,mapping_method,confidence,evidence,observation_hash)
values
('C0212',562727,1,'VERIFIED_FULL_NAME_VARIANT',1.0,'{"name":"David Raya"}'::jsonb,md5('C0212|manual|562727|1')),
('C0212',610184,41,'VERIFIED_FULL_NAME_VARIANT',1.0,'{"name":"Emiliano Buendía"}'::jsonb,md5('C0212|manual|610184|41')),
('C0212',1292092,84,'VERIFIED_FULL_NAME_VARIANT',1.0,'{"name":"António Silva"}'::jsonb,md5('C0212|manual|1292092|84')),
('C0212',1067256,59,'VERIFIED_TRANSLITERATED_NAME',1.0,'{"name":"Djordje Petrovic"}'::jsonb,md5('C0212|manual|1067256|59')),
('C0212',1302005,108,'VERIFIED_COMMON_NAME',1.0,'{"name":"Igor Thiago"}'::jsonb,md5('C0212|manual|1302005|108')),
('C0212',1354561,128,'VERIFIED_FULL_NAME_VARIANT',1.0,'{"name":"Diego Gómez"}'::jsonb,md5('C0212|manual|1354561|128')),
('C0212',1096400,156,'VERIFIED_FULL_NAME_VARIANT',1.0,'{"name":"Levi Colwill"}'::jsonb,md5('C0212|manual|1096400|156')),
('C0212',789571,147,'VERIFIED_FULL_NAME_VARIANT',1.0,'{"name":"Robert Sánchez"}'::jsonb,md5('C0212|manual|789571|147')),
('C0212',859282,218,'VERIFIED_FULL_NAME_AND_HISTORICAL_CLUB',1.0,'{"name":"Daniel Muñoz"}'::jsonb,md5('C0212|manual|859282|218')),
('C0212',821728,276,'VERIFIED_FULL_NAME_VARIANT',1.0,'{"name":"Jorge Cuenca"}'::jsonb,md5('C0212|manual|821728|276')),
('C0212',614006,429,'VERIFIED_FULL_NAME_VARIANT',1.0,'{"name":"Rúben Dias"}'::jsonb,md5('C0212|manual|614006|429')),
('C0212',422685,470,'VERIFIED_FULL_NAME_VARIANT',1.0,'{"name":"Bruno Fernandes"}'::jsonb,md5('C0212|manual|422685|470')),
('C0212',863098,472,'VERIFIED_FULL_NAME_VARIANT',1.0,'{"name":"Matheus Cunha"}'::jsonb,md5('C0212|manual|863098|472')),
('C0212',785411,546,'VERIFIED_FULL_NAME_VARIANT',1.0,'{"name":"Marcos Senesi"}'::jsonb,md5('C0212|manual|785411|546')),
('C0212',774448,114,'VERIFIED_TRANSLITERATED_NAME',1.0,'{"name":"Ferdi Kadioglu"}'::jsonb,md5('C0212|manual|774448|114')),
('C0212',268375,30,'VERIFIED_FULL_NAME_AND_CURRENT_IDENTITY',1.0,'{"name":"Emiliano Martínez"}'::jsonb,md5('C0212|manual|268375|30')),
('C0212',843040,163,'VERIFIED_FULL_NAME_VARIANT',1.0,'{"name":"Pedro Neto"}'::jsonb,md5('C0212|manual|843040|163')),
('C0212',1047676,227,'VERIFIED_TRANSLITERATED_NAME',1.0,'{"name":"Yéremi Pino"}'::jsonb,md5('C0212|manual|1047676|227')),
('C0212',751550,461,'VERIFIED_FULL_NAME_VARIANT',1.0,'{"name":"Diogo Dalot"}'::jsonb,md5('C0212|manual|751550|461')),
('C0212',1280132,444,'VERIFIED_FULL_NAME_VARIANT',1.0,'{"name":"Nico González"}'::jsonb,md5('C0212|manual|1280132|444')),
('C0212',935728,381,'VERIFIED_NAME_ORDER_VARIANT',1.0,'{"name":"Ao Tanaka"}'::jsonb,md5('C0212|manual|935728|381'))
on conflict (observation_hash) do nothing;

create or replace view public.current_fotmob_player_identities
with (security_invoker = true)
as
select distinct on (source_fotmob_player_id)
  source_fotmob_player_id,player_id,mapping_method,confidence,evidence,observed_at,observation_hash
from public.fotmob_player_identity_observations
order by source_fotmob_player_id,observed_at desc,id desc;
revoke all on public.current_fotmob_player_identities from anon, authenticated;
grant select on public.current_fotmob_player_identities to service_role;

create or replace view public.current_realized_player_roles
with (security_invoker = true)
as
with resolved as (
  select r.*,
         coalesce(r.player_id,i.player_id) as resolved_player_id,
         case when r.player_id is not null then r.mapping_status else i.mapping_method end as resolved_mapping_method
  from public.realized_player_role_observations r
  left join public.current_fotmob_player_identities i on i.source_fotmob_player_id=r.source_fotmob_player_id
), ranked as (
  select r.*,
         row_number() over(partition by r.resolved_player_id order by r.kickoff_time desc, r.id desc) as rn
  from resolved r
  where r.resolved_player_id is not null
    and r.is_starting
    and r.realized_role is not null
    and r.production_role_enabled
), recent as (
  select * from ranked where rn <= 3
), latest as (
  select * from ranked where rn = 1
), agg as (
  select resolved_player_id,
         count(*)::integer as recent_role_samples,
         count(*) filter(where realized_role = (select l.realized_role from latest l where l.resolved_player_id=recent.resolved_player_id))::integer as latest_role_matches_l3
  from recent
  group by resolved_player_id
)
select l.resolved_player_id as player_id,
       l.realized_role as current_role,
       l.realized_role as latest_realized_role,
       l.tactical_band as latest_tactical_band,
       l.width_band as latest_width_band,
       l.formation as latest_formation,
       l.role_confidence as latest_role_confidence,
       a.recent_role_samples,
       a.latest_role_matches_l3,
       case when a.recent_role_samples > 0 then a.latest_role_matches_l3::numeric/a.recent_role_samples else null end as role_stability,
       l.kickoff_time as latest_role_match_kickoff,
       l.evidence_cutoff as latest_known_at,
       l.observation_hash as latest_observation_hash,
       l.source_key,
       l.source_url,
       l.source_fotmob_player_id,
       coalesce(l.fpl_position,p.position) as fpl_position,
       l.usual_playing_position_id,
       l.resolved_mapping_method as mapping_method
from latest l
join agg a using(resolved_player_id)
join public.players p on p.id=l.resolved_player_id;

revoke all on public.current_realized_player_roles from anon, authenticated;
grant select on public.current_realized_player_roles to service_role;
