create table if not exists private.c0213_manager_plan_write_blocks(
  id bigint generated by default as identity primary key,
  attempted_at timestamptz not null default clock_timestamp(),
  gameweek integer not null,
  status text,
  source text,
  readiness jsonb not null,
  reason text not null default 'MANAGER_PLAN_READINESS_BLOCKED'
);
revoke all on table private.c0213_manager_plan_write_blocks from public,anon,authenticated;
grant select,insert on table private.c0213_manager_plan_write_blocks to service_role;
grant usage,select on sequence private.c0213_manager_plan_write_blocks_id_seq to service_role;

create or replace function private.c0213_p2_current_lineage_v03(p_gameweek integer default null)
returns jsonb
language plpgsql
security definer
set search_path='private','public','pg_temp'
as $$
declare
  v jsonb; v_gw integer; v_projection_ready boolean; v_decision_ready boolean;
  v_result_ready boolean:=false; v_role_ready boolean:=false; v_evidence_ready boolean:=false;
  v_opt jsonb; v_manager jsonb; v_manager_ready boolean:=false; v_optimizer_ready boolean:=false;
  v_lineage jsonb; v_blockers jsonb; v_plan_exists boolean:=false;
begin
  v:=private.c0213_p2_current_lineage_v02(p_gameweek);
  if not coalesce((v->>'ok')::boolean,false) then return v; end if;
  v_gw:=(v->>'gameweek')::integer;
  v_projection_ready:=coalesce((v->>'projection_ready')::boolean,false);
  v_opt:=private.c0213_p2_optimizer_status_v01(v_gw,3);
  v_manager:=coalesce(v_opt#>'{readiness,manager_state}','{}'::jsonb);
  v_manager_ready:=coalesce((v_manager->>'ready')::boolean,false);
  v_optimizer_ready:=coalesce((v_opt->>'ready')::boolean,false);

  select exists(select 1 from jsonb_array_elements(v->'lineage') x where x->>'stage'='RESULTS' and x->>'state'='READY') into v_result_ready;
  select exists(select 1 from jsonb_array_elements(v->'lineage') x where x->>'stage'='REALIZED_ROLES' and x->>'state'='READY') into v_role_ready;
  select exists(select 1 from jsonb_array_elements(v->'lineage') x where x->>'stage'='DECISION_READINESS' and x->>'state'='READY') into v_evidence_ready;
  select exists(select 1 from public.fpl_manager_plans where gameweek=v_gw) into v_plan_exists;

  v_decision_ready:=v_projection_ready and v_result_ready and v_role_ready and v_evidence_ready and v_manager_ready and v_optimizer_ready;

  with rows as (
    select case
      when x->>'stage'='FULL_POOL_OPTIMIZER' then
        jsonb_build_object(
          'stage_order',100,'stage','FULL_POOL_OPTIMIZER',
          'state',case when v_optimizer_ready then 'READY' else coalesce(v_opt->>'status','NOT_READY') end,
          'optimizer_run_id',nullif(v_opt->>'optimizer_run_id','')::bigint,
          'request_id',nullif(v_opt->>'request_id','')::bigint,
          'input_signature',v_opt->>'input_signature',
          'horizon',3,
          'edge_classification',v_opt->>'edge_classification',
          'objective_gap_to_second',v_opt->'objective_gap_to_second',
          'required_for_projection',false,'required_for_decision',true
        )
      when x->>'stage'='SAVED_MANAGER_PLAN' then
        x || jsonb_build_object('state',case when v_plan_exists then 'READY' when v_decision_ready then 'MISSING_REQUIRED_OUTPUT' else 'NOT_YET_ALLOWED' end)
      else x end as row
    from jsonb_array_elements(v->'lineage') x
    union all
    select jsonb_build_object(
      'stage_order',95,'stage','MANAGER_STATE','state',case when v_manager_ready then 'READY' else 'NOT_CAPTURED' end,
      'manager_state_id',nullif(v_manager->>'id','')::bigint,'captured_at',v_manager->>'captured_at',
      'free_transfers',nullif(v_manager->>'free_transfers','')::integer,'bank_tenths',nullif(v_manager->>'bank_tenths','')::integer,
      'acquisition_squad_cost_tenths',nullif(v_manager->>'acquisition_squad_cost_tenths','')::integer,
      'required_for_projection',false,'required_for_decision',true
    )
  )
  select coalesce(jsonb_agg(row order by (row->>'stage_order')::integer),'[]'::jsonb) into v_lineage from rows;

  select coalesce(jsonb_agg(b),'[]'::jsonb) into v_blockers
  from jsonb_array_elements(v->'blockers') b
  where b->>'code' not in ('OPTIMIZER_HORIZON_LT_3','OPTIMIZER_NOT_RUN','OPTIMIZER_NOT_CURRENT','MANAGER_PLAN_MISSING_AFTER_READINESS');

  if not v_manager_ready then
    v_blockers:=v_blockers||jsonb_build_array(jsonb_build_object('stage','MANAGER_STATE','code','MANAGER_STATE_NOT_READY','gameweek',v_gw));
  end if;
  if not v_optimizer_ready then
    v_blockers:=v_blockers||jsonb_build_array(jsonb_build_object('stage','FULL_POOL_OPTIMIZER','code','FULL_POOL_OPTIMIZER_NOT_CURRENT','status',v_opt->>'status','horizon',3));
  end if;
  if v_decision_ready and not v_plan_exists then
    v_blockers:=v_blockers||jsonb_build_array(jsonb_build_object('stage','SAVED_MANAGER_PLAN','code','MANAGER_PLAN_MISSING_AFTER_READINESS'));
  end if;

  return (v - 'lineage' - 'blockers' - 'decision_ready' - 'contract_version') || jsonb_build_object(
    'lineage',v_lineage,'blockers',v_blockers,'decision_ready',v_decision_ready,
    'contract_version','C0213_P2_V03','manager_state_ready',v_manager_ready,'optimizer_ready',v_optimizer_ready,
    'optimizer_status',v_opt,'manager_plan_exists',v_plan_exists
  );
end $$;
revoke all on function private.c0213_p2_current_lineage_v03(integer) from public,anon,authenticated;
grant execute on function private.c0213_p2_current_lineage_v03(integer) to service_role;

create or replace function private.capture_c0213_p2_lineage_v01(p_gameweek integer default null)
returns jsonb
language plpgsql
security definer
set search_path='private','public','pg_temp'
as $$
declare v jsonb; v_id bigint;
begin
  v:=private.c0213_p2_current_lineage_v03(p_gameweek);
  if not coalesce((v->>'ok')::boolean,false) then return v; end if;
  insert into private.c0213_p2_lineage_snapshots(gameweek,projection_ready,decision_ready,lineage,blockers,source_manifest)
  values((v->>'gameweek')::integer,(v->>'projection_ready')::boolean,(v->>'decision_ready')::boolean,v->'lineage',v->'blockers',jsonb_build_object('contract_version',v->>'contract_version','captured_at',v->>'captured_at'))
  returning id into v_id;
  return v||jsonb_build_object('lineage_snapshot_id',v_id,'status','CAPTURED');
end $$;
revoke all on function private.capture_c0213_p2_lineage_v01(integer) from public,anon,authenticated;
grant execute on function private.capture_c0213_p2_lineage_v01(integer) to service_role;

create or replace function private.c0213_guard_manager_plan_insert_v01()
returns trigger
language plpgsql
security definer
set search_path='private','public','pg_temp'
as $$
declare v_deadline timestamptz; v_ready jsonb;
begin
  select min(kickoff_time)-interval '90 minutes' into v_deadline from public.matches where source='fpl' and gameweek=new.gameweek;
  if v_deadline is not null and v_deadline>clock_timestamp() then
    v_ready:=private.c0213_p2_current_lineage_v03(new.gameweek);
    if not coalesce((v_ready->>'decision_ready')::boolean,false) then
      insert into private.c0213_manager_plan_write_blocks(gameweek,status,source,readiness)
      values(new.gameweek,new.status,new.source,v_ready);
      return null;
    end if;
  end if;
  return new;
end $$;
revoke all on function private.c0213_guard_manager_plan_insert_v01() from public,anon,authenticated;
drop trigger if exists trg_c0213_guard_manager_plan_insert on public.fpl_manager_plans;
create trigger trg_c0213_guard_manager_plan_insert before insert on public.fpl_manager_plans for each row execute function private.c0213_guard_manager_plan_insert_v01();

create or replace function public.engine_diagnostics_status_v01(p_gameweek integer)
returns jsonb
language sql
security definer
set search_path='public','private','pg_temp'
as $$
  select jsonb_build_object(
    'governance', private.audit_change_tracker_governance_v01(),
    'decision_evidence_audit', private.c0167_decision_evidence_audit_v01(p_gameweek),
    'production_evidence_audit', private.c0166_production_evidence_audit_v01(p_gameweek),
    'p2_lineage', private.c0213_p2_current_lineage_v03(p_gameweek),
    'optimizer_orchestration', private.c0213_p2_optimizer_status_v01(p_gameweek,3),
    'a0005', private.a0005_forward_validation_status_v01(),
    'w0002', private.w0002_forward_validation_status_v01(),
    'zero_cost', private.c0139_zero_cost_source_status_v01(),
    'fotmob_metrics', private.c0139_fotmob_metric_status_v01(),
    'physical_load', private.c0140_team_physical_load_status_v01()
  );
$$;
revoke all on function public.engine_diagnostics_status_v01(integer) from public,anon,authenticated;
grant execute on function public.engine_diagnostics_status_v01(integer) to service_role;

do $$
begin
  if not exists(select 1 from cron.job where jobname='football_intelligence_c0213_lineage_capture' and active) then
    perform cron.schedule('football_intelligence_c0213_lineage_capture','14 * * * *',$cmd$select private.capture_c0213_p2_lineage_v01(null);$cmd$);
  end if;
end $$;