create table if not exists public.research_c0202_validation_runs (
  run_key text primary key,
  change_id text not null default 'C0202',
  frozen_at timestamptz not null default clock_timestamp(),
  evidence_cutoff timestamptz not null,
  definition jsonb not null,
  benchmark jsonb not null,
  decision text not null,
  research_only boolean not null default true check (research_only),
  model_effect_enabled boolean not null default false check (not model_effect_enabled),
  created_at timestamptz not null default clock_timestamp()
);

create table if not exists public.research_c0202_player_side_snapshots (
  id bigint generated by default as identity primary key,
  run_key text not null references public.research_c0202_validation_runs(run_key),
  gameweek integer not null,
  match_id bigint references public.matches(id),
  player_id bigint not null references public.players(id),
  team_id bigint references public.teams(id),
  opponent_team_id bigint references public.teams(id),
  primary_role text,
  secondary_role text,
  prior_shots integer not null default 0,
  median_y numeric,
  attack_side text not null check (attack_side in ('ATT_LEFT','ATT_RIGHT','LEFT_LEAN','RIGHT_LEAN','MIXED','UNRESOLVED')),
  side_confidence numeric check (side_confidence is null or (side_confidence >= 0 and side_confidence <= 1)),
  inference_method text not null,
  evidence jsonb not null default '{}'::jsonb,
  research_only boolean not null default true check (research_only),
  model_effect_enabled boolean not null default false check (not model_effect_enabled),
  created_at timestamptz not null default clock_timestamp(),
  unique(run_key, match_id, player_id)
);

alter table public.research_c0202_validation_runs enable row level security;
alter table public.research_c0202_player_side_snapshots enable row level security;
revoke all on public.research_c0202_validation_runs from anon,authenticated;
revoke all on public.research_c0202_player_side_snapshots from anon,authenticated;
revoke all on sequence public.research_c0202_player_side_snapshots_id_seq from anon,authenticated;

create or replace function private.block_c0202_research_mutation_v01()
returns trigger
language plpgsql
set search_path=public,private,pg_temp
as $$
begin
  raise exception 'C0202 research evidence is append-only';
end $$;
revoke all on function private.block_c0202_research_mutation_v01() from public,anon,authenticated;

drop trigger if exists research_c0202_validation_runs_append_only on public.research_c0202_validation_runs;
create trigger research_c0202_validation_runs_append_only
before update or delete on public.research_c0202_validation_runs
for each row execute function private.block_c0202_research_mutation_v01();

drop trigger if exists research_c0202_player_side_snapshots_append_only on public.research_c0202_player_side_snapshots;
create trigger research_c0202_player_side_snapshots_append_only
before update or delete on public.research_c0202_player_side_snapshots
for each row execute function private.block_c0202_research_mutation_v01();

insert into public.research_c0202_validation_runs(
  run_key,evidence_cutoff,definition,benchmark,decision
) values (
  'C0202_V01_FLANK_SHADOW_20260904',
  '2026-09-04T17:30:00Z',
  jsonb_build_object(
    'coordinate_semantics',jsonb_build_object(
      'low_y','attacking left / defending right',
      'high_y','attacking right / defending left',
      'validation','known left-sided attackers/full-backs cluster low-Y while known right-sided anchors cluster high-Y'
    ),
    'player_side_method','prior-shot geometry only; minimum five prior shots; exact tactical side is not inferred from generic WIDE_BACK/WING_BACK role labels',
    'chronology','all side inference must use only events before the target fixture/evidence cutoff',
    'candidate_windows',jsonb_build_array(3,5,8),
    'target','future side-specific attacker xGI / excess xGI',
    'missing_data_rule','missing or unresolved side is never zero and must fail closed'
  ),
  jsonb_build_object(
    'shot_xg_flank_persistence',jsonb_build_object('n',660,'corr',-0.030,'direction_accuracy',0.489,'decision','reject'),
    'walkforward_raw_side_xgi',jsonb_build_object('n',660,'corr',0.050,'direction_accuracy',0.520,'strong_signal_accuracy',0.500,'decision','reject'),
    'walkforward_attacker_baseline_residual',jsonb_build_object('n',591,'corr',0.042,'direction_accuracy',0.525,'strong_signal_accuracy',0.482,'decision','reject'),
    'side_level_interaction_full_sample',jsonb_build_object('n',995,'corr',0.081,'high_vulnerability_future_excess_xgi',0.071,'low_vulnerability_future_excess_xgi',-0.083),
    'sensitivity_holdout',jsonb_build_object(
      'train_gw1_25',jsonb_build_object('n',513,'corr_p3',0.153,'corr_p5',0.127,'corr_p8',0.159),
      'holdout_gw26_38',jsonb_build_object('n',417,'corr_p3',0.015,'corr_p5',0.011,'corr_p8',0.032,'p5_high_future_excess_xgi',0.054,'p5_high_n',29),
      'conclusion','apparent in-sample side persistence collapses out of sample'
    )
  ),
  'RESEARCH_FRAMEWORK_ONLY_NO_PRODUCTION_EFFECT'
)
on conflict do nothing;

create or replace function private.c0202_status_v01()
returns jsonb
language sql
stable
set search_path=public,private,pg_temp
as $$
select jsonb_build_object(
  'change_id','C0202',
  'runs',(select count(*) from public.research_c0202_validation_runs),
  'player_side_snapshots',(select count(*) from public.research_c0202_player_side_snapshots),
  'latest_decision',(select decision from public.research_c0202_validation_runs order by frozen_at desc limit 1),
  'model_effect_enabled',false,
  'append_only',true
);
$$;
revoke all on function private.c0202_status_v01() from public,anon,authenticated;
