create table if not exists public.research_c0202_directional_outcomes (
  id bigint generated by default as identity primary key,
  evaluation_run_key text not null references public.research_c0202_validation_runs(run_key),
  snapshot_id bigint not null references public.research_c0202_directional_matchup_snapshots(id),
  snapshot_run_key text not null,
  result_run_id bigint not null references public.gameweek_result_runs(id),
  gameweek integer not null,
  attacker_player_id bigint not null references public.players(id),
  archetype text not null check (archetype in ('WIDE_ATTACKER_VS_WIDE_DEFENDER','ATTACKING_WIDE_BACK_VS_WIDE_DEFENDER','SIDE_RESOLVED_OPPONENT_UNRESOLVED')),
  mapping_quality text not null check (mapping_quality in ('HIGH','MEDIUM','UNRESOLVED')),
  defender_pair_status text not null,
  minutes integer,
  total_points integer,
  goals integer,
  assists integer,
  bonus integer,
  defensive_contribution integer,
  xg numeric,
  xa numeric,
  xgi numeric,
  xgi90 numeric,
  fixture_count integer not null,
  actuals_observed_at timestamptz not null,
  actuals_final boolean not null check (actuals_final),
  evidence jsonb not null default '{}'::jsonb,
  research_only boolean not null default true check (research_only),
  model_effect_enabled boolean not null default false check (not model_effect_enabled),
  created_at timestamptz not null default clock_timestamp(),
  unique(evaluation_run_key,snapshot_id,result_run_id)
);

alter table public.research_c0202_directional_outcomes enable row level security;
revoke all on public.research_c0202_directional_outcomes from public,anon,authenticated;
revoke all on sequence public.research_c0202_directional_outcomes_id_seq from public,anon,authenticated;

drop trigger if exists research_c0202_directional_outcomes_append_only on public.research_c0202_directional_outcomes;
create trigger research_c0202_directional_outcomes_append_only
before update or delete on public.research_c0202_directional_outcomes
for each row execute function private.block_c0202_research_mutation_v01();

insert into public.research_c0202_validation_runs(run_key,evidence_cutoff,definition,benchmark,decision)
values (
 'C0202_V04_FORWARD_ARCHETYPE_EVAL_20260904',
 '2026-09-04T17:30:00Z',
 jsonb_build_object(
   'scope','preregister outcome evaluation for frozen C0202 V03 GW3 directional snapshots',
   'snapshot_run_key','C0202_V03_STRUCTURAL_DIRECTIONAL_20260904',
   'capture_gate','latest official_fpl gameweek_result_run for GW3 must have is_final=true',
   'double_gameweek_rule','player actual with fixture_count != 1 is unsupported for this GW3 evaluator and must not be silently aggregated',
   'archetypes',jsonb_build_array('WIDE_ATTACKER_VS_WIDE_DEFENDER','ATTACKING_WIDE_BACK_VS_WIDE_DEFENDER','SIDE_RESOLVED_OPPONENT_UNRESOLVED'),
   'metrics',jsonb_build_array('minutes','total_points','P5+','P10+','goals','assists','bonus','defensive_contribution','xG','xA','xGI','xGI90'),
   'stratification',jsonb_build_array('archetype','mapping_quality','defender_pair_status'),
   'no_tuning_rule','definitions and groups are frozen before GW3 outcomes; do not alter after results to improve fit',
   'promotion_rule','GW3 is descriptive only. No xPts effect may be considered until at least 100 paired exact-side outcomes across at least five Gameweeks plus a later holdout/sensitivity test.'
 ),
 jsonb_build_object(
   'pregame_snapshot_rows',33,
   'paired_exact_side',11,
   'high_mapping_quality',9,
   'unresolved_exact_opponent',22,
   'outcomes_available_at_registration',false,
   'latest_result_run_at_registration',jsonb_build_object('id',117,'observed_at','2026-09-04T18:30:09.215002Z','is_final',false,'finished_fixtures',0,'fixture_count',10)
 ),
 'PREREGISTER_FORWARD_ARCHETYPE_EVALUATION; NO_MODEL_EFFECT_FROM_GW3_ALONE'
) on conflict do nothing;

create or replace function private.capture_c0202_v03_outcomes_v01()
returns jsonb
language plpgsql
security definer
set search_path=public,private,pg_temp
as $$
declare
  v_run public.gameweek_result_runs%rowtype;
  v_inserted integer:=0;
  v_existing integer:=0;
  v_missing integer:=0;
  v_unsupported integer:=0;
begin
  select * into v_run
  from public.gameweek_result_runs
  where gameweek=3 and source='official_fpl' and is_final=true
  order by observed_at desc,id desc limit 1;

  if v_run.id is null then
    return jsonb_build_object(
      'ready',false,
      'reason','GW3_OFFICIAL_RESULT_RUN_NOT_FINAL',
      'snapshot_rows',(select count(*) from public.research_c0202_directional_matchup_snapshots where run_key='C0202_V03_STRUCTURAL_DIRECTIONAL_20260904'),
      'captured_outcomes',(select count(*) from public.research_c0202_directional_outcomes where evaluation_run_key='C0202_V04_FORWARD_ARCHETYPE_EVAL_20260904'),
      'model_effect_enabled',false
    );
  end if;

  select count(*) into v_unsupported
  from public.research_c0202_directional_matchup_snapshots s
  join public.player_gameweek_actuals a on a.gameweek=3 and a.player_id=s.attacker_player_id and a.result_run_id=v_run.id
  where s.run_key='C0202_V03_STRUCTURAL_DIRECTIONAL_20260904' and cardinality(a.fixture_ids)<>1;

  with ins as (
    insert into public.research_c0202_directional_outcomes(
      evaluation_run_key,snapshot_id,snapshot_run_key,result_run_id,gameweek,attacker_player_id,archetype,mapping_quality,defender_pair_status,
      minutes,total_points,goals,assists,bonus,defensive_contribution,xg,xa,xgi,xgi90,fixture_count,actuals_observed_at,actuals_final,evidence
    )
    select
      'C0202_V04_FORWARD_ARCHETYPE_EVAL_20260904',s.id,s.run_key,v_run.id,3,s.attacker_player_id,
      case
        when s.defender_pair_status='PAIRED_EXACT_SIDE' and s.attacker_role in ('WIDE_ATTACKER','WIDE_FORWARD') then 'WIDE_ATTACKER_VS_WIDE_DEFENDER'
        when s.defender_pair_status='PAIRED_EXACT_SIDE' and s.attacker_role in ('WIDE_BACK','WING_BACK') then 'ATTACKING_WIDE_BACK_VS_WIDE_DEFENDER'
        else 'SIDE_RESOLVED_OPPONENT_UNRESOLVED'
      end,
      s.mapping_quality,s.defender_pair_status,a.minutes,a.total_points,a.goals,a.assists,a.bonus,a.defensive_contribution,a.xg,a.xa,a.xgi,
      case when a.minutes>0 and a.xgi is not null then 90.0*a.xgi/a.minutes else null end,
      cardinality(a.fixture_ids),v_run.observed_at,true,
      jsonb_build_object(
        'snapshot_effect_direction',s.effect_direction,
        'snapshot_mapping_quality',s.mapping_quality,
        'snapshot_defender_pair_status',s.defender_pair_status,
        'actuals_source',v_run.source,
        'actuals_result_run_id',v_run.id,
        'preregistered_before_outcomes',true,
        'gw3_descriptive_only',true,
        'model_effect_enabled',false
      )
    from public.research_c0202_directional_matchup_snapshots s
    join public.player_gameweek_actuals a on a.gameweek=3 and a.player_id=s.attacker_player_id and a.result_run_id=v_run.id
    where s.run_key='C0202_V03_STRUCTURAL_DIRECTIONAL_20260904' and cardinality(a.fixture_ids)=1
    on conflict do nothing
    returning id
  ) select count(*) into v_inserted from ins;

  select count(*) into v_existing from public.research_c0202_directional_outcomes where evaluation_run_key='C0202_V04_FORWARD_ARCHETYPE_EVAL_20260904' and result_run_id=v_run.id;
  select count(*) into v_missing from public.research_c0202_directional_matchup_snapshots s where s.run_key='C0202_V03_STRUCTURAL_DIRECTIONAL_20260904' and not exists (select 1 from public.player_gameweek_actuals a where a.gameweek=3 and a.player_id=s.attacker_player_id and a.result_run_id=v_run.id);

  return jsonb_build_object(
    'ready',true,'result_run_id',v_run.id,'actuals_observed_at',v_run.observed_at,'inserted',v_inserted,'captured_total',v_existing,
    'missing_actual_rows',v_missing,'unsupported_fixture_count_rows',v_unsupported,'model_effect_enabled',false
  );
end;
$$;
revoke all on function private.capture_c0202_v03_outcomes_v01() from public,anon,authenticated;

create or replace function private.c0202_v04_outcome_status_v01()
returns jsonb
language sql
stable
security definer
set search_path=public,private,pg_temp
as $$
with latest as (
 select id,observed_at,is_final,metadata from public.gameweek_result_runs where gameweek=3 and source='official_fpl' order by observed_at desc,id desc limit 1
), o as (
 select * from public.research_c0202_directional_outcomes where evaluation_run_key='C0202_V04_FORWARD_ARCHETYPE_EVAL_20260904'
), groups as (
 select archetype,mapping_quality,count(*) n,
        round(avg(total_points)::numeric,3) mean_points,
        round(avg(xgi)::numeric,3) mean_xgi,
        round(avg(xgi90)::numeric,3) mean_xgi90,
        round(avg(case when total_points>=5 then 1.0 else 0.0 end)::numeric,3) p5_plus,
        round(avg(case when total_points>=10 then 1.0 else 0.0 end)::numeric,3) p10_plus
 from o group by archetype,mapping_quality
)
select jsonb_build_object(
 'change_id','C0202',
 'evaluation_run_key','C0202_V04_FORWARD_ARCHETYPE_EVAL_20260904',
 'latest_result_run',(select to_jsonb(latest) from latest),
 'ready_to_capture',coalesce((select is_final from latest),false),
 'outcome_rows',(select count(*) from o),
 'groups',(select coalesce(jsonb_agg(groups order by archetype,mapping_quality),'[]'::jsonb) from groups),
 'promotion_gate',jsonb_build_object('minimum_paired_outcomes',100,'minimum_gameweeks',5,'later_holdout_required',true),
 'gw3_descriptive_only',true,
 'model_effect_enabled',false,
 'append_only',true
);
$$;
revoke all on function private.c0202_v04_outcome_status_v01() from public,anon,authenticated;
