create table if not exists public.blind_fixture_replay_runs (
  id bigint generated by default as identity primary key,
  gameweek integer not null,
  replay_version text not null,
  created_at timestamptz not null default clock_timestamp(),
  run_hash text not null unique,
  input_policy jsonb not null,
  actual_data_used boolean not null default false check (actual_data_used=false),
  model_effect_enabled boolean not null default false check (model_effect_enabled=false)
);

create table if not exists public.blind_fixture_replay_matches (
  id bigint generated by default as identity primary key,
  run_id bigint not null references public.blind_fixture_replay_runs(id),
  match_id bigint not null references public.matches(id),
  gameweek integer not null,
  kickoff_time timestamptz not null,
  base_prediction_snapshot_id bigint references public.fixture_prediction_snapshots(id),
  base_prediction_available boolean not null,
  base_prediction_captured_at timestamptz,
  home_lambda numeric,
  away_lambda numeric,
  top_scoreline text,
  top_scoreline_probability numeric,
  markets jsonb,
  score_matrix jsonb,
  player_prediction_as_of timestamptz,
  home_expected_xi_available boolean not null default false,
  away_expected_xi_available boolean not null default false,
  evidence_cutoff timestamptz,
  evidence jsonb not null default '{}'::jsonb,
  replay_hash text not null unique,
  actual_data_used boolean not null default false check (actual_data_used=false),
  model_effect_enabled boolean not null default false check (model_effect_enabled=false),
  unique(run_id,match_id)
);

create table if not exists public.blind_fixture_replay_signals (
  id bigint generated by default as identity primary key,
  run_id bigint not null references public.blind_fixture_replay_runs(id),
  match_id bigint not null references public.matches(id),
  gameweek integer not null,
  team_id bigint not null references public.teams(id),
  opponent_team_id bigint not null references public.teams(id),
  kickoff_time timestamptz not null,
  signal_key text not null,
  score_type text not null,
  score numeric,
  direction text not null,
  attacking_component numeric,
  resistance_component numeric,
  confidence numeric,
  data_coverage numeric,
  evidence_cutoff timestamptz,
  evidence jsonb not null default '{}'::jsonb,
  observation_hash text not null unique,
  actual_data_used boolean not null default false check (actual_data_used=false),
  forward_valid boolean not null default false check (forward_valid=false),
  model_effect_enabled boolean not null default false check (model_effect_enabled=false),
  unique(run_id,match_id,team_id,signal_key)
);

create table if not exists public.blind_fixture_replay_evaluations (
  id bigint generated by default as identity primary key,
  run_id bigint not null references public.blind_fixture_replay_runs(id),
  match_id bigint not null references public.matches(id),
  evaluated_at timestamptz not null default clock_timestamp(),
  actual_home_score integer not null,
  actual_away_score integer not null,
  actual_outcome text not null,
  predicted_outcome text,
  predicted_outcome_probability numeric,
  predicted_outcome_hit boolean,
  top_scoreline text,
  top_scoreline_hit boolean,
  actual_score_probability numeric,
  actual_score_log_loss numeric,
  home_goal_error numeric,
  away_goal_error numeric,
  total_goal_error numeric,
  brier_1x2 numeric,
  evaluation jsonb not null default '{}'::jsonb,
  model_effect_enabled boolean not null default false check (model_effect_enabled=false),
  unique(run_id,match_id)
);

alter table public.blind_fixture_replay_runs enable row level security;
alter table public.blind_fixture_replay_matches enable row level security;
alter table public.blind_fixture_replay_signals enable row level security;
alter table public.blind_fixture_replay_evaluations enable row level security;
revoke all on public.blind_fixture_replay_runs,public.blind_fixture_replay_matches,public.blind_fixture_replay_signals,public.blind_fixture_replay_evaluations from anon,authenticated;
grant select,insert on public.blind_fixture_replay_runs,public.blind_fixture_replay_matches,public.blind_fixture_replay_signals,public.blind_fixture_replay_evaluations to service_role;
grant usage,select on all sequences in schema public to service_role;

create index if not exists blind_replay_matches_run_idx on public.blind_fixture_replay_matches(run_id,match_id);
create index if not exists blind_replay_matches_match_fk_idx on public.blind_fixture_replay_matches(match_id);
create index if not exists blind_replay_matches_base_snapshot_fk_idx on public.blind_fixture_replay_matches(base_prediction_snapshot_id) where base_prediction_snapshot_id is not null;
create index if not exists blind_replay_signals_run_match_idx on public.blind_fixture_replay_signals(run_id,match_id,team_id);
create index if not exists blind_replay_signals_match_fk_idx on public.blind_fixture_replay_signals(match_id);
create index if not exists blind_replay_signals_team_fk_idx on public.blind_fixture_replay_signals(team_id);
create index if not exists blind_replay_signals_opponent_fk_idx on public.blind_fixture_replay_signals(opponent_team_id);
create index if not exists blind_replay_eval_run_idx on public.blind_fixture_replay_evaluations(run_id,match_id);
create index if not exists blind_replay_evaluations_match_fk_idx on public.blind_fixture_replay_evaluations(match_id);

create or replace view public.current_blind_fixture_replay with (security_invoker=true) as
select m.*,r.replay_version,r.created_at run_created_at,r.input_policy
from public.blind_fixture_replay_matches m join public.blind_fixture_replay_runs r on r.id=m.run_id
where r.id=(select max(id) from public.blind_fixture_replay_runs where gameweek=m.gameweek);

create or replace view public.current_blind_fixture_replay_signals with (security_invoker=true) as
select s.*,r.replay_version,r.created_at run_created_at
from public.blind_fixture_replay_signals s join public.blind_fixture_replay_runs r on r.id=s.run_id
where r.id=(select max(id) from public.blind_fixture_replay_runs where gameweek=s.gameweek);

revoke all on public.current_blind_fixture_replay,public.current_blind_fixture_replay_signals from anon,authenticated;
grant select on public.current_blind_fixture_replay,public.current_blind_fixture_replay_signals to service_role;
