-- C0117 — Player ability prior v2 evidence expansion
-- Research only. Does not alter A0005 or any frozen prediction.

create table if not exists public.player_ability_prior_v2_observations (
  id bigint generated by default as identity primary key,
  player_id bigint not null references public.players(id),
  team_id bigint not null references public.teams(id),
  season text not null,
  position text not null,
  observed_at timestamptz not null default clock_timestamp(),
  season_minutes integer not null,
  base_attack_quality_percentile numeric,
  base_defence_quality_percentile numeric,
  base_overall_quality_percentile numeric,
  event_matches integer not null default 0,
  team_continuity_ratio numeric,
  opponent_elo_coverage numeric,
  average_opponent_pre_match_elo numeric,
  attack_per90_event_raw numeric,
  defence_per90_event_raw numeric,
  attack_per90_opponent_adjusted numeric,
  defence_per90_opponent_adjusted numeric,
  attack_per90_v2_shrunk numeric,
  defence_per90_v2_shrunk numeric,
  attack_quality_percentile_v2 numeric,
  defence_quality_percentile_v2 numeric,
  overall_quality_percentile_v2 numeric,
  confidence numeric not null,
  opponent_adjustment_applied boolean not null default false,
  method text not null,
  evidence jsonb not null default '{}'::jsonb,
  actual_data_used boolean not null default false,
  model_effect_enabled boolean not null default false,
  constraint player_ability_prior_v2_unique unique(player_id,season,method),
  constraint player_ability_prior_v2_flags_check check (actual_data_used=false and model_effect_enabled=false)
);

alter table public.player_ability_prior_v2_observations enable row level security;
revoke all on public.player_ability_prior_v2_observations from anon, authenticated;

create index if not exists player_ability_prior_v2_player_idx
  on public.player_ability_prior_v2_observations(player_id,season);
create index if not exists player_ability_prior_v2_position_idx
  on public.player_ability_prior_v2_observations(position,season);

create or replace function private.block_player_ability_prior_v2_mutation()
returns trigger
language plpgsql
set search_path=public,private,pg_temp
as $$
begin
  raise exception 'player_ability_prior_v2_observations is append-only';
end;
$$;
revoke all on function private.block_player_ability_prior_v2_mutation() from public, anon, authenticated;

drop trigger if exists player_ability_prior_v2_append_only on public.player_ability_prior_v2_observations;
create trigger player_ability_prior_v2_append_only
before update or delete on public.player_ability_prior_v2_observations
for each row execute function private.block_player_ability_prior_v2_mutation();

create or replace function public.refresh_player_ability_priors_v2_2025_26()
returns jsonb
language plpgsql
set search_path=public,private,pg_temp
as $$
declare v_inserted integer:=0;
begin
  with team_alias as materialized (
    select * from (values
      (1::bigint,'arsenal','Arsenal'),(2,'aston-villa','Aston Villa'),(3,'afc-bournemouth','Bournemouth'),
      (4,'brentford','Brentford'),(5,'brighton-hove-albion','Brighton'),(6,'chelsea','Chelsea'),
      (7,'coventry-city','Coventry'),(8,'crystal-palace','Crystal Palace'),(9,'everton','Everton'),
      (10,'fulham','Fulham'),(11,'hull-city','Hull'),(12,'ipswich-town','Ipswich'),(13,'leeds-united','Leeds'),
      (14,'liverpool','Liverpool'),(15,'manchester-city','Man City'),(16,'manchester-united','Man United'),
      (17,'newcastle-united','Newcastle'),(18,'nottingham-forest','Nott''m Forest'),
      (19,'tottenham-hotspur','Tottenham'),(20,'sunderland','Sunderland')
    ) v(team_id,source_slug,elo_name)
  ), opponent_alias as materialized (
    select * from (values
      ('afc-bournemouth','Bournemouth'),('arsenal','Arsenal'),('aston-villa','Aston Villa'),('brentford','Brentford'),
      ('brighton-hove-albion','Brighton'),('burnley','Burnley'),('chelsea','Chelsea'),('crystal-palace','Crystal Palace'),
      ('everton','Everton'),('fulham','Fulham'),('leeds-united','Leeds'),('liverpool','Liverpool'),
      ('manchester-city','Man City'),('manchester-united','Man United'),('newcastle-united','Newcastle'),
      ('nottingham-forest','Nott''m Forest'),('sunderland','Sunderland'),('tottenham-hotspur','Tottenham'),
      ('west-ham-united','West Ham'),('wolverhampton-wanderers','Wolves')
    ) v(source_slug,elo_name)
  ), base as materialized (
    select q.*
    from public.player_quality_prior_observations q
    where q.season='2025-2026'
      and q.method='player_quality_v0.1_position_normalized'
      and q.position<>'GKP'
  ), events as materialized (
    select b.player_id,b.team_id,b.position,b.minutes season_minutes,b.sample_weight,b.confidence base_confidence,
      b.attack_quality_percentile base_aq,b.defence_quality_percentile base_dq,b.overall_quality_percentile base_oq,
      b.attack_per90_shrunk base_attack_shrunk,b.defence_per90_shrunk base_def_shrunk,
      h.source_match_id,h.minutes event_minutes,
      nullif(h.raw->>'xg','')::numeric xg,
      nullif(h.raw->>'xa','')::numeric xa,
      nullif(h.raw->>'tackles','')::numeric tackles,
      nullif(h.raw->>'interceptions','')::numeric interceptions,
      nullif(h.raw->>'blocks','')::numeric blocks,
      nullif(h.raw->>'clearances','')::numeric clearances,
      nullif(h.raw->>'recoveries','')::numeric recoveries,
      ta.source_slug team_slug,ta.elo_name team_elo_name,
      case when h.source_match_id like '25-26-prem-'||ta.source_slug||'-vs-%' then 'home'
           when h.source_match_id like '25-26-prem-%-vs-'||ta.source_slug then 'away' end venue,
      case when h.source_match_id like '25-26-prem-'||ta.source_slug||'-vs-%'
             then substring(h.source_match_id from length('25-26-prem-'||ta.source_slug||'-vs-')+1)
           when h.source_match_id like '25-26-prem-%-vs-'||ta.source_slug
             then substring(h.source_match_id from length('25-26-prem-')+1 for length(h.source_match_id)-length('25-26-prem-')-length('-vs-'||ta.source_slug)) end opponent_slug
    from base b
    join team_alias ta on ta.team_id=b.team_id
    left join public.historical_player_event_evidence h
      on h.player_id=b.player_id and h.season='2025-2026' and h.minutes>0
  ), mapped as materialized (
    select e.*,oa.elo_name opponent_elo_name,elo.opponent_pre_match_elo,
      case when e.xg is not null and e.xa is not null then e.xg+e.xa end attack_value,
      case when e.tackles is not null and e.interceptions is not null and e.blocks is not null
                 and e.clearances is not null and e.recoveries is not null
           then e.tackles+e.interceptions+e.blocks+e.clearances+e.recoveries end defence_value,
      case when elo.opponent_pre_match_elo is not null
           then greatest(.85::numeric,least(1.15::numeric,exp((elo.opponent_pre_match_elo-1500::numeric)/1000::numeric))) end opponent_factor
    from events e
    left join opponent_alias oa on oa.source_slug=e.opponent_slug
    left join public.historical_football_data_elo_observations elo
      on elo.provider_team_name=e.team_elo_name
     and elo.provider_opponent_name=oa.elo_name
     and elo.venue=e.venue
     and elo.fixture_kickoff>='2025-08-01'::timestamptz
     and elo.fixture_kickoff<'2026-06-01'::timestamptz
     and elo.model_version='football_data_elo_v0.1'
  ), agg as materialized (
    select player_id,team_id,position,max(season_minutes) season_minutes,max(sample_weight) sample_weight,
      max(base_confidence) base_confidence,max(base_aq) base_aq,max(base_dq) base_dq,max(base_oq) base_oq,
      max(base_attack_shrunk) base_attack_shrunk,max(base_def_shrunk) base_def_shrunk,
      count(*) filter(where event_minutes is not null) event_matches,
      count(*) filter(where venue is not null) continuity_matches,
      sum(event_minutes) filter(where event_minutes is not null) event_minutes_total,
      sum(event_minutes) filter(where opponent_pre_match_elo is not null) elo_minutes,
      90*sum(attack_value)/nullif(sum(event_minutes) filter(where attack_value is not null),0) attack90_raw,
      90*sum(defence_value)/nullif(sum(event_minutes) filter(where defence_value is not null),0) defence90_raw,
      90*sum(attack_value*opponent_factor)/nullif(sum(event_minutes) filter(where attack_value is not null and opponent_factor is not null),0) attack90_adj,
      90*sum(defence_value*opponent_factor)/nullif(sum(event_minutes) filter(where defence_value is not null and opponent_factor is not null),0) defence90_adj,
      sum(opponent_pre_match_elo*event_minutes)/nullif(sum(event_minutes) filter(where opponent_pre_match_elo is not null),0) avg_opp_elo
    from mapped
    group by player_id,team_id,position
  ), coverage as materialized (
    select a.*,
      continuity_matches::numeric/nullif(event_matches,0) continuity_ratio,
      elo_minutes::numeric/nullif(event_minutes_total,0) elo_coverage,
      least(sample_weight,coalesce(elo_minutes::numeric/nullif(season_minutes,0),0),
            coalesce(continuity_matches::numeric/nullif(event_matches,0),0)) event_weight
    from agg a
  ), pos_med as materialized (
    select position,
      percentile_cont(.5) within group(order by attack90_adj)
        filter(where continuity_ratio>=.80 and elo_coverage>=.60 and attack90_adj is not null) med_attack_adj,
      percentile_cont(.5) within group(order by defence90_adj)
        filter(where continuity_ratio>=.80 and elo_coverage>=.60 and defence90_adj is not null) med_def_adj
    from coverage group by position
  ), shrunk as materialized (
    select c.*,
      case when c.continuity_ratio>=.80 and c.elo_coverage>=.60 and c.attack90_adj is not null and p.med_attack_adj is not null
           then c.event_weight*c.attack90_adj+(1-c.event_weight)*p.med_attack_adj else c.base_attack_shrunk end attack90_v2,
      case when c.continuity_ratio>=.80 and c.elo_coverage>=.60 and c.defence90_adj is not null and p.med_def_adj is not null
           then c.event_weight*c.defence90_adj+(1-c.event_weight)*p.med_def_adj else c.base_def_shrunk end defence90_v2,
      (c.continuity_ratio>=.80 and c.elo_coverage>=.60 and c.attack90_adj is not null and c.defence90_adj is not null) opponent_adjustment_applied
    from coverage c join pos_med p using(position)
  ), ranked as materialized (
    select s.*,
      percent_rank() over(partition by position order by attack90_v2) aq2,
      percent_rank() over(partition by position order by defence90_v2) dq2
    from shrunk s
  ), ins as (
    insert into public.player_ability_prior_v2_observations(
      player_id,team_id,season,position,season_minutes,
      base_attack_quality_percentile,base_defence_quality_percentile,base_overall_quality_percentile,
      event_matches,team_continuity_ratio,opponent_elo_coverage,average_opponent_pre_match_elo,
      attack_per90_event_raw,defence_per90_event_raw,attack_per90_opponent_adjusted,defence_per90_opponent_adjusted,
      attack_per90_v2_shrunk,defence_per90_v2_shrunk,attack_quality_percentile_v2,defence_quality_percentile_v2,
      overall_quality_percentile_v2,confidence,opponent_adjustment_applied,method,evidence
    )
    select player_id,team_id,'2025-2026',position,season_minutes,base_aq,base_dq,base_oq,event_matches,
      round(continuity_ratio,4),round(elo_coverage,4),round(avg_opp_elo,2),
      round(attack90_raw,4),round(defence90_raw,4),round(attack90_adj,4),round(defence90_adj,4),
      round(attack90_v2::numeric,4),round(defence90_v2::numeric,4),round(aq2::numeric,4),round(dq2::numeric,4),
      round((case position when 'FWD' then .80*aq2+.20*dq2 when 'MID' then .70*aq2+.30*dq2 when 'DEF' then .25*aq2+.75*dq2 end)::numeric,4),
      round(least(.85::numeric,base_confidence*(case when opponent_adjustment_applied then .85+.15*least(1::numeric,elo_coverage) else .75 end)),4),
      opponent_adjustment_applied,'player_ability_v0.2_opponent_elo_context',
      jsonb_build_object(
        'change_id','C0117','base_method','player_quality_v0.1_position_normalized',
        'event_source','historical_player_event_evidence 2025-2026',
        'opponent_strength_source','historical_football_data_elo_observations football_data_elo_v0.1',
        'team_continuity_threshold',.80,'opponent_elo_coverage_threshold',.60,
        'opponent_factor','clamp(exp((opponent_pre_match_elo-1500)/1000),0.85,1.15)',
        'missing_policy','metric row excluded when required event fields are missing; never coalesced to zero',
        'multi_season_available',false,'second_historical_player_season_required_for_C0092_completion',true,
        'opponent_adjustment_applied',opponent_adjustment_applied,'actual_data_used',false,
        'model_effect_enabled',false,'a0005_modified',false
      )
    from ranked
    on conflict(player_id,season,method) do nothing
    returning 1
  )
  select count(*) into v_inserted from ins;

  return jsonb_build_object(
    'ok',true,'change_id','C0117','inserted',v_inserted,
    'method','player_ability_v0.2_opponent_elo_context',
    'multi_season_available',false,'model_effect_enabled',false,'a0005_modified',false
  );
end;
$$;

revoke all on function public.refresh_player_ability_priors_v2_2025_26() from public, anon, authenticated;
