-- C0147 / E0011 — prospective matchup predictive validation v0.1
-- Pre-registered before GW3. No production model effect.

create table if not exists public.matchup_predictive_validation_cohort (
  id bigint generated by default as identity primary key,
  experiment_key text not null,
  change_id text not null,
  match_id bigint not null references public.matches(id),
  gameweek integer not null,
  split text not null check (split in ('VALIDATION','TEST')),
  kickoff_time timestamptz not null,
  cohort_frozen_at timestamptz not null default clock_timestamp(),
  definition jsonb not null default '{}'::jsonb,
  actual_data_used boolean not null default false,
  model_effect_enabled boolean not null default false,
  unique(experiment_key, match_id)
);

create table if not exists public.matchup_predictive_feature_snapshots (
  id bigint generated by default as identity primary key,
  experiment_key text not null,
  match_id bigint not null references public.matches(id),
  gameweek integer not null,
  team_id bigint not null references public.teams(id),
  opponent_team_id bigint not null references public.teams(id),
  kickoff_time timestamptz not null,
  captured_at timestamptz not null,
  input_cutoff timestamptz not null,
  baseline_prediction_snapshot_id bigint not null references public.fixture_prediction_snapshots(id),
  wide_score numeric, wide_confidence numeric, wide_coverage numeric,
  aerial_set_piece_score numeric, aerial_set_piece_confidence numeric, aerial_set_piece_coverage numeric,
  central_creation_score numeric, central_creation_confidence numeric, central_creation_coverage numeric,
  transition_score numeric, transition_confidence numeric, transition_coverage numeric,
  personnel_disruption_score numeric, personnel_disruption_confidence numeric, personnel_disruption_coverage numeric,
  creator_absence_burden numeric, striker_absence_burden numeric, defensive_absence_burden numeric, set_piece_absence_burden numeric,
  absence_coverage numeric,
  absence_candidate_count integer not null default 0,
  feature_vector jsonb not null default '{}'::jsonb,
  source_ids jsonb not null default '{}'::jsonb,
  chronology_valid boolean not null,
  actual_data_used boolean not null default false,
  model_effect_enabled boolean not null default false,
  feature_hash text not null unique,
  created_at timestamptz not null default clock_timestamp()
);
create index if not exists matchup_predictive_feature_match_idx on public.matchup_predictive_feature_snapshots(experiment_key,match_id,team_id,input_cutoff desc);

create table if not exists public.matchup_predictive_predictions (
  id bigint generated by default as identity primary key,
  experiment_key text not null,
  match_id bigint not null references public.matches(id),
  gameweek integer not null,
  split text not null check (split in ('VALIDATION','TEST')),
  variant_key text not null,
  home_feature_snapshot_id bigint not null references public.matchup_predictive_feature_snapshots(id),
  away_feature_snapshot_id bigint not null references public.matchup_predictive_feature_snapshots(id),
  base_prediction_snapshot_id bigint not null references public.fixture_prediction_snapshots(id),
  captured_at timestamptz not null,
  input_cutoff timestamptz not null,
  kickoff_time timestamptz not null,
  home_log_adjustment numeric not null,
  away_log_adjustment numeric not null,
  baseline_home_lambda numeric not null,
  baseline_away_lambda numeric not null,
  home_lambda numeric not null,
  away_lambda numeric not null,
  markets jsonb not null,
  adjustment_manifest jsonb not null default '{}'::jsonb,
  prediction_hash text not null unique,
  chronology_valid boolean not null,
  actual_data_used boolean not null default false,
  model_effect_enabled boolean not null default false,
  created_at timestamptz not null default clock_timestamp()
);
create index if not exists matchup_predictive_predictions_lookup_idx on public.matchup_predictive_predictions(experiment_key,match_id,variant_key,input_cutoff desc);

create table if not exists public.matchup_predictive_evaluations (
  id bigint generated by default as identity primary key,
  experiment_key text not null,
  prediction_id bigint not null references public.matchup_predictive_predictions(id),
  match_id bigint not null references public.matches(id),
  gameweek integer not null,
  split text not null check (split in ('VALIDATION','TEST')),
  variant_key text not null,
  evaluated_at timestamptz not null default clock_timestamp(),
  actual_home_goals integer not null,
  actual_away_goals integer not null,
  actual_home_xg numeric,
  actual_away_xg numeric,
  brier_1x2 numeric not null,
  score_log_loss numeric not null,
  goals_mae numeric not null,
  process_mae numeric,
  over_2_5_brier numeric not null,
  btts_brier numeric not null,
  direction_hit boolean not null,
  evaluation_evidence jsonb not null default '{}'::jsonb,
  actual_data_used boolean not null default true,
  model_effect_enabled boolean not null default false,
  unique(experiment_key,match_id,variant_key)
);
create index if not exists matchup_predictive_eval_variant_idx on public.matchup_predictive_evaluations(experiment_key,split,variant_key);

alter table public.matchup_predictive_validation_cohort enable row level security;
alter table public.matchup_predictive_feature_snapshots enable row level security;
alter table public.matchup_predictive_predictions enable row level security;
alter table public.matchup_predictive_evaluations enable row level security;
revoke all on public.matchup_predictive_validation_cohort from anon,authenticated;
revoke all on public.matchup_predictive_feature_snapshots from anon,authenticated;
revoke all on public.matchup_predictive_predictions from anon,authenticated;
revoke all on public.matchup_predictive_evaluations from anon,authenticated;
grant select,insert on public.matchup_predictive_validation_cohort to service_role;
grant select,insert on public.matchup_predictive_feature_snapshots to service_role;
grant select,insert on public.matchup_predictive_predictions to service_role;
grant select,insert on public.matchup_predictive_evaluations to service_role;
grant usage,select on all sequences in schema public to service_role;

create or replace function private.c0147_block_mutation_v01() returns trigger language plpgsql as $$
begin
  raise exception 'C0147 matchup predictive validation records are append-only';
end $$;

drop trigger if exists trg_c0147_cohort_immutable on public.matchup_predictive_validation_cohort;
create trigger trg_c0147_cohort_immutable before update or delete on public.matchup_predictive_validation_cohort for each row execute function private.c0147_block_mutation_v01();
drop trigger if exists trg_c0147_features_immutable on public.matchup_predictive_feature_snapshots;
create trigger trg_c0147_features_immutable before update or delete on public.matchup_predictive_feature_snapshots for each row execute function private.c0147_block_mutation_v01();
drop trigger if exists trg_c0147_predictions_immutable on public.matchup_predictive_predictions;
create trigger trg_c0147_predictions_immutable before update or delete on public.matchup_predictive_predictions for each row execute function private.c0147_block_mutation_v01();
drop trigger if exists trg_c0147_evaluations_immutable on public.matchup_predictive_evaluations;
create trigger trg_c0147_evaluations_immutable before update or delete on public.matchup_predictive_evaluations for each row execute function private.c0147_block_mutation_v01();

create or replace function private.c0147_poisson_markets_v01(p_home numeric,p_away numeric)
returns jsonb language sql immutable as $$
with cells as (
  select h,a,
    exp(-p_home::double precision)*power(p_home::double precision,h)/factorial(h)::double precision *
    exp(-p_away::double precision)*power(p_away::double precision,a)/factorial(a)::double precision as p
  from generate_series(0,12) h cross join generate_series(0,12) a
), z as (select sum(p) mass from cells), agg as (
  select
    sum(p) filter(where h>a)/(select mass from z) home_win,
    sum(p) filter(where h=a)/(select mass from z) draw,
    sum(p) filter(where h<a)/(select mass from z) away_win,
    sum(p) filter(where h+a>=3)/(select mass from z) over_2_5,
    sum(p) filter(where h>0 and a>0)/(select mass from z) btts_yes
  from cells
)
select jsonb_build_object(
  'home_win',home_win,'draw',draw,'away_win',away_win,
  'over_2_5',over_2_5,'under_2_5',1-over_2_5,
  'btts_yes',btts_yes,'btts_no',1-btts_yes,
  'home_clean_sheet',exp(-p_away::double precision),
  'away_clean_sheet',exp(-p_home::double precision)
) from agg
$$;

create or replace function private.c0147_capture_side_feature_v01(
  p_match_id bigint,p_gameweek integer,p_team_id bigint,p_opponent_team_id bigint,p_kickoff timestamptz,p_base_id bigint,p_base_captured timestamptz,p_cutoff timestamptz
) returns bigint language plpgsql security definer set search_path=public,private,extensions,pg_temp as $$
declare
  v_wide numeric;v_wide_conf numeric;v_wide_cov numeric;v_wide_id bigint;v_wide_at timestamptz;
  v_aerial numeric;v_aerial_conf numeric;v_aerial_cov numeric;v_aerial_id bigint;v_aerial_at timestamptz;
  v_central numeric;v_central_conf numeric;v_central_cov numeric;v_central_id bigint;v_central_at timestamptz;
  v_trans numeric;v_trans_conf numeric;v_trans_cov numeric;v_trans_id bigint;v_trans_at timestamptz;
  v_pers numeric;v_pers_conf numeric;v_pers_cov numeric;v_pers_id bigint;v_pers_at timestamptz;
  v_creator numeric;v_striker numeric;v_def numeric;v_setpiece numeric;v_abs_cov numeric;v_abs_n integer;v_abs_at timestamptz;
  v_input timestamptz;v_hash text;v_id bigint;v_sources jsonb;v_vector jsonb;
begin
  with latest as (
    select distinct on(signal_key) id,signal_key,score,confidence,data_coverage,captured_at
    from public.fixture_tactical_matchup_observations
    where match_id=p_match_id and team_id=p_team_id and captured_at<p_cutoff and evidence_cutoff<=p_cutoff and model_effect_enabled=false
    order by signal_key,captured_at desc,id desc
  ) select
    max(score) filter(where signal_key='wide_channel_pressure'),max(confidence) filter(where signal_key='wide_channel_pressure'),max(data_coverage) filter(where signal_key='wide_channel_pressure'),max(id) filter(where signal_key='wide_channel_pressure'),max(captured_at) filter(where signal_key='wide_channel_pressure'),
    max(score) filter(where signal_key='aerial_set_piece_mismatch'),max(confidence) filter(where signal_key='aerial_set_piece_mismatch'),max(data_coverage) filter(where signal_key='aerial_set_piece_mismatch'),max(id) filter(where signal_key='aerial_set_piece_mismatch'),max(captured_at) filter(where signal_key='aerial_set_piece_mismatch'),
    max(score) filter(where signal_key='central_creation_vs_block'),max(confidence) filter(where signal_key='central_creation_vs_block'),max(data_coverage) filter(where signal_key='central_creation_vs_block'),max(id) filter(where signal_key='central_creation_vs_block'),max(captured_at) filter(where signal_key='central_creation_vs_block'),
    max(score) filter(where signal_key='direct_transition_opportunity'),max(confidence) filter(where signal_key='direct_transition_opportunity'),max(data_coverage) filter(where signal_key='direct_transition_opportunity'),max(id) filter(where signal_key='direct_transition_opportunity'),max(captured_at) filter(where signal_key='direct_transition_opportunity'),
    max(score) filter(where signal_key='personnel_disruption'),max(confidence) filter(where signal_key='personnel_disruption'),max(data_coverage) filter(where signal_key='personnel_disruption'),max(id) filter(where signal_key='personnel_disruption'),max(captured_at) filter(where signal_key='personnel_disruption')
  into v_wide,v_wide_conf,v_wide_cov,v_wide_id,v_wide_at,
       v_aerial,v_aerial_conf,v_aerial_cov,v_aerial_id,v_aerial_at,
       v_central,v_central_conf,v_central_cov,v_central_id,v_central_at,
       v_trans,v_trans_conf,v_trans_cov,v_trans_id,v_trans_at,
       v_pers,v_pers_conf,v_pers_cov,v_pers_id,v_pers_at
  from latest;

  with latest_av as (
    select distinct on(player_id) *
    from public.player_fixture_availability_observations
    where match_id=p_match_id and team_id=p_team_id and captured_at<p_cutoff
    order by player_id,captured_at desc,id desc
  ), latest_role as (
    select distinct on(player_id) player_id,primary_role,secondary_role,confidence,captured_at
    from public.player_fixture_role_observations
    where match_id=p_match_id and team_id=p_team_id and captured_at<p_cutoff
    order by player_id,captured_at desc,id desc
  ), latest_ability as (
    select distinct on(player_id) player_id,recent_minutes,attack_quality_percentile_v3,defence_quality_percentile_v3,overall_quality_percentile_v3,confidence,observed_at
    from public.player_ability_prior_v3_observations
    where observed_at<p_cutoff
    order by player_id,observed_at desc,id desc
  ), c as (
    select a.player_id,p.position,a.availability_status,a.chance_of_playing,a.news,a.captured_at,
      r.primary_role,r.secondary_role,r.confidence role_confidence,r.captured_at role_captured_at,
      q.recent_minutes,q.attack_quality_percentile_v3,q.defence_quality_percentile_v3,q.overall_quality_percentile_v3,q.confidence ability_confidence,q.observed_at ability_observed_at,
      p.penalties_order,p.direct_freekicks_order,p.corners_and_indirect_freekicks_order,
      greatest(0::numeric,least(1::numeric,1-coalesce(a.chance_of_playing,case when upper(a.availability_status)='AVAILABLE' then 1 else 0 end))) loss,
      least(1::numeric,coalesce(q.recent_minutes,0)::numeric/2700.0) usage,
      coalesce(q.attack_quality_percentile_v3,q.overall_quality_percentile_v3) atkq,
      coalesce(q.defence_quality_percentile_v3,q.overall_quality_percentile_v3) defq
    from latest_av a
    join public.players p on p.id=a.player_id
    left join latest_role r on r.player_id=a.player_id
    left join latest_ability q on q.player_id=a.player_id
    where upper(a.availability_status)<>'AVAILABLE'
      and not (upper(a.availability_status)='UNAVAILABLE' and lower(coalesce(a.news,'')) ~ '(joined|loan|departed|free agent|returned to)')
  ), scored as (
    select *,
      greatest(
        case when primary_role='CREATOR_10' then 1 when primary_role='WIDE_ATTACKER' then .8 when primary_role='BOX_TO_BOX' then .5 when primary_role='LINK_FORWARD' then .45 else 0 end,
        case when secondary_role='CREATOR_10' then .65 when secondary_role='WIDE_ATTACKER' then .5 when secondary_role='BOX_TO_BOX' then .3 when secondary_role='LINK_FORWARD' then .3 else 0 end,
        case when position='MID' then .25 else 0 end
      )::numeric creator_factor,
      greatest(
        case when primary_role in ('CENTRAL_STRIKER','TARGET_FORWARD') then 1 when primary_role in ('WIDE_FORWARD','LINK_FORWARD') then .75 else 0 end,
        case when secondary_role in ('CENTRAL_STRIKER','TARGET_FORWARD') then .65 when secondary_role in ('WIDE_FORWARD','LINK_FORWARD') then .5 else 0 end,
        case when position='FWD' then .6 else 0 end
      )::numeric striker_factor,
      greatest(
        case when primary_role in ('CENTRE_BACK','HYBRID_DEFENDER','GOALKEEPER') then 1 when primary_role in ('WIDE_BACK','HOLDING_MIDFIELDER','WING_BACK') then .75 else 0 end,
        case when secondary_role in ('CENTRE_BACK','HYBRID_DEFENDER','GOALKEEPER') then .65 when secondary_role in ('WIDE_BACK','HOLDING_MIDFIELDER','WING_BACK') then .5 else 0 end,
        case when position in ('DEF','GKP') then .65 else 0 end
      )::numeric defensive_factor,
      case when penalties_order=1 or direct_freekicks_order=1 or corners_and_indirect_freekicks_order=1 then 1::numeric else 0::numeric end setpiece_factor
    from c
  ), agg as (
    select count(*) n,
      count(*) filter(where atkq is not null and defq is not null and recent_minutes is not null) covered_n,
      max(greatest(captured_at,coalesce(role_captured_at,captured_at),coalesce(ability_observed_at,captured_at))) source_at,
      least(1::numeric,sum(loss*usage*atkq*creator_factor*coalesce(ability_confidence,.5))) creator_raw,
      least(1::numeric,sum(loss*usage*atkq*striker_factor*coalesce(ability_confidence,.5))) striker_raw,
      least(1::numeric,sum(loss*usage*defq*defensive_factor*coalesce(ability_confidence,.5))) def_raw,
      least(1::numeric,sum(loss*usage*coalesce(atkq,.5)*setpiece_factor*coalesce(ability_confidence,.5))) setpiece_raw
    from scored
  ) select
    case when n=0 then 0 when covered_n::numeric/nullif(n,0)>=.8 then creator_raw else null end,
    case when n=0 then 0 when covered_n::numeric/nullif(n,0)>=.8 then striker_raw else null end,
    case when n=0 then 0 when covered_n::numeric/nullif(n,0)>=.8 then def_raw else null end,
    case when n=0 then 0 when covered_n::numeric/nullif(n,0)>=.8 then setpiece_raw else null end,
    case when n=0 then 1 else covered_n::numeric/nullif(n,0) end,n,source_at
  into v_creator,v_striker,v_def,v_setpiece,v_abs_cov,v_abs_n,v_abs_at from agg;

  v_input=greatest(p_base_captured,coalesce(v_wide_at,p_base_captured),coalesce(v_aerial_at,p_base_captured),coalesce(v_central_at,p_base_captured),coalesce(v_trans_at,p_base_captured),coalesce(v_pers_at,p_base_captured),coalesce(v_abs_at,p_base_captured));
  v_sources=jsonb_build_object('wide_signal_id',v_wide_id,'aerial_signal_id',v_aerial_id,'central_signal_id',v_central_id,'transition_signal_id',v_trans_id,'personnel_signal_id',v_pers_id,'baseline_prediction_snapshot_id',p_base_id);
  v_vector=jsonb_build_object('wide',v_wide,'aerial_set_piece',v_aerial,'central_creation',v_central,'transition',v_trans,'personnel_disruption',v_pers,'creator_absence_burden',v_creator,'striker_absence_burden',v_striker,'defensive_absence_burden',v_def,'set_piece_absence_burden',v_setpiece,'absence_coverage',v_abs_cov);
  v_hash=encode(extensions.digest(jsonb_build_object('experiment','E0011','match_id',p_match_id,'team_id',p_team_id,'base_id',p_base_id,'input_cutoff',v_input,'vector',v_vector,'sources',v_sources)::text,'sha256'),'hex');

  insert into public.matchup_predictive_feature_snapshots(
    experiment_key,match_id,gameweek,team_id,opponent_team_id,kickoff_time,captured_at,input_cutoff,baseline_prediction_snapshot_id,
    wide_score,wide_confidence,wide_coverage,aerial_set_piece_score,aerial_set_piece_confidence,aerial_set_piece_coverage,
    central_creation_score,central_creation_confidence,central_creation_coverage,transition_score,transition_confidence,transition_coverage,
    personnel_disruption_score,personnel_disruption_confidence,personnel_disruption_coverage,
    creator_absence_burden,striker_absence_burden,defensive_absence_burden,set_piece_absence_burden,absence_coverage,absence_candidate_count,
    feature_vector,source_ids,chronology_valid,actual_data_used,model_effect_enabled,feature_hash
  ) values(
    'E0011',p_match_id,p_gameweek,p_team_id,p_opponent_team_id,p_kickoff,clock_timestamp(),v_input,p_base_id,
    v_wide,v_wide_conf,v_wide_cov,v_aerial,v_aerial_conf,v_aerial_cov,v_central,v_central_conf,v_central_cov,v_trans,v_trans_conf,v_trans_cov,
    v_pers,v_pers_conf,v_pers_cov,v_creator,v_striker,v_def,v_setpiece,v_abs_cov,v_abs_n,v_vector,v_sources,(v_input<p_kickoff),false,false,v_hash
  ) on conflict(feature_hash) do nothing returning id into v_id;
  if v_id is null then select id into v_id from public.matchup_predictive_feature_snapshots where feature_hash=v_hash; end if;
  return v_id;
end $$;

create or replace function private.capture_matchup_predictive_validation_v01(p_gameweek integer default null)
returns jsonb language plpgsql security definer set search_path=public,private,extensions,pg_temp as $$
declare
  v_now timestamptz:=clock_timestamp(); r record; b record;
  h public.matchup_predictive_feature_snapshots%rowtype; a public.matchup_predictive_feature_snapshots%rowtype;
  v_hid bigint;v_aid bigint;v_variant text;v_hadj numeric;v_aadj numeric;v_hlambda numeric;v_alambda numeric;v_markets jsonb;v_manifest jsonb;v_hash text;v_input timestamptz;v_inserted integer:=0;v_features integer:=0;
  v_h_w numeric;v_a_w numeric;v_h_sp numeric;v_a_sp numeric;v_h_c numeric;v_a_c numeric;v_h_t numeric;v_a_t numeric;v_h_pc numeric;v_a_pc numeric;v_h_cr numeric;v_a_cr numeric;v_h_st numeric;v_a_st numeric;v_h_defopp numeric;v_a_defopp numeric;v_h_sa numeric;v_a_sa numeric;
begin
  for r in
    select c.*,m.home_team_id,m.away_team_id
    from public.matchup_predictive_validation_cohort c join public.matches m on m.id=c.match_id
    where c.experiment_key='E0011' and c.kickoff_time>v_now and (p_gameweek is null or c.gameweek=p_gameweek)
    order by c.kickoff_time
  loop
    select fps.* into b from public.fixture_prediction_snapshots fps
    where fps.match_id=r.match_id and fps.is_pre_kickoff=true and fps.captured_at<v_now and fps.captured_at<r.kickoff_time
      and coalesce(fps.source_snapshot->>'generator','')='forward_fixture_v0.1.3'
    order by fps.captured_at desc,fps.id desc limit 1;
    if b.id is null then continue; end if;

    v_hid=private.c0147_capture_side_feature_v01(r.match_id,r.gameweek,r.home_team_id,r.away_team_id,r.kickoff_time,b.id,b.captured_at,least(v_now,r.kickoff_time));
    v_aid=private.c0147_capture_side_feature_v01(r.match_id,r.gameweek,r.away_team_id,r.home_team_id,r.kickoff_time,b.id,b.captured_at,least(v_now,r.kickoff_time));
    select * into h from public.matchup_predictive_feature_snapshots where id=v_hid;
    select * into a from public.matchup_predictive_feature_snapshots where id=v_aid;
    v_features:=v_features+2;
    if not h.chronology_valid or not a.chronology_valid then continue; end if;

    v_h_w=coalesce((h.wide_score-.5)*2*.04*h.wide_confidence*h.wide_coverage,0);
    v_a_w=coalesce((a.wide_score-.5)*2*.04*a.wide_confidence*a.wide_coverage,0);
    v_h_sp=coalesce((h.aerial_set_piece_score-.5)*2*.035*h.aerial_set_piece_confidence*h.aerial_set_piece_coverage,0);
    v_a_sp=coalesce((a.aerial_set_piece_score-.5)*2*.035*a.aerial_set_piece_confidence*a.aerial_set_piece_coverage,0);
    v_h_c=coalesce((h.central_creation_score-.5)*2*.05*h.central_creation_confidence*h.central_creation_coverage,0);
    v_a_c=coalesce((a.central_creation_score-.5)*2*.05*a.central_creation_confidence*a.central_creation_coverage,0);
    v_h_t=coalesce(greatest(h.transition_score-.55,0)/.45*.025*h.transition_confidence*h.transition_coverage,0);
    v_a_t=coalesce(greatest(a.transition_score-.55,0)/.45*.025*a.transition_confidence*a.transition_coverage,0);
    v_h_pc=coalesce(-h.personnel_disruption_score*h.personnel_disruption_confidence*.04 + a.personnel_disruption_score*a.personnel_disruption_confidence*.03,0);
    v_a_pc=coalesce(-a.personnel_disruption_score*a.personnel_disruption_confidence*.04 + h.personnel_disruption_score*h.personnel_disruption_confidence*.03,0);
    v_h_cr=coalesce(-h.creator_absence_burden*.06,0); v_a_cr=coalesce(-a.creator_absence_burden*.06,0);
    v_h_st=coalesce(-h.striker_absence_burden*.07,0); v_a_st=coalesce(-a.striker_absence_burden*.07,0);
    v_h_defopp=coalesce(a.defensive_absence_burden*.05,0); v_a_defopp=coalesce(h.defensive_absence_burden*.05,0);
    v_h_sa=coalesce(-h.set_piece_absence_burden*.03,0); v_a_sa=coalesce(-a.set_piece_absence_burden*.03,0);

    foreach v_variant in array array['BASE','WIDE_ONLY','AERIAL_SET_PIECE_ONLY','CENTRAL_ONLY','TRANSITION_ONLY','PERSONNEL_CONTINUITY_ONLY','CREATOR_ABSENCE_ONLY','STRIKER_ABSENCE_ONLY','DEFENSIVE_ABSENCE_ONLY','SET_PIECE_ABSENCE_ONLY','COMBINED_V01'] loop
      v_hadj=case v_variant
        when 'BASE' then 0 when 'WIDE_ONLY' then v_h_w when 'AERIAL_SET_PIECE_ONLY' then v_h_sp when 'CENTRAL_ONLY' then v_h_c when 'TRANSITION_ONLY' then v_h_t
        when 'PERSONNEL_CONTINUITY_ONLY' then v_h_pc when 'CREATOR_ABSENCE_ONLY' then v_h_cr when 'STRIKER_ABSENCE_ONLY' then v_h_st
        when 'DEFENSIVE_ABSENCE_ONLY' then v_h_defopp when 'SET_PIECE_ABSENCE_ONLY' then v_h_sa
        else greatest(-.12,least(.12,v_h_w+v_h_sp+v_h_c+v_h_t+v_h_cr+v_h_st+v_h_defopp+v_h_sa)) end;
      v_aadj=case v_variant
        when 'BASE' then 0 when 'WIDE_ONLY' then v_a_w when 'AERIAL_SET_PIECE_ONLY' then v_a_sp when 'CENTRAL_ONLY' then v_a_c when 'TRANSITION_ONLY' then v_a_t
        when 'PERSONNEL_CONTINUITY_ONLY' then v_a_pc when 'CREATOR_ABSENCE_ONLY' then v_a_cr when 'STRIKER_ABSENCE_ONLY' then v_a_st
        when 'DEFENSIVE_ABSENCE_ONLY' then v_a_defopp when 'SET_PIECE_ABSENCE_ONLY' then v_a_sa
        else greatest(-.12,least(.12,v_a_w+v_a_sp+v_a_c+v_a_t+v_a_cr+v_a_st+v_a_defopp+v_a_sa)) end;

      v_hlambda=round((b.home_lambda*exp(v_hadj::double precision))::numeric,6);
      v_alambda=round((b.away_lambda*exp(v_aadj::double precision))::numeric,6);
      v_markets=private.c0147_poisson_markets_v01(v_hlambda,v_alambda);
      v_input=greatest(b.captured_at,h.input_cutoff,a.input_cutoff);
      v_manifest=jsonb_build_object('policy','matchup_shadow_ablation_v0.1','variant',v_variant,'home_log_adjustment',v_hadj,'away_log_adjustment',v_aadj,'caps',jsonb_build_object('wide',.04,'aerial_set_piece',.035,'central',.05,'transition',.025,'creator_absence',.06,'striker_absence',.07,'opponent_defensive_absence',.05,'set_piece_absence',.03,'combined_total',.12),'missing_components','ignored_not_zero','model_effect_enabled',false);
      v_hash=encode(extensions.digest(jsonb_build_object('experiment','E0011','match_id',r.match_id,'variant',v_variant,'base_id',b.id,'home_feature',h.feature_hash,'away_feature',a.feature_hash,'home_lambda',v_hlambda,'away_lambda',v_alambda,'input_cutoff',v_input)::text,'sha256'),'hex');

      insert into public.matchup_predictive_predictions(
        experiment_key,match_id,gameweek,split,variant_key,home_feature_snapshot_id,away_feature_snapshot_id,base_prediction_snapshot_id,captured_at,input_cutoff,kickoff_time,
        home_log_adjustment,away_log_adjustment,baseline_home_lambda,baseline_away_lambda,home_lambda,away_lambda,markets,adjustment_manifest,prediction_hash,chronology_valid,actual_data_used,model_effect_enabled
      ) values(
        'E0011',r.match_id,r.gameweek,r.split,v_variant,h.id,a.id,b.id,v_now,v_input,r.kickoff_time,v_hadj,v_aadj,b.home_lambda,b.away_lambda,v_hlambda,v_alambda,v_markets,v_manifest,v_hash,(v_input<r.kickoff_time),false,false
      ) on conflict(prediction_hash) do nothing;
      if found then v_inserted:=v_inserted+1; end if;
    end loop;
  end loop;
  return jsonb_build_object('ok',true,'experiment_key','E0011','captured_at',v_now,'gameweek_filter',p_gameweek,'feature_rows_touched',v_features,'prediction_rows_inserted',v_inserted);
end $$;

create or replace function private.evaluate_matchup_predictive_validation_v01()
returns jsonb language plpgsql security definer set search_path=public,private,pg_temp as $$
declare v_n integer:=0;
begin
  with latest as (
    select distinct on(p.match_id,p.variant_key) p.*
    from public.matchup_predictive_predictions p
    join public.matchup_predictive_validation_cohort c on c.experiment_key=p.experiment_key and c.match_id=p.match_id
    where p.experiment_key='E0011' and p.chronology_valid=true and p.input_cutoff<p.kickoff_time
    order by p.match_id,p.variant_key,p.input_cutoff desc,p.id desc
  ), actuals as (
    select l.*,m.home_score,m.away_score,coalesce(m.home_xg,x.home_xg) home_xg,coalesce(m.away_xg,x.away_xg) away_xg
    from latest l join public.matches m on m.id=l.match_id and m.finished=true
    left join lateral (
      select mm.home_xg,mm.away_xg
      from public.matches mm
      where mm.home_team_id=m.home_team_id and mm.away_team_id=m.away_team_id and mm.home_xg is not null
        and abs(extract(epoch from(mm.kickoff_time-m.kickoff_time)))<21600
      order by abs(extract(epoch from(mm.kickoff_time-m.kickoff_time))),mm.updated_at desc limit 1
    ) x on true
  ), calc as (
    select a.*,
      ((coalesce((markets->>'home_win')::numeric,0)-(case when home_score>away_score then 1 else 0 end))^2 +
       (coalesce((markets->>'draw')::numeric,0)-(case when home_score=away_score then 1 else 0 end))^2 +
       (coalesce((markets->>'away_win')::numeric,0)-(case when home_score<away_score then 1 else 0 end))^2)::numeric brier,
      -ln(greatest(1e-12::numeric,(exp(-home_lambda::double precision)*power(home_lambda::double precision,home_score)/factorial(home_score)::double precision * exp(-away_lambda::double precision)*power(away_lambda::double precision,away_score)/factorial(away_score)::double precision)::numeric)) score_ll,
      (abs(home_lambda-home_score)+abs(away_lambda-away_score))/2 goals_mae_v,
      case when home_xg is not null and away_xg is not null then (abs(home_lambda-home_xg)+abs(away_lambda-away_xg))/2 end process_mae_v,
      power(coalesce((markets->>'over_2_5')::numeric,0)-(case when home_score+away_score>=3 then 1 else 0 end),2) over_brier,
      power(coalesce((markets->>'btts_yes')::numeric,0)-(case when home_score>0 and away_score>0 then 1 else 0 end),2) btts_brier_v,
      ((home_lambda>away_lambda and home_score>away_score) or (home_lambda<away_lambda and home_score<away_score) or (abs(home_lambda-away_lambda)<.05 and home_score=away_score)) direction_hit_v
    from actuals a
  )
  insert into public.matchup_predictive_evaluations(
    experiment_key,prediction_id,match_id,gameweek,split,variant_key,actual_home_goals,actual_away_goals,actual_home_xg,actual_away_xg,brier_1x2,score_log_loss,goals_mae,process_mae,over_2_5_brier,btts_brier,direction_hit,evaluation_evidence,actual_data_used,model_effect_enabled
  )
  select 'E0011',id,match_id,gameweek,split,variant_key,home_score,away_score,home_xg,away_xg,brier,score_ll,goals_mae_v,process_mae_v,over_brier,btts_brier_v,direction_hit_v,
    jsonb_build_object('prediction_input_cutoff',input_cutoff,'kickoff_time',kickoff_time,'latest_pre_kickoff_prediction',true,'target_actual_data_used_in_generation',false),true,false
  from calc
  on conflict(experiment_key,match_id,variant_key) do nothing;
  get diagnostics v_n=row_count;
  return jsonb_build_object('ok',true,'experiment_key','E0011','evaluations_inserted',v_n,'evaluated_at',clock_timestamp());
end $$;

create or replace function private.matchup_predictive_validation_status_v01()
returns jsonb language sql security definer set search_path=public,private,pg_temp as $$
with cohort as (
  select split,count(*) fixtures from public.matchup_predictive_validation_cohort where experiment_key='E0011' group by split
), a as (
  select e.split,e.variant_key,count(*) n,avg(e.brier_1x2) brier,avg(e.score_log_loss) log_loss,avg(e.goals_mae) goals_mae,avg(e.process_mae) process_mae,
    avg(e.over_2_5_brier) over_brier,avg(e.btts_brier) btts_brier,avg((e.direction_hit)::int::numeric) direction_accuracy,
    count(*) filter(where greatest(abs(p.home_log_adjustment),abs(p.away_log_adjustment))>=.005) activated_n
  from public.matchup_predictive_evaluations e join public.matchup_predictive_predictions p on p.id=e.prediction_id
  where e.experiment_key='E0011' group by e.split,e.variant_key
), b as (select * from a where variant_key='BASE'), metrics as (
  select a.*,a.brier-b.brier brier_delta,a.log_loss-b.log_loss log_loss_delta,a.goals_mae-b.goals_mae goals_mae_delta,
    case when a.process_mae is not null and b.process_mae is not null then a.process_mae-b.process_mae end process_mae_delta
  from a join b using(split)
), integ as (
  select
    (select count(*) from public.matchup_predictive_predictions where experiment_key='E0011' and (not chronology_valid or input_cutoff>=kickoff_time or actual_data_used or model_effect_enabled)) prediction_violations,
    (select count(*) from public.matchup_predictive_feature_snapshots where experiment_key='E0011' and (not chronology_valid or input_cutoff>=kickoff_time or actual_data_used or model_effect_enabled)) feature_violations,
    (select count(*) from public.matchup_predictive_evaluations where experiment_key='E0011' and model_effect_enabled) evaluation_effect_violations,
    (select count(*) from (select match_id,variant_key,count(*) n from public.matchup_predictive_evaluations where experiment_key='E0011' group by match_id,variant_key having count(*)>1) d) duplicate_evaluations
), counts as (
  select coalesce((select count(distinct match_id) from public.matchup_predictive_evaluations where experiment_key='E0011' and split='VALIDATION'),0) val_n,
    coalesce((select count(distinct match_id) from public.matchup_predictive_evaluations where experiment_key='E0011' and split='TEST'),0) test_n
)
select jsonb_build_object(
  'ok',true,'experiment_key','E0011','change_id','C0147','model_effect_enabled',false,
  'policy',jsonb_build_object('validation_gameweeks',jsonb_build_array(3,4,5,6),'test_gameweeks',jsonb_build_array(7,8,9,10),'no_retuning_between_splits',true,'minimum_validation_fixtures',40,'minimum_test_fixtures',40,'minimum_signal_activations_per_split',8,'promotion','manual_new_change_id_only','noise_control','must improve both 1X2 Brier and score log loss in validation and test; process MAE must not regress >2% where available'),
  'cohort',(select coalesce(jsonb_agg(jsonb_build_object('split',split,'fixtures',fixtures) order by split),'[]'::jsonb) from cohort),
  'metrics',(select coalesce(jsonb_agg(jsonb_build_object('split',split,'variant_key',variant_key,'n',n,'activated_n',activated_n,'brier',brier,'brier_delta',brier_delta,'score_log_loss',log_loss,'log_loss_delta',log_loss_delta,'goals_mae',goals_mae,'goals_mae_delta',goals_mae_delta,'process_mae',process_mae,'process_mae_delta',process_mae_delta,'over_2_5_brier',over_brier,'btts_brier',btts_brier,'direction_accuracy',direction_accuracy) order by split,variant_key),'[]'::jsonb) from metrics),
  'integrity',(select to_jsonb(integ) from integ),
  'decision_state',(select case when val_n<40 then 'ACCUMULATING_VALIDATION_GW3_GW6' when test_n<40 then 'VALIDATION_COMPLETE_ACCUMULATING_TEST_GW7_GW10' else 'READY_FOR_MANUAL_REVIEW_NO_AUTO_PROMOTION' end from counts)
)
$$;

revoke all on function private.c0147_capture_side_feature_v01(bigint,integer,bigint,bigint,timestamptz,bigint,timestamptz,timestamptz) from public,anon,authenticated;
revoke all on function private.capture_matchup_predictive_validation_v01(integer) from public,anon,authenticated;
revoke all on function private.evaluate_matchup_predictive_validation_v01() from public,anon,authenticated;
revoke all on function private.matchup_predictive_validation_status_v01() from public,anon,authenticated;
grant execute on function private.capture_matchup_predictive_validation_v01(integer) to service_role;
grant execute on function private.evaluate_matchup_predictive_validation_v01() to service_role;
grant execute on function private.matchup_predictive_validation_status_v01() to service_role;

insert into public.research_experiments(
  experiment_key,change_id,parent_experiment_key,experiment_name,purpose,hypothesis,experiment_type,feature_schema_version,feature_families,
  baseline_model_version,candidate_model_version,outcome_model_version,chronology_policy,train_window,validation_window,test_window,coefficient_manifest,external_refs,
  definition_hash,status,actual_data_allowed_in_generation,forward_valid,model_effect_enabled,created_by
)
select 'E0011','C0147','E0008','Prospective matchup predictive validation v0.1',
  'Test whether pre-kickoff tactical matchup and role-specific absence signals improve fixture probability and goal-process forecasts beyond the production baseline without outcome-driven tuning.',
  'Wide pressure, aerial/set-piece mismatch, central creation, transition opportunity and role-specific creator/striker/defensive/set-piece absences contain incremental forward predictive information.',
  'ABLATION','matchup_predictive_features_v0.1',
  '["wide_channel_pressure","aerial_set_piece_mismatch","central_creation_vs_block","direct_transition_opportunity","personnel_disruption","creator_absence","striker_absence","defensive_absence","set_piece_absence"]'::jsonb,
  'forward_fixture_v0.1.3','matchup_shadow_ablation_v0.1','independent_poisson',
  '{"latest_pre_kickoff_only":true,"evidence_cutoff_before_kickoff":true,"actual_target_data_forbidden_in_generation":true,"historical_gw1_gw2_excluded_from_selection":true,"no_retuning_between_validation_and_test":true}'::jsonb,
  null,'{"gameweeks":[3,4,5,6],"fixtures":40,"role":"VALIDATION"}'::jsonb,'{"gameweeks":[7,8,9,10],"fixtures":40,"role":"TEST"}'::jsonb,
  '{"wide_max_log":0.04,"aerial_set_piece_max_log":0.035,"central_creation_max_log":0.05,"transition_positive_max_log":0.025,"creator_absence_max_log":0.06,"striker_absence_max_log":0.07,"opponent_defensive_absence_max_log":0.05,"set_piece_absence_max_log":0.03,"personnel_continuity_own_max_log":0.04,"personnel_continuity_opponent_max_log":0.03,"combined_cap_abs_log":0.12,"variants":["BASE","WIDE_ONLY","AERIAL_SET_PIECE_ONLY","CENTRAL_ONLY","TRANSITION_ONLY","PERSONNEL_CONTINUITY_ONLY","CREATOR_ABSENCE_ONLY","STRIKER_ABSENCE_ONLY","DEFENSIVE_ABSENCE_ONLY","SET_PIECE_ABSENCE_ONLY","COMBINED_V01"]}'::jsonb,
  '{"design_note":"C0147 pre-registered before GW3 kickoff; GW1/GW2 outcomes may not select coefficients."}'::jsonb,
  encode(extensions.digest('E0011|C0147|matchup_predictive_features_v0.1|GW3-6_VALIDATION|GW7-10_TEST|fixed_coefficients_v0.1','sha256'),'hex'),
  'REGISTERED',false,true,false,'service_role'
where not exists(select 1 from public.research_experiments where experiment_key='E0011');

insert into public.matchup_predictive_validation_cohort(experiment_key,change_id,match_id,gameweek,split,kickoff_time,definition,actual_data_used,model_effect_enabled)
select 'E0011','C0147',m.id,m.gameweek,case when m.gameweek between 3 and 6 then 'VALIDATION' else 'TEST' end,m.kickoff_time,
  jsonb_build_object('pre_registered_before_gw3',true,'source','FPL fixture schedule','selection','all Premier League fixtures in GW3-GW10'),false,false
from public.matches m
where m.source='fpl' and m.gameweek between 3 and 10
on conflict(experiment_key,match_id) do nothing;

insert into public.change_tracker_working(
  change_id,parent_id,workstream,item_type,title,description,status,delivery_stage,priority,phase,depends_on,acceptance_criteria,model_effect,integrity_rule,
  implementation_refs,notes,last_updated,temporary_working_ledger,decision_required,decision_refs
)
values(
  'C0147','C0146','Model Validation','Experiment','Matchup Predictive Validation layer',
  'Prospective fixed-coefficient ablation and forward-scoring layer for tactical matchup and role-specific absence signals.',
  'In Progress','Executed','High','Phase 4',array['C0146','C0082','C0091'],
  'Pre-register GW3-GW6 validation and GW7-GW10 test cohorts before GW3; capture immutable pre-kickoff feature/prediction snapshots; evaluate BASE vs single-signal and combined variants on Brier, score log loss, goals MAE and process MAE; preserve missing-is-not-zero; no model activation without independent forward evidence and a new manual Change ID.',
  'Observational research only; model_effect_enabled=false.',
  'GW1/GW2 outcomes cannot tune C0147 coefficients. Validation/test split is frozen before GW3. Latest pre-kickoff only; actual target data forbidden in generation; append-only predictions/evaluations; no automatic promotion.',
  array['supabase:migration:c0147_matchup_predictive_validation_v01','supabase:experiment:E0011','supabase:function:private.capture_matchup_predictive_validation_v01','supabase:function:private.evaluate_matchup_predictive_validation_v01','supabase:function:private.matchup_predictive_validation_status_v01'],
  'Fixed structural-prior coefficients only. Promotion gate requires forward evidence; GW1/GW2 are explicitly excluded from coefficient selection.',clock_timestamp(),true,true,array['research_experiment:E0011']
) on conflict(change_id) do nothing;

select cron.unschedule(jobid) from cron.job where jobname in ('c0147_matchup_predictive_capture','c0147_matchup_predictive_evaluate');
select cron.schedule('c0147_matchup_predictive_capture','*/15 * * * *',$$select private.capture_matchup_predictive_validation_v01(null);$$);
select cron.schedule('c0147_matchup_predictive_evaluate','17 * * * *',$$select private.evaluate_matchup_predictive_validation_v01();$$);
