create table if not exists public.fpl_full_pool_optimizer_runs(
  id bigint generated by default as identity primary key,
  captured_at timestamptz not null default clock_timestamp(),
  request_id bigint,
  gameweek integer not null,
  horizon integer not null,
  optimizer_version text not null,
  model_version text,
  source_pool_count integer,
  xmins_top_n integer,
  explosive_exception_count integer,
  candidate_counts jsonb not null default '{}'::jsonb,
  prediction_runs jsonb not null default '[]'::jsonb,
  objective numeric,
  objective_gap_to_second numeric,
  model_error_margin_points numeric,
  edge_classification text,
  cost_tenths integer,
  itb_tenths integer,
  transfers_in integer,
  search_method text,
  search_exact boolean not null default false,
  decisioning boolean not null default false,
  writes_manager_plan boolean not null default false,
  result_status text not null,
  evidence jsonb not null default '{}'::jsonb,
  change_id text not null default 'C0213'
);
create index if not exists fpl_full_pool_optimizer_runs_gw_time_idx on public.fpl_full_pool_optimizer_runs(gameweek,captured_at desc,id desc);
alter table public.fpl_full_pool_optimizer_runs enable row level security;
revoke all on table public.fpl_full_pool_optimizer_runs from anon,authenticated;
grant select,insert on table public.fpl_full_pool_optimizer_runs to service_role;
grant usage,select on sequence public.fpl_full_pool_optimizer_runs_id_seq to service_role;

create or replace function private.block_fpl_full_pool_optimizer_run_mutation_v01()
returns trigger language plpgsql set search_path='private','pg_temp' as $$
begin raise exception 'fpl_full_pool_optimizer_runs is append-only'; end $$;
drop trigger if exists trg_block_fpl_full_pool_optimizer_run_update_delete on public.fpl_full_pool_optimizer_runs;
create trigger trg_block_fpl_full_pool_optimizer_run_update_delete before update or delete on public.fpl_full_pool_optimizer_runs for each row execute function private.block_fpl_full_pool_optimizer_run_mutation_v01();

create or replace function private.capture_c0213_optimizer_response_v01(p_request_id bigint)
returns jsonb
language plpgsql
security definer
set search_path='private','public','net','pg_temp'
as $$
declare v_code integer; v_body jsonb; v_id bigint;
begin
  select status_code,content::jsonb into v_code,v_body from net._http_response where id=p_request_id;
  if v_code is null then return jsonb_build_object('ok',false,'status','RESPONSE_NOT_AVAILABLE','request_id',p_request_id); end if;
  if v_code<>200 or not coalesce((v_body->>'ok')::boolean,false) then
    return jsonb_build_object('ok',false,'status','OPTIMIZER_RESPONSE_NOT_SUCCESS','request_id',p_request_id,'status_code',v_code,'body',v_body);
  end if;
  if exists(select 1 from public.fpl_full_pool_optimizer_runs where request_id=p_request_id) then
    select id into v_id from public.fpl_full_pool_optimizer_runs where request_id=p_request_id order by id desc limit 1;
    return jsonb_build_object('ok',true,'status','ALREADY_CAPTURED','request_id',p_request_id,'optimizer_run_id',v_id);
  end if;
  insert into public.fpl_full_pool_optimizer_runs(
    request_id,gameweek,horizon,optimizer_version,model_version,source_pool_count,xmins_top_n,explosive_exception_count,candidate_counts,prediction_runs,
    objective,objective_gap_to_second,model_error_margin_points,edge_classification,cost_tenths,itb_tenths,transfers_in,search_method,search_exact,decisioning,writes_manager_plan,result_status,evidence
  ) values(
    p_request_id,(v_body->>'gameweek')::integer,(v_body->>'horizon')::integer,v_body->>'optimizer_version',v_body->>'model_version',
    nullif(v_body->>'source_pool_count','')::integer,nullif(v_body->>'xmins_top_n','')::integer,nullif(v_body->>'explosive_exception_count','')::integer,
    coalesce(v_body->'candidate_counts','{}'::jsonb),coalesce(v_body->'prediction_runs','[]'::jsonb),
    nullif(v_body#>>'{best,objective}','')::numeric,nullif(v_body->>'objective_gap_to_second','')::numeric,nullif(v_body->>'model_error_margin_points','')::numeric,v_body->>'edge_classification',
    nullif(v_body#>>'{best,cost_tenths}','')::integer,nullif(v_body#>>'{best,itb_tenths}','')::integer,nullif(v_body#>>'{best,transfers_in}','')::integer,
    v_body->>'search_method',coalesce((v_body->>'search_exact')::boolean,false),coalesce((v_body->>'decisioning')::boolean,false),coalesce((v_body->>'writes_manager_plan')::boolean,false),
    v_body->>'status',jsonb_build_object('constraints',v_body->'constraints','notes',v_body->'notes','weights',v_body->'weights','gws',v_body->'gws')
  ) returning id into v_id;
  return jsonb_build_object('ok',true,'status','CAPTURED','request_id',p_request_id,'optimizer_run_id',v_id);
end $$;
revoke all on function private.capture_c0213_optimizer_response_v01(bigint) from public,anon,authenticated;
grant execute on function private.capture_c0213_optimizer_response_v01(bigint) to service_role;
