-- Fixture-specific Tactical Matchup Intelligence v0.1.1.
-- Research only. No score in this layer changes xPts, fixture lambdas, or betting probabilities.

create table if not exists public.fixture_tactical_matchup_observations (
  id bigint generated by default as identity primary key,
  match_id bigint not null references public.matches(id),
  gameweek integer not null,
  team_id bigint not null references public.teams(id),
  opponent_team_id bigint not null references public.teams(id),
  kickoff_time timestamptz not null,
  captured_at timestamptz not null default clock_timestamp(),
  evidence_cutoff timestamptz,
  signal_family text not null,
  signal_key text not null,
  score_type text not null check (score_type in ('ADVANTAGE','OPPORTUNITY','DISRUPTION')),
  score numeric check (score is null or (score >= 0 and score <= 1)),
  direction text not null,
  attacking_component numeric check (attacking_component is null or (attacking_component >= 0 and attacking_component <= 1)),
  resistance_component numeric check (resistance_component is null or (resistance_component >= 0 and resistance_component <= 1)),
  confidence numeric check (confidence is null or (confidence >= 0 and confidence <= 1)),
  data_coverage numeric check (data_coverage is null or (data_coverage >= 0 and data_coverage <= 1)),
  team_tactical_observation_id bigint references public.team_fixture_tactical_observations(id),
  opponent_tactical_observation_id bigint references public.team_fixture_tactical_observations(id),
  evidence jsonb not null default '{}'::jsonb,
  observation_hash text not null,
  model_effect_enabled boolean not null default false check (model_effect_enabled=false),
  unique(match_id,team_id,signal_key,observation_hash)
);

alter table public.fixture_tactical_matchup_observations enable row level security;
revoke all on public.fixture_tactical_matchup_observations from public,anon,authenticated;
grant select,insert,update,delete on public.fixture_tactical_matchup_observations to service_role;
grant usage,select on sequence public.fixture_tactical_matchup_observations_id_seq to service_role;

create index if not exists fixture_tactical_matchup_match_team_idx on public.fixture_tactical_matchup_observations(match_id,team_id,captured_at desc);
create index if not exists fixture_tactical_matchup_signal_idx on public.fixture_tactical_matchup_observations(signal_family,signal_key,captured_at desc);
create index if not exists fixture_tactical_matchup_team_tact_fk_idx on public.fixture_tactical_matchup_observations(team_tactical_observation_id);
create index if not exists fixture_tactical_matchup_opp_tact_fk_idx on public.fixture_tactical_matchup_observations(opponent_tactical_observation_id);
create index if not exists fixture_tactical_matchup_team_fk_idx on public.fixture_tactical_matchup_observations(team_id);
create index if not exists fixture_tactical_matchup_opp_team_fk_idx on public.fixture_tactical_matchup_observations(opponent_team_id);

create or replace function private.guard_tactical_matchup_preko()
returns trigger
language plpgsql
set search_path=private,public,pg_temp
as $$
declare m record;
begin
  select id,kickoff_time,home_team_id,away_team_id into m from public.matches where id=new.match_id;
  if not found then raise exception 'match not found'; end if;
  if new.kickoff_time is distinct from m.kickoff_time then raise exception 'kickoff mismatch'; end if;
  if new.captured_at >= m.kickoff_time or now() >= m.kickoff_time then raise exception 'fixture tactical matchup frozen at kickoff'; end if;
  if new.evidence_cutoff is not null and new.evidence_cutoff >= m.kickoff_time then raise exception 'tactical matchup evidence cutoff must be pre-kickoff'; end if;
  if not ((new.team_id=m.home_team_id and new.opponent_team_id=m.away_team_id) or (new.team_id=m.away_team_id and new.opponent_team_id=m.home_team_id)) then raise exception 'team/opponent mismatch'; end if;
  return new;
end $$;

drop trigger if exists trg_fixture_tactical_matchup_preko on public.fixture_tactical_matchup_observations;
create trigger trg_fixture_tactical_matchup_preko before insert or update on public.fixture_tactical_matchup_observations for each row execute function private.guard_tactical_matchup_preko();

create or replace view public.current_fixture_tactical_matchups
with (security_invoker=true) as
select distinct on (match_id,team_id,signal_key) *
from public.fixture_tactical_matchup_observations
order by match_id,team_id,signal_key,captured_at desc,id desc;
revoke all on public.current_fixture_tactical_matchups from public,anon,authenticated;
grant select on public.current_fixture_tactical_matchups to service_role;

create or replace function public.refresh_fixture_tactical_matchups_v01(p_gameweek integer default null)
returns jsonb
language plpgsql
security invoker
set search_path=public,private,pg_temp
as $$
declare v_now timestamptz:=clock_timestamp(); v_gw integer:=p_gameweek; v_inserted integer:=0;
begin
  if v_gw is null then select gameweek into v_gw from public.matches where source='fpl' and gameweek is not null and kickoff_time>v_now order by kickoff_time limit 1; end if;
  if v_gw is null then return jsonb_build_object('ok',true,'gameweek',null,'inserted',0,'model_effect_enabled',false); end if;

  with future as materialized (
    select id match_id,gameweek,kickoff_time,home_team_id,away_team_id from public.matches where source='fpl' and gameweek=v_gw and kickoff_time>v_now
  ), sides as materialized (
    select match_id,gameweek,kickoff_time,home_team_id team_id,away_team_id opponent_team_id from future
    union all select match_id,gameweek,kickoff_time,away_team_id,home_team_id from future
  ), role_rows as materialized (
    select a.match_id,a.team_id,a.player_id,a.expected_xi,p.position,r.primary_role,r.confidence role_conf,r.captured_at role_captured_at,pr.feature_vector
    from public.current_player_fixture_availability a
    join future f on f.match_id=a.match_id
    join public.players p on p.id=a.player_id
    left join public.current_player_fixture_roles r on r.match_id=a.match_id and r.team_id=a.team_id and r.player_id=a.player_id and r.taxonomy_version='event_role_v0.2.1'
    left join public.player_role_profile_observations pr on pr.player_id=r.player_id and pr.observed_at=r.profile_observed_at and pr.taxonomy_version=r.taxonomy_version
    where a.expected_xi=true
  ), role_agg as materialized (
    select match_id,team_id,count(*) xi_expected,count(*) filter(where feature_vector is not null) role_covered,max(role_captured_at) role_captured_at,
      avg(role_conf) filter(where feature_vector is not null) role_conf,
      avg((feature_vector->>'width')::numeric) filter(where feature_vector ? 'width') xi_width,
      avg((feature_vector->>'creation')::numeric) filter(where feature_vector ? 'creation') xi_creation,
      avg((feature_vector->>'progression')::numeric) filter(where feature_vector ? 'progression') xi_progression,
      avg((feature_vector->>'shot_threat')::numeric) filter(where feature_vector ? 'shot_threat') xi_shot,
      avg((feature_vector->>'box_occupation')::numeric) filter(where feature_vector ? 'box_occupation') xi_box,
      avg((feature_vector->>'defensive_load')::numeric) filter(where feature_vector ? 'defensive_load') xi_def,
      avg((feature_vector->>'aerial')::numeric) filter(where feature_vector ? 'aerial' and position in ('MID','FWD')) attacker_aerial,
      avg((feature_vector->>'aerial')::numeric) filter(where feature_vector ? 'aerial' and position='DEF') defender_aerial,
      (count(*) filter(where primary_role in ('WIDE_BACK','WING_BACK','WIDE_ATTACKER','WIDE_FORWARD')))::numeric/nullif(count(*) filter(where feature_vector is not null),0) wide_role_share,
      (count(*) filter(where primary_role in ('CREATOR_10','BOX_TO_BOX','LINK_FORWARD')))::numeric/nullif(count(*) filter(where feature_vector is not null),0) creator_role_share
    from role_rows group by match_id,team_id
  ), replacement_agg as materialized (
    select b.match_id,b.team_id,count(*) target_count,count(distinct b.candidate_player_id) candidate_count,max(b.captured_at) replacement_captured_at,
      avg(b.confidence) replacement_confidence,
      max(((b.evidence->>'absence_relevance_proxy')::numeric) * (1-coalesce(b.composite_score,b.role_fit_score)) * case when a.chance_of_playing is not null then greatest(0::numeric,least(1::numeric,1-a.chance_of_playing)) else 1::numeric end) max_individual_disruption,
      count(*) filter(where b.quality_status='ROLE_FIT_ONLY') role_fit_only_count,
      count(*) filter(where b.quality_status='PROXY_NOT_VALIDATED') proxy_count
    from public.current_best_replacement_quality b join future f on f.match_id=b.match_id
    left join public.player_fixture_availability_observations a on a.id=b.target_availability_observation_id
    group by b.match_id,b.team_id
  ), base as materialized (
    select s.*,tt.id team_tactical_observation_id,ot.id opponent_tactical_observation_id,
      tt.captured_at team_tactical_captured_at,ot.captured_at opponent_tactical_captured_at,
      tt.possession_control_score team_control,tt.directness_score team_directness,tt.width_score team_width,tt.set_piece_score team_set_piece,tt.defensive_block_score team_defensive_block,tt.confidence team_tactical_confidence,
      ot.possession_control_score opponent_control,ot.defensive_block_score opponent_defensive_block,ot.confidence opponent_tactical_confidence,
      r.xi_expected,r.role_covered,r.role_captured_at,r.role_conf,r.xi_width,r.xi_creation,r.xi_progression,r.xi_shot,r.xi_box,r.xi_def,r.attacker_aerial,r.defender_aerial,r.wide_role_share,r.creator_role_share,
      ro.xi_expected opponent_xi_expected,ro.role_covered opponent_role_covered,ro.role_captured_at opponent_role_captured_at,ro.role_conf opponent_role_conf,ro.xi_def opponent_xi_def,ro.defender_aerial opponent_defender_aerial,ro.wide_role_share opponent_wide_role_share,
      rep.target_count,rep.candidate_count,rep.replacement_captured_at,rep.replacement_confidence,rep.max_individual_disruption,rep.role_fit_only_count,rep.proxy_count,
      case when r.xi_expected>0 then r.role_covered::numeric/r.xi_expected end role_coverage,
      case when ro.xi_expected>0 then ro.role_covered::numeric/ro.xi_expected end opponent_role_coverage
    from sides s
    left join public.current_team_fixture_tactics tt on tt.match_id=s.match_id and tt.team_id=s.team_id
    left join public.current_team_fixture_tactics ot on ot.match_id=s.match_id and ot.team_id=s.opponent_team_id
    left join role_agg r on r.match_id=s.match_id and r.team_id=s.team_id
    left join role_agg ro on ro.match_id=s.match_id and ro.team_id=s.opponent_team_id
    left join replacement_agg rep on rep.match_id=s.match_id and rep.team_id=s.team_id
  ), components as materialized (
    select b.*,
      private.weighted_mean(array[team_width,xi_width,xi_creation,wide_role_share],array[.38,.22,.20,.20]::numeric[]) wide_attack,
      private.weighted_mean(array[opponent_defensive_block,opponent_xi_def,opponent_wide_role_share],array[.45,.35,.20]::numeric[]) wide_resistance,
      private.weighted_mean(array[team_set_piece,team_width,attacker_aerial],array[.45,.20,.35]::numeric[]) aerial_attack,
      private.weighted_mean(array[opponent_defender_aerial,opponent_xi_def],array[.55,.45]::numeric[]) aerial_resistance,
      private.weighted_mean(array[team_control,xi_creation,xi_progression,creator_role_share],array[.30,.30,.25,.15]::numeric[]) central_attack,
      private.weighted_mean(array[opponent_defensive_block,opponent_xi_def],array[.55,.45]::numeric[]) central_resistance,
      private.weighted_mean(array[team_directness,xi_shot,xi_box,opponent_control,case when opponent_defensive_block is null then null else 1-opponent_defensive_block end],array[.30,.20,.15,.20,.15]::numeric[]) transition_opportunity,
      least(.80,private.weighted_mean(array[team_tactical_confidence,opponent_tactical_confidence,role_conf,opponent_role_conf],array[.30,.25,.25,.20]::numeric[]) * least(coalesce(role_coverage,1),coalesce(opponent_role_coverage,1))) matchup_confidence,
      private.weighted_mean(array[role_coverage,opponent_role_coverage,case when team_tactical_observation_id is null then null else 1::numeric end,case when opponent_tactical_observation_id is null then null else 1::numeric end],array[.40,.35,.125,.125]::numeric[]) matchup_coverage,
      case when target_count is null then null else greatest(0::numeric,least(1::numeric,coalesce(max_individual_disruption,0)+.08*greatest(target_count-1,0)+.12*greatest(target_count-candidate_count,0))) end personnel_disruption,
      greatest(team_tactical_captured_at,opponent_tactical_captured_at,role_captured_at,opponent_role_captured_at,replacement_captured_at) source_cutoff
    from base b
  ), signals as materialized (
    select c.*,x.signal_family,x.signal_key,x.score_type,x.attack_component,x.resistance_component,x.score,x.direction,x.signal_confidence
    from components c cross join lateral (values
      ('TACTICAL_MATCHUP','wide_channel_pressure','ADVANTAGE',c.wide_attack,c.wide_resistance,case when c.wide_attack is null or c.wide_resistance is null then null else greatest(0::numeric,least(1::numeric,.5+.5*(c.wide_attack-c.wide_resistance))) end,case when c.wide_attack is null or c.wide_resistance is null then 'INSUFFICIENT_DATA' when .5+.5*(c.wide_attack-c.wide_resistance)>=.62 then 'ATTACK_ADVANTAGE' when .5+.5*(c.wide_attack-c.wide_resistance)<=.38 then 'DEFENSIVE_RESISTANCE' else 'BALANCED' end,c.matchup_confidence),
      ('TACTICAL_MATCHUP','aerial_set_piece_mismatch','ADVANTAGE',c.aerial_attack,c.aerial_resistance,case when c.aerial_attack is null or c.aerial_resistance is null then null else greatest(0::numeric,least(1::numeric,.5+.5*(c.aerial_attack-c.aerial_resistance))) end,case when c.aerial_attack is null or c.aerial_resistance is null then 'INSUFFICIENT_DATA' when .5+.5*(c.aerial_attack-c.aerial_resistance)>=.62 then 'ATTACK_ADVANTAGE' when .5+.5*(c.aerial_attack-c.aerial_resistance)<=.38 then 'DEFENSIVE_RESISTANCE' else 'BALANCED' end,c.matchup_confidence),
      ('TACTICAL_MATCHUP','central_creation_vs_block','ADVANTAGE',c.central_attack,c.central_resistance,case when c.central_attack is null or c.central_resistance is null then null else greatest(0::numeric,least(1::numeric,.5+.5*(c.central_attack-c.central_resistance))) end,case when c.central_attack is null or c.central_resistance is null then 'INSUFFICIENT_DATA' when .5+.5*(c.central_attack-c.central_resistance)>=.62 then 'ATTACK_ADVANTAGE' when .5+.5*(c.central_attack-c.central_resistance)<=.38 then 'DEFENSIVE_RESISTANCE' else 'BALANCED' end,c.matchup_confidence),
      ('TACTICAL_MATCHUP','direct_transition_opportunity','OPPORTUNITY',c.transition_opportunity,c.opponent_defensive_block,c.transition_opportunity,case when c.transition_opportunity is null then 'INSUFFICIENT_DATA' when c.transition_opportunity>=.62 then 'TRANSITION_OPPORTUNITY' when c.transition_opportunity<=.38 then 'LOW_TRANSITION_OPPORTUNITY' else 'MODERATE_TRANSITION_OPPORTUNITY' end,c.matchup_confidence),
      ('PERSONNEL','personnel_disruption','DISRUPTION',null,null,c.personnel_disruption,case when c.target_count is null then 'NO_MATERIAL_TARGET_IDENTIFIED' when c.personnel_disruption>=.35 then 'MATERIAL_DISRUPTION' when c.personnel_disruption>=.18 then 'MODERATE_DISRUPTION' else 'LOW_DISRUPTION' end,least(.75,coalesce(c.replacement_confidence,.35)))
    ) x(signal_family,signal_key,score_type,attack_component,resistance_component,score,direction,signal_confidence)
  ), ins as (
    insert into public.fixture_tactical_matchup_observations(match_id,gameweek,team_id,opponent_team_id,kickoff_time,captured_at,evidence_cutoff,signal_family,signal_key,score_type,score,direction,attacking_component,resistance_component,confidence,data_coverage,team_tactical_observation_id,opponent_tactical_observation_id,evidence,observation_hash,model_effect_enabled)
    select match_id,gameweek,team_id,opponent_team_id,kickoff_time,v_now,source_cutoff,signal_family,signal_key,score_type,round(score,4),direction,round(attack_component,4),round(resistance_component,4),round(signal_confidence,4),round(matchup_coverage,4),team_tactical_observation_id,opponent_tactical_observation_id,
      jsonb_build_object('method','fixture_tactical_matchup_v0.1','score_semantics',score_type,'direction',direction,'team_tactical_confidence',team_tactical_confidence,'opponent_tactical_confidence',opponent_tactical_confidence,'role_coverage',role_coverage,'opponent_role_coverage',opponent_role_coverage,'role_confidence',role_conf,'opponent_role_confidence',opponent_role_conf,'wide_components',jsonb_build_object('team_width',team_width,'xi_width',xi_width,'xi_creation',xi_creation,'wide_role_share',wide_role_share,'opponent_defensive_block',opponent_defensive_block,'opponent_xi_defensive_load',opponent_xi_def,'opponent_wide_role_share',opponent_wide_role_share),'aerial_components',jsonb_build_object('team_set_piece',team_set_piece,'team_width',team_width,'attacker_aerial',attacker_aerial,'opponent_defender_aerial',opponent_defender_aerial,'opponent_xi_defensive_load',opponent_xi_def),'central_components',jsonb_build_object('team_possession_control',team_control,'xi_creation',xi_creation,'xi_progression',xi_progression,'creator_role_share',creator_role_share,'opponent_defensive_block',opponent_defensive_block,'opponent_xi_defensive_load',opponent_xi_def),'transition_components',jsonb_build_object('team_directness',team_directness,'xi_shot_threat',xi_shot,'xi_box_occupation',xi_box,'opponent_possession_control',opponent_control,'opponent_defensive_block',opponent_defensive_block,'high_line_not_modeled',true),'personnel_components',jsonb_build_object('replacement_targets',target_count,'distinct_candidates',candidate_count,'max_individual_disruption',max_individual_disruption,'replacement_confidence',replacement_confidence,'role_fit_only_count',role_fit_only_count,'proxy_count',proxy_count),'limitations',jsonb_build_array('no left/right flank assignment','no defensive pressing intensity','no defensive line height','replacement ability not validated','score is observational research only'),'missing_components_ignored_not_zero',true,'model_effect_enabled',false),
      md5(jsonb_build_object('match_id',match_id,'team_id',team_id,'signal_key',signal_key,'score',round(score,4),'direction',direction,'attack',round(attack_component,4),'resistance',round(resistance_component,4),'source_cutoff',source_cutoff)::text),false
    from signals on conflict(match_id,team_id,signal_key,observation_hash) do nothing returning 1
  ) select count(*) into v_inserted from ins;
  return jsonb_build_object('ok',true,'gameweek',v_gw,'inserted',v_inserted,'method','fixture_tactical_matchup_v0.1','model_effect_enabled',false,'limitations',jsonb_build_array('no left/right flank assignment','no pressing intensity','no defensive line height','replacement ability not validated'));
end $$;

create or replace function public.refresh_fixture_tactical_matchups_v011(p_gameweek integer default null)
returns jsonb
language plpgsql
security invoker
set search_path=public,private,pg_temp
as $$
declare v_base jsonb; v_now timestamptz:=clock_timestamp(); v_gw integer:=p_gameweek; v_inserted integer:=0;
begin
  v_base:=public.refresh_fixture_tactical_matchups_v01(p_gameweek);
  if v_gw is null then v_gw:=nullif(v_base->>'gameweek','')::integer; end if;
  if v_gw is null then return jsonb_build_object('ok',true,'gameweek',null,'inserted',0,'base',v_base,'model_effect_enabled',false); end if;
  with raw_latest as materialized (
    select distinct on (x.match_id,x.team_id,x.signal_key) x.*
    from public.fixture_tactical_matchup_observations x join public.matches m on m.id=x.match_id
    where x.gameweek=v_gw and m.kickoff_time>v_now and x.evidence->>'method'='fixture_tactical_matchup_v0.1'
    order by x.match_id,x.team_id,x.signal_key,x.captured_at desc,x.id desc
  ), src as materialized (
    select x.*,case when x.score_type='ADVANTAGE' and x.score is null then 'INSUFFICIENT_DATA' when x.score_type='ADVANTAGE' and x.score>=.62 then 'ATTACK_ADVANTAGE' when x.score_type='ADVANTAGE' and x.score>=.55 then 'ATTACK_LEAN' when x.score_type='ADVANTAGE' and x.score<=.38 then 'DEFENSIVE_RESISTANCE' when x.score_type='ADVANTAGE' and x.score<=.45 then 'DEFENSIVE_LEAN' else x.direction end calibrated_direction
    from raw_latest x
  ), ins as (
    insert into public.fixture_tactical_matchup_observations(match_id,gameweek,team_id,opponent_team_id,kickoff_time,captured_at,evidence_cutoff,signal_family,signal_key,score_type,score,direction,attacking_component,resistance_component,confidence,data_coverage,team_tactical_observation_id,opponent_tactical_observation_id,evidence,observation_hash,model_effect_enabled)
    select match_id,gameweek,team_id,opponent_team_id,kickoff_time,v_now,evidence_cutoff,signal_family,signal_key,score_type,score,calibrated_direction,attacking_component,resistance_component,confidence,data_coverage,team_tactical_observation_id,opponent_tactical_observation_id,
      evidence || jsonb_build_object('method','fixture_tactical_matchup_v0.1.1','direction',calibrated_direction,'evidence_revision',2,'direction_calibration',jsonb_build_object('attack_advantage_gte',.62,'attack_lean_gte',.55,'defensive_lean_lte',.45,'defensive_resistance_lte',.38),'model_effect_enabled',false),
      md5(jsonb_build_object('match_id',match_id,'team_id',team_id,'signal_key',signal_key,'method','fixture_tactical_matchup_v0.1.1','evidence_revision',2,'score',score,'direction',calibrated_direction,'source_hash',observation_hash)::text),false
    from src on conflict(match_id,team_id,signal_key,observation_hash) do nothing returning 1
  ) select count(*) into v_inserted from ins;
  return jsonb_build_object('ok',true,'gameweek',v_gw,'inserted',v_inserted,'base',v_base,'method','fixture_tactical_matchup_v0.1.1','evidence_revision',2,'model_effect_enabled',false);
end $$;

revoke all on function public.refresh_fixture_tactical_matchups_v01(integer) from public,anon,authenticated;
revoke all on function public.refresh_fixture_tactical_matchups_v011(integer) from public,anon,authenticated;
grant execute on function public.refresh_fixture_tactical_matchups_v01(integer) to postgres,service_role;
grant execute on function public.refresh_fixture_tactical_matchups_v011(integer) to postgres,service_role;
