create table if not exists public.fpl_projection_eligibility_events (
  id bigint generated by default as identity primary key,
  player_id bigint not null references public.players(id),
  event_at timestamptz not null default clock_timestamp(),
  eligibility_status text not null check (eligibility_status in ('EXCLUDED','RESTORED')),
  reason_code text not null,
  reason_detail text,
  change_id text not null default 'C0204',
  evidence jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default clock_timestamp()
);
create index if not exists fpl_projection_eligibility_events_player_idx on public.fpl_projection_eligibility_events(player_id,event_at desc,id desc);
alter table public.fpl_projection_eligibility_events enable row level security;

create table if not exists public.fpl_projection_coverage_audits (
  id bigint generated by default as identity primary key,
  prediction_run_id bigint references public.gameweek_prediction_runs(id),
  gameweek integer not null,
  captured_at timestamptz not null default clock_timestamp(),
  projectable_count integer not null,
  governed_excluded_count integer not null,
  ungoverned_missing_count integer not null,
  total_fpl_players integer not null,
  coverage jsonb not null,
  change_id text not null default 'C0204',
  created_at timestamptz not null default clock_timestamp()
);
create index if not exists fpl_projection_coverage_audits_gw_idx on public.fpl_projection_coverage_audits(gameweek,captured_at desc,id desc);
alter table public.fpl_projection_coverage_audits enable row level security;

create or replace function private.block_c0204_projection_coverage_mutation_v01()
returns trigger language plpgsql as $$
begin
  raise exception 'C0204 projection coverage evidence is append-only';
end;$$;

drop trigger if exists trg_block_c0204_eligibility_mutation on public.fpl_projection_eligibility_events;
create trigger trg_block_c0204_eligibility_mutation before update or delete on public.fpl_projection_eligibility_events for each row execute function private.block_c0204_projection_coverage_mutation_v01();
drop trigger if exists trg_block_c0204_coverage_audit_mutation on public.fpl_projection_coverage_audits;
create trigger trg_block_c0204_coverage_audit_mutation before update or delete on public.fpl_projection_coverage_audits for each row execute function private.block_c0204_projection_coverage_mutation_v01();

create or replace function private.c0204_projection_coverage_rows_v01(p_gameweek integer, p_as_of timestamptz default clock_timestamp())
returns table(
  player_id bigint,
  web_name text,
  player_position text,
  team_id bigint,
  fpl_player_id integer,
  player_status text,
  has_current_state boolean,
  has_baseline_prediction boolean,
  latest_eligibility_status text,
  coverage_status text,
  reason_code text
)
language sql stable security definer set search_path=private,public,pg_temp as $$
with active_model as (
  select id from public.model_versions where is_active=true order by id desc limit 1
), target_players as (
  select p.*
  from public.players p
  where p.fpl_player_id is not null
    and exists (
      select 1 from public.matches m
      where m.source='fpl' and m.gameweek=p_gameweek
        and (m.home_team_id=p.team_id or m.away_team_id=p.team_id)
    )
), facts as (
  select p.id,p.web_name,p.position,p.team_id,p.fpl_player_id,p.status,
    exists(select 1 from public.player_state ps where ps.player_id=p.id and ps.as_of<=p_as_of) as has_state,
    exists(select 1 from public.model_predictions mp, active_model am where mp.player_id=p.id and mp.model_version_id=am.id and mp.prediction_run_id is null and mp.generated_at<p_as_of) as has_baseline,
    ev.eligibility_status as ev_status,
    ev.reason_code as ev_reason
  from target_players p
  left join lateral (
    select e.eligibility_status,e.reason_code
    from public.fpl_projection_eligibility_events e
    where e.player_id=p.id and e.event_at<=p_as_of
    order by e.event_at desc,e.id desc limit 1
  ) ev on true
)
select id,web_name,position,team_id,fpl_player_id,status,
  has_state,has_baseline,ev_status,
  case when has_state and has_baseline then 'PROJECTABLE'
       when ev_status='EXCLUDED' then 'EXCLUDED_GOVERNED'
       else 'UNGOVERNED_MISSING' end,
  case when has_state and has_baseline then 'OK'
       when ev_status='EXCLUDED' then ev_reason
       when not has_state and not has_baseline then 'MISSING_STATE_AND_BASELINE'
       when not has_state then 'MISSING_CURRENT_STATE'
       else 'MISSING_BASELINE_PREDICTION' end
from facts;
$$;

create or replace function private.c0204_projection_coverage_summary_v01(p_gameweek integer, p_as_of timestamptz default clock_timestamp())
returns jsonb language sql stable security definer set search_path=private,public,pg_temp as $$
with r as (select * from private.c0204_projection_coverage_rows_v01(p_gameweek,p_as_of))
select jsonb_build_object(
  'change_id','C0204',
  'gameweek',p_gameweek,
  'as_of',p_as_of,
  'total_fpl_players',count(*),
  'projectable_count',count(*) filter(where coverage_status='PROJECTABLE'),
  'governed_excluded_count',count(*) filter(where coverage_status='EXCLUDED_GOVERNED'),
  'ungoverned_missing_count',count(*) filter(where coverage_status='UNGOVERNED_MISSING'),
  'missing_data_is_not_zero',true,
  'excluded',coalesce(jsonb_agg(jsonb_build_object('player_id',player_id,'name',web_name,'position',player_position,'status',player_status,'reason',reason_code) order by player_id) filter(where coverage_status<>'PROJECTABLE'),'[]'::jsonb)
) from r;
$$;

alter function private.generate_upcoming_fpl_snapshot_v01(integer,boolean) rename to generate_upcoming_fpl_snapshot_c0160_legacy_v01;

create or replace function private.generate_upcoming_fpl_snapshot_v01(p_gameweek integer default null, p_force boolean default false)
returns jsonb
language plpgsql security definer set search_path=private,public,pg_temp as $$
declare
  v_now timestamptz := clock_timestamp();
  v_gw integer;
  v_cov jsonb;
  v_res jsonb;
  v_run_id bigint;
begin
  if p_gameweek is null then
    select x.gameweek into v_gw
    from (
      select m.gameweek,min(m.kickoff_time)-interval '90 minutes' deadline_at
      from public.matches m where m.source='fpl' and m.gameweek between 1 and 38
      group by m.gameweek
    ) x
    where x.deadline_at>v_now order by x.gameweek limit 1;
  else
    v_gw:=p_gameweek;
  end if;
  if v_gw is null then
    return jsonb_build_object('ok',false,'status','NO_FUTURE_GAMEWEEK','change_id','C0204');
  end if;

  v_cov:=private.c0204_projection_coverage_summary_v01(v_gw,v_now);
  if coalesce((v_cov->>'ungoverned_missing_count')::integer,0)>0 then
    insert into public.fpl_projection_coverage_audits(prediction_run_id,gameweek,captured_at,projectable_count,governed_excluded_count,ungoverned_missing_count,total_fpl_players,coverage)
    values(null,v_gw,v_now,(v_cov->>'projectable_count')::integer,(v_cov->>'governed_excluded_count')::integer,(v_cov->>'ungoverned_missing_count')::integer,(v_cov->>'total_fpl_players')::integer,v_cov);
    return jsonb_build_object('ok',false,'status','C0204_PROJECTION_COVERAGE_BLOCKED','gameweek',v_gw,'projection_coverage',v_cov,'historical_forecasts_rewritten',false);
  end if;

  v_res:=private.generate_upcoming_fpl_snapshot_c0160_legacy_v01(v_gw,p_force);
  if v_res ? 'run_id' then v_run_id:=(v_res->>'run_id')::bigint; end if;
  insert into public.fpl_projection_coverage_audits(prediction_run_id,gameweek,captured_at,projectable_count,governed_excluded_count,ungoverned_missing_count,total_fpl_players,coverage)
  values(v_run_id,v_gw,v_now,(v_cov->>'projectable_count')::integer,(v_cov->>'governed_excluded_count')::integer,(v_cov->>'ungoverned_missing_count')::integer,(v_cov->>'total_fpl_players')::integer,v_cov);
  return v_res || jsonb_build_object('change_id','C0204','projection_coverage',v_cov,'historical_forecasts_rewritten',false);
end;$$;

create or replace function private.c0204_projection_coverage_status_v01(p_gameweek integer default null)
returns jsonb language plpgsql stable security definer set search_path=private,public,pg_temp as $$
declare v_gw integer; v_s jsonb;
begin
  if p_gameweek is null then
    select x.gameweek into v_gw from (select m.gameweek,min(m.kickoff_time)-interval '90 minutes' deadline_at from public.matches m where m.source='fpl' and m.gameweek between 1 and 38 group by m.gameweek) x where x.deadline_at>clock_timestamp() order by x.gameweek limit 1;
  else v_gw:=p_gameweek; end if;
  if v_gw is null then return jsonb_build_object('change_id','C0204','status','NO_FUTURE_GAMEWEEK'); end if;
  v_s:=private.c0204_projection_coverage_summary_v01(v_gw,clock_timestamp());
  return v_s || jsonb_build_object('latest_audit',(select to_jsonb(a) from public.fpl_projection_coverage_audits a where a.gameweek=v_gw order by a.captured_at desc,a.id desc limit 1));
end;$$;