create table if not exists public.research_c0197_cross_source_match_audits (
  id bigint generated by default as identity primary key,
  change_id text not null default 'C0197',
  audit_definition_version text not null,
  season text not null,
  football_data_capture_id bigint not null references public.research_c0197_long_history_captures(id),
  football_data_source_match_id text not null,
  fpl_core_source_match_id text not null,
  fpl_core_source_commit_sha text,
  gameweek integer,
  score_exact boolean not null,
  core_equals_football_data_halftime boolean not null,
  shot_abs_delta numeric not null,
  sot_abs_delta numeric not null,
  score_status text not null,
  stat_status text not null,
  goal_residual_eligible boolean not null,
  process_feature_eligible boolean not null,
  overall_rich_feature_eligible boolean not null,
  audit_evidence jsonb not null,
  research_only boolean not null default true,
  model_effect_enabled boolean not null default false,
  created_at timestamptz not null default now(),
  unique (football_data_capture_id, fpl_core_source_match_id, audit_definition_version),
  check (research_only = true),
  check (model_effect_enabled = false)
);

alter table public.research_c0197_cross_source_match_audits enable row level security;
revoke all on public.research_c0197_cross_source_match_audits from anon, authenticated;

create trigger c0197_block_cross_source_audit_mutation
before update or delete on public.research_c0197_cross_source_match_audits
for each row execute function private.c0197_block_long_history_mutation_v01();

create or replace function private.c0197_fd_team_slug_v01(p_team text,p_season text)
returns text
language sql
immutable
set search_path = pg_catalog
as $$
select case p_team
  when 'Arsenal' then 'arsenal'
  when 'Aston Villa' then 'aston-villa'
  when 'Bournemouth' then 'afc-bournemouth'
  when 'Brentford' then 'brentford'
  when 'Brighton' then case when p_season='2024-2025' then 'brighton-&-hove-albion' else 'brighton-hove-albion' end
  when 'Burnley' then 'burnley'
  when 'Chelsea' then 'chelsea'
  when 'Crystal Palace' then 'crystal-palace'
  when 'Everton' then 'everton'
  when 'Fulham' then 'fulham'
  when 'Ipswich' then 'ipswich-town'
  when 'Leeds' then 'leeds-united'
  when 'Leicester' then 'leicester-city'
  when 'Liverpool' then 'liverpool'
  when 'Man City' then 'manchester-city'
  when 'Man United' then 'manchester-united'
  when 'Newcastle' then 'newcastle-united'
  when 'Nott''m Forest' then 'nottingham-forest'
  when 'Southampton' then 'southampton'
  when 'Sunderland' then 'sunderland'
  when 'Tottenham' then 'tottenham-hotspur'
  when 'West Ham' then 'west-ham-united'
  when 'Wolves' then 'wolverhampton-wanderers'
  else null
end;
$$;

create or replace view private.c0197_cross_source_overlap_v01
with (security_invoker = true)
as
with fd as (
  select l.*,
         private.c0197_fd_team_slug_v01(l.home_team,l.season) as home_slug,
         private.c0197_fd_team_slug_v01(l.away_team,l.season) as away_slug
  from private.c0197_long_history_latest_matches_v01 l
  where l.season in ('2024-2025','2025-2026')
), fd_key as (
  select fd.*,
         (case season when '2024-2025' then '24-25-prem-' when '2025-2026' then '25-26-prem-' end)||home_slug||'-vs-'||away_slug as core_id
  from fd
), core as (
  select season,source_match_id,
         max(gameweek) as gameweek,
         max(source_commit_sha) as source_commit_sha,
         max(goals_for) filter(where venue='home') as home_goals,
         max(goals_for) filter(where venue='away') as away_goals,
         max(shots_for) filter(where venue='home') as home_shots,
         max(shots_for) filter(where venue='away') as away_shots,
         max(shots_on_target_for) filter(where venue='home') as home_sot,
         max(shots_on_target_for) filter(where venue='away') as away_sot
  from public.research_c0197_team_match_evidence
  where season in ('2024-2025','2025-2026')
  group by season,source_match_id
)
select f.capture_id as football_data_capture_id,
       f.season,
       f.source_match_id as football_data_source_match_id,
       c.source_match_id as fpl_core_source_match_id,
       c.source_commit_sha as fpl_core_source_commit_sha,
       c.gameweek,
       f.match_date,f.home_team,f.away_team,
       f.full_time_home_goals as fd_home_goals,f.full_time_away_goals as fd_away_goals,
       f.half_time_home_goals as fd_half_home_goals,f.half_time_away_goals as fd_half_away_goals,
       c.home_goals as core_home_goals,c.away_goals as core_away_goals,
       f.home_shots as fd_home_shots,f.away_shots as fd_away_shots,c.home_shots as core_home_shots,c.away_shots as core_away_shots,
       f.home_shots_on_target as fd_home_sot,f.away_shots_on_target as fd_away_sot,c.home_sot as core_home_sot,c.away_sot as core_away_sot,
       (f.full_time_home_goals=c.home_goals and f.full_time_away_goals=c.away_goals) as score_exact,
       (f.half_time_home_goals=c.home_goals and f.half_time_away_goals=c.away_goals) as core_equals_fd_halftime,
       (abs(f.home_shots-c.home_shots)+abs(f.away_shots-c.away_shots))::numeric as shot_abs_delta,
       (abs(f.home_shots_on_target-c.home_sot)+abs(f.away_shots_on_target-c.away_sot))::numeric as sot_abs_delta
from fd_key f
join core c on c.season=f.season and c.source_match_id=f.core_id;

revoke all on private.c0197_cross_source_overlap_v01 from public, anon, authenticated;
grant select on private.c0197_cross_source_overlap_v01 to service_role;

create or replace function private.c0197_cross_source_audit_status_v01()
returns jsonb
language sql
security invoker
set search_path = pg_catalog, public, private
as $$
select jsonb_build_object(
  'change_id','C0197',
  'audit_definition_version','C0197_XSRC_V01',
  'model_effect_enabled',false,
  'by_season',coalesce(jsonb_agg(to_jsonb(s) order by s.season),'[]'::jsonb)
)
from (
  select season,count(*) as matches,
         count(*) filter(where score_status='EXACT') as exact_scores,
         count(*) filter(where score_status='HALF_TIME_SCORE_CONTAMINATION') as halftime_score_contamination,
         count(*) filter(where stat_status='EXACT') as exact_stats,
         count(*) filter(where stat_status='MINOR_PROVIDER_VARIANCE') as minor_provider_variance,
         count(*) filter(where stat_status='SEVERE_STAT_CONFLICT') as severe_stat_conflicts,
         count(*) filter(where overall_rich_feature_eligible) as overall_rich_feature_eligible
  from public.research_c0197_cross_source_match_audits
  where audit_definition_version='C0197_XSRC_V01'
  group by season
) s;
$$;
revoke all on function private.c0197_cross_source_audit_status_v01() from public, anon, authenticated;
grant execute on function private.c0197_cross_source_audit_status_v01() to service_role;
