-- C0277 P2 — future opportunity scenarios are contingencies, not predictions.
create or replace function private.c0277_future_opportunity_scenarios_v01(p_gameweek integer, p_exact_decision_horizon integer default 3, p_seasonal_chip_end_gameweek integer default 19)
returns jsonb language plpgsql security definer set search_path='' as $$
declare v_r jsonb; v_s jsonb; v_non jsonb; v_dbl jsonb; v_blk jsonb; v_struct_only jsonb; v_has_non boolean; v_best boolean;
begin
 v_r:=private.c0277_reservation_value_status_v01(p_gameweek,p_exact_decision_horizon,p_seasonal_chip_end_gameweek);
 if not coalesce((v_r->>'ok')::boolean,false) then return jsonb_build_object('ok',false,'status','C0277_RESERVATION_INPUT_NOT_READY','change_id','C0277','historical_forecasts_rewritten',false); end if;
 v_s:=private.c0248_structural_chip_window_status_v01(p_gameweek);
 v_non:=coalesce(v_s->'confirmed_nonstandard_structural_gameweeks','[]'::jsonb); v_dbl:=coalesce(v_s->'confirmed_double_or_multi_gameweeks','[]'::jsonb); v_blk:=coalesce(v_s->'confirmed_blank_gameweeks','[]'::jsonb); v_struct_only:=coalesce(v_s->'structural_only_gameweeks','[]'::jsonb);
 v_has_non:=jsonb_array_length(v_non)>0; v_best:=coalesce((v_r->>'season_best_chip_weeks_resolved')::boolean,false);
 return jsonb_build_object('ok',true,'status','C0277_FUTURE_OPPORTUNITY_SCENARIOS_V01_EVALUATED','change_id','C0277','gameweek',p_gameweek,'exact_decision_horizon',p_exact_decision_horizon,'seasonal_chip_end_gameweek',p_seasonal_chip_end_gameweek,
 'observed_structure',jsonb_build_object('confirmed_nonstandard_gameweeks',v_non,'confirmed_double_gameweeks',v_dbl,'confirmed_blank_gameweeks',v_blk,'structural_only_gameweeks',v_struct_only),
 'scenarios',jsonb_build_array(
  jsonb_build_object('scenario_id','S0_CURRENT_SCHEDULE_PERSISTS','evidence_class','OBSERVED_CURRENT_STRUCTURE','condition','No later first-half fixture restructuring becomes confirmed','chip_implications',jsonb_build_object('BENCH_BOOST','RESERVE_UNRESOLVED','TRIPLE_CAPTAIN','RESERVE_UNRESOLVED','FREE_HIT','RESERVE_UNRESOLVED','WILDCARD','RESERVE_INFORMATION_OPTION'),'numeric_probability',null,'numeric_points',null,'authorization_allowed',false),
  jsonb_build_object('scenario_id','S1_LATER_DGW_EMERGES','evidence_class',case when jsonb_array_length(v_dbl)>0 then 'CONFIRMED_PRESENT' else 'PLAUSIBLE_NOT_CONFIRMED' end,'condition','One or more later first-half teams acquire multiple fixtures in a GW','chip_implications',jsonb_build_object('BENCH_BOOST','POTENTIAL_HIGHER_OPTION_VALUE','TRIPLE_CAPTAIN','POTENTIAL_HIGHER_OPTION_VALUE','FREE_HIT','CONTEXT_DEPENDENT','WILDCARD','PREPARATION_OR_RECOVERY_OPTION'),'numeric_probability',null,'numeric_points',null,'authorization_allowed',false),
  jsonb_build_object('scenario_id','S2_LATER_BGW_OR_ASYMMETRY_EMERGES','evidence_class',case when jsonb_array_length(v_blk)>0 then 'CONFIRMED_PRESENT' else 'PLAUSIBLE_NOT_CONFIRMED' end,'condition','One or more later first-half teams blank or fixture asymmetry becomes confirmed','chip_implications',jsonb_build_object('FREE_HIT','POTENTIAL_HIGHER_OPTION_VALUE','WILDCARD','CONTEXT_DEPENDENT','BENCH_BOOST','LOWER_PRIORITY_WITHOUT_COMPANION_DGW','TRIPLE_CAPTAIN','LOWER_PRIORITY_WITHOUT_COMPANION_DGW'),'numeric_probability',null,'numeric_points',null,'authorization_allowed',false),
  jsonb_build_object('scenario_id','S3_SQUAD_STATE_DETERIORATES_OR_INFORMATION_SHIFTS','evidence_class','FUTURE_STATE_UNRESOLVED','condition','Injuries, transfers, roles, prices, tactical changes or fixture information materially change squad opportunity cost','chip_implications',jsonb_build_object('WILDCARD','POTENTIAL_HIGHER_OPTION_VALUE','FREE_HIT','CONTEXT_DEPENDENT','BENCH_BOOST','SQUAD_DEPENDENT','TRIPLE_CAPTAIN','CAPTAIN_FIXTURE_DEPENDENT'),'numeric_probability',null,'numeric_points',null,'authorization_allowed',false)),
 'scenario_control',jsonb_build_object('confirmed_nonstandard_present',v_has_non,'season_best_chip_weeks_resolved',v_best,'scenario_probabilities_authorized',false,'scenario_expected_points_authorized',false,'current_chip_authorization_override',false,'rerun_triggers',jsonb_build_array('FIXTURE_RESTRUCTURE','NEW_DECISION_GRADE_PROJECTION','ROLE_OR_XMINS_CHANGE','AVAILABILITY_CHANGE','SQUAD_OR_PRICE_STATE_CHANGE')),
 'current_action',v_r->'current_action','policy',jsonb_build_object('scenarios_are_contingencies_not_predictions',true,'no_subjective_probability_invention',true,'no_fake_future_player_precision',true,'scenario_layer_preserves_option_value',true,'scenario_layer_cannot_authorize_chip_spend',true,'one_chip_per_gameweek_preserved',true,'does_not_execute',true),'historical_forecasts_rewritten',false);
end $$;
revoke all on function private.c0277_future_opportunity_scenarios_v01(integer,integer,integer) from public;
grant execute on function private.c0277_future_opportunity_scenarios_v01(integer,integer,integer) to service_role;
