create table if not exists public.research_c0197_shootout_forward_runs (
  run_key text primary key,
  change_id text not null default 'C0197',
  model_version text not null,
  definition jsonb not null default '{}'::jsonb,
  decision text not null,
  research_only boolean not null default true check (research_only),
  model_effect_enabled boolean not null default false check (not model_effect_enabled),
  created_at timestamptz not null default clock_timestamp()
);

create table if not exists public.research_c0197_shootout_forward_scalers (
  id bigint generated by default as identity primary key,
  run_key text not null references public.research_c0197_shootout_forward_runs(run_key),
  scaler_key text not null,
  mean_value numeric,
  sd_value numeric,
  prior_value numeric,
  source_scope text not null,
  evidence jsonb not null default '{}'::jsonb,
  research_only boolean not null default true check (research_only),
  model_effect_enabled boolean not null default false check (not model_effect_enabled),
  created_at timestamptz not null default clock_timestamp(),
  unique(run_key,scaler_key)
);

create table if not exists public.research_c0197_shootout_forward_snapshots (
  id bigint generated by default as identity primary key,
  run_key text not null references public.research_c0197_shootout_forward_runs(run_key),
  observation_hash text not null,
  snapshot_as_of timestamptz not null,
  match_id bigint not null references public.matches(id),
  gameweek integer not null,
  kickoff_time timestamptz not null,
  home_team_id bigint not null references public.teams(id),
  away_team_id bigint not null references public.teams(id),
  home_team text not null,
  away_team text not null,
  market_bookmakers integer not null default 0,
  market_home_prob numeric,
  market_draw_prob numeric,
  market_away_prob numeric,
  favorite_prob numeric,
  inverse_favorite_prob numeric,
  home_history_n integer not null,
  away_history_n integer not null,
  home_sot numeric,
  away_sot numeric,
  min_sot numeric,
  home_gf numeric,
  away_gf numeric,
  min_gf numeric,
  home_btts_rate numeric,
  away_btts_rate numeric,
  btts_rate numeric,
  z_min_sot numeric,
  z_min_gf numeric,
  z_btts numeric,
  z_inverse_favorite numeric,
  base_score_v01 numeric,
  home_breadth_n integer not null,
  away_breadth_n integer not null,
  home_sot_players numeric,
  away_sot_players numeric,
  min_sot_players numeric,
  home_xg_breadth numeric,
  away_xg_breadth numeric,
  min_xg_breadth numeric,
  z_min_sot_players numeric,
  z_min_xg_breadth numeric,
  breadth_score_v01 numeric,
  combined_score_v02 numeric,
  base_rank integer,
  combined_rank integer,
  base_history_coverage numeric not null,
  breadth_history_coverage numeric not null,
  confidence text not null,
  evidence jsonb not null default '{}'::jsonb,
  research_only boolean not null default true check (research_only),
  model_effect_enabled boolean not null default false check (not model_effect_enabled),
  created_at timestamptz not null default clock_timestamp(),
  unique(run_key,match_id,observation_hash)
);

create table if not exists public.research_c0197_shootout_forward_evaluations (
  id bigint generated by default as identity primary key,
  run_key text not null references public.research_c0197_shootout_forward_runs(run_key),
  snapshot_id bigint not null references public.research_c0197_shootout_forward_snapshots(id),
  match_id bigint not null references public.matches(id),
  gameweek integer not null,
  actual_home_goals integer not null,
  actual_away_goals integer not null,
  actual_total_goals integer not null,
  actual_shootout boolean not null,
  actual_demolition boolean not null,
  base_top10 boolean,
  combined_top10 boolean,
  evaluated_at timestamptz not null default clock_timestamp(),
  research_only boolean not null default true check (research_only),
  model_effect_enabled boolean not null default false check (not model_effect_enabled),
  unique(run_key,snapshot_id)
);

alter table public.research_c0197_shootout_forward_runs enable row level security;
alter table public.research_c0197_shootout_forward_scalers enable row level security;
alter table public.research_c0197_shootout_forward_snapshots enable row level security;
alter table public.research_c0197_shootout_forward_evaluations enable row level security;
revoke all on public.research_c0197_shootout_forward_runs from anon, authenticated;
revoke all on public.research_c0197_shootout_forward_scalers from anon, authenticated;
revoke all on public.research_c0197_shootout_forward_snapshots from anon, authenticated;
revoke all on public.research_c0197_shootout_forward_evaluations from anon, authenticated;
revoke all on sequence public.research_c0197_shootout_forward_scalers_id_seq from anon, authenticated;
revoke all on sequence public.research_c0197_shootout_forward_snapshots_id_seq from anon, authenticated;
revoke all on sequence public.research_c0197_shootout_forward_evaluations_id_seq from anon, authenticated;

create or replace function private.block_c0197_shootout_forward_mutation_v01()
returns trigger language plpgsql set search_path=public,private,pg_temp as $$
begin
  raise exception 'C0197 shootout forward evidence is append-only';
end $$;
revoke all on function private.block_c0197_shootout_forward_mutation_v01() from public,anon,authenticated;

drop trigger if exists research_c0197_shootout_forward_runs_append_only on public.research_c0197_shootout_forward_runs;
create trigger research_c0197_shootout_forward_runs_append_only before update or delete on public.research_c0197_shootout_forward_runs for each row execute function private.block_c0197_shootout_forward_mutation_v01();
drop trigger if exists research_c0197_shootout_forward_scalers_append_only on public.research_c0197_shootout_forward_scalers;
create trigger research_c0197_shootout_forward_scalers_append_only before update or delete on public.research_c0197_shootout_forward_scalers for each row execute function private.block_c0197_shootout_forward_mutation_v01();
drop trigger if exists research_c0197_shootout_forward_snapshots_append_only on public.research_c0197_shootout_forward_snapshots;
create trigger research_c0197_shootout_forward_snapshots_append_only before update or delete on public.research_c0197_shootout_forward_snapshots for each row execute function private.block_c0197_shootout_forward_mutation_v01();
drop trigger if exists research_c0197_shootout_forward_evaluations_append_only on public.research_c0197_shootout_forward_evaluations;
create trigger research_c0197_shootout_forward_evaluations_append_only before update or delete on public.research_c0197_shootout_forward_evaluations for each row execute function private.block_c0197_shootout_forward_mutation_v01();

insert into public.research_c0197_shootout_forward_runs(run_key,model_version,definition,decision)
values (
 'C0197_SHOOTOUT_FORWARD_20260904_V01',
 'C0197_SHOOTOUT_FORWARD_V01',
 jsonb_build_object(
   'registered_before_gw3','true',
   'target','SHOOTOUT = 6+ total goals and both teams score at least 2',
   'v01_base','equal weight standardized min rolling SOT, min rolling GF, average rolling BTTS rate, inverse opening favorite probability',
   'v02_breadth','equal weight six components: V01 four components plus min rolling number of SOT contributors and min rolling xG outside top two shooters',
   'base_scaling','fixed from 2020/21-2022/23 full-window EPL fixtures; no target refit',
   'breadth_scaling','fixed from 2025/26 shot-level process distribution; no outcome conditioning',
   'window','last 10 prior EPL matches; current season plus immediately prior EPL season only',
   'early_season_shrinkage','missing history positions shrink linearly to fixed league prior up to 10 matches',
   'promoted_clubs','no Championship-equivalent fabrication; Coventry/Hull/Ipswich missing prior EPL-season positions shrink to league prior',
   'market_input','earliest captured pre-match H2H prices per bookmaker, devigged then averaged; BTTS/totals/SOT markets excluded from score',
   'output','relative rank only; no shootout probability until forward calibration exists',
   'production_effect','none'
 ),
 'FORWARD_SHADOW_REGISTERED_NO_PRODUCTION_EFFECT'
) on conflict do nothing;

insert into public.research_c0197_shootout_forward_scalers(run_key,scaler_key,mean_value,sd_value,prior_value,source_scope,evidence)
values
('C0197_SHOOTOUT_FORWARD_20260904_V01','MIN_SOT',3.767980,0.807958,4.403350,'2020/21-2022/23 Football-Data EPL',jsonb_build_object('training_match_n',990,'team_prior_n',2030)),
('C0197_SHOOTOUT_FORWARD_20260904_V01','MIN_GF',1.063636,0.391222,1.389655,'2020/21-2022/23 Football-Data EPL',jsonb_build_object('training_match_n',990,'team_prior_n',2030)),
('C0197_SHOOTOUT_FORWARD_20260904_V01','BTTS_RATE',0.497121,0.110584,0.498325,'2020/21-2022/23 Football-Data EPL',jsonb_build_object('training_match_n',990,'team_prior_n',2030)),
('C0197_SHOOTOUT_FORWARD_20260904_V01','INVERSE_FAVORITE',0.462185,0.132885,null,'2020/21-2022/23 Football-Data opening 1X2',jsonb_build_object('training_match_n',990)),
('C0197_SHOOTOUT_FORWARD_20260904_V01','MIN_SOT_PLAYERS',3.105051,0.447752,3.420807,'2025/26 C0197 eligible shot-event process distribution',jsonb_build_object('paired_match_n',198,'team_roll_n',471)),
('C0197_SHOOTOUT_FORWARD_20260904_V01','MIN_XG_BREADTH',0.456922,0.105019,0.537464,'2025/26 C0197 eligible shot-event process distribution',jsonb_build_object('paired_match_n',198,'team_roll_n',471))
on conflict do nothing;

create or replace function private.c0197_capture_shootout_forward_v01(p_gameweek integer, p_as_of timestamptz default clock_timestamp())
returns jsonb language plpgsql set search_path=public,private,pg_temp as $$
declare
  v_inserted integer := 0;
  v_run_key constant text := 'C0197_SHOOTOUT_FORWARD_20260904_V01';
begin
  with fixtures as (
    select m.id match_id,m.gameweek,m.kickoff_time,m.home_team_id,m.away_team_id,ht.name home_team,at.name away_team
    from public.matches m join public.teams ht on ht.id=m.home_team_id join public.teams at on at.id=m.away_team_id
    where m.gameweek=p_gameweek and not m.finished and m.kickoff_time>p_as_of
  ), sides as (
    select f.*,f.home_team_id team_id,'home'::text side from fixtures f
    union all
    select f.*,f.away_team_id,'away'::text from fixtures f
  ), base_hist as (
    select s.match_id,s.side,s.team_id,
      count(h.*)::integer hist_n,
      (coalesce(sum(h.shots_on_target_for),0) + (10-count(h.*))*4.403350)/10.0 eff_sot,
      (coalesce(sum(h.goals_for),0) + (10-count(h.*))*1.389655)/10.0 eff_gf,
      (coalesce(sum(case when h.goals_for>0 and h.goals_against>0 then 1.0 else 0.0 end),0) + (10-count(h.*))*0.498325)/10.0 eff_btts
    from sides s
    left join lateral (
      select e.* from public.research_c0197_team_match_evidence e
      where e.team_id=s.team_id
        and e.season in ('2025-2026','2026-2027')
        and e.fixture_kickoff < least(s.kickoff_time,p_as_of)
      order by e.fixture_kickoff desc,e.gameweek desc,e.id desc
      limit 10
    ) h on true
    group by s.match_id,s.side,s.team_id
  ), shot_quality as (
    select q.season,q.gameweek,q.source_match_id,q.team_id,q.venue,e.fixture_kickoff
    from private.c0197_shot_side_quality_v01 q
    join public.research_c0197_team_match_evidence e
      on e.season=q.season and e.source_match_id=q.source_match_id and e.team_id=q.team_id and e.venue=q.venue
    where q.season in ('2025-2026','2026-2027')
      and q.esot_training_eligible
      and e.fixture_kickoff < p_as_of
  ), player_shot as (
    select q.season,q.gameweek,q.source_match_id,q.team_id,q.venue,q.fixture_kickoff,s.source_player_id,
      sum(coalesce(s.xg,0)) player_xg,
      bool_or(lower(coalesce(s.outcome,'')) in ('goal','save')) has_sot
    from shot_quality q
    join public.research_c0197_shot_events s
      on s.season=q.season and s.source_match_id=q.source_match_id and s.is_home=(q.venue='home')
    group by q.season,q.gameweek,q.source_match_id,q.team_id,q.venue,q.fixture_kickoff,s.source_player_id
  ), breadth_side as (
    select season,gameweek,source_match_id,team_id,venue,fixture_kickoff,
      count(*) filter(where source_player_id is not null and has_sot)::numeric sot_players,
      greatest(0,sum(player_xg)-coalesce((array_agg(player_xg order by player_xg desc))[1],0)-coalesce((array_agg(player_xg order by player_xg desc))[2],0))::numeric xg_breadth,
      sum(case when source_player_id is null then player_xg else 0 end)::numeric unknown_player_xg
    from player_shot
    group by season,gameweek,source_match_id,team_id,venue,fixture_kickoff
  ), breadth_hist as (
    select s.match_id,s.side,s.team_id,
      count(h.*)::integer hist_n,
      (coalesce(sum(h.sot_players),0)+(10-count(h.*))*3.420807)/10.0 eff_sot_players,
      (coalesce(sum(h.xg_breadth),0)+(10-count(h.*))*0.537464)/10.0 eff_xg_breadth
    from sides s
    left join lateral (
      select b.* from breadth_side b
      where b.team_id=s.team_id and b.fixture_kickoff < least(s.kickoff_time,p_as_of) and b.unknown_player_xg<=0.000001
      order by b.fixture_kickoff desc,b.gameweek desc,b.source_match_id desc
      limit 10
    ) h on true
    group by s.match_id,s.side,s.team_id
  ), opening_quotes as (
    select * from (
      select o.*,
        row_number() over(partition by o.match_id,o.provider,o.bookmaker,o.selection_key order by o.captured_at asc,o.source_timestamp asc,o.id asc) rn
      from public.odds_market_selections o
      join fixtures f on f.match_id=o.match_id
      where o.market_key='h2h' and o.selection_key in ('home','draw','away')
        and o.decimal_odds>1 and o.captured_at<=p_as_of
    ) x where rn=1
  ), market_books as (
    select match_id,provider,bookmaker,
      max(decimal_odds) filter(where selection_key='home') oh,
      max(decimal_odds) filter(where selection_key='draw') od,
      max(decimal_odds) filter(where selection_key='away') oa
    from opening_quotes group by match_id,provider,bookmaker
  ), market_norm as (
    select match_id,provider,bookmaker,
      (1/oh)/((1/oh)+(1/od)+(1/oa)) ph,
      (1/od)/((1/oh)+(1/od)+(1/oa)) pd,
      (1/oa)/((1/oh)+(1/od)+(1/oa)) pa
    from market_books where oh is not null and od is not null and oa is not null
  ), market as (
    select match_id,count(*)::integer bookmakers,avg(ph) ph,avg(pd) pd,avg(pa) pa
    from market_norm group by match_id
  ), features as (
    select f.*,coalesce(m.bookmakers,0) market_bookmakers,m.ph,m.pd,m.pa,
      greatest(m.ph,m.pa) favorite_prob,1-greatest(m.ph,m.pa) inverse_favorite_prob,
      hb.hist_n home_history_n,ab.hist_n away_history_n,hb.eff_sot home_sot,ab.eff_sot away_sot,
      least(hb.eff_sot,ab.eff_sot) min_sot,hb.eff_gf home_gf,ab.eff_gf away_gf,least(hb.eff_gf,ab.eff_gf) min_gf,
      hb.eff_btts home_btts_rate,ab.eff_btts away_btts_rate,(hb.eff_btts+ab.eff_btts)/2 btts_rate,
      hbr.hist_n home_breadth_n,abr.hist_n away_breadth_n,hbr.eff_sot_players home_sot_players,abr.eff_sot_players away_sot_players,
      least(hbr.eff_sot_players,abr.eff_sot_players) min_sot_players,
      hbr.eff_xg_breadth home_xg_breadth,abr.eff_xg_breadth away_xg_breadth,
      least(hbr.eff_xg_breadth,abr.eff_xg_breadth) min_xg_breadth
    from fixtures f
    join base_hist hb on hb.match_id=f.match_id and hb.side='home'
    join base_hist ab on ab.match_id=f.match_id and ab.side='away'
    join breadth_hist hbr on hbr.match_id=f.match_id and hbr.side='home'
    join breadth_hist abr on abr.match_id=f.match_id and abr.side='away'
    left join market m on m.match_id=f.match_id
  ), scored as (
    select *,
      (min_sot-3.767980)/0.807958 z_min_sot,
      (min_gf-1.063636)/0.391222 z_min_gf,
      (btts_rate-0.497121)/0.110584 z_btts,
      case when inverse_favorite_prob is null then null else (inverse_favorite_prob-0.462185)/0.132885 end z_inverse_favorite,
      (min_sot_players-3.105051)/0.447752 z_min_sot_players,
      (min_xg_breadth-0.456922)/0.105019 z_min_xg_breadth,
      least(home_history_n,away_history_n)/10.0 base_history_coverage,
      least(home_breadth_n,away_breadth_n)/10.0 breadth_history_coverage
    from features
  ), final_score as (
    select *,
      case when z_inverse_favorite is null then null else (z_min_sot+z_min_gf+z_btts+z_inverse_favorite)/4.0 end base_score_v01,
      (z_min_sot_players+z_min_xg_breadth)/2.0 breadth_score_v01,
      case when z_inverse_favorite is null then null else (z_min_sot+z_min_gf+z_btts+z_inverse_favorite+z_min_sot_players+z_min_xg_breadth)/6.0 end combined_score_v02
    from scored
  ), ranked as (
    select *,
      case when base_score_v01 is null then null else rank() over(order by base_score_v01 desc nulls last)::integer end base_rank,
      case when combined_score_v02 is null then null else rank() over(order by combined_score_v02 desc nulls last)::integer end combined_rank,
      case when least(home_history_n,away_history_n)>=10 and least(home_breadth_n,away_breadth_n)>=8 and market_bookmakers>=5 then 'HIGH'
           when least(home_history_n,away_history_n)>=8 and least(home_breadth_n,away_breadth_n)>=5 and market_bookmakers>=3 then 'MEDIUM'
           else 'LOW' end confidence
    from final_score
  ), ins as (
    insert into public.research_c0197_shootout_forward_snapshots(
      run_key,observation_hash,snapshot_as_of,match_id,gameweek,kickoff_time,home_team_id,away_team_id,home_team,away_team,
      market_bookmakers,market_home_prob,market_draw_prob,market_away_prob,favorite_prob,inverse_favorite_prob,
      home_history_n,away_history_n,home_sot,away_sot,min_sot,home_gf,away_gf,min_gf,home_btts_rate,away_btts_rate,btts_rate,
      z_min_sot,z_min_gf,z_btts,z_inverse_favorite,base_score_v01,
      home_breadth_n,away_breadth_n,home_sot_players,away_sot_players,min_sot_players,home_xg_breadth,away_xg_breadth,min_xg_breadth,
      z_min_sot_players,z_min_xg_breadth,breadth_score_v01,combined_score_v02,base_rank,combined_rank,base_history_coverage,breadth_history_coverage,confidence,evidence
    )
    select v_run_key,
      md5(concat_ws('|',match_id,round(coalesce(base_score_v01,-99)::numeric,8),round(coalesce(combined_score_v02,-99)::numeric,8),home_history_n,away_history_n,home_breadth_n,away_breadth_n,market_bookmakers)),
      p_as_of,match_id,gameweek,kickoff_time,home_team_id,away_team_id,home_team,away_team,
      market_bookmakers,ph,pd,pa,favorite_prob,inverse_favorite_prob,
      home_history_n,away_history_n,home_sot,away_sot,min_sot,home_gf,away_gf,min_gf,home_btts_rate,away_btts_rate,btts_rate,
      z_min_sot,z_min_gf,z_btts,z_inverse_favorite,base_score_v01,
      home_breadth_n,away_breadth_n,home_sot_players,away_sot_players,min_sot_players,home_xg_breadth,away_xg_breadth,min_xg_breadth,
      z_min_sot_players,z_min_xg_breadth,breadth_score_v01,combined_score_v02,base_rank,combined_rank,base_history_coverage,breadth_history_coverage,confidence,
      jsonb_build_object('market_policy','earliest captured h2h quote per bookmaker before snapshot','history_policy','2025/26 + 2026/27 EPL evidence only; shrink missing slots to fixed prior','breadth_quality','C0197 shot reconciliation eligible sides only')
    from ranked
    on conflict(run_key,match_id,observation_hash) do nothing
    returning id
  ) select count(*) into v_inserted from ins;

  return jsonb_build_object(
    'run_key',v_run_key,
    'gameweek',p_gameweek,
    'snapshot_as_of',p_as_of,
    'inserted',v_inserted,
    'model_effect_enabled',false,
    'top_base',(select jsonb_build_object('match',home_team||' vs '||away_team,'score',round(base_score_v01,4),'rank',base_rank,'confidence',confidence) from public.research_c0197_shootout_forward_snapshots where run_key=v_run_key and gameweek=p_gameweek and snapshot_as_of<=p_as_of order by snapshot_as_of desc,base_rank asc limit 1),
    'top_combined',(select jsonb_build_object('match',home_team||' vs '||away_team,'score',round(combined_score_v02,4),'rank',combined_rank,'confidence',confidence) from public.research_c0197_shootout_forward_snapshots where run_key=v_run_key and gameweek=p_gameweek and snapshot_as_of<=p_as_of order by snapshot_as_of desc,combined_rank asc limit 1)
  );
end $$;
revoke all on function private.c0197_capture_shootout_forward_v01(integer,timestamptz) from public,anon,authenticated;

create or replace function private.c0197_evaluate_shootout_forward_v01(p_gameweek integer)
returns jsonb language plpgsql set search_path=public,private,pg_temp as $$
declare v_inserted integer := 0; v_run_key constant text := 'C0197_SHOOTOUT_FORWARD_20260904_V01';
begin
  with first_snap as (
    select distinct on (s.match_id) s.* from public.research_c0197_shootout_forward_snapshots s
    where s.run_key=v_run_key and s.gameweek=p_gameweek
    order by s.match_id,s.snapshot_as_of asc,s.id asc
  ), ins as (
    insert into public.research_c0197_shootout_forward_evaluations(run_key,snapshot_id,match_id,gameweek,actual_home_goals,actual_away_goals,actual_total_goals,actual_shootout,actual_demolition,base_top10,combined_top10)
    select v_run_key,s.id,m.id,m.gameweek,m.home_score,m.away_score,m.home_score+m.away_score,
      (m.home_score+m.away_score>=6 and m.home_score>=2 and m.away_score>=2),
      (m.home_score+m.away_score>=6 and least(m.home_score,m.away_score)<=1),
      s.base_rank<=greatest(1,ceil((select count(*) from first_snap)*0.10)::integer),
      s.combined_rank<=greatest(1,ceil((select count(*) from first_snap)*0.10)::integer)
    from first_snap s join public.matches m on m.id=s.match_id
    where m.finished and m.home_score is not null and m.away_score is not null
    on conflict(run_key,snapshot_id) do nothing returning id
  ) select count(*) into v_inserted from ins;
  return jsonb_build_object('run_key',v_run_key,'gameweek',p_gameweek,'inserted',v_inserted,'model_effect_enabled',false);
end $$;
revoke all on function private.c0197_evaluate_shootout_forward_v01(integer) from public,anon,authenticated;

create or replace function private.c0197_shootout_forward_status_v01()
returns jsonb language sql stable set search_path=public,private,pg_temp as $$
select jsonb_build_object(
  'change_id','C0197',
  'run_key','C0197_SHOOTOUT_FORWARD_20260904_V01',
  'runs',(select count(*) from public.research_c0197_shootout_forward_runs),
  'scalers',(select count(*) from public.research_c0197_shootout_forward_scalers),
  'snapshots',(select count(*) from public.research_c0197_shootout_forward_snapshots),
  'evaluations',(select count(*) from public.research_c0197_shootout_forward_evaluations),
  'gameweeks',(select coalesce(jsonb_agg(distinct gameweek order by gameweek),'[]'::jsonb) from public.research_c0197_shootout_forward_snapshots),
  'model_effect_enabled',false
); $$;
revoke all on function private.c0197_shootout_forward_status_v01() from public,anon,authenticated;