create table if not exists public.realized_player_role_observations (
  id bigint generated by default as identity primary key,
  change_id text not null default 'C0212',
  source_key text not null default 'fotmob_match_details',
  source_url text not null,
  source_fotmob_match_id bigint not null,
  source_fotmob_player_id bigint not null,
  match_id bigint not null references public.matches(id),
  gameweek integer not null check (gameweek between 1 and 38),
  kickoff_time timestamptz not null,
  team_id bigint not null references public.teams(id),
  player_id bigint references public.players(id),
  player_name text not null,
  fpl_position text,
  usual_playing_position_id integer,
  formation text,
  is_starting boolean not null default true,
  position_id integer,
  layout_x numeric,
  layout_y numeric,
  tactical_band text,
  width_band text,
  realized_role text,
  role_confidence numeric check (role_confidence is null or (role_confidence >= 0 and role_confidence <= 1)),
  mapping_status text not null,
  source_payload jsonb not null default '{}'::jsonb,
  captured_at timestamptz not null default now(),
  evidence_cutoff timestamptz not null default now(),
  observation_hash text not null unique,
  production_role_enabled boolean not null default true,
  model_effect_enabled boolean not null default false,
  constraint realized_role_xy_pair check ((layout_x is null) = (layout_y is null))
);

create index if not exists realized_player_role_player_recent_idx
  on public.realized_player_role_observations(player_id, kickoff_time desc, id desc)
  where player_id is not null and is_starting;
create index if not exists realized_player_role_match_idx
  on public.realized_player_role_observations(match_id, team_id);
create index if not exists realized_player_role_source_player_idx
  on public.realized_player_role_observations(source_fotmob_player_id, kickoff_time desc);

alter table public.realized_player_role_observations enable row level security;
revoke all on public.realized_player_role_observations from anon, authenticated;
grant select, insert on public.realized_player_role_observations to service_role;
grant usage, select on sequence public.realized_player_role_observations_id_seq to service_role;

create or replace function private.block_c0212_realized_role_mutation()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  raise exception 'C0212 realized player role observations are append-only';
end
$$;
revoke all on function private.block_c0212_realized_role_mutation() from public, anon, authenticated;

drop trigger if exists trg_c0212_realized_role_append_only on public.realized_player_role_observations;
create trigger trg_c0212_realized_role_append_only
before update or delete on public.realized_player_role_observations
for each row execute function private.block_c0212_realized_role_mutation();

create or replace view public.current_realized_player_roles
with (security_invoker = true)
as
with ranked as (
  select r.*,
         row_number() over(partition by r.player_id order by r.kickoff_time desc, r.id desc) as rn
  from public.realized_player_role_observations r
  where r.player_id is not null
    and r.is_starting
    and r.realized_role is not null
    and r.production_role_enabled
), recent as (
  select * from ranked where rn <= 3
), latest as (
  select * from ranked where rn = 1
), agg as (
  select player_id,
         count(*)::integer as recent_role_samples,
         count(*) filter(where realized_role = (select l.realized_role from latest l where l.player_id=recent.player_id))::integer as latest_role_matches_l3,
         max(kickoff_time) as latest_kickoff
  from recent
  group by player_id
)
select l.player_id,
       l.realized_role as current_role,
       l.realized_role as latest_realized_role,
       l.tactical_band as latest_tactical_band,
       l.width_band as latest_width_band,
       l.formation as latest_formation,
       l.role_confidence as latest_role_confidence,
       a.recent_role_samples,
       a.latest_role_matches_l3,
       case when a.recent_role_samples > 0 then a.latest_role_matches_l3::numeric/a.recent_role_samples else null end as role_stability,
       l.kickoff_time as latest_role_match_kickoff,
       l.evidence_cutoff as latest_known_at,
       l.observation_hash as latest_observation_hash,
       l.source_key,
       l.source_url,
       l.source_fotmob_player_id,
       l.fpl_position,
       l.usual_playing_position_id
from latest l
join agg a using(player_id);

revoke all on public.current_realized_player_roles from anon, authenticated;
grant select on public.current_realized_player_roles to service_role;

create or replace view public.current_player_role_profiles
with (security_invoker = true)
as
with b as (
  select distinct on (player_id)
    id,player_id,observed_at,evidence_cutoff,taxonomy_version,primary_role,secondary_role,
    primary_score,secondary_score,confidence,weighted_minutes,competitive_minutes,preseason_minutes,
    feature_vector,evidence,observation_hash,model_effect_enabled
  from public.player_role_profile_observations
  order by player_id,observed_at desc,id desc
)
select b.id,
       b.player_id,
       greatest(b.observed_at, coalesce(r.latest_known_at,b.observed_at)) as observed_at,
       greatest(b.evidence_cutoff, coalesce(r.latest_known_at,b.evidence_cutoff)) as evidence_cutoff,
       case when r.current_role is null then b.taxonomy_version else b.taxonomy_version || '+realized_v0.1' end as taxonomy_version,
       coalesce(r.current_role,b.primary_role) as primary_role,
       case when r.current_role is null then b.secondary_role
            when b.primary_role is distinct from r.current_role then b.primary_role
            else b.secondary_role end as secondary_role,
       case when r.current_role is null then b.primary_score else coalesce(r.role_stability,r.latest_role_confidence,b.primary_score) end as primary_score,
       case when r.current_role is null then b.secondary_score else b.primary_score end as secondary_score,
       case when r.current_role is null then b.confidence else greatest(coalesce(b.confidence,0),coalesce(r.latest_role_confidence,0)) end as confidence,
       b.weighted_minutes,b.competitive_minutes,b.preseason_minutes,
       b.feature_vector || case when r.current_role is null then '{}'::jsonb else jsonb_build_object(
         'realized_role',r.current_role,
         'realized_tactical_band',r.latest_tactical_band,
         'realized_width_band',r.latest_width_band,
         'realized_formation',r.latest_formation,
         'realized_role_stability',r.role_stability,
         'realized_role_samples',r.recent_role_samples
       ) end as feature_vector,
       b.evidence || case when r.current_role is null then '{}'::jsonb else jsonb_build_object(
         'realized_role_source',r.source_key,
         'realized_role_source_url',r.source_url,
         'realized_role_known_at',r.latest_known_at,
         'fpl_position_remains_scoring_classification',true,
         'realized_role_overrides_fpl_family_guardrail_for_tactical_role_only',true,
         'numeric_role_uplift_enabled',false
       ) end as evidence,
       case when r.current_role is null then b.observation_hash else md5(b.observation_hash || '|' || r.latest_observation_hash) end as observation_hash,
       b.model_effect_enabled
from b
left join public.current_realized_player_roles r on r.player_id=b.player_id;

revoke all on public.current_player_role_profiles from anon, authenticated;
grant select on public.current_player_role_profiles to service_role;
