import { createClient } from 'supabase';
import Papa from 'papaparse';

const H={'content-type':'application/json; charset=utf-8','cache-control':'no-store'};
const REPO='olbauday/FPL-Core-Insights';
const SOURCE='fpl_core_insights_github';
const SEASON='2025-2026';
const PINNED_SHA='4f9cdaad9c60f62f3c5106753ccdfb6a467dcf04';
const PINNED_AT='2026-09-04T12:13:37Z';
const enc=new TextEncoder();
const n=(v:any)=>v===undefined||v===null||String(v).trim()===''?null:Number(v);
const i=(v:any)=>{const x=n(v);return x===null||!Number.isFinite(x)?null:Math.round(x)};
const b=(v:any)=>String(v).trim().toLowerCase()==='true';
const chunks=<T>(a:T[],z=200)=>{const out:T[][]=[];for(let k=0;k<a.length;k+=z)out.push(a.slice(k,k+z));return out};
async function sha256(s:string){const d=await crypto.subtle.digest('SHA-256',enc.encode(s));return Array.from(new Uint8Array(d)).map(x=>x.toString(16).padStart(2,'0')).join('')}
function rawUrl(path:string){return `https://raw.githubusercontent.com/${REPO}/${PINNED_SHA}/${path.split('/').map(encodeURIComponent).join('/')}`}
async function csv(path:string){const r=await fetch(rawUrl(path),{cache:'no-store',headers:{'user-agent':'FootballIntelligence/0.6','accept':'text/plain'}});if(!r.ok)throw new Error(`${path} ${r.status}`);const text=await r.text();const rows=Papa.parse(text,{header:true,skipEmptyLines:true,transformHeader:(h:string)=>h.trim().replace(/^\uFEFF/,'')}).data as any[];return {text,rows}}
function paths(gw:number){const base=`data/${SEASON}/By Tournament/Premier League/GW${gw}`;return {lineups:`${base}/lineups.csv`,avg:`${base}/average_positions.csv`}}

Deno.serve(async(req)=>{try{
 if(req.method!=='POST')return new Response(JSON.stringify({ok:false,error:'POST required'}),{status:405,headers:H});
 const ks=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')||'{}'),key=ks.default||Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!key)throw new Error('Missing service credential');
 const sb=createClient(Deno.env.get('SUPABASE_URL')!,key,{auth:{persistSession:false}});
 const {data:tok,error:ae}=await sb.rpc('get_backend_secret',{secret_name:'FOOTBALL_ENGINE_ADMIN_TOKEN'});if(ae||!tok||req.headers.get('x-engine-token')!==tok)return new Response(JSON.stringify({ok:false,error:'unauthorized'}),{status:401,headers:H});
 const body=await req.json().catch(()=>({}));const gameweeks=(Array.isArray(body.gameweeks)?body.gameweeks:[body.gameweek]).map(Number).filter((x:number)=>Number.isInteger(x)&&x>=1&&x<=38);if(!gameweeks.length||gameweeks.length>5)throw new Error('Provide 1-5 gameweeks in range 1..38');
 const {data:teams,error:te}=await sb.from('teams').select('id,team_code');if(te)throw te;const teamMap=new Map((teams||[]).filter((x:any)=>x.team_code!==null).map((x:any)=>[Number(x.team_code),Number(x.id)]));
 const totals:any={captures:0,lineups:0,average_positions:0};const perGw:any[]=[];
 async function ensureCapture(kind:'lineups'|'average_positions',gw:number,path:string,text:string,rowCount:number){const payload=await sha256(text);const oh=await sha256(['C0202',SOURCE,SEASON,gw,kind,PINNED_SHA,payload].join('|'));const row={source_key:SOURCE,season:SEASON,gameweek:gw,file_kind:kind,source_repo:REPO,source_path:path,source_url:rawUrl(path),source_commit_sha:PINNED_SHA,source_commit_at:PINNED_AT,source_as_of:PINNED_AT,payload_sha256:payload,row_count:rowCount,observation_hash:oh,notes:'C0202 post-match historical side/formation ground truth; training/validation label only; no same-fixture pre-kickoff use; no production model effect.'};const {data,error}=await sb.from('research_c0202_source_file_captures').upsert(row,{onConflict:'observation_hash',ignoreDuplicates:true}).select('id');if(error)throw new Error(`capture ${kind}: ${error.message}`);if(data?.[0]?.id){totals.captures++;return Number(data[0].id)}const {data:e,error:ee}=await sb.from('research_c0202_source_file_captures').select('id').eq('observation_hash',oh).single();if(ee)throw ee;return Number(e.id)}
 for(const gw of gameweeks){const p=paths(gw);const [lf,af]=await Promise.all([csv(p.lineups),csv(p.avg)]);const capL=await ensureCapture('lineups',gw,p.lineups,lf.text,lf.rows.length);const capA=await ensureCapture('average_positions',gw,p.avg,af.text,af.rows.length);
   const {data:hist,error:he}=await sb.from('research_c0197_player_match_evidence').select('source_match_id,source_player_id,player_id,source_team_code').eq('season',SEASON).eq('gameweek',gw);if(he)throw new Error(`historical map gw${gw}: ${he.message}`);const playerMap=new Map<string,{playerId:number|null,teamCode:number|null}>();for(const r of hist||[]){const sid=i(r.source_player_id);if(sid===null)continue;const k=`${String(r.source_match_id)}|${sid}`;if(!playerMap.has(k)||r.player_id!==null)playerMap.set(k,{playerId:r.player_id===null?null:Number(r.player_id),teamCode:i(r.source_team_code)})}
   const lineupRows:any[]=[];for(const r of lf.rows){const sm=String(r.match_id||'').trim(),side=String(r.team_side||'').trim().toLowerCase(),sid=i(r.player_id),name=String(r.player_name||'').trim();if(!sm||!['home','away'].includes(side)||!name)continue;const mapped=sid===null?null:playerMap.get(`${sm}|${sid}`),teamCode=i(r.team_code),teamId=teamCode===null?null:(teamMap.get(teamCode)||null),playerId=mapped?.playerId||null;lineupRows.push({source_file_capture_id:capL,source_commit_sha:PINNED_SHA,season:SEASON,gameweek:gw,source_match_id:sm,match_id:null,team_side:side,source_team_code:teamCode,team_id:teamId,source_player_id:sid,player_id:playerId,player_name:name,position:String(r.position||'').trim()||null,jersey_number:i(r.jersey_number),is_starting:b(r.is_starting),formation:String(r.formation||'').trim()||null,lineup_status:String(r.lineup_status||'').trim()||null,mapping_status:playerId?'historical_player_mapped_current':'historical_source_only',source_row:r})}
   let li=0;for(const c of chunks(lineupRows)){const {data,error}=await sb.from('research_c0202_lineup_labels').upsert(c,{onConflict:'source_file_capture_id,source_match_id,team_side,source_player_id,player_name',ignoreDuplicates:true}).select('id');if(error)throw new Error(`lineups gw${gw}: ${error.message}`);li+=(data||[]).length}totals.lineups+=li;
   const avgRows:any[]=[];for(const r of af.rows){const sm=String(r.match_id||'').trim(),side=String(r.team_side||'').trim().toLowerCase(),sid=i(r.player_id),name=String(r.player_name||'').trim(),x=n(r.x),y=n(r.y);if(!sm||!['home','away'].includes(side)||!name||x===null||y===null)continue;const mapped=sid===null?null:playerMap.get(`${sm}|${sid}`),playerId=mapped?.playerId||null;avgRows.push({source_file_capture_id:capA,source_commit_sha:PINNED_SHA,season:SEASON,gameweek:gw,source_match_id:sm,match_id:null,team_side:side,source_player_id:sid,player_id:playerId,player_name:name,jersey_number:i(r.jersey_number),position:String(r.position||'').trim()||null,avg_x:x,avg_y:y,mapping_status:playerId?'historical_player_mapped_current':'historical_source_only',source_row:r})}
   let ai=0;for(const c of chunks(avgRows)){const {data,error}=await sb.from('research_c0202_average_position_labels').upsert(c,{onConflict:'source_file_capture_id,source_match_id,team_side,source_player_id,player_name',ignoreDuplicates:true}).select('id');if(error)throw new Error(`average_positions gw${gw}: ${error.message}`);ai+=(data||[]).length}totals.average_positions+=ai;
   perGw.push({gameweek:gw,source_rows:{lineups:lf.rows.length,average_positions:af.rows.length},inserted:{lineups:li,average_positions:ai}})
 }
 return new Response(JSON.stringify({ok:true,change_id:'C0202',season:SEASON,gameweeks,source_commit_sha:PINNED_SHA,source_commit_at:PINNED_AT,totals,per_gameweek:perGw,post_match_labels_only:true,research_only:true,model_effect_enabled:false}),{headers:H});
}catch(e){return new Response(JSON.stringify({ok:false,error:e instanceof Error?e.message:String(e)}),{status:500,headers:H})}});
