import { createClient } from 'supabase';
import Papa from 'papaparse';
const H={'content-type':'application/json; charset=utf-8','cache-control':'no-store'};
const n=(v:any)=>v===undefined||v===null||String(v).trim()===''?null:Number(v);
const i=(v:any)=>{const x=n(v);return x===null?null:Math.round(x)};
const b=(v:any)=>String(v).toLowerCase()==='true';
const strictSum=(...xs:any[])=>{const ns=xs.map(n);return ns.some(x=>x===null)?null:ns.reduce((a,x)=>a+(x||0),0)};
const chunks=<T>(a:T[],z=200)=>{const out:T[][]=[];for(let k=0;k<a.length;k+=z)out.push(a.slice(k,k+z));return out};
async function csv(url:string){const r=await fetch(url,{cache:'no-store',headers:{'user-agent':'FootballIntelligence/0.4'}});if(!r.ok)throw new Error(`${url} ${r.status}`);return Papa.parse(await r.text(),{header:true,skipEmptyLines:true,transformHeader:(h:string)=>h.trim().replace(/^\uFEFF/,'')}).data as any[]}
Deno.serve(async(req)=>{try{
 if(req.method!=='POST')return new Response(JSON.stringify({ok:false,error:'POST required'}),{status:405,headers:H});
 const ks=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')||'{}'),key=ks.default||Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!key)throw new Error('Missing service credential');
 const sb=createClient(Deno.env.get('SUPABASE_URL')!,key,{auth:{persistSession:false}});const {data:tok,error:ae}=await sb.rpc('get_backend_secret',{secret_name:'FOOTBALL_ENGINE_ADMIN_TOKEN'});if(ae||!tok||req.headers.get('x-engine-token')!==tok)return new Response(JSON.stringify({ok:false,error:'unauthorized'}),{status:401,headers:H});
 const body=await req.json().catch(()=>({}));let gw=Number(body.gameweek||0),now=new Date().toISOString();if(!gw){const {data:m,error}=await sb.from('matches').select('gameweek').eq('source','fpl').lte('kickoff_time',now).not('gameweek','is',null).order('gameweek',{ascending:false}).limit(1).maybeSingle();if(error)throw error;gw=Number(m?.gameweek||0)}if(!gw)throw new Error('No gameweek resolved');
 const base=`https://raw.githubusercontent.com/olbauday/FPL-Core-Insights/main/data/2026-2027/By%20Tournament/Premier%20League/GW${gw}`;const [mr,pr]=await Promise.all([csv(`${base}/matches.csv`),csv(`${base}/playermatchstats.csv`)]);
 const [{data:teams,error:te},{data:players,error:pe},{data:fx,error:fe}]=await Promise.all([sb.from('teams').select('id,team_code'),sb.from('players').select('id,fpl_player_id'),sb.from('matches').select('id,gameweek,kickoff_time,home_team_id,away_team_id,finished').eq('source','fpl').eq('gameweek',gw)]);if(te)throw te;if(pe)throw pe;if(fe)throw fe;
 const tm=new Map((teams||[]).map((x:any)=>[Number(x.team_code),Number(x.id)])),pm=new Map((players||[]).map((x:any)=>[Number(x.fpl_player_id),Number(x.id)]));const fxMap=new Map((fx||[]).map((x:any)=>[`${x.home_team_id}|${x.away_team_id}`,x]));const matchMap=new Map<string,any>();let teamRows:any[]=[];let processedMatches=0,playerProcessedMatches=0,unmappedMatches=0;
 for(const r of mr){const ht=tm.get(Number(r.home_team)),at=tm.get(Number(r.away_team));if(!ht||!at){unmappedMatches++;continue}const f=fxMap.get(`${ht}|${at}`);if(!f){unmappedMatches++;continue}matchMap.set(String(r.match_id),{f,row:r});if(!f.finished&&!b(r.finished))continue;processedMatches++;
  const side=(home:boolean)=>({source:'fpl_core_insights_premier_league',source_match_id:String(r.match_id),match_id:f.id,team_id:home?ht:at,fixture_kickoff:f.kickoff_time,captured_at:now,venue:home?'home':'away',competition:'premier_league',goals_for:n(home?r.home_score:r.away_score),goals_against:n(home?r.away_score:r.home_score),xg_for:n(home?r.home_expected_goals_xg:r.away_expected_goals_xg),xg_against:n(home?r.away_expected_goals_xg:r.home_expected_goals_xg),shots_for:n(home?r.home_total_shots:r.away_total_shots),shots_against:n(home?r.away_total_shots:r.home_total_shots),big_chances_for:n(home?r.home_big_chances:r.away_big_chances),big_chances_against:n(home?r.away_big_chances:r.home_big_chances),raw:{...r,team_side:home?'home':'away',stats_processed:b(r.stats_processed),player_stats_processed:b(r.player_stats_processed)}});teamRows.push(side(true),side(false));if(b(r.player_stats_processed))playerProcessedMatches++;
 }
 let teamInserted=0;for(const c of chunks(teamRows)){const {data,error}=await sb.from('team_match_intelligence').upsert(c,{onConflict:'source,source_match_id,team_id',ignoreDuplicates:true}).select('id');if(error)throw new Error(`team evidence: ${error.message}`);teamInserted+=(data||[]).length}
 const pRows:any[]=[];let skippedUnprocessed=0,skippedUnmappedPlayers=0;for(const r of pr){const mm=matchMap.get(String(r.match_id));if(!mm||!mm.f?.finished){skippedUnprocessed++;continue}if(!b(mm.row.player_stats_processed)){skippedUnprocessed++;continue}const pid=pm.get(Number(r.player_id));if(!pid){skippedUnmappedPlayers++;continue}const mins=i(r.minutes_played);const cbit=strictSum(r.clearances,r.blocks,r.interceptions,r.tackles),cbirt=cbit===null||n(r.recoveries)===null?null:cbit+Number(r.recoveries);const xg=n(r.xg),xa=n(r.xa);pRows.push({source:'fpl_core_insights_premier_league',source_player_id:i(r.player_id),source_match_id:String(r.match_id),player_id:pid,match_id:mm.f.id,minutes:mins,started:mins!==null&&mins>0&&i(r.start_min)===0,formation:null,role:null,xg,xa,xgi:xg===null&&xa===null?null:(xg||0)+(xa||0),xgot:n(r.xgot),shots:i(r.total_shots),shots_in_box:null,shots_on_target:i(r.shots_on_target),big_chances:null,big_chances_created:null,big_chances_missed:i(r.big_chances_missed),touches_box:i(r.touches_opposition_box),goals:i(r.goals),assists:i(r.assists),clearances:i(r.clearances),blocks:i(r.blocks),interceptions:i(r.interceptions),tackles:i(r.tackles),recoveries:i(r.recoveries),cbit:cbit===null?null:Math.round(cbit),cbirt:cbirt===null?null:Math.round(cbirt),raw:r})}
 let playerInserted=0;for(const c of chunks(pRows)){const {data,error}=await sb.from('player_matches').upsert(c,{onConflict:'player_id,match_id',ignoreDuplicates:true}).select('id');if(error)throw new Error(`player evidence: ${error.message}`);playerInserted+=(data||[]).length}
 return new Response(JSON.stringify({ok:true,gameweek:gw,source_matches:mr.length,processed_finished_matches:processedMatches,player_stats_processed_matches:playerProcessedMatches,team_evidence_candidates:teamRows.length,team_evidence_inserted:teamInserted,player_evidence_candidates:pRows.length,player_evidence_inserted:playerInserted,skipped_unprocessed_player_rows:skippedUnprocessed,skipped_unmapped_players:skippedUnmappedPlayers,unmapped_matches:unmappedMatches,model_effect_enabled:false,note:'Only source matches marked player_stats_processed are used for competitive player-event evidence; missing values remain null.'}),{headers:H});
}catch(e){return new Response(JSON.stringify({ok:false,error:e instanceof Error?e.message:String(e)}),{status:500,headers:H})}});
