-- Mispricing Intelligence v0.1: observational signals only. No lambda/xPts adjustment.
-- Internal backend data: RLS enabled, no anon/authenticated access.

create table if not exists public.team_match_intelligence (
  id bigint generated by default as identity primary key,
  team_id bigint not null,
  match_id bigint,
  fixture_kickoff timestamptz not null,
  captured_at timestamptz not null default now(),
  source text not null,
  source_match_id text,
  venue text check (venue in ('home','away','neutral')),
  goals_for numeric,
  goals_against numeric,
  xg_for numeric,
  xg_against numeric,
  shots_for numeric,
  shots_against numeric,
  big_chances_for numeric,
  big_chances_against numeric,
  competition text,
  raw jsonb not null default '{}'::jsonb
);

alter table public.team_match_intelligence enable row level security;
revoke all on table public.team_match_intelligence from anon, authenticated;
grant select, insert, update, delete on table public.team_match_intelligence to service_role;
grant usage, select on sequence public.team_match_intelligence_id_seq to service_role;

create index if not exists tmi_team_kickoff_idx
  on public.team_match_intelligence(team_id, fixture_kickoff desc);

-- Historical ingestion must be idempotent per source/match/team.
create unique index if not exists tmi_source_match_team_uidx
  on public.team_match_intelligence(source, source_match_id, team_id)
  where source_match_id is not null;

create table if not exists public.fixture_intelligence_signals (
  id bigint generated by default as identity primary key,
  match_id bigint not null,
  gameweek integer,
  team_id bigint,
  opponent_team_id bigint,
  signal_family text not null check (signal_family in ('recent_performance','schedule_fatigue')),
  signal_key text not null,
  direction smallint not null default 0 check (direction between -1 and 1),
  magnitude numeric not null default 0,
  confidence numeric not null check (confidence between 0 and 1),
  evidence jsonb not null default '{}'::jsonb,
  source text not null,
  source_updated_at timestamptz,
  captured_at timestamptz not null default now(),
  model_effect_enabled boolean not null default false
);

alter table public.fixture_intelligence_signals enable row level security;
revoke all on table public.fixture_intelligence_signals from anon, authenticated;
grant select, insert, update, delete on table public.fixture_intelligence_signals to service_role;
grant usage, select on sequence public.fixture_intelligence_signals_id_seq to service_role;

create index if not exists fis_match_family_idx
  on public.fixture_intelligence_signals(match_id, signal_family, captured_at desc);

-- Canonicalize overlapping sources by team + match date before calculating form.
-- This avoids double-counting the same match when Football-Data and an xG provider
-- both contribute complementary facts, or when an ingestion job is retried.
create or replace view public.team_intelligence_features
with (security_invoker = true)
as
with fixtures as (
  select m.id match_id, m.gameweek, m.kickoff_time,
         m.home_team_id team_id, m.away_team_id opponent_team_id
  from public.matches m where m.source='fpl'
  union all
  select m.id, m.gameweek, m.kickoff_time,
         m.away_team_id, m.home_team_id
  from public.matches m where m.source='fpl'
), canonical_history as (
  select
    team_id,
    fixture_kickoff::date fixture_date,
    max(fixture_kickoff) fixture_kickoff,
    max(goals_for) filter (where goals_for is not null) goals_for,
    max(goals_against) filter (where goals_against is not null) goals_against,
    max(xg_for) filter (where xg_for is not null) xg_for,
    max(xg_against) filter (where xg_against is not null) xg_against,
    max(shots_for) filter (where shots_for is not null) shots_for,
    max(shots_against) filter (where shots_against is not null) shots_against,
    max(big_chances_for) filter (where big_chances_for is not null) big_chances_for,
    max(big_chances_against) filter (where big_chances_against is not null) big_chances_against,
    array_agg(distinct source order by source) sources
  from public.team_match_intelligence
  group by team_id, fixture_kickoff::date
), hist as (
  select f.*, h.fixture_kickoff, h.fixture_date,
         h.xg_for, h.xg_against, h.goals_for, h.goals_against,
         h.shots_for, h.shots_against, h.big_chances_for, h.big_chances_against,
         h.sources,
         row_number() over(
           partition by f.match_id,f.team_id
           order by h.fixture_kickoff desc
         ) rn
  from fixtures f
  left join canonical_history h
    on h.team_id=f.team_id
   and h.fixture_kickoff < f.kickoff_time
), agg as (
  select
    match_id, gameweek, kickoff_time, team_id, opponent_team_id,
    avg(xg_for) filter(where rn<=5) l5_xg_for,
    avg(xg_against) filter(where rn<=5) l5_xg_against,
    avg(xg_for) filter(where rn<=10) l10_xg_for,
    avg(xg_against) filter(where rn<=10) l10_xg_against,
    avg(goals_for) filter(where rn<=5) l5_goals_for,
    avg(goals_against) filter(where rn<=5) l5_goals_against,
    avg(shots_for) filter(where rn<=5) l5_shots_for,
    avg(shots_against) filter(where rn<=5) l5_shots_against,
    max(fixture_kickoff) filter(where rn=1) previous_match,
    count(*) filter(
      where fixture_kickoff >= kickoff_time-interval '14 days'
    ) matches_prev_14d,
    count(*) filter(
      where fixture_kickoff >= kickoff_time-interval '7 days'
    ) matches_prev_7d,
    count(xg_for) filter(where rn<=5) sample_l5,
    count(xg_for) filter(where rn<=10) sample_l10
  from hist
  group by match_id,gameweek,kickoff_time,team_id,opponent_team_id
)
select *,
  extract(epoch from(kickoff_time-previous_match))/86400.0 rest_days,
  case
    when matches_prev_7d>=3 then 'high'
    when matches_prev_14d>=4 then 'medium'
    else 'normal'
  end congestion_band
from agg;

revoke all on table public.team_intelligence_features from anon, authenticated;
grant select on table public.team_intelligence_features to service_role;

-- Appends interpretable snapshots; never overwrites history.
create or replace function public.generate_observational_intelligence(p_gameweek integer)
returns integer
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  n_attack integer := 0;
  n_defence integer := 0;
  n_schedule integer := 0;
begin
  insert into public.fixture_intelligence_signals(
    match_id,gameweek,team_id,opponent_team_id,
    signal_family,signal_key,direction,magnitude,confidence,
    evidence,source,model_effect_enabled
  )
  select
    match_id,gameweek,team_id,opponent_team_id,
    'recent_performance','attacking_xg_trend',
    case
      when coalesce(l5_xg_for-l10_xg_for,0)>.12 then 1
      when coalesce(l5_xg_for-l10_xg_for,0)<-.12 then -1
      else 0
    end,
    coalesce(l5_xg_for-l10_xg_for,0),
    least(1,coalesce(sample_l10,0)/10.0),
    jsonb_build_object(
      'l5_xg_for',l5_xg_for,
      'l10_xg_for',l10_xg_for,
      'l5_xga',l5_xg_against,
      'l10_xga',l10_xg_against,
      'l5_goals_for',l5_goals_for,
      'l5_shots_for',l5_shots_for,
      'sample_l5',sample_l5,
      'sample_l10',sample_l10
    ),
    'team_match_intelligence',false
  from public.team_intelligence_features
  where gameweek=p_gameweek;
  get diagnostics n_attack=row_count;

  insert into public.fixture_intelligence_signals(
    match_id,gameweek,team_id,opponent_team_id,
    signal_family,signal_key,direction,magnitude,confidence,
    evidence,source,model_effect_enabled
  )
  select
    match_id,gameweek,team_id,opponent_team_id,
    'recent_performance','defensive_xga_trend',
    case
      when coalesce(l10_xg_against-l5_xg_against,0)>.12 then 1
      when coalesce(l10_xg_against-l5_xg_against,0)<-.12 then -1
      else 0
    end,
    coalesce(l10_xg_against-l5_xg_against,0),
    least(1,coalesce(sample_l10,0)/10.0),
    jsonb_build_object(
      'l5_xga',l5_xg_against,
      'l10_xga',l10_xg_against,
      'l5_goals_against',l5_goals_against,
      'l5_shots_against',l5_shots_against,
      'sample_l5',sample_l5,
      'sample_l10',sample_l10
    ),
    'team_match_intelligence',false
  from public.team_intelligence_features
  where gameweek=p_gameweek;
  get diagnostics n_defence=row_count;

  insert into public.fixture_intelligence_signals(
    match_id,gameweek,team_id,opponent_team_id,
    signal_family,signal_key,direction,magnitude,confidence,
    evidence,source,model_effect_enabled
  )
  select
    match_id,gameweek,team_id,opponent_team_id,
    'schedule_fatigue','rest_congestion',
    case
      when rest_days is null then 0
      when rest_days<4 or matches_prev_7d>=3 then -1
      when rest_days>=7 then 1
      else 0
    end,
    case
      when rest_days is null then 0
      when rest_days<4 then 4-rest_days
      when rest_days>=7 then least(rest_days-6,4)
      else 0
    end,
    case when previous_match is null then .25 else .9 end,
    jsonb_build_object(
      'rest_days',rest_days,
      'matches_prev_7d',matches_prev_7d,
      'matches_prev_14d',matches_prev_14d,
      'congestion_band',congestion_band
    ),
    'fixture_schedule',false
  from public.team_intelligence_features
  where gameweek=p_gameweek;
  get diagnostics n_schedule=row_count;

  return n_attack+n_defence+n_schedule;
end $$;

revoke all on function public.generate_observational_intelligence(integer) from public, anon, authenticated;
grant execute on function public.generate_observational_intelligence(integer) to service_role;
